force-app/main/default/objects/Archivo_url__c/Archivo_url__c.object-meta.xml
<CustomObject>
    <label>Archivo url</label>
    <nameField>
        <label>Nombre de Archivo url</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archivos url</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archivo_url__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Nombre_original__c.field-meta.xml
<CustomField>
    <fullName>Nombre_original__c</fullName>
    <label>Nombre original</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_de_solicitud_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud_SS__c</fullName>
    <label>Nro de solicitud SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interfaz_financiera.recordType-meta.xml
<RecordType>
    <fullName>Interfaz_financiera</fullName>
    <active>true</active>
    <businessProcess>Interfaz financiera</businessProcess>
    <label>Interfaz financiera</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_alta_familiar.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_alta_familiar</fullName>
    <active>true</active>
    <businessProcess>Solicitud alta familiar</businessProcess>
    <label>Solicitud de alta familiar</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_baja.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_baja</fullName>
    <active>true</active>
    <businessProcess>Solicitud de bajas</businessProcess>
    <label>Solicitud de baja</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_cambio_de_plan.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_cambio_de_plan</fullName>
    <active>true</active>
    <businessProcess>Solicitud de cambio de plan</businessProcess>
    <label>Solicitud de cambio de plan</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_datos_particulares.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_datos_particulares</fullName>
    <active>true</active>
    <businessProcess>Solicitud de datos particulares</businessProcess>
    <label>Solicitud de datos particulares</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_despegues.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_despegues</fullName>
    <active>true</active>
    <businessProcess>Solicitud de despegue</businessProcess>
    <label>Solicitud de despegues</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_segmento.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_segmento</fullName>
    <active>true</active>
    <businessProcess>Solicitud de segmento</businessProcess>
    <label>Solicitud de segmento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/recordTypes/Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Corporativo</fullName>
    <active>true</active>
    <businessProcess>Corporativo</businessProcess>
    <description>Tipo de registro exclusivo para ventas de tipo Corporativas</description>
    <label>Corporativo</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Corporativo</fullName>
    <active>true</active>
    <businessProcess>Venta Corporativa</businessProcess>
    <description>Tipo de registro exclusivo para ventas corporativas</description>
    <label>Corporativo</label>
</RecordType>

force-app/main/default/classes/ContentDocumentTriggerHelper.cls
public class ContentDocumentTriggerHelper {
	public static void avoidDeleteSentOpportunityFiles(Map<Id, ContentDocument> oldMapTrigger) {
		User usuario = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
		
		for(ContentDocument cd : [
			SELECT Id, ( 
					SELECT LinkedEntityId 
					FROM ContentDocumentLinks 
					WHERE LinkedEntity.Type = 'Opportunity' AND LinkedEntity.RecordType.DeveloperName != 'Corporativo'
				)
				//(SELECT Enviado__c FROM ContentVersions WHERE Enviado__c = true)
			FROM ContentDocument 
			WHERE Id IN :oldMapTrigger.keyset()
		]) {
			//if(!cd.ContentDocumentLinks.isEmpty() && !cd.ContentVersions.isEmpty()) {
			if(!cd.ContentDocumentLinks.isEmpty() && usuario.Profile.Name != 'Administrador del sistema') {
				Trigger.oldMap.get(cd.Id).addError('No se pueden eliminar archivos de oportunidades');
			}

		}
	}

	public static void copyTheLastContentNoteToNotaFieldInLead(Id[] contentNoteIds) {
		Map<Id, Id> leadIdByContentNoteId = new Map<Id, Id>();
		Lead[] leadsToUpdate = new List<Lead>(); 

		for(ContentDocument cd : [
			SELECT Id, 
				(SELECT Id, LinkedEntityId FROM ContentDocumentLinks WHERE LinkedEntity.Type = 'Lead') 
			FROM ContentDocument
			WHERE Id IN :contentNoteIds
		]) {
			if(!cd.ContentDocumentLinks.isEmpty()) {
				leadIdByContentNoteId.put(cd.Id, cd.ContentDocumentLinks[0].LinkedEntityId);
			}
		}

		Lead[] leadsWithAttachedContentNotes = [
			SELECT Id, Nota__c, (SELECT id, TextPreview, FileType, CreatedDate FROM AttachedContentNotes ORDER BY CreatedDate DESC) 
			FROM Lead 
			WHERE Id IN :leadIdByContentNoteId.values()
		];
			
		System.debug('****leadsWithAttachedContentNotes: ' + leadsWithAttachedContentNotes);

		for(Lead cand : leadsWithAttachedContentNotes) {
			System.debug('****cand.AttachedContentNotes[0].Id: ' + cand.AttachedContentNotes[0].Id);
			System.debug('****cand.AttachedContentNotes[0].TextPreview: ' + cand.AttachedContentNotes[0].TextPreview);

			if(cand.AttachedContentNotes.size() == 1 && cand.Nota__c != null) {
				cand.Nota__c = null;

				leadsToUpdate.add(cand);
			}
			// si es distinto de null, la ultima nota adjunta es la que se esta eliminando
			else if(leadIdByContentNoteId.get(cand.AttachedContentNotes[0].Id) != null 
					&& cand.Nota__c != cand.AttachedContentNotes[1].TextPreview
			) {
				cand.Nota__c = cand.AttachedContentNotes[1].TextPreview;

				leadsToUpdate.add(cand);
			}

		}

		update leadsToUpdate;
	}

	public static void avoidDeleteSentSalesCaseFiles(Map<Id, ContentDocument> oldMapTrigger) {
		User usuario = [
            SELECT Id, Profile.Name 
            FROM User 
            WHERE Id =: UserInfo.getUserId()
        ];
        
		String[] RECORD_TYPES = new List<String>{
			'Solicitud_de_alta_familiar',
			'Solicitud_de_segmento',
			'Solicitud_de_cambio_de_plan',
			'Solicitud_de_baja',
			'Interfaz_financiera',
			'Solicitud_de_despegues',
			'Solicitud_de_datos_particulares'
		};
		Set<Id> caseIds = new Set<Id>();
		
		for(ContentDocument cd : [
			SELECT Id, ( 
					SELECT LinkedEntityId 
					FROM ContentDocumentLinks 
					WHERE LinkedEntity.Type = 'Case' AND LinkedEntity.RecordType.DeveloperName IN :RECORD_TYPES
				)
			FROM ContentDocument 
			WHERE Id IN :oldMapTrigger.keyset()
		]) {
			for(ContentDocumentLink cdl : cd.ContentDocumentLinks) {
				caseIds.add(cdl.LinkedEntityId);
			}
		}

		Case[] casesSentToSS = [
			SELECT Id 
			FROM Case 
			WHERE Id IN :caseIds 
				AND Nro_de_solicitud_SS__c != null
		];

		for(ContentDocument cd : [
			SELECT Id, (SELECT LinkedEntityId FROM ContentDocumentLinks WHERE LinkedEntityId IN :casesSentToSS)
			FROM ContentDocument 
			WHERE Id IN :oldMapTrigger.keyset()
		]) {
			
			if(!cd.ContentDocumentLinks.isEmpty() && usuario.Profile.Name != 'Administrador del sistema') {
				Trigger.oldMap.get(cd.Id).addError('No se pueden eliminar archivos si el caso ya fue enviado a Salud Soft');
			}
			
		}
	}
	
	public static void avoidDeletionOfSentFiles(List<ContentDocument> contentDocuments) {
		Map<Id, ContentDocument> cdById = new Map<Id, ContentDocument>();
		Set<Id> cdIds = new Set<Id>();
		List<String> titles = new List<String>();
		for(ContentDocument cd : contentDocuments) {
			titles.add(cd.Title);
			cdIds.add(cd.Id);
			cdById.put(cd.Id, cd);
		}

		List<ContentDocumentLink> cdls = [
			SELECT Id, ContentDocument.Title, LinkedEntityId, ContentDocumentId
			FROM ContentDocumentLink
			WHERE ContentDocumentId IN :cdIds
		];
		System.debug('****cdls: ' + cdls);

		Map<Id, ContentDocumentLink> cdlByLinkedEntityId = new Map<Id, ContentDocumentLink>();
		for(ContentDocumentLink cdl : cdls) {
			cdlByLinkedEntityId.put(cdl.LinkedEntityId, cdl);
		}

		List<Archivo_url__c> archivosUrls = [
			SELECT Id, Enviado__c, Name, Caso__c, Evento_Medico__c, Oportunidad__c
			FROM Archivo_url__c
			WHERE (Caso__c IN :cdlByLinkedEntityId.keyset()
					OR Evento_Medico__c IN :cdlByLinkedEntityId.keyset()
					OR Oportunidad__c IN :cdlByLinkedEntityId.keyset())
				AND Nombre_original__c IN :titles
		];

		System.debug('****archivosUrls: ' + archivosUrls);

		List<Archivo_url__c> cantDelete = new List<Archivo_url__c>();
		for(Archivo_url__c fileToDelete : archivosUrls) {
			if(fileToDelete.Enviado__c) {
				cantDelete.add(fileToDelete);
			}
		}

		System.debug('****cantDelete: ' + cantDelete);
		List<ContentDocument> cdToAddError = new List<ContentDocument>();
		for(Archivo_url__c file : cantDelete) {
			if(String.isNotBlank(file.Caso__c)) {
				cdToAddError.add(cdById.get(cdlByLinkedEntityId.get(file.Caso__c).ContentDocumentId));
			}
			else if(String.isNotBlank(file.Evento_Medico__c)) {
				cdToAddError.add(cdById.get(cdlByLinkedEntityId.get(file.Evento_Medico__c).ContentDocumentId));
			}
			else if(String.isNotBlank(file.Oportunidad__c)) {
				cdToAddError.add(cdById.get(cdlByLinkedEntityId.get(file.Oportunidad__c).ContentDocumentId));
			}
		}

		for(ContentDocument cd : cdToAddError) {
			cd.addError('No se puede eliminar el archivo, ya fue enviado a SaludSoft');
		}
	}
}