force-app/main/default/objects/Archivo_url__c/Archivo_url__c.object-meta.xml
<CustomObject>
    <label>Archivo url</label>
    <nameField>
        <label>Nombre de Archivo url</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archivos url</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archivo_url__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Enviado__c.field-meta.xml
<CustomField>
    <fullName>Enviado__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enviado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Nombre_original__c.field-meta.xml
<CustomField>
    <fullName>Nombre_original__c</fullName>
    <label>Nombre original</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Archivos url</relationshipLabel>
    <relationshipName>Archivos_url</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archivo_url__c/fields/Ruta_relativa__c.field-meta.xml
<CustomField>
    <fullName>Ruta_relativa__c</fullName>
    <label>Ruta relativa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentDocumentQueueable.cls
public class ContentDocumentQueueable implements Queueable, Database.AllowsCallouts {
	List<ContentDocument> cds;

	public ContentDocumentQueueable(List<ContentDocument> contentDocuments) {
		cds = contentDocuments;
	}

	public void execute(QueueableContext context) {
		System.debug('****cds: ' + cds);
        if(!cds.isEmpty()) {
            ContentDocument cd = cds.remove(0);
            System.debug('****ContentDocument: ' + cd);
            List<Archivo_url__c> archivoUrls = [
                SELECT Id, Nombre_original__c, Caso__c, Evento_Medico__c, 
                    Oportunidad__c, Ruta_relativa__c, Enviado__c
                FROM Archivo_url__c
                WHERE Nombre_original__c =: cd.Title.toUpperCase()
            ];

            System.debug('****archivoUrls: ' + archivoUrls);
            if(archivoUrls.isEmpty()) {
                return;
            }

            Set<Id> entitiesIds = new Set<Id>();
            for(Archivo_url__c file : archivoUrls) {
                if(String.isNotBlank(file.Caso__c)) {
                    entitiesIds.add(file.Caso__c);
                }
                else if(String.isNotBlank(file.Evento_Medico__c)) {
                    entitiesIds.add(file.Evento_Medico__c);
                }
                else if(String.isNotBlank(file.Oportunidad__c)) {
                    entitiesIds.add(file.Oportunidad__c);
                }
            }

            Archivo_url__c archivoUrl = null;
            List<ContentDocumentLink> cdls = [
                SELECT Id, ContentDocument.Title, LinkedEntityId, ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId IN :entitiesIds
                    AND ContentDocument.Title =: cd.Title
            ];
            System.debug('****cdls: ' + cdls);

            Map<Id, ContentDocumentLink> cdlByLinkedEntityId = new Map<Id, ContentDocumentLink>();
            for(ContentDocumentLink cdl : cdls) {
                cdlByLinkedEntityId.put(cdl.LinkedEntityId, cdl);
            }

            for(Archivo_url__c file : archivoUrls) {
                if(String.isNotBlank(file.Caso__c) && cdlByLinkedEntityId.get(file.Caso__c) == null) {
                    archivoUrl = file;
                }
                else if(String.isNotBlank(file.Evento_Medico__c) && cdlByLinkedEntityId.get(file.Evento_Medico__c) == null) {
                    archivoUrl = file;
                }
                else if(String.isNotBlank(file.Oportunidad__c) && cdlByLinkedEntityId.get(file.Oportunidad__c) == null) {
                    archivoUrl = file;
                }
            }
            System.debug('****archivoUrl: ' + archivoUrl);

            if(archivoUrl != null) {
                AWS.Response resp = AWS.deleteFile(archivoUrl);
                System.debug('****resp: ' + resp);
                if(!resp.hasError) {
                    delete archivoUrl;
                }
            }           
        }

        if(!cds.isEmpty()){
            System.enqueueJob(new ContentDocumentQueueable(cds));
        }
    }
}