force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Efectores__c.field-meta.xml
<CustomField>
    <fullName>Efectores__c</fullName>
    <label>Efectores</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchEfector.cls
global class  ScheduleBatchEfector implements Schedulable{
    global void execute(SchedulableContext sc) {

        MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
        Datetime lastUpdate = System.now();
        if (config != null && config.Efectores__c != null) {
            lastUpdate = config.Efectores__c;
        }
		//-----------------------------------------------------------------------
		//lastUpdate = Datetime.newInstance(2019, 12, 09, 12, 30, 2);
		//-----------------------------------------------------------------------
        Database.executeBatch(new MasterBatch(new AccountEfectorProcessor(100, lastUpdate)));
    }
}