force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Clausulas_Temporales__c.field-meta.xml
<CustomField>
    <fullName>Clausulas_Temporales__c</fullName>
    <label>Clausulas Temporales</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchClausulasTemp.cls
global class ScheduleBatchClausulasTemp implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
		Datetime lastUpdate = System.now();
		if (config != null && config.Clausulas_Temporales__c != null) {
			lastUpdate = config.Clausulas_Temporales__c;
		}

		Database.executeBatch(new MasterBatch(new ClausulasTempProcessor(100, lastUpdate)));
	}

}