force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Empresas__c.field-meta.xml
<CustomField>
    <fullName>Empresas__c</fullName>
    <label>Empresas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchEmpresa.cls
global class ScheduleBatchEmpresa implements Schedulable{

    global void execute(SchedulableContext sc) {

        MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
        Datetime lastUpdate = System.now();
        if (config != null && config.Empresas__c != null) {
            lastUpdate = config.Empresas__c;
        }
        //-----------------------------------------------------------------------
		//lastUpdate = Datetime.newInstance(2020, 5, 13, 12, 30, 2);
		//-----------------------------------------------------------------------
        Database.executeBatch(new MasterBatch(new AccountEmpresaProcessor(100, lastUpdate)));
    }
}