force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Asociados__c.field-meta.xml
<CustomField>
    <fullName>Asociados__c</fullName>
    <label>Asociados</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchAsociado.cls
global class ScheduleBatchAsociado implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
		Datetime lastUpdate = System.now();
		if (config != null && config.Asociados__c != null) {
			lastUpdate = config.Asociados__c;
		}
		//-----------------------------------------------------------------------
		//lastUpdate = Datetime.newInstance(2019, 12, 17, 12, 30, 2);
		//-----------------------------------------------------------------------
		Database.executeBatch(new MasterBatch(new AccountProcessor(100, lastUpdate)));
	}

}