force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Delegaciones__c.field-meta.xml
<CustomField>
    <fullName>Delegaciones__c</fullName>
    <label>Delegaciones</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchDelegacion.cls
global class ScheduleBatchDelegacion implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
		Datetime lastUpdate = System.now();
		if (config != null && config.Delegaciones__c != null) {
			lastUpdate = config.Delegaciones__c;
		}
		//-----------------------------------------------------------------------
//		lastUpdate = Datetime.newInstance(2020, 01, 20, 12, 30, 2);
		//-----------------------------------------------------------------------
		Database.executeBatch(new MasterBatch(new DelegacionProcessor(100, lastUpdate)));
	}

}