force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Medicamentos__c.field-meta.xml
<CustomField>
    <fullName>Medicamentos__c</fullName>
    <label>Medicamentos</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleBatchMedicamentos.cls
global class ScheduleBatchMedicamentos implements Schedulable {
	
	global void execute(SchedulableContext sc) {
		MasterConfigs__c config = MasterConfigs__c.getOrgDefaults();
		Datetime lastUpdate = System.now();
		if (config != null && config.Medicamentos__c != null) {
			lastUpdate = config.Medicamentos__c;
		}
		//-----------------------------------------------------------------------
		//lastUpdate = Datetime.newInstance(2019, 01, 01, 12, 30, 2);
		//-----------------------------------------------------------------------
		Database.executeBatch(new MasterBatch(new MedicamentosProcessor(100, lastUpdate)));
	}
}