force-app/main/default/objects/Case/fields/Ap_autorizada__c.field-meta.xml
<CustomField>
    <fullName>Ap_autorizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se utiliza para marcar con un trigger cuando todas las alertas de todas las prestaciones se resuelven o no tienen alertas</description>
    <label>Ap autorizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/Medicamento__c.object-meta.xml
<CustomObject>
    <label>Medicamento</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Medicamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORÍA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Medicamento__c.field-meta.xml
<CustomField>
    <fullName>Medicamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medicamento</label>
    <referenceTo>Medicamento__c</referenceTo>
    <relationshipLabel>Prestaciones</relationshipLabel>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Medicamento__c.field-meta.xml
<CustomField>
    <fullName>Medicamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medicamento</label>
    <referenceTo>Medicamento__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/recordTypes/Medicamento.recordType-meta.xml
<RecordType>
    <fullName>Medicamento</fullName>
    <active>true</active>
    <label>Medicamento</label>
</RecordType>

force-app/main/default/classes/PrestacionTriggerHelper.cls
public class PrestacionTriggerHelper  {
	public static void authorizeCases(Set<String> idCases) {
		//Set<Id> idCases = new Set<Id>();
		Case[] casesToAuthorize = new List<Case>();

		//for(Prestacion_de_reintegro__c prest : prestaciones) {
			//idCases.add(prest.Caso__c);
		//}
		  
		Case[] cases = [
			SELECT Id, Status, RecordTypeId,
				(SELECT Id, Estado__c FROM Prestaciones__r)
			FROM Case
			WHERE Id IN :idCases
		];

		for(Case aCase : cases) {
			Boolean authorize = true;
			
			for(Prestacion__c prest : aCase.Prestaciones__r) {
				if(prest.Estado__c != 'C1----AS' && prest.Estado__c != 'C1EA--AA') {
					authorize = false;
				}
			}

			if(authorize) {
				if(aCase.Status != 'Autorizada') {
					aCase.Cambio_Manual__c = false;
					aCase.Ap_autorizada__c = true;
				
					if(aCase.Status != 'CA-----E' && aCase.Status != 'CA-----N') {
						aCase.Status = 'Autorizada';
					}

					casesToAuthorize.add(aCase);
				}
			}
		}

		update casesToAuthorize;
		
	}

	public static void validateDuplicateNomencladorOrMedicamento(Prestacion__c[] prestaciones) {
		Set<Id> idCases = new Set<Id>();

		for(Prestacion__c prest : prestaciones) {
			if(prest.Ap__c != null) {
				idCases.add(prest.Ap__c);
			}
		}

		Map<Id, Case> casesById = new Map<Id, Case>([
			SELECT Id, Status, RecordTypeId,
				(SELECT Id, Estado__c, Prestacion__c, Medicamento__c FROM Prestaciones__r)
			FROM Case
			WHERE Id IN :idCases
		]);


		for(Prestacion__c prestToValidate : prestaciones) {
			
			for(Prestacion__c prestFromQuery : casesById.get(prestToValidate.Ap__c).Prestaciones__r) {
				if(prestToValidate.Id != prestFromQuery.Id 
					&& prestToValidate.Prestacion__c == prestFromQuery.Prestacion__c
					&& prestToValidate.Prestacion__c != null
				) {
					prestToValidate.addError('No se permite cargar dos prestaciones con el mismo nomenclador al mismo caso');
				}

				if(prestToValidate.Id != prestFromQuery.Id 
					&& prestToValidate.Medicamento__c == prestFromQuery.Medicamento__c
					&& prestToValidate.Medicamento__c != null
				) {
					prestToValidate.addError('No se permite cargar dos prestaciones con el mismo medicamento al mismo caso');
				}	
			} 
			
		}

	}

	public static void deleteWhenCasesStatusIsNotCentroAutorizador(Map<Id, Prestacion__c> prestacionesById) {
		Prestacion__c[] prestacionesWithCaseStatus = [
			SELECT Id, Ap__r.Status FROM Prestacion__c 
			WHERE Id IN :prestacionesById.values()
		];
		User usuario = [SELECT Id, Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
		Boolean isAdmin = usuario.Profile.Name == 'Administrador del sistema';

		if(!isAdmin) {
			for(Prestacion__c prest : prestacionesWithCaseStatus) {
				if(prest.Ap__r.Status != 'CA-----G') {
					Prestacion__c prestToAddError = prestacionesById.get(prest.Id);
					prestToAddError.addError('El caso debe estar en estado "Generada" para poder eliminar prestaciones');
				}
			}
		}
	}
}