force-app/main/default/objects/Case/fields/AP_Material__c.field-meta.xml
<CustomField>
    <fullName>AP_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP Material</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/AP_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>AP_Presupuesto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP Presupuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Categorizacion_SS__c.field-meta.xml
<CustomField>
    <fullName>Categorizacion_SS__c</fullName>
    <label>Categorización SS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baja complejidad</fullName>
            </value>
            <value>
                <fullName>Alta complejidad</fullName>
            </value>
            <value>
                <fullName>Posible preexistencia</fullName>
            </value>
            <value>
                <fullName>ACM / No nomencladas</fullName>
            </value>
            <value>
                <fullName>Cubiertos</fullName>
            </value>
            <value>
                <fullName>Cubiertos por PMI madre</fullName>
            </value>
            <value>
                <fullName>Cubiertos solo PMI hijo</fullName>
            </value>
            <value>
                <fullName>Cubierto con AP</fullName>
            </value>
            <value>
                <fullName>Cubierto solo por programa</fullName>
            </value>
            <value>
                <fullName>No cubiertos</fullName>
            </value>
            <value>
                <fullName>Cubiertos por provision</fullName>
                <label>Cubiertos por provisión</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_de_solicitud_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud_SS__c</fullName>
    <label>Nro de solicitud SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_tipo__c.field-meta.xml
<CustomField>
    <fullName>Sub_tipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cuota</fullName>
            </value>
            <value>
                <fullName>Oxi cronico</fullName>
                <label>Oxi crónico</label>
            </value>
            <value>
                <fullName>Oxi terapia</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Presupuesto</fullName>
            </value>
            <value>
                <fullName>Idom</fullName>
            </value>
            <value>
                <fullName>Psiquiatrico</fullName>
                <label>Psiquiátrico</label>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
                <label>Rehabilitación</label>
            </value>
            <value>
                <fullName>Clinico</fullName>
            </value>
            <value>
                <fullName>Quirurgico</fullName>
            </value>
            <value>
                <fullName>Aportes</fullName>
            </value>
            <value>
                <fullName>Libre de deuda</fullName>
            </value>
            <value>
                <fullName>Capital cooperativo</fullName>
            </value>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Autorizacion online</fullName>
            </value>
            <value>
                <fullName>Validacion en Prestador</fullName>
            </value>
            <value>
                <fullName>Reclamo obra social</fullName>
            </value>
            <value>
                <fullName>Error en datos del asociado</fullName>
            </value>
            <value>
                <fullName>Cargas sociales</fullName>
            </value>
            <value>
                <fullName>Por debito automatico</fullName>
            </value>
            <value>
                <fullName>No imputados</fullName>
            </value>
            <value>
                <fullName>Diferencia de pagos</fullName>
            </value>
            <value>
                <fullName>Aplicacion de  saldos</fullName>
            </value>
            <value>
                <fullName>Devoluciones</fullName>
            </value>
            <value>
                <fullName>Bonificaciones</fullName>
            </value>
            <value>
                <fullName>Reclamo por aumento indebido</fullName>
            </value>
            <value>
                <fullName>Error de datos personales</fullName>
            </value>
            <value>
                <fullName>Error en plan asignados</fullName>
            </value>
            <value>
                <fullName>Reclamos por ajustes de cuotas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tiempo_SLA__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_SLA__c</fullName>
    <label>Tiempo SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>96</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>144</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>240</fullName>
            </value>
            <value>
                <fullName>480</fullName>
            </value>
            <value>
                <fullName>1 Legal</fullName>
            </value>
            <value>
                <fullName>2 Legales</fullName>
            </value>
            <value>
                <fullName>3 Legales</fullName>
            </value>
            <value>
                <fullName>5 Legales</fullName>
            </value>
            <value>
                <fullName>8 Legales</fullName>
            </value>
            <value>
                <fullName>10 Legales</fullName>
            </value>
            <value>
                <fullName>15 Legales</fullName>
            </value>
            <value>
                <fullName>360</fullName>
            </value>
            <value>
                <fullName>120 Legales</fullName>
                <isActive>false</isActive>
                <label>120 Legales</label>
            </value>
            <value>
                <fullName>24 Legales</fullName>
                <isActive>false</isActive>
                <label>24 Legales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/AP_material__c.field-meta.xml
<CustomField>
    <fullName>AP_material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP material</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/AP_presupuesto__c.field-meta.xml
<CustomField>
    <fullName>AP_presupuesto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP presupuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_de_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de solicitud</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Usuario_error__c.field-meta.xml
<CustomField>
    <fullName>Usuario_error__c</fullName>
    <label>Usuario error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Semid__c.field-meta.xml
<CustomField>
    <fullName>Semid__c</fullName>
    <externalId>true</externalId>
    <label>Sem_id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ArchivosReintentoCargaBatchTest.cls
@isTest 
private class ArchivosReintentoCargaBatchTest {

	static XHttpCalloutMock getSuccessResponse;
	static XHttpCalloutMock getErrorResponse;

	static{
		getSuccessResponse = new XHttpCalloutMock();
        getSuccessResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getSuccessResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSArchivosCargaMock.getFound())
                .addForAddress(WSArchivosCarga.SERVICE_CONFIG.URL__c + '/v1/salud/archivos');
        getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('Error al cargar archivos.')
                .withStatusCode(422)
                .withBody(WSArchivosCargaMock.getError())
                .addForAddress(WSArchivosCarga.SERVICE_CONFIG.URL__c + '/v1/salud/archivos');
	}

	@isTest
	private static void reintentoDeEnvioArchivosExitoso() {
		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		Case nCase = new Case(
            Type='Prestacion',
            RecordTypeId = XappiaHelper.getRecordType('Case','Autorizacion_previa').Id,
            Sub_tipo__c= 'Presupuesto',
            Categorizacion_SS__c = 'Alta complejidad',
            AP_Presupuesto__c = false, 
            AP_Material__c = false,
			Tiempo_SLA__c = '72',
			Nro_de_solicitud_SS__c = '123'
        );
		insert nCase;

		ContentVersion ver1 = new ContentVersion();
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';

		insert ver1;

		ContentVersion cv = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver1.Id
		];

		
		ContentDocumentLink contLink = new ContentDocumentLink();
		contLink.ContentDocumentId = cv.ContentDocumentId;
		contLink.LinkedEntityId =nCase.Id;
		contLink.ShareType = 'V';
		insert contLink;
		
		/*ContentVersion ver2 = new ContentVersion();
		ver2.VersionData = Blob.valueOf('test 2');
		ver2.Title = 'test 2';
		ver2.PathOnClient = '/test2';
		ver2.Error_al_enviar__c = 'error';
		ver2.Fecha_de_error__c = Datetime.now();
		ver2.Id_reintento__c = '123';
		ver2.Tipo_entidad_error__c = 'autorizacion';

		insert ver2;*/

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		//ver2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver2.Id];

		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();


		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
		/*ver2 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver2.ContentDocumentId AND IsLatest = true
			];*/

		System.assertEquals(true, ver1.Enviado__c);
		//System.assertEquals(true, ver2.Enviado__c);
		System.assertEquals(null, ver1.Error_al_enviar__c);
		//System.assertEquals(null, ver2.Error_al_enviar__c);
		System.assertEquals(null, ver1.Id_reintento__c);
		//System.assertEquals(null, ver2.Id_reintento__c);


	}


		@isTest
	private static void reintentoDeEnvioArchivosNoExitoso() {
		Test.setMock(HttpCalloutMock.class, getErrorResponse);
		

		ContentVersion ver1 = new ContentVersion();
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';
		ver1.Usuario_error__c = 'CRIOS';

		insert ver1;

		
		ContentVersion ver2 = new ContentVersion();
		ver2.VersionData = Blob.valueOf('test 2');
		ver2.Title = 'test 2';
		ver2.PathOnClient = '/test2';
		ver2.Error_al_enviar__c = 'error';
		ver2.Fecha_de_error__c = Datetime.now();
		ver2.Id_reintento__c = '1234';
		ver2.Tipo_entidad_error__c = 'autorizacion';
		ver2.Usuario_error__c = 'CRIOS';

		insert ver2;

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		ver2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver2.Id];

		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();

		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
		ver2 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver2.ContentDocumentId AND IsLatest = true
			];

		System.assertEquals(false, ver1.Enviado__c);
		System.assertEquals(false, ver2.Enviado__c);
		//System.assertEquals('El id ingresado no coincide con un evento medico valido.', ver1.Error_al_enviar__c);
		//System.assertEquals('El id ingresado no coincide con un evento medico valido.', ver2.Error_al_enviar__c);
		System.assertEquals('123', ver1.Id_reintento__c);
		System.assertEquals('1234', ver2.Id_reintento__c);


	}

	@isTest
	public static void ifTheFileHaveACaseAssociateMustTakeTheDataFromThatObject(){

		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		Case nCase = new Case(
            Type='Prestacion',
            RecordTypeId = XappiaHelper.getRecordType('Case','Autorizacion_previa').Id,
            Sub_tipo__c= 'Presupuesto',
            Categorizacion_SS__c = 'Alta complejidad',
            AP_Presupuesto__c = false, 
            AP_Material__c = false,
			Tiempo_SLA__c = '72',
			Nro_de_solicitud_SS__c = '123'
        );

		insert nCase;

		/*ContentDocument doc = new ContentDocument();
		insert doc;*/


		ContentVersion ver1 = new ContentVersion();
		ver1.Title = 'TESTAWSTRIGGER';
		ver1.VersionData = Blob.valueOf('TESTAWSTRIGGER');
		ver1.PathOnClient = '/TESTAWSTRIGGER.TXT';
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';

		insert ver1;

		ContentVersion cv = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver1.Id
		];
		
		ContentDocumentLink contLink = new ContentDocumentLink();
		contLink.ContentDocumentId = cv.ContentDocumentId;
		contLink.LinkedEntityId =nCase.Id;
		contLink.ShareType = 'V';
		insert contLink;
		
		ContentVersion ver2 = new ContentVersion();
		ver2.VersionData = Blob.valueOf('test 2');
		ver2.Title = 'test 2';
		ver2.PathOnClient = '/test2';
		ver2.Error_al_enviar__c = 'error';
		ver2.Fecha_de_error__c = Datetime.now();
		ver2.Id_reintento__c = '123';
		ver2.Tipo_entidad_error__c = 'autorizacion';
		

		insert ver2;

		ContentVersion cv2 = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver2.Id
		];
		
		ContentDocumentLink contLink2 = new ContentDocumentLink();
		contLink2.ContentDocumentId = cv2.ContentDocumentId;
		contLink2.LinkedEntityId =nCase.Id;
		contLink2.ShareType = 'V';
		insert contLink2;
		

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		ver2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver2.Id];

		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();


		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
		ver2 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver2.ContentDocumentId AND IsLatest = true
			];

		System.assertEquals(true, ver1.Enviado__c);
		System.assertEquals(true, ver2.Enviado__c);
		System.assertEquals(null, ver1.Error_al_enviar__c);
		System.assertEquals(null, ver2.Error_al_enviar__c);
		System.assertEquals(null, ver1.Id_reintento__c);
		System.assertEquals(null, ver2.Id_reintento__c);

	}

	@isTest
	public static void ifTheFileHaveASegmentoAssociateMustTakeTheDataFromThatObject(){

		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		Segmentos__c seg = new Segmentos__c(Semid__c = '111');
		insert seg;

		/*ContentDocument doc = new ContentDocument();
		insert doc;*/


		ContentVersion ver1 = new ContentVersion();
		ver1.Title = 'TESTAWSTRIGGER';
		ver1.VersionData = Blob.valueOf('TESTAWSTRIGGER');
		ver1.PathOnClient = '/TESTAWSTRIGGER.TXT';
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';

		insert ver1;

		ContentVersion cv = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver1.Id
		];
		
		ContentDocumentLink contLink = new ContentDocumentLink();
		contLink.ContentDocumentId = cv.ContentDocumentId;
		contLink.LinkedEntityId =seg.Id;
		contLink.ShareType = 'V';
		insert contLink;
		
		ContentVersion ver2 = new ContentVersion();
		ver2.VersionData = Blob.valueOf('test 2');
		ver2.Title = 'test 2';
		ver2.PathOnClient = '/test2';
		ver2.Error_al_enviar__c = 'error';
		ver2.Fecha_de_error__c = Datetime.now();
		ver2.Id_reintento__c = '123';
		ver2.Tipo_entidad_error__c = 'autorizacion';
		

		insert ver2;

		ContentVersion cv2 = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver2.Id
		];
		
		ContentDocumentLink contLink2 = new ContentDocumentLink();
		contLink2.ContentDocumentId = cv2.ContentDocumentId;
		contLink2.LinkedEntityId =seg.Id;
		contLink2.ShareType = 'V';
		insert contLink2;
		

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		ver2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver2.Id];

		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();


		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
		ver2 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver2.ContentDocumentId AND IsLatest = true
			];

		System.assertEquals(true, ver1.Enviado__c);
		System.assertEquals(true, ver2.Enviado__c);
		System.assertEquals(null, ver1.Error_al_enviar__c);
		System.assertEquals(null, ver2.Error_al_enviar__c);
		System.assertEquals(null, ver1.Id_reintento__c);
		System.assertEquals(null, ver2.Id_reintento__c);

	}


	@isTest
	public static void ifTheFileHaveAEventoMedicoAssociateMustTakeTheDataFromThatObject(){

		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		Evento_medico__c em = new Evento_medico__c();
		em.Nro_de_Evento_Medico_SS__c = '1234';
        insert em;

		/*ContentDocument doc = new ContentDocument();
		insert doc;*/


		ContentVersion ver1 = new ContentVersion();
		ver1.Title = 'TESTAWSTRIGGER';
		ver1.VersionData = Blob.valueOf('TESTAWSTRIGGER');
		ver1.PathOnClient = '/TESTAWSTRIGGER.TXT';
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';

		insert ver1;

		ContentVersion cv = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver1.Id
		];
		
		ContentDocumentLink contLink = new ContentDocumentLink();
		contLink.ContentDocumentId = cv.ContentDocumentId;
		contLink.LinkedEntityId =em.Id;
		contLink.ShareType = 'V';
		insert contLink;
		
		/*ContentVersion ver2 = new ContentVersion();
		ver2.VersionData = Blob.valueOf('test 2');
		ver2.Title = 'test 2';
		ver2.PathOnClient = '/test2';
		ver2.Error_al_enviar__c = 'error';
		ver2.Fecha_de_error__c = Datetime.now();
		ver2.Id_reintento__c = '123';
		ver2.Tipo_entidad_error__c = 'autorizacion';
		

		insert ver2;*/

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		//ver2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver2.Id];

		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();


		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
		/*ver2 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver2.ContentDocumentId AND IsLatest = true
			];*/

		System.assertEquals(true, ver1.Enviado__c);
		//System.assertEquals(true, ver2.Enviado__c);
		System.assertEquals(null, ver1.Error_al_enviar__c);
		//System.assertEquals(null, ver2.Error_al_enviar__c);
		System.assertEquals(null, ver1.Id_reintento__c);
		//System.assertEquals(null, ver2.Id_reintento__c);

	}


	@isTest
	public static void ifTheFileHaveAnOpportunityAssociateMustTakeTheDataFromThatObject(){

		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		Opportunity opp = new Opportunity();
		opp.Name = 'Test opp';
		opp.StageName = 'En Edición';
		opp.CloseDate = Date.today().addDays(15);
		opp.Nro_de_Solicitud__c = '1234';
        insert opp;

		/*ContentDocument doc = new ContentDocument();
		insert doc;*/


		ContentVersion ver1 = new ContentVersion();
		ver1.Title = 'TESTAWSTRIGGER';
		ver1.VersionData = Blob.valueOf('TESTAWSTRIGGER');
		ver1.PathOnClient = '/TESTAWSTRIGGER.TXT';
		ver1.VersionData = Blob.valueOf('test 1');
		ver1.Title = 'test 1';
		ver1.PathOnClient = '/test';
		ver1.Error_al_enviar__c = 'error';
		ver1.Fecha_de_error__c = Datetime.now();
		ver1.Id_reintento__c = '123';
		ver1.Tipo_entidad_error__c = 'evento_medico';

		insert ver1;

		ContentVersion cv = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE Id = :ver1.Id
		];
		
		ContentDocumentLink contLink = new ContentDocumentLink();
		contLink.ContentDocumentId = cv.ContentDocumentId;
		contLink.LinkedEntityId =opp.Id;
		contLink.ShareType = 'V';
		insert contLink;

		ver1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver1.Id];
		
		Test.startTest();
		Database.executeBatch(new ArchivosReintentoCargaBatch());
		Test.stopTest();


		ver1 = [
				SELECT Enviado__c, Error_al_enviar__c, Id_reintento__c, Fecha_de_error__c, Tipo_entidad_error__c 
				FROM ContentVersion 
				WHERE ContentDocumentId = :ver1.ContentDocumentId AND IsLatest = true
			];
	

		System.assertEquals(true, ver1.Enviado__c);
		
		System.assertEquals(null, ver1.Error_al_enviar__c);
		
		System.assertEquals(null, ver1.Id_reintento__c);
		

	}
}