force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Contiene_alerta_AM__c.field-meta.xml
<CustomField>
    <fullName>Contiene_alerta_AM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contiene alerta AM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Derivacion_de_lote__c.field-meta.xml
<CustomField>
    <fullName>Derivacion_de_lote__c</fullName>
    <label>Derivacion de lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lote Vigente</fullName>
                <default>true</default>
                <label>Lote Vigente</label>
            </value>
            <value>
                <fullName>Lote Devolucion</fullName>
            </value>
            <value>
                <fullName>Lote Pendiente</fullName>
            </value>
            <value>
                <fullName>Lote Especial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Estado_de_documentacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_documentacion__c</fullName>
    <label>Estado de documentación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solicitar documentacion</fullName>
            </value>
            <value>
                <fullName>Documentacion faltante</fullName>
                <label>Documentacion pedida al socio</label>
            </value>
            <value>
                <fullName>Documentacion finalizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FormulatiempoSLA__c.field-meta.xml
<CustomField>
    <fullName>FormulatiempoSLA__c</fullName>
    <formula>IF(IsClosedOnCreate, &apos;&apos;, TEXT(Tiempo_SLA__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FormulatiempoSLA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Medico_asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Médico asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Auditor Medico</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Coordinador de Mesa de Ayuda</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsable_de_presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_presupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable presupuesto / compras</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Casos_responsable_presupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Retencion_Lograda__c.field-meta.xml
<CustomField>
    <fullName>Retencion_Lograda__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retención Lograda</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sin_alertas_AM_pendientes__c.field-meta.xml
<CustomField>
    <fullName>Sin_alertas_AM_pendientes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sin alertas AM pendientes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Caso_a_tipificar.recordType-meta.xml
<RecordType>
    <fullName>Caso_a_tipificar</fullName>
    <active>true</active>
    <businessProcess>Caso a tipificar</businessProcess>
    <label>Caso a tipificar</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Internacion.recordType-meta.xml
<RecordType>
    <fullName>Internacion</fullName>
    <active>true</active>
    <businessProcess>Internacion</businessProcess>
    <label>Internación</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_alta_familiar.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_alta_familiar</fullName>
    <active>true</active>
    <businessProcess>Solicitud alta familiar</businessProcess>
    <label>Solicitud de alta familiar</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_datos_particulares.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_datos_particulares</fullName>
    <active>true</active>
    <businessProcess>Solicitud de datos particulares</businessProcess>
    <label>Solicitud de datos particulares</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_despegues.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_despegues</fullName>
    <active>true</active>
    <businessProcess>Solicitud de despegue</businessProcess>
    <label>Solicitud de despegues</label>
</RecordType>

force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Cambio_Manual__c.field-meta.xml
<CustomField>
    <fullName>Cambio_Manual__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Cambio Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**-----------------------------------------------------------------------------------------------------------------------
@author			Jeferson Ruiz.
@description	Clase manejadora del desencadenador para el objeto Case
@date			08/12/2021
------------------------------------------------------------------------------------------------------------------------*/
@SuppressWarnings('PMD.ApexCRUDViolation')
public with sharing class CaseTriggerHandler extends TriggerHandler {
	List<Case> lNew = (List<Case>) Trigger.new;
	List<Case> lOld = (List<Case>) Trigger.old;
	Map<Id,Case> mNew = (Map<Id,Case>) Trigger.newMap;
	Map<Id,Case> mOld = (Map<Id,Case>) Trigger.oldMap;
	/** Variables */
	private static Id casoATipificarRtId = XappiaHelper.getRecordType('Case', 'Caso_a_tipificar').Id;
	private static Id solicitudDeDatosParticulares = XappiaHelper.getRecordType('Case','Solicitud_de_datos_particulares').Id;
	private static Id apRtId = XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id;
	private static Id internacionRtId = XappiaHelper.getRecordType('Case', 'Internacion').Id;
	private static Id reintegroRtId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
	private static Id seguimientoRtId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
	private static List<Id> casosValidosActualizarStatus = new List<Id>{
		XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id,
		XappiaHelper.getRecordType('Case', 'Reintegro').Id,
		XappiaHelper.getRecordType('Case', 'Internacion').Id,
		XappiaHelper.getRecordType('Case', 'Seguimiento').Id,
		XappiaHelper.getRecordType('Case', 'Solicitud_de_alta_familiar').Id,
		XappiaHelper.getRecordType('Case', 'Solicitud_de_despegues').Id
	};
	public override void beforeInsert() {
		List<Case> casesToChangeDelegacionFront = new List<Case>();
		CaseTriggerHelper.checkDuplicateDNIOnAltaFamiliar(lNew);
		caseLiveChatHelper.assignAccounts(lNew);
		SLAUtils.assignEntitlements(lNew);
		CaseTriggerHelper.avoidCreationOfReintegroWithALoteThatIsClosed(lNew);
	}
	public override void beforeUpdate() {
		CaseTriggerHelper.checkIfHaveEquipoDeCaso(lNew, mOld);
		CaseTriggerHelper.checkDuplicateDNIOnAltaFamiliar(lNew);
		CaseTriggerHelper.changeStatusToClosed(lNew, mOld);
		Set<Id> casesIdBaja = new Set<Id>();
		List<Case> casesToUpdateStatus = new List<Case>();
		List<Case> casesToChangeDelegacion = new List<Case>();
		List<Case> updatedCases = new List<Case>();
		List<Case> casesWhereEstadoDeDocumentacionIsChanged = new List<Case>();
		List<Case> casesToCloseSla = new List<Case>();
		List<Case> casesWithMedicoAsignadoChangedAndOldInNull = new List<Case>();
		List<Case> casesWithMedicoAsignadoChangedAndOldNotNull = new List<Case>();
		List<Case> casesWithResponsableChangedAndOldInNull = new List<Case>();
		List<Case> casesWithResponsableChangedAndOldNotNull = new List<Case>();
		List<Case> casesWithResponsablePresuChangedAndOldInNull = new List<Case>();
		List<Case> casesWithResponsablePresuChangedAndOldNotNull = new List<Case>();
		List<Case> casesToUpdateFieldsOnEM = new List<Case>();
		List<Case> casesToChangeLote = new List<Case>();
		Map<Id, Case> casesToReopenSLAById = new Map<Id, Case>();
		for(Case caso : lNew) {
			Case oldCase = mOld.get(caso.Id);
			Boolean rtToValidateResp = caso.RecordTypeId == seguimientoRtId
										|| caso.RecordTypeId == internacionRtId
										|| caso.RecordTypeId == reintegroRtId
										|| caso.RecordTypeId == apRtId;
			Boolean isFromEM = String.isNotBlank(caso.Evento_Medico__c)
								&& (caso.RecordTypeId == seguimientoRtId
									|| caso.RecordTypeId == internacionRtId);
			if(oldCase.RecordTypeId == casoATipificarRtId && oldCase.RecordTypeId != caso.RecordTypeId){
				caso.Cambio_Manual__c = false;
				caso.Usuario__c = null;
				if(caso.Type == null){
					Case dummyCase = (Case)Case.sObjectType.newSObject(caso.RecordTypeId,true);
					caso.Type = dummyCase.Type;
				}
				casesToChangeDelegacion.add(caso);
				if(casosValidosActualizarStatus.contains(caso.RecordTypeId)){
					casesToUpdateStatus.add(caso);
				}else if(caso.RecordTypeId == solicitudDeDatosParticulares){
					caso.SuppliedEmail = '';
				}
			}
			if(oldCase.Medico_asignado__c != caso.Medico_asignado__c && rtToValidateResp) {
				if (oldCase.Medico_asignado__c == null) {
					casesWithMedicoAsignadoChangedAndOldInNull.add(caso);
				}
				else {
					casesWithMedicoAsignadoChangedAndOldNotNull.add(caso);
				}
			}
			if(oldCase.Responsable_de_presupuesto__c != caso.Responsable_de_presupuesto__c && rtToValidateResp) {
				if (oldCase.Responsable_de_presupuesto__c == null) {
					casesWithResponsablePresuChangedAndOldInNull.add(caso);
				}
				else {
					casesWithResponsablePresuChangedAndOldNotNull.add(caso);
				}
			}
			if(oldCase.Usuario__c != caso.Usuario__c && rtToValidateResp && oldCase.RecordTypeId != casoATipificarRtId) {
				if (oldCase.Usuario__c == null) {
					casesWithResponsableChangedAndOldInNull.add(caso);
				}
				else {
					casesWithResponsableChangedAndOldNotNull.add(caso);
				}
			}
			if((caso.Status == 'CA-----G' && oldCase.Status == 'Rechazado')
				|| (!caso.Caso_Rechazado__c && oldCase.Caso_Rechazado__c)) {
				casesToReopenSLAById.put(caso.Id, caso);
			}
			if(caso.FormulatiempoSLA__c != oldCase.FormulatiempoSLA__c
				|| (caso.AccountId != oldCase.AccountId && oldCase.AccountId == null)) {
				updatedCases.add(caso);
			}
			if(caso.Estado_de_documentacion__c != oldCase.estado_de_documentacion__c
				&& caso.Estado_de_documentacion__c != 'Documentacion faltante'){
				casesWhereEstadoDeDocumentacionIsChanged.add(caso);
			}
			if(isFromEM && CaseTriggerHelper.hasChangesSomeFieldToUpdateEM(caso, oldCase)) {
				casesToUpdateFieldsOnEM.add(caso);
			}
			if((!oldCase.Retencion_lograda__c && caso.Retencion_lograda__c) && caso.Origin == 'Web'){
				casesIdBaja.add(caso.Id);
			}
			if(caso.RecordTypeId == reintegroRTId && caso.Status == 'Rechazado'){
				caso.Derivacion_de_lote__c	= 'Lote Devolucion';
				casesToChangeLote.add(caso);
			}
		}
		if(!casesToChangeLote.isEmpty()){
			if(!Test.isRunningTest()){
				Lote__c lote;
				if(ConfigUtils.isSandboxEnviroment()){
					lote = [SELECT Id, Name FROM Lote__c WHERE Name = 'LOTE-0004'];
				}else{
					lote = [SELECT Id,Name FROM Lote__c WHERE Name = 'LOTE-0001'];
				}
				for(Case caso : casesToChangeLote){
					caso.Lote__c = lote.Id;
				}
			}
		}
		if(!casesToChangeDelegacion.isEmpty()){
			CaseTriggerHelperWithoutSharing.cambiarDelegacionCDC(casesToChangeDelegacion);
		}
		if(!casesToUpdateStatus.isEmpty()){
			CaseTriggerHelperWithoutSharing.changeStateToDefaultPicklist(casesToUpdateStatus);
		}
		if(!casesIdBaja.isEmpty()){
			CaseTriggerHelper.darDeBajaCasos(casesIdBaja);
		}
		if(!casesToReopenSLAById.isEmpty()) {
			SLAUtils.reopenSLA(casesToReopenSLAById);
		}
		if(!updatedCases.isEmpty()) {
			SLAUtils.assignEntitlements(updatedCases);
		}
		if(!casesWithMedicoAsignadoChangedAndOldInNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldInNull(casesWithMedicoAsignadoChangedAndOldInNull, 'medico');
		}
		if(!casesWithMedicoAsignadoChangedAndOldNotNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldNotNull(casesWithMedicoAsignadoChangedAndOldNotNull, 'medico');
		}
		if(!casesWithResponsableChangedAndOldInNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldInNull(casesWithResponsableChangedAndOldInNull, 'responsable');
		}
		if(!casesWithResponsableChangedAndOldNotNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldNotNull(casesWithResponsableChangedAndOldNotNull, 'responsable');
		}
		if(!casesWithResponsablePresuChangedAndOldInNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldInNull(casesWithResponsablePresuChangedAndOldInNull, 'presupuesto');
		}
		if(!casesWithResponsablePresuChangedAndOldNotNull.isEmpty()) {
			CaseTriggerHelper.validateMedicoAsignadoOldNotNull(casesWithResponsablePresuChangedAndOldNotNull, 'presupuesto');
		}
		if(casesWhereEstadoDeDocumentacionIsChanged.size() > 0) {
			CaseTriggerHelper.derivaconAlCompletarDocumentacion(casesWhereEstadoDeDocumentacionIsChanged);
		}
		if(!casesToUpdateFieldsOnEM.isEmpty()) {
			CaseTriggerHelper.updateFieldsOnEM(casesToUpdateFieldsOnEM);
		}
	}
	public override void beforeDelete() {
		// Nothing
	}
	public override void afterInsert() {
		Map<Id, List<Case>> userIdCasesMap = new Map<Id, List<Case>>();
		List<Id> casesToChangeDelegacionFront = new List<Id>();
		for (Case caso : lNew) {
			if(caso.RecordTypeId == casoATipificarRtId){
				casesToChangeDelegacionFront.add(caso.Id);
			}
			if (userIdCasesMap.containsKey(caso.OwnerId)) {
				List<Case> casesFromMap = userIdCasesMap.get(caso.OwnerId);
				casesFromMap.add(new Case(Id = caso.Id));
				userIdCasesMap.put(caso.OwnerId, casesFromMap);
			} else {
				userIdCasesMap.put(caso.OwnerId, new List<Case>{new Case(Id = caso.Id)});
			}
		}
		if (!userIdCasesMap.isEmpty()) {
			CaseTriggerHelper.assignDelegacionFromUser(userIdCasesMap);
		}
		if(!casesToChangeDelegacionFront.isEmpty()){
			CaseTriggerHelperWithoutSharing.cambiarDelegacionFront(casesToChangeDelegacionFront);
		}
	}
	public override void afterUpdate() {
		List<Case> reintegrosAReasignar =  new List<Case>();
		Map<Id, String> mapCases = new Map<Id, String>();
		Case[] casesChangeAlertAMPending = new List<Case>();
		Map<Id, Case> casesToReopenSLAById = new Map<Id, Case>();
		Boolean isAsync = System.isFuture() || System.isQueueable();
		for(Case caso : lNew){
			Case oldCase = mOld.get(caso.Id);
			Boolean changeContieneAlertaAM = caso.Contiene_alerta_AM__c != oldCase.Contiene_alerta_AM__c;
			Boolean changeSinAlertaAM = caso.Sin_alertas_AM_pendientes__c != oldCase.Sin_alertas_AM_pendientes__c;
			if(caso.RecordTypeId == reintegroRtId
				&& caso.Lote__c != mOld.get(caso.Id).Lote__c
				&& caso.Codigo_reintegro_SS__c != null) {
				reintegrosAReasignar.add(caso);
			}
			if(caso.Evento_Medico__c != null && (changeContieneAlertaAM || changeSinAlertaAM)) {
				casesChangeAlertAMPending.add(caso);
			}
			if(caso.RecordTypeId == XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id) {
				if(caso.Status == 'CA-----N') {
					mapCases.put( caso.Orden_de_Compra__c, 'Anulada');
				}

				else if(caso.Status == 'CA-----E') {
					mapCases.put(caso.Orden_de_Compra__c, 'Finalizada');
				}

				else if(caso.Status == 'Rechazado' || caso.caso_rechazado__c == true) {
					mapCases.put(caso.Orden_de_Compra__c, 'Rechazada');
				}
			}
		}
		List<Orden_de_Compra__c> ordenes = [SELECT Id,
												Estado_OC__c,
												(SELECT Id
													FROM Cotizaciones_Prestadores__r)
											FROM Orden_de_Compra__c
											WHERE Id IN :mapCases.keySet()];
		for (Orden_de_Compra__c orden : ordenes) {
			orden.Estado_OC__c = mapCases.get(orden.Id);
			if(orden.Estado_OC__c == 'Finalizada' && orden.Cotizaciones_Prestadores__r.isEmpty()) {
				orden.Estado_OC__c = 'Desestimada';
			}
		}
		update ordenes;
		if(!reintegrosAReasignar.isEmpty() && !isAsync) {
			System.enqueueJob(new ReintegroReasignacionQueueable(reintegrosAReasignar));
		}
		if(!casesChangeAlertAMPending.isEmpty()) {
			CaseTriggerHelper.checkNoAlertsPendingOnEM(casesChangeAlertAMPending);
		}
	}
	public override void afterDelete() {
		// Nothing
	}
	public override void afterUndelete() {
		// Nothing
	}
}