force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Derivacion_de_lote__c.field-meta.xml
<CustomField>
    <fullName>Derivacion_de_lote__c</fullName>
    <label>Derivacion de lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lote Vigente</fullName>
                <default>true</default>
                <label>Lote Vigente</label>
            </value>
            <value>
                <fullName>Lote Devolucion</fullName>
            </value>
            <value>
                <fullName>Lote Pendiente</fullName>
            </value>
            <value>
                <fullName>Lote Especial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Se utiliza para saber los errores de los lotes de reintegro</description>
    <inlineHelpText>Representa el error que puede devolver Salud soft</inlineHelpText>
    <label>Error</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestaciones_en_auditoria__c.field-meta.xml
<CustomField>
    <fullName>Prestaciones_en_auditoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestaciones en auditoría</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de cuenta</description>
    <formula>TEXT(Account.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Este campo se utiliza en regla de validación para bloquear registro para bloquear registro y podes codificarlo desde el boton &quot;Reabrir orden&quot;</description>
    <label>Bloqueo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Errores_reintegros__c.field-meta.xml
<CustomField>
    <fullName>Errores_reintegros__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Errores reintegros</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Flag_Deshace_Orden__c.field-meta.xml
<CustomField>
    <fullName>Flag_Deshace_Orden__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo usado para habilitar bonton de Deshace Orden</description>
    <label>Flag Deshace Orden</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Especial</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Devoluciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteGeneracionDeOrdenCtrl.cls
public class LoteGeneracionDeOrdenCtrl  {

	@AuraEnabled
    public static Response validarReintegrosEnAuditoria(String id_lote) {
		
		if(String.isBlank(id_lote)){
			return new Response(true, 'El lote no existe en SS');
		}

		Lote__c lote = [SELECT Id, Estado__c FROM Lote__c WHERE Id_lote_SS__c = :id_lote];
		List<Case> reintegros = [
            SELECT Id, Status, Codigo_reintegro_SS__c, CaseNumber, Caso_Rechazado__c, Prestaciones_en_auditoria__c
            FROM Case 
            WHERE Lote__c = :lote.Id
        ];
		String msg = 'Los siguientes reintegros tienen prestaciones en auditoría: \n';
		Boolean err = false;

		if(!reintegros.isEmpty()) {
			for(Case reintegro : reintegros) {
				if(reintegro.Prestaciones_en_auditoria__c && reintegro.Status == 'CA-----A') {
					err = true;
					msg += '- Nro en SF: ' + reintegro.CaseNumber + 
							'. Código en SS: ' + reintegro.Codigo_reintegro_SS__c + '\n';
				}
			}
		}

		if(err) {
			return new Response(err, msg);
		}
		
		return new Response(false, 'ok');
	}

	@AuraEnabled
    public static Response generacionDeOrden(String id_lote,String accion) {

		Lote__c lote = [SELECT Id, Estado__c,Errores_reintegros__c,Flag_Deshace_Orden__c,Bloqueo__c FROM Lote__c WHERE Id_lote_SS__c = :id_lote];

		User usuario = [SELECT Id,CommunityNickname FROM User WHERE Id = :UserInfo.getUserId()];
		String apodo = usuario.CommunityNickname != null ? usuario.CommunityNickname.toUpperCase() : null;

		String body = '{"accion":"'+ accion +'","usuario":"'+ apodo +'"}';
		System.debug('****body: ' + body);
		WSLoteGeneracionDeOrden.Response wsResponse =  WSLoteGeneracionDeOrden.generacionDeOrden(id_lote,body);
		System.debug('RESULTADO');
		System.debug(wsResponse);

        if(!wsResponse.hasError){
			lote.Estado__c = wsResponse.lote.data.lote.estado;
			lote.Bloqueo__c = false;
			if(lote.Estado__c == 'C' && accion == 'GENERAR'){
				lote.Flag_Deshace_Orden__c = true;
			}
			else{
				lote.Flag_Deshace_Orden__c = false;
			}
			
			Map<String,String> reintegrosWithError = new Map<String,String>();
			if(accion == 'GENERAR'){
				if(wsResponse.lote.data.lote.logs != null){
					lote.Errores_reintegros__c = true;
					for(WSLoteGeneracionDeOrdenResp.Logs log : wsResponse.lote.data.lote.logs){
						reintegrosWithError.put(log.rei_rei_id, log.texto);
					}
				}
			}else{
				lote.Errores_reintegros__c = false;
			}
			update lote;
			
            List<Case> reintegros = [
                SELECT Id, Status, Codigo_reintegro_SS__c, Error__c, Caso_Rechazado__c, Prestaciones_en_auditoria__c
                FROM Case 
                WHERE Lote__c = :lote.Id
            ];

			List<Id> reintegroIds = new List<Id>((new Map<Id,Case>(reintegros)).keySet());
			

			Case[] reintegrosToUpdate = new List<Case>();
			if(accion == 'GENERAR') {
				//System.enqueueJob(new ReintegroEmitirOrdenQueueable(reintegros, reintegrosWithError));
				emitirOrdenReintegros(reintegroIds, reintegrosWithError);
			}
			else {
				for(Case reintegro : reintegros){
					reintegro.Cambio_Manual__c = false;
					reintegro.Error__c = null;
					reintegro.Status = 'CA-----A';

					reintegrosToUpdate.add(reintegro);
					
				}

				update reintegrosToUpdate;
			}
            
            return new Response(false, wsResponse.lote.message);
        }
		return new Response(true, wsResponse.message);
    }

	@Future(callout=true)
	private static void emitirOrdenReintegros(List<Id> reintegroIds, Map<String,String> reintegrosWithError) {
		Map<Id, Case> reintegros = new Map<Id, Case>([
			SELECT Id, Status, Prestaciones_en_auditoria__c, Codigo_reintegro_SS__c, Caso_Rechazado__c, Lote__c
			FROM Case 
			WHERE Id IN :reintegroIds
		]);
		Lote__c[] lotePendiente = [SELECT Id, Tipo__c FROM Lote__c WHERE Tipo__c = 'Pendiente'];
		Case[] reintegrosToUpdate = new List<Case>();
		Case[] reintegrosPendientes = new List<Case>();
		Case[] reintegrosPendientesToReasignar = new List<Case>();
		Case[] reintegrosConError = new List<Case>();
		Integer i = 0;
		Integer cant = reintegroIds.size();

		for(i = 0; i < cant; i++) {			
			Id reintegroId = reintegroIds.remove(0);
			Case reintegro = reintegros.get(reintegroId);

			if(reintegrosWithError.containsKey(reintegro.Codigo_reintegro_SS__c)) {
				reintegro.Error__c = reintegrosWithError.get(reintegro.Codigo_reintegro_SS__c);

				reintegrosConError.add(reintegro);
			}
			else {
				reintegro.Cambio_Manual__c = false;
				reintegro.Error__c = null;
				if(reintegro.Status == 'CA-----G' || reintegro.Status == 'CA-----N' || reintegro.Caso_Rechazado__c) {
					reintegro.Derivacion_de_lote__c = 'Lote Pendiente';
					reintegro.Lote__c = lotePendiente.isEmpty() ? reintegro.Lote__c : lotePendiente[0].Id;
						
					if(String.isBlank(reintegro.Codigo_reintegro_SS__c)) {
						reintegrosPendientes.add(reintegro);
					}
					else {
						reintegrosPendientesToReasignar.add(reintegro);
					}

				} 
				else if(!reintegro.Prestaciones_en_auditoria__c 
						&& (reintegro.Status == 'CA-----A' || reintegro.Status == 'Autorizada')
				) {
					reintegro.Status = 'CA-----E';

					reintegrosToUpdate.add(reintegro);
				}
			}

		}

		Database.SaveResult[] resultsEmitir = Database.update(reintegrosToUpdate);
		System.debug('**** resultsEmitir: ' + resultsEmitir);

		Database.SaveResult[] resultsPendientes = Database.update(reintegrosPendientes);
		System.debug('**** resultsPendientes: ' + resultsPendientes);

		Database.SaveResult[] resultsReasignar = Database.update(reintegrosPendientesToReasignar);
		System.debug('**** resultsReasignar: ' + resultsReasignar);

		Database.SaveResult[] resultsReintegrosConError = Database.update(reintegrosConError);
		System.debug('**** resultsReintegrosConError: ' + resultsReintegrosConError);

		if(!reintegrosPendientesToReasignar.isEmpty()) {
			System.enqueueJob(new ReintegroReasignacionQueueable(reintegrosPendientesToReasignar));
		}
		
	}

    public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message){
            this.hasError = hasError;
            this.message = message;
        }
    }
}