force-app/main/default/objects/Case/fields/CBU__c.field-meta.xml
<CustomField>
    <fullName>CBU__c</fullName>
    <label>CBU</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Efector_realizador__c.field-meta.xml
<CustomField>
    <fullName>Efector_realizador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector realizador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <infoMessage>El valor no existe o no coinciden los criterios de filtro.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Importe_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Importe_reintegro__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/Nomenclador_de_Prestacion__c.object-meta.xml
<CustomObject>
    <label>Nomenclador de Prestación</label>
    <nameField>
        <label>Código Nomenclador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomenclador de Prestaciónes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_auditor__c</fullName>
    <label>Importe Reintegro auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacional__c.field-meta.xml
<CustomField>
    <fullName>Prestacional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestacion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Nomenclador_de_Prestacion__c.Descripcion_tipo_nomenclador__c</field>
            <operation>notContain</operation>
            <value>ODONTOLOGICAS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/recordTypes/Prestacional.recordType-meta.xml
<RecordType>
    <fullName>Prestacional</fullName>
    <active>true</active>
    <label>Prestacional</label>
</RecordType>

force-app/main/default/classes/prestacionReintegroBtnCtrlTest.cls
@isTest
public class prestacionReintegroBtnCtrlTest {
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getErrorResponse;
	static String body;
    static Prestacion_de_reintegro__c prest;
    static Case reintegro;

	static {
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSPrestacionActualizarImporteMock.getFound())
			.addForAddress(WSPrestacionActualizarImporte.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/' + 553277 + '/prestaciones/' + 74043157 + '/importe');

		getErrorResponse = new XHttpCalloutMock();
		getErrorResponse.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getErrorResponse.buildResponse()
			.withStatus('Not Found')
			.withStatusCode(404)
			.withBody(WSPrestacionActualizarImporteMock.getError())
            .addForAddress(WSPrestacionActualizarImporte.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/' + 0 + '/prestaciones/' + 0 + '/importe');
            
        reintegro = new Case();
        reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
        reintegro.Status = 'Generada';
        reintegro.Type = 'Prestacion';
        reintegro.Importe_reintegro__c = 0;
        reintegro.AccountId = Build.anAccount().withLastName('Test').build().Id;
        reintegro.CBU__c = '123123123';
        reintegro.Efector_realizador__c = Build.anAccountEfector().withLastName('Efector').build().Id;
        reintegro.Codigo_reintegro_SS__c = '553277';
        insert reintegro;

		Nomenclador_de_Prestacion__c nom = new Nomenclador_de_Prestacion__c();
		nom.Estado__c = 'A';
		nom.Codigo__c = '2222';
		insert nom;

		prest = new Prestacion_de_reintegro__c();
		prest.RecordTypeId = XappiaHelper.getRecordType('Prestacion_de_reintegro__c', 'Prestacional').Id;
		prest.Id_Externo__c = '74043157';
        prest.Caso__c = reintegro.Id;
		prest.Importe_Reintegro_auditor__c = 1000;
		prest.Importe_cargo_al_socio_auditor__c = 999.50;
		prest.Prestacional__c = nom.Id;
		insert prest;

		
	}
	
	@IsTest
	private static void whenTheWSIsConsume_getPrestaciones(){
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		
		Test.startTest();
		prestacionReintegroBtnCtrl.Response resp = prestacionReintegroBtnCtrl.sendUpdateToSS(prest.Id);
		Test.stopTest();

		System.assertEquals(false, resp.hasError);
		System.assertEquals('ok', resp.message);
		
	}

	@IsTest
	private static void whenTheWSIsConsume_GetErrorResponse(){
        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        reintegro.Codigo_reintegro_SS__c = '0';
        update reintegro;
        prest.Id_Externo__c = '0';
        update prest;
		
		Test.startTest();
		prestacionReintegroBtnCtrl.Response resp = prestacionReintegroBtnCtrl.sendUpdateToSS(prest.Id);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.debug(resp.message);
		System.assertEquals('El reintegro solicitado es inválido.', resp.message);
	}

	@IsTest
	private static void whenTheReintegroHasntExternalId_showErrorMsj() {
		reintegro.Codigo_reintegro_SS__c = null;
		update reintegro;
		
		Test.startTest();
		prestacionReintegroBtnCtrl.Response resp = prestacionReintegroBtnCtrl.sendUpdateToSS(prest.Id);
		Test.stopTest();
		
		String info = 'No se pueden actualizar los importes en Salud Soft:'
						+ ' revise que el reintegro y la prestacion hayan sido enviados';
		System.assertEquals(false, resp.hasError);
		System.assertEquals(info, resp.message);
	}
}