force-app/main/default/objects/Case/fields/Celula__c.field-meta.xml
<CustomField>
    <fullName>Celula__c</fullName>
    <label>Célula</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celula 1</fullName>
                <label>Emi sin material</label>
            </value>
            <value>
                <fullName>Celula 2</fullName>
                <label>Trámites con material</label>
            </value>
            <value>
                <fullName>Celula 3</fullName>
                <label>Oxigenoterapia</label>
            </value>
            <value>
                <fullName>Celula 4</fullName>
                <label>Fertilidad</label>
            </value>
            <value>
                <fullName>Celula 5</fullName>
                <label>Célula 5</label>
            </value>
            <value>
                <fullName>Celula 6</fullName>
                <label>Programas</label>
            </value>
            <value>
                <fullName>Celula 7</fullName>
                <label>Medicación alto costo</label>
            </value>
            <value>
                <fullName>Celula 8</fullName>
                <label>Reintegros</label>
            </value>
            <value>
                <fullName>Celula 9</fullName>
                <label>Discapacidad</label>
            </value>
            <value>
                <fullName>Celula 10</fullName>
                <label>Célula 10</label>
            </value>
            <value>
                <fullName>Celula 11</fullName>
                <label>Falseamiento de DDJJ</label>
            </value>
            <value>
                <fullName>Celula 12</fullName>
                <label>IDOM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Medico_asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Médico asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Auditor Medico</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Coordinador de Mesa de Ayuda</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseDeleteMedicoAsignadoCtrl.cls
public class CaseDeleteMedicoAsignadoCtrl  {
	@AuraEnabled
	public static Response deleteMedico(Id caseId) {
		
		Case[] cases = [SELECT Id, Celula__c, Medico_asignado__c FROM Case WHERE Id = :caseId];
		User usuario = [
			SELECT CommunityNickname, Profile.Name, UserRole.DeveloperName, Codigo_delegacion__c 
			FROM User 
			WHERE Id =: UserInfo.getUserId()
		];
		
		if(cases[0].Medico_asignado__c != null) {
			cases[0].Medico_asignado__c = null;

			update cases[0];

			return new Response(false, 'ok');
		}
		else {
			return new Response(false, 'No hay ningún médico asignado actualmente.');
		}
	}

	public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message) {
            this.hasError = hasError;
            this.message = message;
        }
    }
}