force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Error_reasignacion__c.field-meta.xml
<CustomField>
    <fullName>Error_reasignacion__c</fullName>
    <description>Info de error al reasociar lote en SS</description>
    <label>Error reasignacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_error_reasignacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_error_reasignacion__c</fullName>
    <description>Fecha en la que fallo la reasignacion de lote en SS</description>
    <label>Fecha error reasignacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Usuario_error_reasignar__c.field-meta.xml
<CustomField>
    <fullName>Usuario_error_reasignar__c</fullName>
    <label>Usuario error reasignar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReintegroReintentoReasignacionBatch.cls
global class ReintegroReintentoReasignacionBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
	
	global ReintegroReintentoReasignacionBatch() {
		
	}
	

	global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator('SELECT Id, Lote__c, Error_reasignacion__c, Fecha_error_reasignacion__c, Usuario_error_reasignar__c, Nro_AP__c, Codigo_reintegro_SS__c FROM Case WHERE Error_reasignacion__c != null');
	}


   	global void execute(Database.BatchableContext context, List<Case> scope) {
		//List<Id> lotesId = new List<Id>();
		//for(Case caso : scope){
			//lotesId.add(caso.Lote__c);
		//}

		//Map<Id,Lote__c> lotesMap = new Map<Id,Lote__c>([SELECT Id_lote_SS__c FROM Lote__c WHERE Id IN :lotesId]);
		
		for(Case caso : scope){
			CaseTriggerHelper.reasignarLote(caso,caso.Usuario_error_reasignar__c);
		}

		if(!scope.isEmpty()){
			update scope;
		}
	}

	global void finish(Database.BatchableContext context) {
		
	}
}