force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Error_reasignacion__c.field-meta.xml
<CustomField>
    <fullName>Error_reasignacion__c</fullName>
    <description>Info de error al reasociar lote en SS</description>
    <label>Error reasignacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha_error_reasignacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_error_reasignacion__c</fullName>
    <description>Fecha en la que fallo la reasignacion de lote en SS</description>
    <label>Fecha error reasignacion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Usuario_error_reasignar__c.field-meta.xml
<CustomField>
    <fullName>Usuario_error_reasignar__c</fullName>
    <label>Usuario error reasignar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/ReintegroReintentoReasignacionBatchTest.cls
@isTest 
private class ReintegroReintentoReasignacionBatchTest {

	static XHttpCalloutMock getSuccessResponse;
	static XHttpCalloutMock getErrorResponse;

	static{
	    getSuccessResponse = new XHttpCalloutMock();
        getSuccessResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getSuccessResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSCaseReintegroReasignarMock.getFound())
                .addForAddress(WSCaseReintegroReasignar.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/553276');

        getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('Error')
                .withStatusCode(500)
                .withBody(WSCaseReintegroReasignarMock.getError())
                .addForAddress(WSCaseReintegroReasignar.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/123');

	}

	@isTest
	private static void testReintentoReasignacion() {
		Test.setMock(HttpCalloutMock.class, getSuccessResponse);
		
		Lote__c lote = new Lote__c();
		lote.Id_lote_SS__c = '999999';
		insert lote;

		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		reintegro.Codigo_reintegro_SS__c = '553276';
		reintegro.Lote__c = lote.Id;
		reintegro.Error_reasignacion__c = 'Error del WS';
		reintegro.Fecha_error_reasignacion__c = Datetime.now();
		reintegro.Usuario_error_reasignar__c = 'CRIOS';
		insert reintegro;


		Test.startTest();
		Database.executeBatch(new ReintegroReintentoReasignacionBatch());
		Test.stopTest();

		reintegro = [SELECT Error_reasignacion__c, Fecha_error_reasignacion__c, Usuario_error_reasignar__c FROM Case WHERE Id = :reintegro.Id];

		System.assertEquals(null, reintegro.Error_reasignacion__c);
		System.assertEquals(null, reintegro.Fecha_error_reasignacion__c);
		System.assertEquals(null, reintegro.Usuario_error_reasignar__c);

	}
}