force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_auditor__c</fullName>
    <label>Importe Reintegro auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/prestacionReintegroBtnCtrl.cls
public class prestacionReintegroBtnCtrl {
    @AuraEnabled
    public static Response sendUpdateToSS(String presId) {
        List<Prestacion_de_reintegro__c> prestacion = [
            SELECT Id_Externo__c, Caso__r.Codigo_reintegro_SS__c , Importe_Reintegro_auditor__c, Importe_cargo_al_socio_auditor__c
            FROM Prestacion_de_reintegro__c 
            WHERE Id =: presId
        ];

        if(String.isBlank(prestacion[0].Caso__r.Codigo_reintegro_SS__c) 
            || String.isBlank(prestacion[0].Id_Externo__c)
        ) {
            return new Response(false, 'No se pueden actualizar los importes en Salud Soft:'
                + ' revise que el reintegro y la prestacion hayan sido enviados'); 
        }

        String body = generateJson(prestacion[0]);

        System.debug(body);
		WSPrestacionActualizarImporte.Response resp = WSPrestacionActualizarImporte.sendImporteToSS(
            body, prestacion[0].Caso__r.Codigo_reintegro_SS__c, prestacion[0].Id_Externo__c
        );

        System.debug('Respuesta: ' + resp);

		if(!resp.hasError) {
			return new Response(false, 'ok');
		} else {
			return new Response(true, resp.message);
		}
    }
    
    private static String generateJson(Prestacion_de_reintegro__c prestacion) {
		Map<String, Object> prestJSON = new Map<String, Object>();
        System.debug(prestacion);
		if(prestacion.Importe_Reintegro_auditor__c != null) {
			prestJSON.put('importe_reintegro', prestacion.Importe_Reintegro_auditor__c);
		}
		if(prestacion.Importe_cargo_al_socio_auditor__c != null) {
			prestJSON.put('importe_socio', prestacion.Importe_cargo_al_socio_auditor__c);
		}
        
		return JSON.serialize(prestJSON);
	}

    public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message){
            this.hasError = hasError;
            this.message = message;
        }
    }  
}