force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Contiene_alerta_AM__c.field-meta.xml
<CustomField>
    <fullName>Contiene_alerta_AM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contiene alerta AM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Medico_asignado__c.field-meta.xml
<CustomField>
    <fullName>Medico_asignado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Médico asignado</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Auditor Medico</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Coordinador de Mesa de Ayuda</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Internacion.recordType-meta.xml
<RecordType>
    <fullName>Internacion</fullName>
    <active>true</active>
    <businessProcess>Internacion</businessProcess>
    <label>Internación</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/APr_Id__c.field-meta.xml
<CustomField>
    <fullName>APr_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Evento_Medico_Id__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Nota SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/fields/Codigo_tipoNA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_tipoNA__c</fullName>
    <externalId>true</externalId>
    <label>Codigo tipoNA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotaDeAuditoriaTriggerHelper.cls
public class NotaDeAuditoriaTriggerHelper  {

	public static void enviarASS(List<Nota_de_Auditoria__c> notasDeAuditoria){
		List<Id> notaDeAuditoriaIds = new List<Id>();
		for(Nota_de_Auditoria__c nda : notasDeAuditoria){
			if(nda.RecordTypeId == XappiaHelper.getRecordType('Nota_de_Auditoria__c', 'Service').Id) {
				notaDeAuditoriaIds.add(nda.Id);
			}
		}
		enviarASS(notaDeAuditoriaIds);
	}

	@Future(callout=true)
	public static void enviarASS(List<Id> notaDeAuditoriaIds){
		List<Nota_de_Auditoria__c> notasToUpdate = new List<Nota_de_Auditoria__c>();
		List<Nota_de_Auditoria__c> notasDeAuditoria = [
			SELECT Nota__c, Owner.Name, Tipo_nota_de_Auditoria__r.Codigo_tipoNA__c, APr_Id__r.Nro_AP__c,
				Evento_Medico_Id__r.Nro_de_Evento_Medico_SS__c, APr_Id__r.Codigo_reintegro_SS__c, Id_Externo__c
			FROM Nota_de_Auditoria__c
			WHERE Id IN :notaDeAuditoriaIds
		];
		for(Nota_de_Auditoria__c nda : notasDeAuditoria){
			WSNotaDeAuditoriaEnviarASS.SSWSResult resp = WSNotaDeAuditoriaEnviarASS.enviar(nda);
			if(!resp.hasError) {
				nda.Id_Externo__c = resp.responseBody.data.id_nota;

				notasToUpdate.add(nda);
			}
		}

		List<Database.SaveResult> resultNotas = Database.update(notasToUpdate);
		System.debug('***resultNotas: ' + resultNotas);
	}

	public static void changesDoctorAtCases(Id[] caseIds) {
		User usuario = [SELECT Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
		Boolean isDoctor = usuario.Profile.Name == 'Auditor Medico' || usuario.Profile.Name == 'Coordinador de Mesa de Ayuda';
		Case[] casesToUpdate = new List<Case>();

		for(Case aCase : [
			SELECT Id, Nivel_de_derivacion__c, Contiene_alerta_AM__c, Medico_asignado__c, RecordTypeId
			FROM Case 
			WHERE Id IN :caseIds
		]) {
			if(isDoctor && String.isBlank(aCase.Medico_asignado__c) && aCase.Contiene_alerta_AM__c
				&& (aCase.Nivel_de_derivacion__c == 'Nivel 2' || aCase.Nivel_de_derivacion__c == 'Nivel 3')
				&& CaseTriggerHelper.hasARecordTypeWithMedicoAsignado(aCase)
			) {
				aCase.Medico_asignado__c = usuario.Id;

				casesToUpdate.add(aCase);
			}	
		}

		if(!casesToUpdate.isEmpty()) {
			update casesToUpdate;
		}
	}

	//public static Boolean hasARecordTypeWithMedicoAsignado(Case aCase) {
		//Id rtInternacion = XappiaHelper.getRecordType('Case', 'Internacion').Id;
		//Id rtSeguimiento = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		//Id rtAP = XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id;
		//Id rtReintegro = XappiaHelper.getRecordType('Case', 'Reintegro').Id;

		//return aCase.RecordTypeId == rtInternacion || aCase.RecordTypeId == rtSeguimiento
				//|| aCase.RecordTypeId == rtAP || aCase.RecordTypeId == rtReintegro;
	//}
}