force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Derivacion_de_lote__c.field-meta.xml
<CustomField>
    <fullName>Derivacion_de_lote__c</fullName>
    <label>Derivacion de lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lote Vigente</fullName>
                <default>true</default>
                <label>Lote Vigente</label>
            </value>
            <value>
                <fullName>Lote Devolucion</fullName>
            </value>
            <value>
                <fullName>Lote Pendiente</fullName>
            </value>
            <value>
                <fullName>Lote Especial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Se utiliza para saber los errores de los lotes de reintegro</description>
    <inlineHelpText>Representa el error que puede devolver Salud soft</inlineHelpText>
    <label>Error</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestaciones_en_auditoria__c.field-meta.xml
<CustomField>
    <fullName>Prestaciones_en_auditoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestaciones en auditoría</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de cuenta</description>
    <formula>TEXT(Account.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Especial</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Devoluciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoteGeneracionDeOrdenTest.cls
@isTest 
private class LoteGeneracionDeOrdenTest {

	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundDeshacer;
	static XHttpCalloutMock getResponseError;

	static {
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSLoteGeneracionDeOrdenMock.getFound())
			.addForAddress(WSLoteGeneracionDeOrden.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes/5402/orden');

		getResponseFoundDeshacer = new XHttpCalloutMock();
		getResponseFoundDeshacer.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundDeshacer.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSLoteGeneracionDeOrdenMock.getFoundDeshacer())
			.addForAddress(WSLoteGeneracionDeOrden.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes/5404/orden');

		getResponseError = new XHttpCalloutMock();
		getResponseError.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseError.buildResponse()
			.withStatus('Error')
			.withStatusCode(422)
			.withBody(WSLoteGeneracionDeOrdenMock.getError())
			.addForAddress(WSLoteGeneracionDeOrden.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes/5600/orden');
		
	}

	@TestSetup 
	private static void setup() {
		Test.startTest(); 
		Lote__c lote = new Lote__c();
		lote.Tipo__c = 'Vigente';
		lote.Id_lote_SS__c = '5402';
		lote.Estado__c = 'A';
		insert lote;
		
		Case[] reintegros = new List<Case>();

		for(Integer i = 0; i < 200; i++) {
			Case rein = new Case();
			rein.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
			//rein.Status = 'CA-----G';
			//rein.Codigo_reintegro_SS__c = '0000' + i;
			rein.Status = 'CA-----A';
			rein.Observaciones__c = '|test|';
			rein.Lote__c = lote.Id;

			reintegros.add(rein);
		}

		insert reintegros;
		Test.stopTest();
	}

	@isTest
	private static void generateOrdenSSFailsInAReintegro() {
		Lote__c lote = [SELECT Id, Id_lote_SS__c FROM Lote__c WHERE Id_lote_SS__c = '5402'];
		//insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', Status = 'CA-----A', 
			RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro;

		Case reintegro2 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553278', Status = 'CA-----A',
			RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro2;

		Case reintegro3 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553277', Status = 'CA-----G',
			RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro3;

		Test.setMock(HttpCalloutMock.class,getResponseFound);
		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.generacionDeOrden(lote.Id_lote_SS__c, 'GENERAR');
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];
		reintegro = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro.Id];
		reintegro2 = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro2.Id];
		reintegro3 = [SELECT Status,Error__c, Derivacion_de_lote__c FROM Case WHERE Id = :reintegro3.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('A', lote.Estado__c);
		System.assertEquals('CA_REI_0006:El reintegro 553279 tiene prestaciones o conceptos sin pasar por el centro autoirizador o pendientes de auditoría', reintegro.Error__c);
		System.assertEquals('CA-----A', reintegro.Status);
		System.assertEquals(null, reintegro2.Error__c);
		System.assertEquals('CA-----E', reintegro2.Status);
		System.assertEquals(null, reintegro3.Error__c);
		System.assertEquals('CA-----G', reintegro3.Status);
		System.assertEquals('Lote Pendiente', reintegro3.Derivacion_de_lote__c);


	}

	@isTest
	private static void undoOrdenSS() {
		Lote__c lote = new Lote__c(Estado__c = 'A', Id_lote_SS__c = '5404');
		insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro;

		Case reintegro2 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553278', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro2;

		Test.setMock(HttpCalloutMock.class,getResponseFoundDeshacer);
		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.generacionDeOrden(lote.Id_lote_SS__c, 'DESHACER');
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];
		reintegro = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro.Id];
		reintegro2 = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro2.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('A', lote.Estado__c);
		System.assertEquals('CA-----A', reintegro.Status);
		System.assertEquals('CA-----A', reintegro2.Status);
	}

	@isTest
	private static void generateOrdenSSWithError() {
		Lote__c lote = new Lote__c(Estado__c = 'A', Id_lote_SS__c = '5600');
		insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro;

		Case reintegro2 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553278', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		insert reintegro2;

		Test.setMock(HttpCalloutMock.class,getResponseError);
		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.generacionDeOrden(lote.Id_lote_SS__c, 'GENERAR');
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];
		reintegro = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro.Id];
		reintegro2 = [SELECT Status,Error__c FROM Case WHERE Id = :reintegro2.Id];

		System.assertEquals(true, resp.hasError);
		System.assertEquals('A', lote.Estado__c);
		System.assertEquals('No se pudo generar la orden. No se pueden visualizar los datos en este momento', resp.message);

	}

	@isTest
	private static void whenTheLoteHasReintegrosEnAuditoria_showErrorMsg() {
		Lote__c lote = new Lote__c(Estado__c = 'A', Id_lote_SS__c = '5600');
		insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		reintegro.Status = 'CA-----A';
		insert reintegro;

		Case reintegro2 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553278', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		reintegro2.Status = 'CA-----A';
		insert reintegro2;

		Case reintegro3 = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553281', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		reintegro3.Status = 'CA-----A';
		insert reintegro3;

		Prestacion_de_reintegro__c pRein = new Prestacion_de_reintegro__c();
		pRein.Estado__c = 'C1-----A';
		pRein.Caso__c = reintegro.Id;
		insert pRein;

		Prestacion_de_reintegro__c pRein2 = new Prestacion_de_reintegro__c();
		pRein2.Estado__c = 'C1-----A';
		pRein2.Caso__c = reintegro2.Id;
		insert pRein2;

		reintegro = [SELECT Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		reintegro2 = [SELECT Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro2.Id];

		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.validarReintegrosEnAuditoria(lote.Id_lote_SS__c);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.assert(resp.message.contains('553278'));
		System.assert(resp.message.contains('553279'));
	}

	@isTest
	private static void whenTheLoteHasNotReintegrosEnAuditoria_showSuccessMsg() {
		Lote__c lote = new Lote__c(Estado__c = 'A', Id_lote_SS__c = '5600');
		insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		reintegro.Status = 'CA-----A';
		insert reintegro;

		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.validarReintegrosEnAuditoria(lote.Id_lote_SS__c);
		Test.stopTest();

		System.assertEquals(false, resp.hasError);
		System.assertEquals('ok', resp.message);
	}

	@isTest
	private static void whenTheLoteHasNotExternalId_showErrorMsg() {
		Lote__c lote = new Lote__c(Estado__c = 'A');
		insert lote;

		Case reintegro = new Case(Lote__c = lote.Id, Codigo_reintegro_SS__c = '553279', RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id);
		reintegro.Status = 'CA-----A';
		insert reintegro;

		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.validarReintegrosEnAuditoria(lote.Id_lote_SS__c);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.assertEquals('El lote no existe en SS', resp.message);
	}
	 
	@isTest
	private static void testMuchosReintegros() {
		Lote__c lote = [SELECT Id, Id_lote_SS__c FROM Lote__c WHERE Id_lote_SS__c = '5402'];

		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		LoteGeneracionDeOrdenCtrl.Response resp = LoteGeneracionDeOrdenCtrl.generacionDeOrden(lote.Id_lote_SS__c, 'GENERAR');
		Test.stopTest();

		Case reintegro = [SELECT Id, Status FROM Case WHERE Lote__c = :lote.Id LIMIT 1];
		
		System.assertEquals('CA-----E', reintegro.Status);

	}
}