force-app/main/default/objects/Case/fields/Codigo_reintegro_SS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_reintegro_SS__c</fullName>
    <externalId>true</externalId>
    <label>Código reintegro SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/APr_Id__c.field-meta.xml
<CustomField>
    <fullName>APr_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Evento_Medico_Id__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Nota SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/fields/Codigo_tipoNA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_tipoNA__c</fullName>
    <externalId>true</externalId>
    <label>Codigo tipoNA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice_endpoint_setting__mdt/Webservice_endpoint_setting__mdt.object-meta.xml
<CustomObject>
    <description>Metadata store endpoint and credentials</description>
    <label>Webservice endpoint setting</label>
    <pluralLabel>Webservice endpoint setting</pluralLabel>
</CustomObject>

force-app/main/default/classes/WSNotaDeAuditoriaEnviarASS.cls
public class WSNotaDeAuditoriaEnviarASS  {

    @TestVisible
    public static final Webservice_endpoint_setting__mdt SERVICE_CONFIG =
            ConfigUtils.getWebServiceConfig('SALUDSOFT.TEST');

    public static SSWSResult enviar(Nota_de_Auditoria__c notaDeAuditoria) {
        RestWS ws = new RestWS(SERVICE_CONFIG.URL__c + '/v1/salud/notas-auditor',
                'POST',
                null,
                JSON.serialize(generateRequest(notaDeAuditoria)));

        ws.request.setHeader('Accept','application/json"');
        ws.request.setHeader('Content-Type', 'application/json');
		//-------------------------------------------------
        System.debug('body****: ' + ws.bodyParameter.value);
        //-------------------------------------------------
		WSAuthToken.Response tokenResp = WSAuthToken.setAuthHeader(ws);
		SSWSResult res = (SSWSResult) ws.invoke(new SSWSResult());
		WSAuthToken.manageTokenResponse(tokenResp);
		return res;
    }

	public class SSWSResult extends WSResult {
		public ResponseBody responseBody;

		public override void processResponse(HttpResponse response) {
			this.responseBody = (ResponseBody)JSON.deserialize(response.getBody(), ResponseBody.class);
		}

		public override void processError(HttpResponse response) {
            Map<String,Object> body = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
			message = UtilsDisplayErrorMessageFromWS.showErrorMessage(body);

        }
	}

	public class ResponseBody {
		public Data data;
		public String message;
		public Integer httpCode;
		public Boolean error;
	}

	public class Data {
		public String id_nota;
	}

	static private Map<String,Object> generateRequest(Nota_de_Auditoria__c nota){
		User usuario = [SELECT CommunityNickname FROM User WHERE Id = :UserInfo.getUserId()];
		String nick = usuario.CommunityNickname.toUppercase();

		Map<String,Object> notaMap = new Map<String,Object>{
			'usuario' => nick,
			'numero_sf' => nota.Id,
			'tipo_nota' => nota.Tipo_nota_de_Auditoria__r.Codigo_tipoNA__c,
			'nota' => nota.Nota__c
		};

		if(nota.APr_Id__c != null){
			if(nota.APr_Id__r.Nro_AP__c != null) {
				notaMap.put('apr_id', nota.APr_Id__r.Nro_AP__c);
			}
			else if(nota.APr_Id__r.Codigo_reintegro_SS__c != null) {
				notaMap.put('rein_id', nota.APr_Id__r.Codigo_reintegro_SS__c);
			}
		}
		if(nota.Evento_Medico_Id__c != null){
			notaMap.put('em_id', nota.Evento_Medico_Id__r.Nro_de_Evento_Medico_SS__c);
		}
		if(nota.Id_Externo__c != null) {
			notaMap.put('nota_id', nota.Id_Externo__c);
		}

		return notaMap;
	}

	//public class RequestBody {
		//public String numero_sf;
		//public String tipo_nota;
		//public String apr_id;
		//public String em_id;
		//public String usuario;
		//public String nota;

		//public RequestBody(Nota_de_Auditoria__c nda){
			//this.numero_sf = nda.Id;
			//this.tipo_nota = nda.Tipo_nota_de_Auditoria__r.Codigo_tipoNA__c;
			//this.apr_id = nda.APr_Id__r.Nro_AP__c;
			//this.em_id = nda.Evento_Medico_Id__r.Nro_de_Evento_Medico_SS__c;
			//this.usuario = 'CRIOS';
			//this.nota = nda.Nota__c;
		//}
	//}
}