force-app/main/default/objects/Case/fields/Estado_de_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_solicitud__c</fullName>
    <label>Estado de solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INCOMPLETA</fullName>
            </value>
            <value>
                <fullName>COMPLETA</fullName>
            </value>
            <value>
                <fullName>TRANSFORMADA</fullName>
            </value>
            <value>
                <fullName>RECHAZADA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_de_solicitud_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud_SS__c</fullName>
    <label>Nro de solicitud SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante_caso__c/Integrante_caso__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integrante_caso__c/fields/Estado_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Estado_solicitud__c</fullName>
    <label>Estado solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incompleta</fullName>
            </value>
            <value>
                <fullName>Completa</fullName>
            </value>
            <value>
                <fullName>Transformada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegranteCasoTriggerTest.cls
@IsTest
public class IntegranteCasoTriggerTest {
    public static final Account cuenta = build.anAccount()
                        .withAfiIddelTitular(182701)
                        .withType('TIT')
                        .withCodigodeAfiliado('70332/34')
                        .withLastName('Testing182701')
                        .withEstado('A')
                        .build();
    public static final Account familiar = build.anAccount()
                        .withAfiIddelTitular(182700)
                        .withCodigodeAfiliado('70331/34')
                        .withLastName('Testingx')
                        .withEstado('A')
                        .build();     
    @IsTest
    private static void casoConTodosSusIntegrantesConEstadoTransformadoDebeCerrarse(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        integrante1.Estado_solicitud__c = 'TRANSFORMADA';
        insert integrante1;

        Integrante_caso__c integrante2 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante2;

        System.assertEquals(null, caso.Estado_de_solicitud__c);
        
        Test.startTest();
        integrante2.Estado_solicitud__c = 'TRANSFORMADA';
        update integrante2;
        Test.stopTest();
        
        caso = [SELECT Id,Estado_de_solicitud__c,Status FROM Case WHERE Id = :caso.Id];
        
        System.assertEquals('TRANSFORMADA',caso.Estado_de_solicitud__c);
        System.assertEquals('Cerrado', caso.Status);
    }
    
    @IsTest
    private static void casoConAlgunIntegranteConEstadoIncompletaDebeTenerEstadoIncompleta(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        integrante1.Estado_solicitud__c = 'TRANSFORMADA';
        insert integrante1;

        Integrante_caso__c integrante2 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante2;

        System.assertEquals(null, caso.Estado_de_solicitud__c);
        
        Test.startTest();
        integrante2.Estado_solicitud__c = 'INCOMPLETA';
        update integrante2;
        Test.stopTest();
        
        caso = [SELECT Id,Estado_de_solicitud__c,Status FROM Case WHERE Id = :caso.Id];
        
        System.assertEquals('INCOMPLETA',caso.Estado_de_solicitud__c);
        System.assertEquals('Pendiente', caso.Status);
    }

    
    @IsTest
    private static void casoConAlgunIntegranteConEstadoCompletaYNingunoConEstadoIncompletaDebeTenerEstadoCompleta(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        integrante1.Estado_solicitud__c = 'TRANSFORMADA';
        insert integrante1;

        Integrante_caso__c integrante2 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante2;

        
        System.assertEquals(null, caso.Estado_de_solicitud__c);
        
        Test.startTest();
        integrante2.Estado_solicitud__c = 'COMPLETA';
        update integrante2;
        Test.stopTest();
        
        caso = [SELECT Id,Estado_de_solicitud__c,Status FROM Case WHERE Id = :caso.Id];
        
        System.assertEquals('COMPLETA',caso.Estado_de_solicitud__c);
        System.assertEquals('Pendiente', caso.Status);
    }
    
    
    @IsTest
    private static void casoConAlgunIntegranteConEstadoCompletaYUnoConEstadoIncompletaDebeTenerElMismoEstado(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        integrante1.Estado_solicitud__c = 'INCOMPLETA';
        insert integrante1;

        Integrante_caso__c integrante2 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante2;
        
        System.assertEquals(null, caso.Estado_de_solicitud__c);
        
        Test.startTest();
        integrante2.Estado_solicitud__c = 'COMPLETA';
        update integrante2;
        Test.stopTest();
        
        caso = [SELECT Id,Estado_de_solicitud__c,Status FROM Case WHERE Id = :caso.Id];
        
        System.assertEquals(null,caso.Estado_de_solicitud__c);
        System.assertEquals('Pendiente', caso.Status);
    }

    @IsTest
    private static void casoNoFueEnviadoASSEntoncesElIntegrantePuedeSerEliminado(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante1;

        Test.startTest();
        Database.DeleteResult integranteDeleteResult = Database.delete(integrante1);
        Test.stopTest();
        
        System.assert(String.isBlank(caso.Nro_de_solicitud_SS__c));
        System.assert(integranteDeleteResult.isSuccess());
    }

    @IsTest 
    private static void casoEnviadoASSEntoncesElIntegranteNoPuedeSerEliminado(){
        insert new List<SObject>{familiar, cuenta};
        Case caso = Build.aCaseSolicitudDeBaja()
                                        .withAccountId(cuenta.Id)
                                        .withType('Baja parcial')
                                        .withFechaDeVigencia(Date.newInstance(2020, 01, 01))
                                        .withMotivoDeLaBaja('2')
                                        .build();
        insert caso;

        Integrante_caso__c integrante1 = Build.anIntegranteCasoBajas()
                                                .withFamiliar(familiar.Id)
                                                .withMotivoDeLaBaja('2')
                                                .withCase(caso.Id)
                                                .build();
        insert integrante1;

        caso.Nro_de_solicitud_SS__c = '123456';
        update caso;

        Test.startTest();
        Database.DeleteResult integranteDeleteResult = Database.delete(integrante1, false);
        Test.stopTest();
        
        System.assert(String.isNotBlank(caso.Nro_de_solicitud_SS__c));
        System.assertEquals(false, integranteDeleteResult.isSuccess());
        System.assertEquals('No se puede eliminar porque el caso ya fue enviado a Salud Soft', integranteDeleteResult.getErrors()[0].getMessage());
    }
}