force-app/main/default/objects/Case/fields/Estado_de_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_solicitud__c</fullName>
    <label>Estado de solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INCOMPLETA</fullName>
            </value>
            <value>
                <fullName>COMPLETA</fullName>
            </value>
            <value>
                <fullName>TRANSFORMADA</fullName>
            </value>
            <value>
                <fullName>RECHAZADA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motivo_de_cierre_solicitudes__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_cierre_solicitudes__c</fullName>
    <label>Motivo de cierre</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cambio de plan</fullName>
            </value>
            <value>
                <fullName>Sumatoria de aportes</fullName>
            </value>
            <value>
                <fullName>Cambio de segmentos</fullName>
            </value>
            <value>
                <fullName>Pluriempleos</fullName>
            </value>
            <value>
                <fullName>Cambio de politica comercial</fullName>
                <label>Cambio de política comercial</label>
            </value>
            <value>
                <fullName>Contencion y asesoramiento</fullName>
                <label>Contención y asesoramiento</label>
            </value>
            <value>
                <fullName>Bonificacion aplicada</fullName>
                <label>Bonificación aplicada</label>
            </value>
            <value>
                <fullName>Baja procesada</fullName>
            </value>
            <value>
                <fullName>PMO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_de_solicitud_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud_SS__c</fullName>
    <label>Nro de solicitud SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante_caso__c/Integrante_caso__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integrante_caso__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nro de caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integrantes</relationshipLabel>
    <relationshipName>Integrantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integrante_caso__c/fields/Estado_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Estado_solicitud__c</fullName>
    <label>Estado solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incompleta</fullName>
            </value>
            <value>
                <fullName>Completa</fullName>
            </value>
            <value>
                <fullName>Transformada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegranteCasoTriggerHelper.cls
public class IntegranteCasoTriggerHelper {
    public static void integrantesConCambioDeEstado(Set<Id> cambioTransformada,Set<Id> cambioCompleta, Set<Id> cambioIncompleta){
        System.debug(cambioTransformada);
        
        if(!cambioTransformada.isEmpty()){
            List<Case> casos = [
                SELECT Id, Status,Estado_de_solicitud__c,Motivo_de_cierre_solicitudes__c, (SELECT Id, Estado_solicitud__c FROM Integrantes__r)
                FROM Case
                WHERE Id IN :cambioTransformada
            ];
            for(Case caso : casos){
                Boolean todosIntegrantesTransformados = true;
                for(Integrante_caso__c integrante : caso.Integrantes__r){
                    todosIntegrantesTransformados = todosIntegrantesTransformados && integrante.Estado_solicitud__c == 'TRANSFORMADA';
                }
                if(todosIntegrantesTransformados){
                	caso.Estado_de_solicitud__c = 'TRANSFORMADA';
                    caso.Motivo_de_cierre_solicitudes__c = 'Baja procesada';
                    caso.Status = 'Cerrado';
                }
            }
            update casos;
        }
        
        if(!cambioCompleta.isEmpty()){
            List<Case> casos = [
                SELECT Id,Estado_de_solicitud__c, (SELECT Id, Estado_solicitud__c FROM Integrantes__r)
                FROM Case
                WHERE Id IN :cambioCompleta
            ];
            for(Case caso : casos){
                Boolean contieneIntegranteIncompleto = false;
                for(Integrante_caso__c integrante : caso.Integrantes__r){
                    contieneIntegranteIncompleto = contieneIntegranteIncompleto || integrante.Estado_solicitud__c == 'Incompleta';
                }
                if(!contieneIntegranteIncompleto){
                	caso.Estado_de_solicitud__c = 'COMPLETA';
                }
            }
            update casos;
        }
        
        if(!cambioIncompleta.isEmpty()){
            List<Case> casos = [
                SELECT Id, Estado_de_solicitud__c
                FROM Case
                WHERE Id IN :cambioIncompleta
            ];
            for(Case caso : casos){
                caso.Estado_de_solicitud__c = 'INCOMPLETA';
            }
            update casos;
        }
    }

    public static void eliminarIntegrantesQueNoTienenCasosEnviadosASS(List<Integrante_caso__c> integrantes) {
        Map<Integrante_caso__c, ID> casesByIntegrantes = new Map<Integrante_caso__c, ID>();
        for(Integrante_caso__c integrante : integrantes){
            casesByIntegrantes.put(integrante, integrante.Caso__c);
        }

        Map<ID, Case> casesById = new Map<ID, Case>(
            [
                SELECT Id, Nro_de_solicitud_SS__c
                FROM Case
                WHERE ID IN :casesByIntegrantes.values()
            ]
        );
        
        for(Integrante_caso__c integrante : casesByIntegrantes.keySet()){
            if(String.isNotBlank(casesById.get(casesByIntegrantes.get(integrante)).Nro_de_solicitud_SS__c)) {
                integrante.addError('No se puede eliminar porque el caso ya fue enviado a Salud Soft');
            }
        }
    }
}