force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Interfaz_financiera.recordType-meta.xml
<RecordType>
    <fullName>Interfaz_financiera</fullName>
    <active>true</active>
    <businessProcess>Interfaz financiera</businessProcess>
    <label>Interfaz financiera</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_alta_familiar.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_alta_familiar</fullName>
    <active>true</active>
    <businessProcess>Solicitud alta familiar</businessProcess>
    <label>Solicitud de alta familiar</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_baja.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_baja</fullName>
    <active>true</active>
    <businessProcess>Solicitud de bajas</businessProcess>
    <label>Solicitud de baja</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_cambio_de_plan.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_cambio_de_plan</fullName>
    <active>true</active>
    <businessProcess>Solicitud de cambio de plan</businessProcess>
    <label>Solicitud de cambio de plan</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_datos_particulares.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_datos_particulares</fullName>
    <active>true</active>
    <businessProcess>Solicitud de datos particulares</businessProcess>
    <label>Solicitud de datos particulares</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_despegues.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_despegues</fullName>
    <active>true</active>
    <businessProcess>Solicitud de despegue</businessProcess>
    <label>Solicitud de despegues</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_nueva_credencial.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_nueva_credencial</fullName>
    <active>true</active>
    <businessProcess>Solicitud de nueva credencial</businessProcess>
    <label>Solicitud de nueva credencial</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Solicitud_de_segmento.recordType-meta.xml
<RecordType>
    <fullName>Solicitud_de_segmento</fullName>
    <active>true</active>
    <businessProcess>Solicitud de segmento</businessProcess>
    <label>Solicitud de segmento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integrante_caso__c/Integrante_caso__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/recordTypes/Integrante.recordType-meta.xml
<RecordType>
    <fullName>Integrante</fullName>
    <active>true</active>
    <label>Integrante</label>
</RecordType>

force-app/main/default/objects/Nota_de_Auditoria__c/recordTypes/Ventas.recordType-meta.xml
<RecordType>
    <fullName>Ventas</fullName>
    <active>true</active>
    <label>Ventas</label>
</RecordType>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CrearNotaDeAuditoriaController.cls
public class CrearNotaDeAuditoriaController  {
	
	@AuraEnabled
	public static Response getRecordTypeId(String recordId){
		//Map<String, Schema.RecordTypeInfo> notaDeAuditoriaRecordTypesByDeveloperName = 
			//Schema.SObjectType.Nota_de_Auditoria__c.getRecordTypeInfosByDeveloperName();
		
		Response response = new Response();
		String strObjPrefix = String.isNotBlank(recordId) ? recordId.substring(0, 3) : null;
		
		if(strObjPrefix == Case.sObjectType.getDescribe().getKeyPrefix()) {
			response.data = XappiaHelper.getRecordType('Nota_de_Auditoria__c','Service').Id;
			response.objectType = 'Case';
		}	
		else if(strObjPrefix == Evento_medico__c.sObjectType.getDescribe().getKeyPrefix()) {
			response.data = XappiaHelper.getRecordType('Nota_de_Auditoria__c','Service').Id;
			response.objectType = 'Evento_Medico__c';
		}
		else if(strObjPrefix == Opportunity.sObjectType.getDescribe().getKeyPrefix()) {
			response.data = XappiaHelper.getRecordType('Nota_de_Auditoria__c','Ventas').Id;
			response.objectType = 'Opportunity';
		}
		else if(strObjPrefix == Integrante_caso__c.sObjectType.getDescribe().getKeyPrefix()) {
			response.data = XappiaHelper.getRecordType('Nota_de_Auditoria__c','Integrante').Id;
			response.objectType = 'Integrante_caso__c';
		}
		else {
			response.hasError = true;
			response.message = 'Solo puede crear Notas de auditoria desde un registro de Oportunidad, ' + 
								'Evento Médico, Caso o Integrante';
		}

		if(response.objectType == 'Case') {
			try {
				Case caso = [SELECT RecordTypeId FROM Case WHERE id = :recordId];
				Id solicitudDeAltaFamiliar = XappiaHelper.getRecordType('Case', 'Solicitud_de_alta_familiar').Id;
				Id solicitudDeDespegues = XappiaHelper.getRecordType('Case', 'Solicitud_de_despegues').Id;
				Id solicitudDeBajas = XappiaHelper.getRecordType('Case', 'Solicitud_de_baja').Id;
				Id solicitudCambioSegmento = XappiaHelper.getRecordType('Case', 'Solicitud_de_segmento').Id;
            	Id solicitudInterfazFinanciera = XappiaHelper.getRecordType('Case', 'Interfaz_financiera').Id;
            	Id solicitudCredencial = XappiaHelper.getRecordType('Case', 'Solicitud_de_nueva_credencial').Id;
            	Id solicitudPlan = XappiaHelper.getRecordType('Case', 'Solicitud_de_cambio_de_plan').Id;
            	Id solicitudDatosParticulares = XappiaHelper.getRecordType('Case', 'Solicitud_de_datos_particulares').Id;
				if(caso.RecordTypeId == solicitudDeDespegues
						|| caso.RecordTypeId == solicitudCambioSegmento 
						|| caso.RecordTypeId == solicitudInterfazFinanciera
						|| caso.RecordTypeId == solicitudCredencial
						|| caso.RecordTypeId == solicitudDatosParticulares
						|| caso.RecordTypeId == solicitudPlan
						|| caso.RecordTypeId == solicitudDeBajas
						|| caso.RecordTypeId == solicitudDeAltaFamiliar){
					Tipo_nota_de_auditoria__c tipoDeNota = [SELECT id FROM Tipo_nota_de_auditoria__c WHERE Name = 'NOTA DDJJ - SOLICITUDES' LIMIT 1];
					if(tipoDeNota != null) {
						response.typeOfNota = tipoDeNota.id;
						return response;
					}
				}
			} catch (Exception e) {
				return response;
			}
		}
		return response;
	}


	public class Response {
		@AuraEnabled public String message {get; set;}
        @AuraEnabled public Boolean hasError {get; set;}
        @AuraEnabled public Object data {get; set;}
		@AuraEnabled public Id typeOfNota {get; set;}
		@AuraEnabled public String objectType {get; set;}

        public Response() {
            hasError = false;
        }
	}
}