force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/classes/EventoMedicoAnularBtnCtrlTest.cls
@IsTest
private class EventoMedicoAnularBtnCtrlTest {
    static XHttpCalloutMock getResponseFound;
    static XHttpCalloutMock getErrorResponse;
	static User usuario;

    static {
		
		String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
		Profile p = [SELECT Id FROM Profile WHERE Name='Front'];
		UserRole role = [SELECT Id,Name FROM UserRole WHERE Name = 'Administrador'];
		usuario = new User(Alias = 'standt', Email='standarduser@testorg.com',
				EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='es',
				LocaleSidKey='es_AR', TimeZoneSidKey='America/Argentina/Buenos_Aires',
				UserName=uniqueUserName, ProfileId = p.Id, UserRole = role, Codigo_delegacion__c='650098');
		insert usuario;

        getResponseFound = new XHttpCalloutMock();
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSEventoMedicoAnularMock.getFound())
                .addForAddress(WSEventoMedicoAnular.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/249818/anular');

        getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('Not Found')
                .withStatusCode(404)
                .withBody(WSEventoMedicoAnularMock.getError())
                .addForAddress(WSEventoMedicoAnular.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/249818/anular');
    }

    @IsTest
    static void anularEMTest() {
        Test.setMock(HttpCalloutMock.class, getResponseFound);
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '249818', Estado__c = 'En Auditoria');
        insert em;
        Case caso = new Case(Evento_Medico__c = em.Id, Status = 'CA-----G');
        insert caso;


        Test.startTest();
        EventoMedicoAnularBtnCtrl.Response resp = EventoMedicoAnularBtnCtrl.anularEM(em.Id);
        Test.stopTest();

        Evento_medico__c emToAssert = [SELECT Estado__c, (
                SELECT Status FROM Casos__r
        )
        FROM Evento_medico__c
        WHERE Nro_de_Evento_Medico_SS__c = '249818'];

        System.assertEquals(false, resp.hasError);
        System.assertEquals('Anulado', emToAssert.Estado__c);
        System.assertEquals('CA-----N', emToAssert.Casos__r[0].Status);
    }

	@IsTest
    static void anularEMWhenExternalIdIsNull() {
        Evento_medico__c em = new Evento_medico__c(Estado__c = 'En Auditoria');
        insert em;

        Case caso = new Case(Evento_Medico__c = em.Id, Status = 'CA-----G');
        insert caso;

        Test.startTest();
        EventoMedicoAnularBtnCtrl.Response resp = EventoMedicoAnularBtnCtrl.anularEM(em.Id);
        Test.stopTest();

        Evento_medico__c emToAssert = [SELECT Estado__c, (
                SELECT Status FROM Casos__r
        )
        FROM Evento_medico__c
        WHERE Id = :em.Id];

        System.assertEquals(false, resp.hasError);
        System.assertEquals('Anulado', emToAssert.Estado__c);
        System.assertEquals('CA-----N', emToAssert.Casos__r[0].Status);
    }

    @IsTest
    static void showTheCorrectMessageWhenTheResponseHasError() {
        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '249818');
        insert em;

        Test.startTest();
        EventoMedicoAnularBtnCtrl.Response resp = EventoMedicoAnularBtnCtrl.anularEM(em.Id);
        Test.stopTest();

        System.assertEquals(true, resp.hasError);
        System.assertEquals('El evento médico solicitado es inválido.', resp.message);
    }

	@isTest
    private static void whenTheUserIsNotTheOwnerOfAnEM_ShowErrorMessage() {
		Evento_medico__c em = new Evento_medico__c();
        em.RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
		em.Nro_de_Evento_Medico_SS__c = '249818';
		insert em;

		EventoMedicoAnularBtnCtrl.Response resp;
		System.runAs(usuario) {
			Test.startTest();
			resp = EventoMedicoAnularBtnCtrl.anularEM(em.Id);
			Test.stopTest();
		}

		System.assertEquals('El usuario no es el propietario', resp.message);
	}
}