force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/APr_Id__c.field-meta.xml
<CustomField>
    <fullName>APr_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Nota SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/fields/Codigo_tipoNA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_tipoNA__c</fullName>
    <externalId>true</externalId>
    <label>Codigo tipoNA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WSNotaDeAuditoriaEnviarASSTest.cls
@isTest 
private class WSNotaDeAuditoriaEnviarASSTest {

	@isTest
	private static void enviarNotaDeAuditoriaASS() {
		// setup
		Case caso = new Case();
		insert caso;

		Tipo_nota_de_auditoria__c tnda = new Tipo_nota_de_auditoria__c(Codigo_tipoNA__c = 'UnCodigo');
		insert tnda;

		Nota_de_Auditoria__c nda = new Nota_de_Auditoria__c(Tipo_nota_de_auditoria__c = tnda.Id,
															APr_Id__c = caso.Id,
															Nota__c = 'Una nota');
		nda.RecordTypeId = XappiaHelper.getRecordType('Nota_de_Auditoria__c', 'Service').Id;
		insert nda;

		String mockResponseBody = '{' +
									  '"error": false,' +
									  '"data": {"id_nota": "562866"},' +
									  '"httpCode": 200,' +
									  '"message": "Se cargó satisfactoriamente la nota de auditor.",' +
									  '"meta": {' +
										'"allowed_includes": [],' +
										'"default_includes": []' +
									  '}' +
									'}';
		XHttpCalloutMock mock = new XHttpCalloutMock();
        mock.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		mock.buildResponse()
			.withStatusCode(200)
			.withBody(mockResponseBody)
			.addForAddress(WSNotaDeAuditoriaEnviarASS.SERVICE_CONFIG.URL__c  + '/v1/salud/notas-auditor');

		Test.setMock(HttpCalloutMock.class, mock);

		// Test
        Test.startTest();
        WSNotaDeAuditoriaEnviarASS.SSWSResult rb = WSNotaDeAuditoriaEnviarASS.enviar(nda);
        Test.stopTest();

		System.assert(!rb.hasError);
		System.assertEquals(200, rb.responseBody.httpCode);
		System.assertEquals('Se cargó satisfactoriamente la nota de auditor.', rb.responseBody.message);

		Nota_de_Auditoria__c ndaQuery = [SELECT Id_Externo__c FROM Nota_de_Auditoria__c WHERE Id =: nda.Id];
		System.assertEquals('562866', ndaQuery.Id_Externo__c);
	}
}