force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/Presupuesto_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Presupuesto de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Cotizacion_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotizacion Prestador</label>
    <referenceTo>Cotizacion_Prestador__c</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripcion</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CotizacionPrestadorTriggerTest.cls
@isTest 
private class CotizacionPrestadorTriggerTest {

	@isTest
	private static void testName() {
		Orden_de_Compra__c orden = new Orden_de_Compra__c();
		insert orden;
		
		Case caso = new Case();
		caso.Description = 'desc';
		caso.Orden_de_Compra__c = orden.Id;
		insert caso;
		
        //insert caso;
        //orden.Ap_orden__c = caso.Id;
		
		Prestacion__c prestacion = new Prestacion__c();
		prestacion.Ap__c = caso.Id;
		Prestacion__c prestacion2 = new Prestacion__c();
		prestacion2.Ap__c = caso.Id;
		List<Prestacion__c> prestacionList = new List<Prestacion__c>{ prestacion, prestacion2 };
		insert prestacionList;

		Cotizacion_Prestador__c cotiz = new Cotizacion_Prestador__c();
		cotiz.Orden_de_Compra__c = orden.Id;
		
		Test.startTest();
		insert cotiz;
		Test.stopTest();

		List<Presupuesto_de_Compra__c> presupuestosList = [
			SELECT Descripcion__c, Prestacion__c 
			FROM Presupuesto_de_Compra__c 
			WHERE Cotizacion_Prestador__c =: cotiz.Id
		];

		System.assertEquals(2, presupuestosList.size());
		System.assertEquals('desc', presupuestosList[0].Descripcion__c);
		System.assertEquals(prestacion.Id, presupuestosList[0].Prestacion__c);

		System.assertEquals('desc', presupuestosList[1].Descripcion__c);
		System.assertEquals(prestacion2.Id, presupuestosList[1].Prestacion__c);
	}
}