force-app/main/default/objects/Case/fields/Prestaciones_en_auditoria__c.field-meta.xml
<CustomField>
    <fullName>Prestaciones_en_auditoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestaciones en auditoría</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reintegro_Total__c.field-meta.xml
<CustomField>
    <fullName>Reintegro_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reintegro Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_auditor__c</fullName>
    <label>Importe Reintegro auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_sys__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_sys__c</fullName>
    <label>Importe Reintegro sys</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrestacionReintegroTriggerHelper.cls
public class PrestacionReintegroTriggerHelper  {
	
	public static void checkPrestacionesEnAuditoriaInCase(Prestacion_de_reintegro__c[] prestaciones) {
		Set<Id> idReintegros = new Set<Id>();
		Case[] reintegrosToUpdate = new List<Case>();

		for(Prestacion_de_reintegro__c prest : prestaciones) {
			idReintegros.add(prest.Caso__c);
		}
		  
		Case[] reintegros = [
			SELECT Id, Prestaciones_en_auditoria__c, 
				(SELECT Id, Estado__c FROM Prestaciones_de_reintegros__r)
			FROM Case
			WHERE Id IN :idReintegros
		];

		for(Case reintegro : reintegros) {
			Boolean prestacionesEnAuditoria = false;

			for(Prestacion_de_reintegro__c prest : reintegro.Prestaciones_de_reintegros__r) {
				if(prest.Estado__c == 'C1-----A') {
					prestacionesEnAuditoria = true;
				}
			}

			System.debug(reintegro.Prestaciones_en_auditoria__c);
			if(prestacionesEnAuditoria != reintegro.Prestaciones_en_auditoria__c) {
				reintegro.Prestaciones_en_auditoria__c = prestacionesEnAuditoria;
				reintegro.Cambio_Manual__c = false;
				reintegrosToUpdate.add(reintegro);
			}
		}

		update reintegrosToUpdate;
		
	}

	public static void updateReintegroTotalFieldInCasesAssociate(Map<Id,Prestacion_de_reintegro__c> prestUpdatedOrCreated){
		
		Map<Id,Decimal> mapIdCaseImporteReintegro = new Map<Id,Decimal>();
		/*Map<Id,Prestacion_de_reintegro__c> mapIdPrest = new Map<Id,Prestacion_de_reintegro__c>();
		mapIdPrest.putAll(prestUpdatedOrCreated);*/
		Set<Id> setIdCasosAsociados = new Set<Id>();
		for(Prestacion_de_reintegro__c prest : prestUpdatedOrCreated.values()){
			setIdCasosAsociados.add(prest.Caso__c);
		}
		for(Prestacion_de_reintegro__c prestAsociadas : [
			SELECT Id, Caso__c,Caso__r.Reintegro_total__c, Cantidad__c,Importe_reintegro_Auditor__c, Importe_reintegro_Sys__c 
			FROM Prestacion_de_reintegro__c 
			WHERE Id NOT IN :prestUpdatedOrCreated.keySet() 
			AND Caso__c IN :setIdCasosAsociados]
		){
			prestUpdatedOrCreated.put(prestAsociadas.Id,prestAsociadas);
		}
		for(Prestacion_de_reintegro__c prest : prestUpdatedOrCreated.values()){
			if(!String.isBlank(prest.Caso__c)){
				
				if(prest.Importe_Reintegro_auditor__c != null || prest.Importe_reintegro_sys__c != null){
					Decimal cantidad = prest.Cantidad__c == null ? 1 : prest.Cantidad__c ;
					System.debug('cantidad: ' + cantidad);
					if(mapIdCaseImporteReintegro.containsKey(prest.Caso__c)){
					
						Decimal totalActual = mapIdCaseImporteReintegro.get(prest.Caso__c);

						System.debug(totalActual + ' + ' + prest.Importe_Reintegro_auditor__c); 
						Decimal importeAIngresar = 0;
						if(
							(prest.Importe_Reintegro_Auditor__c == 0 || prest.Importe_Reintegro_auditor__c == null) &&
							(prest.Importe_Reintegro_sys__c != 0 && prest.Importe_reintegro_sys__c != null)
						){
							importeAIngresar = prest.Importe_Reintegro_sys__c * cantidad;
						}else if(prest.Importe_reintegro_Auditor__c != 0  && prest.Importe_reintegro_Auditor__c != null){
							importeAIngresar = Prest.Importe_reintegro_Auditor__c * cantidad;
						}
						System.debug(importeAIngresar);
						totalActual += importeAIngresar;
						mapIdCaseImporteReintegro.put(prest.Caso__c,totalActual);
					}else{
						Decimal importeAIngresar = 0;
						if(
							(prest.Importe_Reintegro_Auditor__c == 0 || prest.Importe_Reintegro_auditor__c == null) &&
							(prest.Importe_Reintegro_sys__c != 0 && prest.Importe_reintegro_sys__c != null)
						){
							importeAIngresar = prest.Importe_Reintegro_sys__c * cantidad;
						}else if(prest.Importe_reintegro_Auditor__c != 0 && prest.Importe_reintegro_Auditor__c != null){
							importeAIngresar = Prest.Importe_reintegro_Auditor__c * cantidad;
						}
						System.debug(importeAIngresar);
						mapIdCaseImporteReintegro.put(prest.Caso__c,importeAIngresar);
					}
				}				
			}
		}

		List<Case> listaCasosAsociados = new List<Case>();
		if(!mapIdCaseImporteReintegro.keySet().isEmpty()){
			listaCasosAsociados = [
				SELECT Id,Reintegro_Total__c,RecordType.Name
				FROM Case
				WHERE Id IN :mapIdCaseImporteReintegro.keySet()
			];	
		}

		for(Case casoAsociado : listaCasosAsociados){
			System.debug(casoAsociado);
			if(mapIdCaseImporteReintegro.containsKey(casoAsociado.Id)){
				System.debug(mapIdCaseImporteReintegro);
				/*if(casoAsociado.Reintegro_Total__c == 0 || casoAsociado.Reintegro_Total__c == null){
					casoAsociado.Reintegro_Total__c = mapIdCaseImporteReintegro.get(casoAsociado.Id);
				}else{
					casoAsociado.Reintegro_Total__c += mapIdCaseImporteReintegro.get(casoAsociado.Id);
				}*/
				casoAsociado.Reintegro_Total__c = mapIdCaseImporteReintegro.get(casoAsociado.Id);
			}
		}

		update listaCasosAsociados;
	}
}