force-app/main/default/objects/Case/fields/Prestaciones_en_auditoria__c.field-meta.xml
<CustomField>
    <fullName>Prestaciones_en_auditoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestaciones en auditoría</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reintegro_Total__c.field-meta.xml
<CustomField>
    <fullName>Reintegro_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reintegro Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_auditor__c</fullName>
    <label>Importe Reintegro auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrestacionReintegroTriggerTest.cls
@isTest 
private class PrestacionReintegroTriggerTest {

	@isTest
	private static void checkTheFieldPrestacionesEnAuditoriaInCaseWhenAPrestacionChangesToThatStatus() {
		System.debug(XappiaHelper.getPicklistFieldValues('Prestacion_de_reintegro__c', 'Estado__c'));

		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Caso__c = reintegro.Id;
		insert prest;

		Test.startTest();
		prest.Estado__c = 'C1-----A';
		update prest;
		Test.stopTest();

		reintegro = [SELECT Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assert(reintegro.Prestaciones_en_auditoria__c);
	}

	@isTest
	private static void uncheckTheFieldPrestacionesEnAuditoriaInCaseWhenNoOnePrestacionHaveThatStatus() {
		System.debug(XappiaHelper.getPicklistFieldValues('Prestacion_de_reintegro__c', 'Estado__c'));

		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		reintegro.Prestaciones_en_auditoria__c = true;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Caso__c = reintegro.Id;
		insert prest;

		Test.startTest();
		prest.Estado__c = 'C1----AS';
		update prest;
		Test.stopTest();

		reintegro = [SELECT Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assert(!reintegro.Prestaciones_en_auditoria__c);
	}

	@isTest
	private static void checkTheFieldPrestacionesEnAuditoriaInCaseWhenAPrestacionIsInsertWithThatStatus() {
		System.debug(XappiaHelper.getPicklistFieldValues('Prestacion_de_reintegro__c', 'Estado__c'));

		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Estado__c = 'C1-----A';
		prest.Caso__c = reintegro.Id;

		Test.startTest();
		insert prest;
		Test.stopTest();

		reintegro = [SELECT Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assert(reintegro.Prestaciones_en_auditoria__c);
	}

	
	@isTest
	public static void whenAPrestacionIsInsertMustUpdateTheCaseFieldWhichShowsTheTotalAmmountOfThePrestacionDeReintegro(){
		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Estado__c = 'C1-----A';
		prest.Caso__c = reintegro.Id;
		prest.Importe_Reintegro_auditor__c = 150.00;

		Test.startTest();
		insert prest;
		Test.stopTest();

		reintegro = [SELECT Reintegro_Total__c,Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assertEquals(150.00,reintegro.Reintegro_Total__c);
	}

	@isTest
	public static void whenAPrestacionIsInsertMustUpdateTheCaseFieldWhichShowsTheTotalAmmountOfBothPrestacionDeReintegroSumm(){
		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Estado__c = 'C1-----A';
		prest.Caso__c = reintegro.Id;
		prest.Importe_Reintegro_auditor__c = 150.00;

		Prestacion_de_reintegro__c prestDos = new Prestacion_de_reintegro__c();
		prestDos.Estado__c = 'C1-----A';
		prestDos.Caso__c = reintegro.Id;
		prestDos.Importe_Reintegro_auditor__c = 250.00;
		insert prestDos;

		Test.startTest();
		insert prest;
		Test.stopTest();

		reintegro = [SELECT Reintegro_Total__c,Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assertEquals(400.00,reintegro.Reintegro_Total__c);
	}

	@isTest
	public static void whenAPrestacionIsInsertMustUpdateTheCaseFieldWhichShowsTheTotalAmmountOfBothPrestacionDeReintegroSummByTheQuantity(){
		Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		insert reintegro;

		Prestacion_de_reintegro__c prest = new Prestacion_de_reintegro__c();
		prest.Estado__c = 'C1-----A';
		prest.Caso__c = reintegro.Id;
		prest.Cantidad__c = 1;
		prest.Importe_Reintegro_auditor__c = 150.00;

		Prestacion_de_reintegro__c prestDos = new Prestacion_de_reintegro__c();
		prestDos.Estado__c = 'C1-----A';
		prestDos.Caso__c = reintegro.Id;
		prestDos.Cantidad__c = 3;
		prestDos.Importe_Reintegro_auditor__c = 250.00;
		insert prestDos;

		Test.startTest();
		insert prest;
		Test.stopTest();

		reintegro = [SELECT Reintegro_Total__c,Prestaciones_en_auditoria__c FROM Case WHERE Id = :reintegro.Id];
		System.assertEquals(900.00,reintegro.Reintegro_Total__c);
	}
}