force-app/main/default/objects/Case/fields/Reintegro_Total__c.field-meta.xml
<CustomField>
    <fullName>Reintegro_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reintegro Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_auditor__c</fullName>
    <label>Importe Reintegro auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Importe_Reintegro_sys__c.field-meta.xml
<CustomField>
    <fullName>Importe_Reintegro_sys__c</fullName>
    <label>Importe Reintegro sys</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateReintegroFromCasesBatch.cls
global without sharing class UpdateReintegroFromCasesBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        String query = 'SELECT Id, Importe_Reintegro_auditor__c,Cantidad__c,Importe_Reintegro_sys__c, Caso__c,Caso__r.Reintegro_Total__c ' +
            'FROM Prestacion_de_reintegro__c ' +
            'WHERE Caso__R.Reintegro_Total__c = 0';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Prestacion_de_reintegro__c> scope){
        // process each batch of records
        if(!scope.isEmpty()){
            map<Id,Prestacion_de_reintegro__c> mapIdPrest = new Map<Id,Prestacion_de_reintegro__c>(scope);
            PrestacionReintegroTriggerHelper.updateReintegroTotalFieldInCasesAssociate(mapIdPrest);
        }
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    
}