force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Elige__c.field-meta.xml
<CustomField>
    <fullName>Elige__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Elige</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_Mejorado__c.field-meta.xml
<CustomField>
    <fullName>Total_Mejorado__c</fullName>
    <label>Total Mejorado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_Socio__c.field-meta.xml
<CustomField>
    <fullName>Total_Socio__c</fullName>
    <label>Total Socio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordenes de Compras</relationshipLabel>
    <relationshipName>Ordenes_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/fields/forma_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>forma_de_Pago__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aca Salud</fullName>
                <label>Avalian</label>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Sin cargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presupuesto_de_Compra__c/Presupuesto_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Presupuesto de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Cotizacion_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotizacion Prestador</label>
    <referenceTo>Cotizacion_Prestador__c</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CotizacionPresatadorElegidaCtrl.cls
public class CotizacionPresatadorElegidaCtrl  {
	public ID ordenId {get; set;}
    public Cotizacion_Prestador__c cotizacion;
	public Orden_de_Compra__c ordenCompra;

    public Cotizacion_Prestador__c getCotizacion() {
        List<Cotizacion_Prestador__c> cotizaciones = [
			SELECT Id,Total_Socio__c, Total_Mejorado__c,Prestador__r.Name,
			Orden_de_Compra__r.Caso__c, (SELECT Id,Prestacion__r.Nombre_de_Prestacion__c FROM Presupuestos_de_Compras__r) 
			FROM Cotizacion_Prestador__c 
			WHERE Elige__c = true  AND Orden_de_Compra__c = :ordenId
		];
        if(!cotizaciones.isEmpty()){
			cotizacion = cotizaciones[0];
		}
		return cotizacion;
    }

	public Orden_de_Compra__c getOrdenCompra() {
        List<Orden_de_Compra__c> ordenes = [
			SELECT Id, forma_de_Pago__c
			FROM Orden_de_Compra__c 
			WHERE Id = :ordenId
		];
        if(!ordenes.isEmpty()){
			ordenCompra = ordenes[0];
		}
		return ordenCompra;
    }
}