force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_a_Pagar__c.field-meta.xml
<CustomField>
    <fullName>Total_a_Pagar__c</fullName>
    <label>Total a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_Mejorado__c.field-meta.xml
<CustomField>
    <fullName>Total_Mejorado__c</fullName>
    <label>Total Mejorado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Total_Presupuesto__c</fullName>
    <label>Total Presupuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Total_Socio__c.field-meta.xml
<CustomField>
    <fullName>Total_Socio__c</fullName>
    <label>Total Socio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/forma_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>forma_de_Pago__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aca Salud</fullName>
                <label>Avalian</label>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Sin cargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/Presupuesto_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Presupuesto de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Cargo_al_socio__c.field-meta.xml
<CustomField>
    <fullName>Cargo_al_socio__c</fullName>
    <label>Cargo al Socio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Cotizacion_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotizacion Prestador</label>
    <referenceTo>Cotizacion_Prestador__c</referenceTo>
    <relationshipLabel>Presupuestos de Compras</relationshipLabel>
    <relationshipName>Presupuestos_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Importe_mejorado__c.field-meta.xml
<CustomField>
    <fullName>Importe_mejorado__c</fullName>
    <label>Importe Mejorado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Presupuesto_de_Compra__c/fields/Importe_unitario__c.field-meta.xml
<CustomField>
    <fullName>Importe_unitario__c</fullName>
    <label>Importe Unitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PresupuestoCompraHelper.cls
public class PresupuestoCompraHelper {
    public static void RecalcularCotizacionPrestador(List<Presupuesto_de_Compra__c> pres) {
        Set<ID> cotizToUpdate = new Set<ID>();
        
		for(Presupuesto_de_Compra__c presupuesto :pres){
            cotizToUpdate.add(presupuesto.Cotizacion_Prestador__c);
        }

        Map<ID, Cotizacion_Prestador__c> cotiz = new Map<ID, Cotizacion_Prestador__c>();
        List<Cotizacion_Prestador__c> cotizaciones = [
			SELECT id, Total_Presupuesto__c, Total_mejorado__c, Total_Socio__c, Orden_de_Compra__r.forma_de_Pago__c
			FROM Cotizacion_Prestador__c 
			WHERE Id IN :cotizToUpdate
		];
        List<Presupuesto_de_Compra__c> presupuestos = [
			SELECT id, Cotizacion_Prestador__c, Importe_unitario__c, Importe_mejorado__c, Cargo_al_socio__c 
			FROM Presupuesto_de_Compra__c 
			WHERE Cotizacion_Prestador__c IN :cotizToUpdate
		];
        
		for (Cotizacion_Prestador__c cotizacion : cotizaciones) {
            Integer cantidadDePresupuestosPorCotizacion = 0;
			Boolean pagoPrest = cotizacion.Orden_de_Compra__r.forma_de_Pago__c == 'Prestador';

            for(Presupuesto_de_Compra__c thisPres : presupuestos){
                if(thisPres.Cotizacion_Prestador__c == cotizacion.Id){
                    if(cotiz.containsKey(thisPres.Cotizacion_Prestador__c)) {
                        Cotizacion_Prestador__c thisCotiz = cotiz.get(thisPres.Cotizacion_Prestador__c);

						System.debug('Total: ' + thisCotiz.Total_Presupuesto__c);
						System.debug('Unitario: ' + thisPres.Importe_unitario__c);
                        thisCotiz.Total_Presupuesto__c = ifNullReturnCero(thisCotiz.Total_Presupuesto__c) 
														+ ifNullReturnCero(thisPres.Importe_unitario__c);
                        thisCotiz.Total_Mejorado__c = ifNullReturnCero(thisCotiz.Total_Mejorado__c) 
													+ ifNullReturnCero(thisPres.Importe_mejorado__c);
                        thisCotiz.Total_Socio__c = ifNullReturnCero(thisCotiz.Total_Socio__c) 
													+ ifNullReturnCero(thisPres.Cargo_al_socio__c);
						thisCotiz.Total_a_Pagar__c = !pagoPrest ? ifNullReturnCero(thisCotiz.Total_Mejorado__c) 
							: ifNullReturnCero(thisCotiz.Total_Mejorado__c) - ifNullReturnCero(thisCotiz.Total_Socio__c);

                        cotiz.put(thisPres.Cotizacion_Prestador__c, thisCotiz);
                    } else {
                        cotizacion.Total_Presupuesto__c = ifNullReturnCero(thisPres.Importe_unitario__c);
                        cotizacion.Total_Mejorado__c = ifNullReturnCero(thisPres.Importe_mejorado__c);
                        cotizacion.Total_Socio__c = ifNullReturnCero(thisPres.Cargo_al_socio__c);
						cotizacion.Total_a_Pagar__c = !pagoPrest ? ifNullReturnCero(cotizacion.Total_Mejorado__c)
							: ifNullReturnCero(cotizacion.Total_Mejorado__c) - ifNullReturnCero(cotizacion.Total_Socio__c);
						
                        cotiz.put(thisPres.Cotizacion_Prestador__c, cotizacion);
                    }
                    cantidadDePresupuestosPorCotizacion = cantidadDePresupuestosPorCotizacion + 1;
                } else {
                    break;
                }
            }
            if(cantidadDePresupuestosPorCotizacion == 0 ){
                cotizacion.Total_Presupuesto__c = 0;
                cotizacion.Total_Mejorado__c = 0;
                cotizacion.Total_Socio__c = 0;
				//cotizacion.Total_a_Pagar__c = 0;

                cotiz.put(cotizacion.Id, cotizacion);
            }
        }
        List<Cotizacion_Prestador__c> cotizacionesParaActualizar = new List<Cotizacion_Prestador__c>();
        for (ID thisCotiz :cotiz.keySet()){
            cotizacionesParaActualizar.add(cotiz.get(thisCotiz));
        }
        update cotizacionesParaActualizar;
    }

	private static Decimal ifNullReturnCero(Decimal num) {
		return num != null ? num : 0;
	}
}