force-app/main/default/objects/Access_Token__c/Access_Token__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Access Token</label>
</CustomObject>

force-app/main/default/objects/Access_Token__c/fields/Encrypting_Key__c.field-meta.xml
<CustomField>
    <fullName>Encrypting_Key__c</fullName>
    <label>Encrypting Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Token__c/fields/Refresh_Value_2__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Value_2__c</fullName>
    <label>Refresh Value 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Token__c/fields/Refresh_Value_3__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Value_3__c</fullName>
    <label>Refresh Value 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Token__c/fields/Refresh_Value_4__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Value_4__c</fullName>
    <label>Refresh Value 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Token__c/fields/Refresh_Value__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Value__c</fullName>
    <label>Refresh Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_settings__mdt/AWS_settings__mdt.object-meta.xml
<CustomObject>
    <description>Datos de la configuracion de AWS</description>
    <label>AWS settings</label>
    <pluralLabel>AWS settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AWS_settings__mdt/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <label>Bucket</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_settings__mdt/fields/File_Directory__c.field-meta.xml
<CustomField>
    <fullName>File_Directory__c</fullName>
    <label>File Directory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_settings__mdt/fields/Name_Credential__c.field-meta.xml
<CustomField>
    <fullName>Name_Credential__c</fullName>
    <label>Name Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Debug_Mail__mdt/Batch_Debug_Mail__mdt.object-meta.xml
<CustomObject>
    <description>Mail para enviar errores de los batch ejecutados</description>
    <label>Batch debug mail</label>
    <pluralLabel>Batch debug mails</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Debug_Mail__mdt/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Webservice_endpoint__mdt/Webservice_endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Endpoints para las APIs de SS</description>
    <label>Webservice endpoint</label>
    <pluralLabel>Webservice endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webservice_endpoint__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Webservice_endpoint__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice_endpoint_setting__mdt/Webservice_endpoint_setting__mdt.object-meta.xml
<CustomObject>
    <description>Metadata store endpoint and credentials</description>
    <label>Webservice endpoint setting</label>
    <pluralLabel>Webservice endpoint setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webservice_endpoint_setting__mdt/fields/Is_Production__c.field-meta.xml
<CustomField>
    <fullName>Is_Production__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Production</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConfigUtils.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class ConfigUtils  {
	public static Organization currentOrg;
	public static Boolean isSandboxEnviroment() {
		if (currentOrg == null) {
			currentOrg = [SELECT Id, Name, IsSandbox FROM Organization LIMIT 1];
		}
		return currentOrg.isSandbox;
	}
	public static Batch_Debug_Mail__mdt getDebugEmail(String name){
		List<Batch_Debug_Mail__mdt> result = [SELECT Id, Mail__c FROM Batch_Debug_Mail__mdt WHERE MasterLabel = :name];
		if(!result.isEmpty()) {return result[0];}
		return null;
	}
	public static List<String> getBatchDebugEmails(){
		List<String> mails = new List<String>();
		List<Batch_Debug_Mail__mdt> result = [SELECT Id, Mail__c FROM Batch_Debug_Mail__mdt];
		for(Batch_Debug_Mail__mdt bdm : result) {
			if(String.isNotBlank(bdm.Mail__c)) {mails.add(bdm.Mail__c);}
		}
		return mails;
	}
	public static Webservice_endpoint_setting__mdt getWebServiceConfig(String name) {
		Boolean isProduction = !isSandboxEnviroment();
		List<Webservice_endpoint_setting__mdt> result = [SELECT
															Id,
															URL__c,
															User__c,
															Password__c,
															Client_Secret__c,
															Client_Id__c
														FROM Webservice_endpoint_setting__mdt
														WHERE MasterLabel = :name
														AND Is_Production__c = :isProduction];
		if(!result.isEmpty()) {return result[0];}
		return null;
	}
	public static Access_Token__c getToken(){
		Access_Token__c[] token = [SELECT DueDate__c,
									Encrypting_Key__c,
									Value__c,
									Value_2__c,
									Value_3__c,
									Value_4__c,
									Value_5__c,
									Refresh_Value__c,
									Refresh_Value_2__c,
									Refresh_Value_3__c,
									Refresh_Value_4__c
							FROM Access_Token__c];
		if(token.isEmpty()){return null;}
		else{return token[0];}
	}
	public static AWS_settings__mdt getAWSConfig(String name) {
		List<AWS_settings__mdt> result = [SELECT Name_Credential__c, Bucket__c, File_Directory__c, Region__c
									FROM AWS_settings__mdt
									WHERE DeveloperName = :name
									LIMIT 1];
		if(!result.isEmpty()) {return result[0];}
		return null;
	}
	public static Map<String, Webservice_endpoint__mdt> getEndpointsByTipo (String tipo) {
		List<Webservice_endpoint__mdt> endpoints = [SELECT Label, Endpoint__c FROM Webservice_endpoint__mdt WHERE Tipo__c =: tipo];
		Map<String, Webservice_endpoint__mdt> mapToReturn = new Map<String, Webservice_endpoint__mdt>();
		for (Webservice_endpoint__mdt endpoint : endpoints) {
			mapToReturn.put(endpoint.Label, endpoint);
		}
		return mapToReturn;
	}
}