force-app/main/default/objects/Integrante__c/Integrante__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Integrante__c.field-meta.xml
<CustomField>
    <fullName>Integrante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integrante</label>
    <referenceTo>Integrante_caso__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias_integrante</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityUpdateNotes.cls
public without sharing class OpportunityUpdateNotes  {

	public static void updateNotesAndIntegrantes(Opportunity oppFromSF,List<Integrante__c> integrantes , List<Nota_de_Auditoria__c> notasUpdate, List<Nota_de_Auditoria__c> notasInsert){
		List<Database.SaveResult> resultInts = Database.update(integrantes);
		System.debug('****resultInt ' + resultInts);
		Database.SaveResult resultOpp = Database.update(oppFromSF);
		System.debug('****resultOpp ' + resultOpp);
		List<Database.SaveResult> resultsNotasInsert = Database.insert(notasInsert);
		System.debug('****resultNotasInsert ' + resultsNotasInsert);
		List<Database.SaveResult> resultsNotas = Database.update(notasUpdate);
		System.debug('****resultNotas ' + resultsNotas);
	}

	public static void updateIntegrantes(List<Integrante__c> integrantes){
		List<Database.SaveResult> resultInts = Database.update(integrantes,false);
		System.debug('****resultInt ' + resultInts);
	}
}