force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Funcion__c.field-meta.xml
<CustomField>
    <fullName>Funcion__c</fullName>
    <label>Función</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <referenceTo>Prestacion_de_reintegro__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ap_autorizada__c.field-meta.xml
<CustomField>
    <fullName>Ap_autorizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se utiliza para marcar con un trigger cuando todas las alertas de todas las prestaciones se resuelven o no tienen alertas</description>
    <label>Ap autorizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Correo_asociado__c.field-meta.xml
<CustomField>
    <fullName>Correo_asociado__c</fullName>
    <label>Correo asociado</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Derivacion_de_lote__c.field-meta.xml
<CustomField>
    <fullName>Derivacion_de_lote__c</fullName>
    <label>Derivacion de lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lote Vigente</fullName>
                <default>true</default>
                <label>Lote Vigente</label>
            </value>
            <value>
                <fullName>Lote Devolucion</fullName>
            </value>
            <value>
                <fullName>Lote Pendiente</fullName>
            </value>
            <value>
                <fullName>Lote Especial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lote</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 9) OR (3 AND 4 AND 9 AND 10) OR (5 AND 6 AND 9) OR (7 AND 8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Especial</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Especial</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Vigente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Vigente</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Devolucion</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Devoluciones</value>
        </filterItems>
        <filterItems>
            <field>$Source.Derivacion_de_lote__c</field>
            <operation>equals</operation>
            <value>Lote Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Pendiente</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Estado__c</field>
            <operation>equals</operation>
            <value>Abierto</value>
        </filterItems>
        <filterItems>
            <field>Lote__c.Visibilidad_Front__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Lote__c</referenceTo>
    <relationshipLabel>Reintegros</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Reintegro.recordType-meta.xml
<RecordType>
    <fullName>Reintegro</fullName>
    <active>true</active>
    <businessProcess>Reintegro</businessProcess>
    <label>Reintegro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORÍA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
            <value>
                <fullName>PREEX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestaciones de reintegros</relationshipLabel>
    <relationshipName>Prestaciones_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prestacion__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Practicas odontologicas</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Prestaciones de reintegros (Prestación de reintegro)</relationshipLabel>
    <relationshipName>Prestacionesodont_de_reintegros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AlertasTriggerTest.cls
@IsTest
private class AlertasTriggerTest {
    @IsTest
    static void whenAnyAlertIsNotFinishedItShouldNotCheckApAutorizadaFieldOnTheAP() {
        Case caseTest = new Case();
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id);
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id);
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id,Estado__c='C1EA-RAA');
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id);
        Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id);
        insert alert1;
        insert alert2;
        insert alert3;
        Test.startTest();
        alert3.Estado__c = 'C1EA--AA';
        update alert3;
        Test.stopTest();
        System.assertEquals(false,[SELECT Id,Ap_autorizada__c FROM Case WHERE Id = :caseTest.Id].Ap_autorizada__c);
    }
	@IsTest
    static void whenAllAlertsAreRefusedItShouldCheckApRechazadaFieldOnTheAP() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA-RAA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA-RAA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id,Estado__c='C1EA-RAA');
        insert alert1;
		Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id,Estado__c='C1EA-RAA');
        insert alert2;
		Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id);
        insert alert3;
		Test.startTest();
        alert3.Estado__c = 'C1EA-RAA';
        update alert3;
        Test.stopTest();
		caseTest = [SELECT Caso_Rechazado__c, Status,Derivacion_de_lote__c FROM Case WHERE Id = :caseTest.Id];
        System.assertEquals(true, caseTest.Caso_Rechazado__c);
        System.assertEquals('Rechazado', caseTest.Status);
    }
	@IsTest
	static void whenPrestacionHaveNoRelationshipWithApDontDoNothing() {
		Prestacion__c prestTest = new Prestacion__c(Estado__c = 'C1EA-RAA');
        insert prestTest;
		Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id);
        insert alert1;
		Test.startTest();
        alert1.Estado__c = 'C1EA-RAA';
        update alert1;
		Test.stopTest();
		// Solo se hace para el porcentaje de cobertura, por eso no hay ningun assert
	}
	@IsTest
	static void whenPrestacionHaveNoRelationshipWithReintegroDontDoNothing() {
		Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Estado__c = 'C1EA-RAA');
        insert prestTest;
		Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id);
        insert alert1;

		Test.startTest();
        alert1.Estado__c = 'C1EA-RAA';
        update alert1;
		Test.stopTest();
		// Solo se hace para el porcentaje de cobertura, por eso no hay ningun assert
	}
	@IsTest
    static void whenAllAlertsAreRefusedItShouldCheckApRechazadaFieldOnTheReintegro() {
        Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
        insert reintegro;
        Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1EA-RAA');
        insert prestTest;
        Prestacion_de_reintegro__c prestTest2 = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1EA-RAA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA-RAA');
        insert alert1;
		Alerta__c alert2 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA-RAA');
        insert alert2;
		Alerta__c alert3 = new Alerta__c(Prestacion_de_reintegro__c = prestTest2.Id);
        insert alert3;
		Test.startTest();
        alert3.Estado__c = 'C1EA-RAA';
        update alert3;
        Test.stopTest();
		reintegro = [SELECT Caso_Rechazado__c, Status FROM Case WHERE Id = :reintegro.Id];
        System.assertEquals(true, reintegro.Caso_Rechazado__c);
		System.assertEquals('Rechazado', reintegro.Status);
    }
	@IsTest
    static void whenAllAlertsAMAreResolvedItShouldCheckSinAlertasAMPendientesOnCase() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id,Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id, Funcion__c = 'AM');
        insert alert1;
        insert alert2;
        insert alert3;
        Test.startTest();
        alert3.Estado__c = 'C1EA--AA';
        update alert3;
        Test.stopTest();
		Case aCase = [SELECT Id, Sin_alertas_AM_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(aCase.Sin_alertas_AM_pendientes__c);
    }
	@IsTest
    static void whenAllAlertsAMAreNotResolvedItShouldNotCheckSinAlertasAMPendientesOnCase() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c[] alerts = new List<Alerta__c>{alert1, alert2, alert3};
		insert alerts;
        Test.startTest();
        alert3.Estado__c = 'C1-----A';
        update alert3;
        Test.stopTest();
		Case aCase = [SELECT Id, Sin_alertas_AM_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(!aCase.Sin_alertas_AM_pendientes__c);
    }
	@IsTest
    static void whenAllAlertsAMAreResolvedItShouldCheckSinAlertasAMPendientesOnCaseReintegro() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Caso__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion_de_reintegro__c prestTest2 = new Prestacion_de_reintegro__c(Caso__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert2 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id,Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert3 = new Alerta__c(Prestacion_de_reintegro__c = prestTest2.Id, Funcion__c = 'AM');
        insert alert1;
        insert alert2;
        insert alert3;
        Test.startTest();
        alert3.Estado__c = 'C1EA--AA';
        update alert3;
        Test.stopTest();
		Case aCase = [SELECT Id, Sin_alertas_AM_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(aCase.Sin_alertas_AM_pendientes__c);
    }
	@IsTest
    static void whenAllAlertsAMAreNotResolvedItShouldNotCheckSinAlertasAMPendientesOnCaseReintegro() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Caso__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion_de_reintegro__c prestTest2 = new Prestacion_de_reintegro__c(Caso__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert2 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c alert3 = new Alerta__c(Prestacion_de_reintegro__c = prestTest2.Id, Estado__c='C1EA--AA', Funcion__c = 'AM');
        Alerta__c[] alerts = new List<Alerta__c>{alert1, alert2, alert3};
		insert alerts;
        Test.startTest();
        alert3.Estado__c = 'C1-----A';
        update alert3;
        Test.stopTest();
		Case aCase = [SELECT Id, Sin_alertas_AM_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(!aCase.Sin_alertas_AM_pendientes__c);
    }
    @IsTest
    static void whenNextAlertInAPrestacionIsDiscaIDCheckAlertasDiscaIDPendientesOnCase() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1-----A', Funcion__c = 'FCION_FRONT', Nivel_de_auditoria__c = 1);
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1-----A', Funcion__c = 'FCION_ID', Nivel_de_auditoria__c = 2);
        Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id, Estado__c='C1-----A', Funcion__c = 'FCION_FRONT', Nivel_de_auditoria__c = 1);
        Alerta__c alert4 = new Alerta__c(Prestacion__c = prestTest2.Id, Estado__c='C1-----A', Funcion__c = 'FCION_DISCA', Nivel_de_auditoria__c = 2);
        insert alert1;
        insert alert2;
        insert alert3;
        insert alert4;
		caseTest = [SELECT Alertas_disca_ID_pendientes__c FROM Case WHERE Id = :caseTest.Id];
		System.debug(caseTest);
        Test.startTest();
        alert1.Estado__c = 'C1EA--AA';
        update alert1;
        Test.stopTest();
		Case aCase = [SELECT Id, Alertas_disca_ID_pendientes__c, Alertas_disca_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(aCase.Alertas_disca_ID_pendientes__c);
        System.assert(!aCase.Alertas_disca_pendientes__c);
    }
    @IsTest
    static void whenAlertDiscaIdIsAuthorizedUnCheckAlertasDiscaIDPendientesOnCase() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
		caseTest.Alertas_disca_ID_pendientes__c = true;
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1EA--AA', Funcion__c = 'FCION_FRONT', Nivel_de_auditoria__c = 1);
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1-----A', Funcion__c = 'FCION_ID', Nivel_de_auditoria__c = 2);
        insert alert1;
        insert alert2;
		caseTest = [SELECT Alertas_disca_ID_pendientes__c FROM Case WHERE Id = :caseTest.Id];
		System.debug(caseTest);
        Test.startTest();
        alert2.Estado__c = 'C1EA--AA';
        update alert2;
        Test.stopTest();
		Case aCase = [SELECT Id, Alertas_disca_ID_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(!aCase.Alertas_disca_ID_pendientes__c);
    }
	@IsTest
    static void whenNextAlertsIsDiscaCheckAlertasDiscaPendientesOnCase() {
        Case caseTest = new Case();
		caseTest.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		caseTest.Correo_asociado__c = 'ej@test.com';
        insert caseTest;
        Prestacion__c prestTest = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest;
        Prestacion__c prestTest2 = new Prestacion__c(Ap__c = caseTest.Id, Estado__c = 'C1EA--AA');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1-----A', Funcion__c = 'FCION_FRONT', Nivel_de_auditoria__c = 1);
        Alerta__c alert2 = new Alerta__c(Prestacion__c = prestTest.Id, Estado__c='C1-----A', Funcion__c = 'FCION_ID', Nivel_de_auditoria__c = 2);
        Alerta__c alert3 = new Alerta__c(Prestacion__c = prestTest2.Id, Estado__c='C1-----A', Funcion__c = 'FCION_DISCA', Nivel_de_auditoria__c = 2);
        Alerta__c[] alertas = new List<Alerta__c>{alert1, alert2, alert3};
        Test.startTest();
        insert alertas;
        Test.stopTest();
		Case aCase = [SELECT Id, Alertas_disca_ID_pendientes__c, Alertas_disca_pendientes__c FROM Case WHERE Id = :caseTest.Id];
        System.assert(aCase.Alertas_disca_pendientes__c);
        System.assert(!aCase.Alertas_disca_ID_pendientes__c);
    }
    @isTest
    public static void whenThePrestacionAssociateToACaseReintegroItsAutorizeShouldAutorizeTheCase(){
        Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
        insert reintegro;
        Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1----AS');
        insert prestTest;
        Prestacion_de_reintegro__c prestTest2 = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1----AS');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1----AS');
        insert alert1;
		Alerta__c alert2 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1----AS');
        insert alert2;
		Alerta__c alert3 = new Alerta__c(Prestacion_de_reintegro__c = prestTest2.Id);
        insert alert3;
		Test.startTest();
        alert3.Estado__c = 'C1EA--AA';
        update alert3;
        Test.stopTest();
		reintegro = [SELECT Caso_Rechazado__c, Status,	Derivacion_de_lote__c FROM Case WHERE Id = :reintegro.Id];
        System.assertEquals(false, reintegro.Caso_Rechazado__c);
		System.assertEquals('Autorizada', reintegro.Status);
    }
	@IsTest
    static void whenAllAlertsAreRefusedItShouldChangeTheLoteDerivacionInTheReintegro() {
        Case reintegro = new Case();
		reintegro.RecordTypeId = XappiaHelper.getRecordType('Case', 'Reintegro').Id;
        insert reintegro;
        Prestacion_de_reintegro__c prestTest = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1---RSA');
        insert prestTest;
        Prestacion_de_reintegro__c prestTest2 = new Prestacion_de_reintegro__c(Caso__c = reintegro.Id, Estado__c = 'C1---RSP');
        insert prestTest2;
        Alerta__c alert1 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA-RAA');
        insert alert1;
		Alerta__c alert2 = new Alerta__c(Prestacion_de_reintegro__c = prestTest.Id, Estado__c='C1EA-RAA');
        insert alert2;
		Alerta__c alert3 = new Alerta__c(Prestacion_de_reintegro__c = prestTest2.Id);
        insert alert3;
		Test.startTest();
        alert3.Estado__c = 'C1EA-RAP';
        update alert3;
        Test.stopTest();
		reintegro = [SELECT Caso_Rechazado__c, Status,Derivacion_de_lote__c,Lote__c FROM Case WHERE Id = :reintegro.Id];
        System.debug('caso test ' + reintegro);
        System.assertEquals(true, reintegro.Caso_Rechazado__c);
		System.assertEquals('Rechazado', reintegro.Status);
    }
}