force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Funcion__c.field-meta.xml
<CustomField>
    <fullName>Funcion__c</fullName>
    <label>Función</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AlertTriggerHandler.cls
/**-----------------------------------------------------------------------------------------------------------------------
@author			Jeferson Ruiz.
@description	Clase manejadora del desencadenador para el objeto Alertas
@date			21/02/2021
------------------------------------------------------------------------------------------------------------------------*/
public with sharing class AlertTriggerHandler extends TriggerHandler {
	List<Alerta__c> lNew = (List<Alerta__c>) Trigger.new;
	List<Alerta__c> lOld = (List<Alerta__c>) Trigger.old;
	Map<Id,Alerta__c> mNew = (Map<Id,Alerta__c>) Trigger.newMap;
	Map<Id,Alerta__c> mOld = (Map<Id,Alerta__c>) Trigger.oldMap;
	public override void beforeInsert() {
		// Nothing
	}
	public override void beforeUpdate() {
		// Nothing
	}
	public override void beforeDelete() {
		// Nothing
	}
	public override void afterInsert() {
		List<Alerta__c> alertsToCheck = new List<Alerta__c>();
		List<Alerta__c> alertsAM = new List<Alerta__c>();
		List<Alerta__c> alertsDisca = new List<Alerta__c>();
		for(Alerta__c alert : lNew) {
			if(AlertasHelper.isRefused(alert.Estado__c) || AlertasHelper.isAuthorized(alert.Estado__c)) {
				alertsToCheck.add(alert);
			}
			if(alert.Funcion__c == 'AM') {
				alertsAM.add(alert);
			}
			if(alert.Funcion__c == 'FCION_DISCA' || alert.Funcion__c == 'FCION_ID') {
				alertsDisca.add(alert);
			}
		}
		if(!alertsToCheck.isEmpty()) {
			AlertasHelper.checkCaseState(alertsToCheck);
		}
		if(!alertsAM.isEmpty()) {
			AlertasHelper.checkCaseNoAlertsAMPending(alertsAM);
		}
		if(!alertsDisca.isEmpty()) {
			AlertasHelper.checkCaseAlertsDiscaPending(alertsDisca);
		}
	}
	public override void afterUpdate() {
		List<Alerta__c> alertsToCheck = new List<Alerta__c>();
		List<Alerta__c> alertsAM = new List<Alerta__c>();
		List<Alerta__c> alertsDisca = new List<Alerta__c>();
		for(Alerta__c alert : lNew) {
			Alerta__c oldAlert = mOld.get(alert.Id);
			if(AlertasHelper.isRefused(alert.Estado__c) || AlertasHelper.isAuthorized(alert.Estado__c)) {
				alertsToCheck.add(alert);
				alertsDisca.add(alert);
			}
			if(alert.Estado__c != oldAlert.Estado__c && alert.Funcion__c == 'AM') {
				alertsAM.add(alert);
			}
		}
		if(!alertsToCheck.isEmpty()) {
			AlertasHelper.checkCaseState(alertsToCheck);
		}
		if(!alertsAM.isEmpty()) {
			AlertasHelper.checkCaseNoAlertsAMPending(alertsAM);
		}
		if(!alertsDisca.isEmpty()) {
			AlertasHelper.checkCaseAlertsDiscaPending(alertsDisca);
		}
	}
	public override void afterDelete() {
		//Nothing
	}
	public override void afterUndelete() {
		//Nothing
	}
}