force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/codigo_ACT_SS__c.field-meta.xml
<CustomField>
    <fullName>codigo_ACT_SS__c</fullName>
    <externalId>true</externalId>
    <label>codigo ACT SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Codigo_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asociado__c</fullName>
    <formula>Asociado__r.Codigo_de_Afiliado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código Asociado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_cierre_de_clausula__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_cierre_de_clausula__c</fullName>
    <description>al cambiar este campo impactará en SS cerrando la act</description>
    <label>Fecha de cierre de clausula</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_vigencia_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_vigencia_hasta__c</fullName>
    <label>Fecha de vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClausulasTempTriggerHelper.cls
public class ClausulasTempTriggerHelper {
    public static void sendToSSAndFillFields(List<Asignacion_de_clausula_temporaria__c> clausulas) {
		  System.enqueueJob(new ClausulaTempQueueable(clausulas));
    }

    public static Asignacion_de_clausula_temporaria__c updateClausula(Asignacion_de_clausula_temporaria__c clausula){
      User usuario = [SELECT Alias, CommunityNickname, Profile.Name FROM User WHERE Id =: clausula.CreatedById];
      String apodo = usuario.CommunityNickname.toUpperCase();
	  String fechaHasta;

	  if(clausula.codigo_ACT_SS__c == null) {
		fechaHasta = clausula.Fecha_de_vigencia_hasta__c != null ? String.valueOf(clausula.Fecha_de_vigencia_hasta__c) : null;
	  } else {
		fechaHasta = clausula.Fecha_de_cierre_de_clausula__c != null 
						? String.valueOf(clausula.Fecha_de_cierre_de_clausula__c) : null;
	  }

      Map<String, Object> jsonMap = new Map<String,Object>{
        'usuario' => apodo,
        'fecha_desde' => clausula.Fecha_desde__c != null ? String.valueOf(clausula.Fecha_desde__c) : null,
        'fecha_hasta' => fechaHasta,
        'codigo_afiliado' => clausula.Codigo_Asociado__c
      };

	  if(clausula.codigo_ACT_SS__c != null) {
		jsonMap.put('acta_id', clausula.codigo_ACT_SS__c);
	  }
	  //else {
		//jsonMap.put('fecha_desde', clausula.Fecha_desde__c != null ? String.valueOf(clausula.Fecha_desde__c) : null);
	  //}

	  String body = JSON.serialize(jsonMap);

      System.debug('body to sendClausula:  ' + body);
      WSClausulaTempEnviarASS.Response resp = WSClausulaTempEnviarASS.sendClausulaTempToSS(body);
      Asignacion_de_clausula_temporaria__c clon = new Asignacion_de_clausula_temporaria__c (Id = clausula.Id);
  
      if(!resp.hasError){
        clon.codigo_ACT_SS__c = resp.clausula.data.acta_id != null ? String.valueOf(resp.clausula.data.acta_id) : null;
        clon.Fallo_en_SS__c = null;
        clon.Fecha_de_fallo__c = null; 
      }
      else{
        clon.Fallo_en_SS__c = resp.message;
        clon.Fecha_de_fallo__c = Datetime.now(); 
      }

      return clon;
    }
}