force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/codigo_ACT_SS__c.field-meta.xml
<CustomField>
    <fullName>codigo_ACT_SS__c</fullName>
    <externalId>true</externalId>
    <label>codigo ACT SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Codigo_Asociado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Asociado__c</fullName>
    <formula>Asociado__r.Codigo_de_Afiliado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código Asociado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_cierre_de_clausula__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_cierre_de_clausula__c</fullName>
    <description>al cambiar este campo impactará en SS cerrando la act</description>
    <label>Fecha de cierre de clausula</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_vigencia_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_vigencia_hasta__c</fullName>
    <label>Fecha de vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClausulaTempReintentoEnvioASSBatch.cls
global class ClausulaTempReintentoEnvioASSBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Fallo_en_SS__c, Fecha_de_fallo__c, CreatedById, Fecha_desde__c, Fecha_de_vigencia_hasta__c, ' +
				 'Codigo_Asociado__c, codigo_ACT_SS__c, Fecha_de_cierre_de_clausula__c ' +
            'FROM Asignacion_de_clausula_temporaria__c WHERE Fecha_de_fallo__c != null'
        );
    }
    global void execute(Database.BatchableContext bc, List<Asignacion_de_clausula_temporaria__c> records){
        List<Asignacion_de_clausula_temporaria__c> clausulas = new List<Asignacion_de_clausula_temporaria__c>();
        for (Asignacion_de_clausula_temporaria__c clausula : records) {
            clausulas.add(ClausulasTempTriggerHelper.updateClausula(clausula));
        }
        if(!clausulas.isEmpty()){
            update clausulas;
        }
        
    }    
    global void finish(Database.BatchableContext bc){
    }    
}