force-app/main/default/objects/Cobertura_Especial__c/Cobertura_Especial__c.object-meta.xml
<CustomObject>
    <label>Cobertura Especial</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Cobertura Especial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coberturas Especiales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cobertura_Especial__c/fields/Error_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Error_en_SS__c</fullName>
    <label>Error en SS</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Evento_Medico_de_Seguimiento__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_de_Seguimiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico de Seguimiento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Evento_medico__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Evento médico de seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Coberturas Especiales</relationshipLabel>
    <relationshipName>Coberturas_Especiales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Fecha_de_error_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_error_en_SS__c</fullName>
    <label>Fecha de error en SS</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/classes/CoberturaEspecialReintentoEnvioBatchTest.cls
@isTest 
private class CoberturaEspecialReintentoEnvioBatchTest {
	
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseError;
	static Cobertura_Especial__c cobertura;
	static Evento_medico__c em;

	static {
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSCoberturaEspecialEnviarMock.getFound())
			.addForAddress(WSCoberturaEspecialEnviar.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/276349/coberturas-especiales');
		
		getResponseError = new XHttpCalloutMock();
		getResponseError.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseError.buildResponse()
			.withStatus('Error')
			.withStatusCode(422)
			.withBody(WSCoberturaEspecialEnviarMock.getError())
			.addForAddress(WSCoberturaEspecialEnviar.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/276349/coberturas-especiales');
	
	}

	@TestSetup
	private static void setup(){
		Test.setMock(HttpCalloutMock.class, getResponseError);

		em = new Evento_medico__c();
		em.RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
		em.Nro_de_Evento_Medico_SS__c = '276349';
		insert em;

		Test.startTest();
		cobertura = new Cobertura_Especial__c();
		cobertura.Evento_Medico_de_Seguimiento__c = em.Id;
		cobertura.Fecha_desde__c = Date.today().addDays(-7);
		insert cobertura;
		Test.stopTest();
	}

	@isTest
	private static void whenACoberturaIsCreatedWithInValidFields_ItShouldReSendToSSAndFillTheCorrespondingFields() {
	
		cobertura = [
			SELECT Error_en_SS__c, Fecha_de_error_en_SS__c, Id_externo__c FROM Cobertura_Especial__c LIMIT 1
		];

		System.assertEquals(null, cobertura.Id_externo__c);
		System.assertNotEquals(null, cobertura.Error_en_SS__c);
		System.assertNotEquals(null, cobertura.Fecha_de_error_en_SS__c);
		
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		Database.executeBatch(new CoberturaEspecialReintentoEnvioASSBatch());
		Test.stopTest();

		cobertura = [
			SELECT Error_en_SS__c, Fecha_de_error_en_SS__c, Id_externo__c FROM Cobertura_Especial__c WHERE Id =: cobertura.Id
		];

		System.assertEquals('191769', cobertura.Id_externo__c);
		System.assertEquals(null, cobertura.Error_en_SS__c);
		System.assertEquals(null, cobertura.Fecha_de_error_en_SS__c);
	}
}