force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Body_error__c.field-meta.xml
<CustomField>
    <fullName>Body_error__c</fullName>
    <label>Body error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cambio_Manual__c.field-meta.xml
<CustomField>
    <fullName>Cambio_Manual__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Cambio Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Error_archivos__c.field-meta.xml
<CustomField>
    <fullName>Error_archivos__c</fullName>
    <label>Error archivos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_error_archivos__c.field-meta.xml
<CustomField>
    <fullName>Fecha_error_archivos__c</fullName>
    <label>Fecha error archivos</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_de_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_solicitud__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de solicitud</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_Solicitud__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Solicitud__c</fullName>
    <label>Tipo de Solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALTA</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>REINGRESO</fullName>
                <label>Reingreso</label>
            </value>
            <value>
                <fullName>REING_GFAM</fullName>
                <label>Reingreso Grupo Familiar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Usuario_error__c.field-meta.xml
<CustomField>
    <fullName>Usuario_error__c</fullName>
    <label>Usuario error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityAttachmentQueueable.cls
public class OpportunityAttachmentQueueable  implements Queueable, Database.AllowsCallouts{
	public List<Opportunity> opps;
	public Opportunity actualOpp;
	public List<Id> docIds;
	public Boolean errorOp;
	public String errorMsg;

	public OpportunityAttachmentQueueable(List<Opportunity> opportunities,Opportunity opp , List<Id> documents, Boolean err){
		this.opps = opportunities;
		this.actualOpp = opp;
		this.docIds = documents;
		this.errorOp = err;
	}

	public void execute(QueueableContext context) {
		if(!docIds.isEmpty()){
			Id versionId = docIds.remove(0);
			
			ContentVersion version = [SELECT Id, VersionData, Title,Enviado__c, FileExtension, Description FROM ContentVersion WHERE Id = :versionId];
			User usuario = [SELECT Id, CommunityNickname FROM User WHERE Id = :UserInfo.getUserId()];
			WSResult resp;
			List<Nota_de_Auditoria__c> notas = new List<Nota_de_Auditoria__c>();
			String nick;
			if(actualOpp.Usuario_error__c != null){
				nick = actualOpp.Usuario_error__c;
			}
			else{
				nick = usuario.CommunityNickname.toUpperCase();
			}
			switch on actualOpp.Tipo_de_Solicitud__c{
				when 'ALTA'{
					Map<String,Object> bodyMap = OpportunitySendAltaBtnCtrl.generateJSON(nick,actualOpp,actualOpp.Localidad_new__r.Loc_Id__c,notas);
					bodyMap.put('archivos', new List<Map<String,Object>> {
						new Map<String, Object>{
							'datos' => 'data:' + Utils.getTypeAndExtension(version.FileExtension) + ';base64,' + EncodingUtil.base64Encode(version.VersionData),
							'observaciones' => null,
    						'descripcion' => version.Description,
							'nombre' => version.Title.contains('.' + version.FileExtension) 
											? version.Title : version.Title + '.' + version.FileExtension
						}
					});
					if(actualOpp.Nro_de_solicitud__c != null){
						List<Object> encabezado = (List<Object>) bodyMap.get('encabezado');
						Map<String, Object> encabezadoMap = (Map<String, Object>) encabezado.remove(0);
						encabezadoMap.put('solicitud_id', actualOpp.Nro_de_solicitud__c);
						encabezado.add(encabezadoMap);
						bodyMap.put('encabezado',encabezado);
					}
					resp = WSOpportunitySendAlta.sendAlta(JSON.serialize(bodyMap));
				}
				when 'REING_GFAM'{
					Map<String,Object> bodyMap = OpportunitySendAltaBtnCtrl.generateJSON(nick,actualOpp,actualOpp.Localidad_new__r.Loc_Id__c,notas);
					bodyMap.put('archivos', new List<Map<String,Object>> {
						new Map<String, Object>{
							'datos' => 'data:' + Utils.getTypeAndExtension(version.FileExtension) + ';base64,' + EncodingUtil.base64Encode(version.VersionData),
							'observaciones' => null,
    						'descripcion' => version.Description,
							'nombre' => version.Title.contains('.' + version.FileExtension) 
											? version.Title : version.Title + '.' + version.FileExtension
						}
					});
					resp = WSOpportunityReingresoGFam.enviarReingresoGrupoFamiliar(JSON.serialize(bodyMap));
				}
				when 'REINGRESO'{
					Map<String,Object> bodyMap = OpportunitySendAltaBtnCtrl.generateReingresoJSON(nick,actualOpp,actualOpp.Localidad_new__r.Loc_Id__c,notas);
					bodyMap.put('archivos', new List<Map<String,Object>> {
						new Map<String, Object>{
							'datos' => 'data:' + Utils.getTypeAndExtension(version.FileExtension) + ';base64,' + EncodingUtil.base64Encode(version.VersionData),
							'observaciones' => null,
    						'descripcion' => version.Description,
							'nombre' => version.Title.contains('.' + version.FileExtension) 
											? version.Title : version.Title + '.' + version.FileExtension
						}
					});
					resp = WSOpportunityReingreso.sendReingreso(JSON.serialize(bodyMap));
				}
				when else{
					//should not happen
				}
			}
			
			if(!resp.hasError || Test.isRunningTest()){
				ContentVersion updateVersion = new ContentVersion(Id = version.Id, Enviado__c = true);
				update updateVersion;
			}
			else{
				errorOp = true;
				errorMsg = resp.message;
			}
			if(docIds.isEmpty() || Test.isRunningTest()){
				if(errorOp){
					actualOpp.Fecha_error_archivos__c = Datetime.now();
					actualOpp.Error_archivos__c = errorMsg;
					if(actualOpp.Usuario_error__c == null){
						actualOpp.Usuario_error__c = usuario.CommunityNickname.toUpperCase();
					}
					//opp.Body_error__c = JSON.serialize(bodyMap);
				}
				else{
					actualOpp.Fecha_error_archivos__c = null;
					actualOpp.Error_archivos__c = null;
					actualOpp.Usuario_error__c = null;
					//opp.Body_error__c = null;
				}
				actualOpp.Cambio_Manual__c = false;
				Database.SaveResult res=Database.update(actualOpp,false);
				System.debug(res);
			}
			if(!Test.isRunningTest()){
				System.enqueueJob(new OpportunityAttachmentQueueable(opps,actualOpp,docIds,errorOp));
			}
		}
		else{
			if(!opps.isEmpty()){
				Opportunity opp = opps.remove(0);
				List<ContentDocumentLink> links = [
					SELECT Id,ContentDocumentId
					FROM ContentDocumentLink
					WHERE LinkedEntityId = :opp.Id
				];
				List<Id> docIds = new List<Id>();
				for(ContentDocumentLink link : links){
					docIds.add(link.ContentDocumentId);
				}
				List<ContentVersion> versions = [
					SELECT Id 
					FROM ContentVersion 
					WHERE ContentDocumentId IN :docIds
					AND Enviado__c = false AND IsLatest = true
					];
				List<Id> versionIds = new List<Id>();
				for(ContentVersion ver : versions){
					versionIds.add(ver.Id);
				}
			
				if(!Test.isRunningTest()){
					if(!opps.isEmpty()){
						System.enqueueJob(new OpportunityAttachmentQueueable(opps,opp,versionIds,false));
					}
				}
			}
		}
	}
}