force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/CIU__c.field-meta.xml
<CustomField>
    <fullName>CIU__c</fullName>
    <label>CIU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Codigo_de_Provincia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Provincia__c</fullName>
    <label>Código de Provincia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Nombre_de_Localidad__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Localidad__c</fullName>
    <label>Nombre de Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Organizador_lookup__c.field-meta.xml
<CustomField>
    <fullName>Organizador_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Localidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/ZG_Codigo__c.field-meta.xml
<CustomField>
    <fullName>ZG_Codigo__c</fullName>
    <label>ZG Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Localidades__c.field-meta.xml
<CustomField>
    <fullName>Localidades__c</fullName>
    <label>Localidades</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LocalidadProcessor.cls
public class LocalidadProcessor implements IMasterBuilder {

	public Boolean hasNext = false;
	public String next;
	public Datetime runTime;
	public Datetime lastUpdateForLocalidades;

	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;

	public LocalidadProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public LocalidadProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForLocalidades) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForLocalidades = lastUpdateForLocalidades;
	}

	public List<WSLocalidadResp.Data> callWebService() {
		List<WSLocalidadResp.Data> wsData = new List<WSLocalidadResp.Data>();
		WSLocalidad.Response result;
		
		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSLocalidad.getLocalidadPorFechaModificacion(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.localidad.links.next != null;
			currentPage = result.localidad.meta.current_page +1;
			lastPage = result.localidad.meta.last_page;
		
			wsData = result.localidad.data;
		}
		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Localidad__c> localidadToUpdate = new List<Localidad__c>();
		Map<String, String> organizadores = new Map<String, String>();
		List<String> locIds = new List<String>();

		for(Object res : wsResponses) {
			WSLocalidadResp.Data localidad = (WSLocalidadResp.Data) res;

			Localidad__c loc = new Localidad__c();
			loc.Codigo_de_Provincia__c = localidad.pcia_codigo;
			loc.Codigo_Postal__c = localidad.codigo_postal;
			loc.Loc_Id__c = localidad.loc_loc_id;
			loc.Nombre_de_Localidad__c = localidad.localidad;
			loc.ZG_Codigo__c = localidad.zn_zona;
            loc.Region__c = localidad.or_zona_nombre;
			loc.CIU__c = localidad.ciu_codigo;

			organizadores.put(loc.Loc_Id__c, localidad.organizador);
			locIds.add(localidad.loc_loc_id);
			localidadToUpdate.add(loc);
		}

		List<User> users = [
			SELECT Id, CommunityNickname, User_ID_en_SS__c 
			FROM User 
			WHERE CommunityNickname IN :organizadores.values()
		];

		for(Localidad__c loc : localidadToUpdate){
			for(User user : users){
				if(user.User_ID_en_SS__c == organizadores.get(loc.Loc_Id__c)){
					loc.Organizador_lookup__c = user.Id;
				}
			}
		}
		
		Database.UpsertResult[] results = Database.upsert(localidadToUpdate, Localidad__c.Fields.Loc_Id__c, false);
		System.debug('****results: ' + results);

		//EmailUtils.sendErrorMail(results, null, null, locIds, 'Localidades');

		Utils.insertBatchLogs(results, null, null, locIds, 'Localidades');
	}

	public void updateDate() {

		if (!hasNext) {
			MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
			lastUpdate.Localidades__c = lastUpdateForLocalidades;
			upsert lastUpdate;
		} else {
			LocalidadProcessor nextProcessor = new LocalidadProcessor(pageSize, currentPage, lastPage, runTime, Datetime.now());
			Database.executeBatch(new MasterBatch(nextProcessor));
		}

	}


}