force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Importe_cargo_al_socio_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_cargo_al_socio_auditor__c</fullName>
    <label>Importe cargo al socio auditor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Importe_convenio_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_convenio_auditor__c</fullName>
    <label>Importe convenio auditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Importe_plan_auditor__c.field-meta.xml
<CustomField>
    <fullName>Importe_plan_auditor__c</fullName>
    <label>Importe plan auditor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion_CA__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_CA__c</fullName>
    <externalId>true</externalId>
    <label>Prestacion CA</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PrestacionAPActualizarImporteBtnCtrl.cls
public class PrestacionAPActualizarImporteBtnCtrl  {
	@AuraEnabled
	public static Response updateImporte(String presId) {
		List<Prestacion__c> prestacion = [
			SELECT Id, Prestacion_CA__c, Importe_cargo_al_socio_auditor__c, Importe_convenio_auditor__c, 
				Importe_plan_auditor__c
			FROM Prestacion__c 
			WHERE Id =: presId
		]; 

		String body = generateJson(prestacion[0]);

		WSPrestacionAPActualizarImporte.Response resp = WSPrestacionAPActualizarImporte.updateImporte(
			prestacion[0].Prestacion_CA__c, body
		);

		if(!resp.hasError) {
			return new Response(false, 'ok');
		} else {
			return new Response(true, resp.message);
		}
	}

	private static String generateJson(Prestacion__c prestacion) {
		Map<String, Object> prestJSON = new Map<String, Object>();
		if(prestacion.Importe_cargo_al_socio_auditor__c != null) {
			prestJSON.put('importe_socio', prestacion.Importe_cargo_al_socio_auditor__c);
		}
		if(prestacion.Importe_convenio_auditor__c != null) {
			prestJSON.put('importe_conv', prestacion.Importe_convenio_auditor__c);
		}
		if(prestacion.Importe_plan_auditor__c != null) {
			prestJSON.put('importe_plan', prestacion.Importe_plan_auditor__c);
		}

		return JSON.serialize(prestJSON);
	}

	public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message) {
            this.hasError = hasError;
            this.message = message;
        }
	}

}