force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/APr_Id__c.field-meta.xml
<CustomField>
    <fullName>APr_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Evento_Medico_Id__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordenes de Compras</relationshipLabel>
    <relationshipName>Ordenes_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/fields/Codigo_tipoNA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_tipoNA__c</fullName>
    <externalId>true</externalId>
    <label>Codigo tipoNA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnvioDeNotaAUserCtrlTest.cls
@isTest 
private class EnvioDeNotaAUserCtrlTest {
	static User u;
	static{
		String uniqueUserName = 'organizador' + DateTime.now().getTime() + '@testorg.com';
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Administrador del sistema' OR Name = 'System Administrator' LIMIT 1];
		UserRole role = [SELECT Id,Name FROM UserRole WHERE Name = 'Administrador'];
		u = new User(Alias = 'standt', Email='standarduser@testorg.com',
				EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
				LocaleSidKey='en_US', ProfileId = p.Id,
				TimeZoneSidKey='America/Los_Angeles',
				UserName=uniqueUserName,UserRole = role);
		insert u;
	}
	@isTest
	private static void sendEmailToOwnerAndDelegacion() {
		Account delegacion = Build.anAccountDelegacion().withEmail('delegacion@testorg.com').build();
		insert delegacion;
		u.Codigo_delegacion__c = delegacion.Id;
		update u;
		Case ap = new Case(OwnerId = u.Id, AccountId = delegacion.Id);
		insert ap;
		Tipo_nota_de_auditoria__c tipoNota = new Tipo_nota_de_auditoria__c(Codigo_tipoNA__c = 'NOT_COB_PROT');
		insert tipoNota;
		Nota_de_Auditoria__c nota = new Nota_de_Auditoria__c(APr_Id__c = ap.Id,Nota__c = 'Cuerpo del mail',Tipo_nota_de_Auditoria__c = tipoNota.Id);
		insert nota;
		Orden_de_Compra__c orden = new Orden_de_Compra__c(Caso__c = ap.Id);
		insert orden;
		Test.startTest();
		EnvioDeNotaAUserCtrl.Response resp = EnvioDeNotaAUserCtrl.envioNota(orden.Caso__c);
		Test.stopTest();
		Orden_de_Compra__c ordenToAssert = [SELECT Id, Estado_OC__c
											FROM Orden_de_Compra__c
											WHERE Id = :orden.Id];
		System.assertEquals(false, resp.hasError);
		System.assertEquals(System.Label.Email_EnvioCorrecto, resp.message);
		System.assertEquals('Diferencia Socio', ordenToAssert.Estado_OC__c);
	}
	@isTest
	private static void sendEmailFailsDueToOrdenWithoutCase() {
		Orden_de_Compra__c orden = new Orden_de_Compra__c();
		insert orden;
		Test.startTest();
		EnvioDeNotaAUserCtrl.Response resp = EnvioDeNotaAUserCtrl.envioNota(orden.Caso__c);
		Test.stopTest();
		System.assertEquals(true, resp.hasError);
		System.assertEquals('Debe tener un Caso asociado.', resp.message);
	}
		@isTest
	private static void sendEmailFailsDueToInexistingNota() {
		Account delegacion = Build.anAccountDelegacion().withEmail('delegacion@testorg.com').build();
		insert delegacion;
		u.Codigo_delegacion__c = delegacion.Id;
		update u;
		Case ap = new Case(OwnerId = u.Id, AccountId = delegacion.Id);
		insert ap;
		Tipo_nota_de_auditoria__c tipoNota = new Tipo_nota_de_auditoria__c(Codigo_tipoNA__c = 'Algo');
		insert tipoNota;
		Nota_de_Auditoria__c nota = new Nota_de_Auditoria__c(APr_Id__c = ap.Id,Nota__c = 'Cuerpo del mail',Tipo_nota_de_Auditoria__c = tipoNota.Id);
		insert nota;
		Orden_de_Compra__c orden = new Orden_de_Compra__c(Caso__c = ap.Id);
		insert orden;
		Test.startTest();
		EnvioDeNotaAUserCtrl.Response resp = EnvioDeNotaAUserCtrl.envioNota(ap.Id);
		Test.stopTest();
		System.assertEquals(true, resp.hasError);
		System.assertEquals('Nota de auditoria COB_PROT inexistente', resp.message);
	}
	@isTest
	private static void sendEmailToOrdenWithAnEM() {
		Evento_medico__c em = new Evento_medico__c();
		insert em;
		Case aCase = new Case();
		aCase.Evento_medico__c = em.Id;
		insert aCase;
		Tipo_nota_de_auditoria__c tipoNota = new Tipo_nota_de_auditoria__c();
		tipoNota.Name = 'AVISO COBERTURA DE MATERIAL';
		tipoNota.Codigo_tipoNA__c = 'NOT_COB_PROT';
		insert tipoNota;
		Nota_de_Auditoria__c nota = new Nota_de_Auditoria__c();
		nota.Nota__c = 'Test';
		nota.Tipo_nota_de_auditoria__c = tipoNota.Id;
		nota.Fecha__c = Date.newInstance(2021, 10, 02);
		nota.Evento_Medico_Id__c = em.Id;
		insert nota;
		Orden_de_Compra__c orden = new Orden_de_Compra__c();
		orden.Caso__c = aCase.Id;
		insert orden;
		Test.startTest();
		EnvioDeNotaAUserCtrl.Response resp = EnvioDeNotaAUserCtrl.envioNota(orden.Caso__c);
		Test.stopTest();
		System.assertEquals(false, resp.hasError);
	}
}