force-app/main/default/objects/Account/fields/Actividad_codigo__c.field-meta.xml
<CustomField>
    <fullName>Actividad_codigo__c</fullName>
    <label>Actividad código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actividad_nombre__c.field-meta.xml
<CustomField>
    <fullName>Actividad_nombre__c</fullName>
    <label>Actividad nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Adherente__c.field-meta.xml
<CustomField>
    <fullName>Adherente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adherente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Afiliacion__c</fullName>
    <label>Asociación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aporte</fullName>
            </value>
            <value>
                <fullName>Aporte Obligatorio</fullName>
            </value>
            <value>
                <fullName>Sin aportes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agencia_codigo__c.field-meta.xml
<CustomField>
    <fullName>Agencia_codigo__c</fullName>
    <label>Agencia código</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agencia_nombre__c.field-meta.xml
<CustomField>
    <fullName>Agencia_nombre__c</fullName>
    <label>Agencia nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Antiguedad_reconocida__c.field-meta.xml
<CustomField>
    <fullName>Antiguedad_reconocida__c</fullName>
    <label>Antigüedad reconocida</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aporta__c.field-meta.xml
<CustomField>
    <fullName>Aporta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aporta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Categoria_codigo__c.field-meta.xml
<CustomField>
    <fullName>Categoria_codigo__c</fullName>
    <label>Categoría código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Categoria_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Nombre__c</fullName>
    <label>Categoría Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Clase_efector__c.field-meta.xml
<CustomField>
    <fullName>Clase_efector__c</fullName>
    <description>Clases en el RT Efector, texto que llega de la int</description>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_Entidad__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Entidad__c</fullName>
    <label>Código de Entidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_codigo__c.field-meta.xml
<CustomField>
    <fullName>Empresa_codigo__c</fullName>
    <label>Empresa código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_nombre__c.field-meta.xml
<CustomField>
    <fullName>Empresa_nombre__c</fullName>
    <label>Empresa nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_sucursal__c.field-meta.xml
<CustomField>
    <fullName>Empresa_sucursal__c</fullName>
    <label>Empresa sucursal</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_sucursal_nombre__c.field-meta.xml
<CustomField>
    <fullName>Empresa_sucursal_nombre__c</fullName>
    <label>Empresa sucursal nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Casado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Soltero</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Concubinato</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Separado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Alta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Alta__c</fullName>
    <label>Fecha Alta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_alta_Administrativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_alta_Administrativa__c</fullName>
    <label>Fecha alta Administrativa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_nacimiento_efector__c.field-meta.xml
<CustomField>
    <fullName>Fecha_nacimiento_efector__c</fullName>
    <description>Fecha de nacimiento del Efector</description>
    <label>Fecha nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gentilicio__c.field-meta.xml
<CustomField>
    <fullName>Gentilicio__c</fullName>
    <label>Gentilicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modelo_Plan_Codigo__c.field-meta.xml
<CustomField>
    <fullName>Modelo_Plan_Codigo__c</fullName>
    <label>Modelo Plan Codigo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modelo_Plan_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Modelo_Plan_Nombre__c</fullName>
    <label>Modelo Plan Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monto_excedente__c.field-meta.xml
<CustomField>
    <fullName>Monto_excedente__c</fullName>
    <label>Monto excedente</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_de_baja__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_baja__c</fullName>
    <label>Motivo de baja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <externalId>true</externalId>
    <label>Número de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_ant_codigo__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_ant_codigo__c</fullName>
    <label>Obra social ant código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_ant_nombre__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_ant_nombre__c</fullName>
    <label>Obra social ant nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_codigo__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_codigo__c</fullName>
    <label>Obra social código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_nombre__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_nombre__c</fullName>
    <label>Obra social nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PA</fullName>
                <label>Padres</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hijo/a</label>
            </value>
            <value>
                <fullName>SO</fullName>
                <label>Sobrino/a</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Hermano/a</label>
            </value>
            <value>
                <fullName>NU</fullName>
                <label>Nuera</label>
            </value>
            <value>
                <fullName>SG</fullName>
                <label>Suegro/a</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Cónyuge</label>
            </value>
            <value>
                <fullName>FC</fullName>
                <label>Familiar a Cargo</label>
            </value>
            <value>
                <fullName>FD</fullName>
                <label>Familiar Directo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Codigo__c.field-meta.xml
<CustomField>
    <fullName>Plan_Codigo__c</fullName>
    <label>Plan Codigo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Plan_Nombre__c</fullName>
    <label>Plan Nombre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTEGRAL AS200</fullName>
            </value>
            <value>
                <fullName>INTEGRAL AS204</fullName>
            </value>
            <value>
                <fullName>PLAN 11 PMO</fullName>
            </value>
            <value>
                <fullName>PLAN 2</fullName>
            </value>
            <value>
                <fullName>PLAN 2D</fullName>
            </value>
            <value>
                <fullName>PLAN 3</fullName>
            </value>
            <value>
                <fullName>PLAN 50</fullName>
            </value>
            <value>
                <fullName>PLAN 9</fullName>
            </value>
            <value>
                <fullName>SELECTA AS400</fullName>
            </value>
            <value>
                <fullName>SELECTA AS500</fullName>
            </value>
            <value>
                <fullName>SUPERIOR AS300</fullName>
            </value>
            <value>
                <fullName>PLAN 4 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1 40</fullName>
            </value>
            <value>
                <fullName>PLAN ACTIVO 7 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1</fullName>
            </value>
            <value>
                <fullName>PLAN 4</fullName>
            </value>
            <value>
                <fullName>PLAN 5</fullName>
            </value>
            <value>
                <fullName>PLAN 6</fullName>
            </value>
            <value>
                <fullName>PLAN 7</fullName>
            </value>
            <value>
                <fullName>PLAN 8</fullName>
            </value>
            <value>
                <fullName>PLAN 10/1</fullName>
            </value>
            <value>
                <fullName>PLAN 10/2</fullName>
            </value>
            <value>
                <fullName>PLAN 11</fullName>
            </value>
            <value>
                <fullName>PLAN 11/1</fullName>
            </value>
            <value>
                <fullName>PLAN 11/2</fullName>
            </value>
            <value>
                <fullName>PLAN 12</fullName>
            </value>
            <value>
                <fullName>PLAN 13</fullName>
            </value>
            <value>
                <fullName>PLAN 14</fullName>
            </value>
            <value>
                <fullName>PLAN 15/1</fullName>
            </value>
            <value>
                <fullName>PLAN 15/2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountAsociadoMapping.cls
public class AccountAsociadoMapping  {
	
	public static Map<String, String> GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS =
		new Map<String, String>{
			'Actividad_codigo__c' => 'actividad_codigo',
			'Actividad_nombre__c' => 'actividad_nombre',
			'Adherente__c' => 'adherente',
			'Afi_Id__c' => 'afi_id',
			'Afiliacion__c' => 'afiliacion',
			'Agencia_codigo__c' => 'agencia_codigo',
			'Agencia_nombre__c' => 'agencia_nombre',
			'Antiguedad_reconocida__c' => 'antiguedad_reconocida',
			'Aporta__c' => 'aporta',
			'CUIT__c' => 'cuit',
			'Categoria_Nombre__c' => 'categoria_nombre',
			'Categoria_codigo__c' => 'categoria_codigo',
			'Clase_efector__c' => 'codigo_1',
			'Codigo_de_Afiliado__c' => 'codigo',
			'Codigo_de_Entidad__c' => 'entidad_codigo',
			'Codigo_de_empresa__c' => 'empresa_codigo',
			'Empresa_codigo__c' => 'empresa_codigo',
			'Empresa_nombre__c' => 'empresa_nombre',
			'Empresa_sucursal__c' => 'empresa_sucursal',
			'Empresa_sucursal_nombre__c' => 'empresa_sucursal_nombre',
			'Estado__c' => 'estado',
			'Estado_civil__c' => 'estado_civil',
			'Fecha_Alta__c' => 'fecha_alta',
			'Fecha_alta_Administrativa__c' => 'fecha_alta_administrativa',
			'Fecha_nacimiento_efector__c' => 'fecha_nacimiento',
			'Fecha_vigencia__c' => 'fecha_vigencia',
			'FirstName' => 'nombres',
			'Gentilicio__c' => 'gentilicio',
			'LastName' => 'apellidos',
			'Modelo_Plan_Codigo__c' => 'modelo_plan_codigo',
			'Modelo_Plan_Nombre__c' => 'modelo_plan_nombre',
			'Monto_excedente__c' => 'excedente',
			'Motivo_de_baja__c' => 'motivo_de_baja',
			'Numero_de_documento__c' => 'numero_documento',
			'Obra_social_ant_codigo__c' => 'obra_social_ant_codigo',
			'Obra_social_ant_nombre__c' => 'obra_social_ant_nombre',
			'Obra_social_codigo__c' => 'obra_social_codigo',
			'Obra_social_nombre__c' => 'obra_social_nombre',
			'Parentesco__c' => 'parentesco',
			'PersonBirthdate' => 'fecha_nacimiento',
			'Plan_Codigo__c' => 'plan_codigo',
			'Plan_Nombre__c' => 'plan_nombre',
			'Sexo__c' => 'sexo',
			'Sujeto_facturacion__c' => 'sujeto_facturacion',
			'Tipo_de_baja_codigo__c' => 'tipo_baja_codigo',
			'Tipo_de_baja_nombre__c' => 'tipo_baja_nombre',
			'Tipo_de_documento__c' => 'tipo_documento',
			'Titular_apellidos__c' => 'titular_apellidos',
			'Titular_codigo__c' => 'afi_id_tit',
			'Titular_nombres__c' => 'titular_nombres',
			'Type' => 'tipo_afiliado'
		};
	
	public static void upsertAccountAsociado(String asociadoId){
		WSAsociadoGetAsociado.Response wsResponse = WSAsociadoGetAsociado.getAsociado(asociadoId);
		
		if(!wsResponse.hasError){
			if(!wsResponse.asociadoApiRespValuesByasociadoApiRespFields.isEmpty()){
				//Get Account Cuenta Personal RecordTypeId
				RecordType cuentaPersonalRecordType = XappiaHelper.getRecordType('Account', 'Cuenta_personal');
				Id cuentaPersonalRecordTypeId = cuentaPersonalRecordType.Id;

				//New cuentaPersonalAccount and assing RecordTypeId
				Account accountCuentaPersonal = new Account();
				accountCuentaPersonal.RecordTypeId = cuentaPersonalRecordTypeId;

				//Mapping
				for(String accountAsociadoField : GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.keySet()){
					Schema.DisplayType fieldType = 
						Schema.SObjectType.Account.fields.getMap().get(accountAsociadoField).getDescribe().getType();
					if(fieldType == Schema.DisplayType.STRING){
						accountCuentaPersonal.put(
							accountAsociadoField,
							String.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(
									GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField)
								)
							)
						);
					}
					if(fieldType == Schema.DisplayType.PICKLIST){
						accountCuentaPersonal.put(
							accountAsociadoField,
							String.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(
									GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField)
								)
							)
						);
					}
					if(fieldType == Schema.DisplayType.BOOLEAN){
						accountCuentaPersonal.put(
							accountAsociadoField,
							Boolean.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(
									GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField)
								)
							)
						);
					}
					if(fieldType == Schema.DisplayType.INTEGER){
						accountCuentaPersonal.put(
							accountAsociadoField,
							Integer.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(
									GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField)
								)
							)
						);
					}
					if(fieldType == Schema.DisplayType.DOUBLE){
						accountCuentaPersonal.put(
							accountAsociadoField,
							Double.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(
									GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField)
								)
							)
						);
					}
					if(fieldType == Schema.DisplayType.DATE){
						Date dateToMapping = Date.valueOf(
							String.valueOf(
								wsResponse.asociadoApiRespValuesByasociadoApiRespFields.get(GETASOCIADOAPIRESPFIELDSBYACCOUNTASOCIADOFIELDS.get(accountAsociadoField))
							)
						);
						accountCuentaPersonal.put(
							accountAsociadoField,
							dateToMapping
						);
					}
				}
				Database.UpsertResult accountUpsertResult = Database.upsert(accountCuentaPersonal, Account.Fields.Afi_Id__c);
				if(!accountUpsertResult.isSuccess()){
					for(Database.Error err : accountUpsertResult.getErrors()) {
						System.debug('The following error has occurred.');                    
						System.debug(err.getStatusCode() + ': ' + err.getMessage());
						System.debug('Fields that affected this error: ' + err.getFields());
					}
				}
			}
		}
	} 
}