force-app/main/default/objects/Account/fields/Actividad_codigo__c.field-meta.xml
<CustomField>
    <fullName>Actividad_codigo__c</fullName>
    <label>Actividad código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Actividad_nombre__c.field-meta.xml
<CustomField>
    <fullName>Actividad_nombre__c</fullName>
    <label>Actividad nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Adherente__c.field-meta.xml
<CustomField>
    <fullName>Adherente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adherente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Afiliacion__c.field-meta.xml
<CustomField>
    <fullName>Afiliacion__c</fullName>
    <label>Asociación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aporte</fullName>
            </value>
            <value>
                <fullName>Aporte Obligatorio</fullName>
            </value>
            <value>
                <fullName>Sin aportes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Agencia_codigo__c.field-meta.xml
<CustomField>
    <fullName>Agencia_codigo__c</fullName>
    <label>Agencia código</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Agencia_nombre__c.field-meta.xml
<CustomField>
    <fullName>Agencia_nombre__c</fullName>
    <label>Agencia nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Antiguedad_reconocida__c.field-meta.xml
<CustomField>
    <fullName>Antiguedad_reconocida__c</fullName>
    <label>Antigüedad reconocida</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Aporta__c.field-meta.xml
<CustomField>
    <fullName>Aporta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aporta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Categoria_codigo__c.field-meta.xml
<CustomField>
    <fullName>Categoria_codigo__c</fullName>
    <label>Categoría código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Categoria_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Nombre__c</fullName>
    <label>Categoría Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Clase_efector__c.field-meta.xml
<CustomField>
    <fullName>Clase_efector__c</fullName>
    <description>Clases en el RT Efector, texto que llega de la int</description>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_Entidad__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Entidad__c</fullName>
    <label>Código de Entidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  PersonBirthdate  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(PersonBirthdate), 
				AND( 
					MONTH(TODAY()) == MONTH(PersonBirthdate), 
					DAY(TODAY()) &lt; DAY(PersonBirthdate) 
					) 
		), 
	1, 
	0 
	)

/*IF( NOT( ISBLANK(  PersonBirthdate  ) ) ,
  IF( DATE( 2000 , MONTH( PersonBirthdate ) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( PersonBirthdate ),
     YEAR (Today()) - YEAR ( PersonBirthdate ) -1 ),
  null)*/</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_codigo__c.field-meta.xml
<CustomField>
    <fullName>Empresa_codigo__c</fullName>
    <label>Empresa código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_nombre__c.field-meta.xml
<CustomField>
    <fullName>Empresa_nombre__c</fullName>
    <label>Empresa nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_sucursal__c.field-meta.xml
<CustomField>
    <fullName>Empresa_sucursal__c</fullName>
    <label>Empresa sucursal</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa_sucursal_nombre__c.field-meta.xml
<CustomField>
    <fullName>Empresa_sucursal_nombre__c</fullName>
    <label>Empresa sucursal nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Casado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Soltero</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Concubinato</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Separado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Alta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Alta__c</fullName>
    <label>Fecha Alta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_alta_Administrativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_alta_Administrativa__c</fullName>
    <label>Fecha alta Administrativa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_nacimiento_efector__c.field-meta.xml
<CustomField>
    <fullName>Fecha_nacimiento_efector__c</fullName>
    <description>Fecha de nacimiento del Efector</description>
    <label>Fecha nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gentilicio__c.field-meta.xml
<CustomField>
    <fullName>Gentilicio__c</fullName>
    <label>Gentilicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modelo_Plan_Codigo__c.field-meta.xml
<CustomField>
    <fullName>Modelo_Plan_Codigo__c</fullName>
    <label>Modelo Plan Codigo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modelo_Plan_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Modelo_Plan_Nombre__c</fullName>
    <label>Modelo Plan Nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monto_excedente__c.field-meta.xml
<CustomField>
    <fullName>Monto_excedente__c</fullName>
    <label>Monto excedente</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_de_baja__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_baja__c</fullName>
    <label>Motivo de baja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <externalId>true</externalId>
    <label>Número de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_ant_codigo__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_ant_codigo__c</fullName>
    <label>Obra social ant código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_ant_nombre__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_ant_nombre__c</fullName>
    <label>Obra social ant nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_codigo__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_codigo__c</fullName>
    <label>Obra social código</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_nombre__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_nombre__c</fullName>
    <label>Obra social nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Codigo__c.field-meta.xml
<CustomField>
    <fullName>Plan_Codigo__c</fullName>
    <label>Plan Codigo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Plan_Nombre__c</fullName>
    <label>Plan Nombre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTEGRAL AS200</fullName>
            </value>
            <value>
                <fullName>INTEGRAL AS204</fullName>
            </value>
            <value>
                <fullName>PLAN 11 PMO</fullName>
            </value>
            <value>
                <fullName>PLAN 2</fullName>
            </value>
            <value>
                <fullName>PLAN 2D</fullName>
            </value>
            <value>
                <fullName>PLAN 3</fullName>
            </value>
            <value>
                <fullName>PLAN 50</fullName>
            </value>
            <value>
                <fullName>PLAN 9</fullName>
            </value>
            <value>
                <fullName>SELECTA AS400</fullName>
            </value>
            <value>
                <fullName>SELECTA AS500</fullName>
            </value>
            <value>
                <fullName>SUPERIOR AS300</fullName>
            </value>
            <value>
                <fullName>PLAN 4 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1 40</fullName>
            </value>
            <value>
                <fullName>PLAN ACTIVO 7 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1</fullName>
            </value>
            <value>
                <fullName>PLAN 4</fullName>
            </value>
            <value>
                <fullName>PLAN 5</fullName>
            </value>
            <value>
                <fullName>PLAN 6</fullName>
            </value>
            <value>
                <fullName>PLAN 7</fullName>
            </value>
            <value>
                <fullName>PLAN 8</fullName>
            </value>
            <value>
                <fullName>PLAN 10/1</fullName>
            </value>
            <value>
                <fullName>PLAN 10/2</fullName>
            </value>
            <value>
                <fullName>PLAN 11</fullName>
            </value>
            <value>
                <fullName>PLAN 11/1</fullName>
            </value>
            <value>
                <fullName>PLAN 11/2</fullName>
            </value>
            <value>
                <fullName>PLAN 12</fullName>
            </value>
            <value>
                <fullName>PLAN 13</fullName>
            </value>
            <value>
                <fullName>PLAN 14</fullName>
            </value>
            <value>
                <fullName>PLAN 15/1</fullName>
            </value>
            <value>
                <fullName>PLAN 15/2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountAsociadoMappingTest.cls
@IsTest
public class AccountAsociadoMappingTest  {
	//@IsTest
	//private static void whenTheWSIsConsume_mappingAccountWithAsociadoResponse_AccountAsociadoShouldBeInsert(){
		//Test.setMock(HttpCalloutMock.class, getResponseFound);
		//Test.startTest();
		//AccountAsociadoMapping.upsertAccountAsociado('131153');
		//Test.stopTest();

        //List<Account> accountsToAssert = [
			//SELECT
				//Actividad_codigo__c,
				//Actividad_nombre__c,
				//Adherente__c,
				//Afi_Id__c,
				//Afiliacion__c,
				//Agencia_codigo__c,
				//Agencia_nombre__c,
				//Antiguedad_reconocida__c,
				//Aporta__c,
				//CUIT__c,
				//Categoria_Nombre__c,
				//Categoria_codigo__c,
				//Clase_efector__c,
				//Codigo_de_Afiliado__c,
				//Codigo_de_Entidad__c,
				//Codigo_de_empresa__c,
				//Edad__c,
				//Empresa_codigo__c,
				//Empresa_nombre__c,
				//Empresa_sucursal__c,
				//Empresa_sucursal_nombre__c,
				//Estado__c,
				//Estado_civil__c,
				//Fecha_Alta__c,
				//Fecha_alta_Administrativa__c,
				//Fecha_nacimiento_efector__c,
				//Fecha_vigencia__c,
				//FirstName,
				//Gentilicio__c,
				//LastName,
				//Modelo_Plan_Codigo__c,
				//Modelo_Plan_Nombre__c,
				//Monto_excedente__c,
				//Motivo_de_baja__c,
				//Numero_de_documento__c,
				//Obra_social_ant_codigo__c,
				//Obra_social_ant_nombre__c,
				//Obra_social_codigo__c,
				//Obra_social_nombre__c,
				//Parentesco__c,
				//PersonBirthdate,
				//Plan_Codigo__c,
				//Plan_Nombre__c,
				//Sexo__c,
				//Sujeto_facturacion__c,
				//Tipo_de_baja_codigo__c,
				//Tipo_de_baja_nombre__c,
				//Tipo_de_documento__c,
				//Titular_apellidos__c,
				//Titular_codigo__c,
				//Titular_nombres__c,
				//Type
			//FROM Account
		//];
		//Account accountAsociadoToAssert = accountsToAssert[0];

		//System.assertEquals('COM', accountAsociadoToAssert.Actividad_codigo__c);
		//System.assertEquals('COMERCIANTE', accountAsociadoToAssert.Actividad_nombre__c);
		//System.assertEquals(false, accountAsociadoToAssert.Adherente__c);
		//System.assertEquals('134495', accountAsociadoToAssert.Afi_Id__c);
		//System.assertEquals('Sin aportes', accountAsociadoToAssert.Afiliacion__c);
		//System.assertEquals(650008, accountAsociadoToAssert.Agencia_codigo__c);
		//System.assertEquals('650008_AG.BAHIA BLANCA-MUTUAL ASOCIADOS COOP.OBRERA', accountAsociadoToAssert.Agencia_nombre__c);
		//System.assertEquals(false, accountAsociadoToAssert.Aporta__c);
		//System.assertEquals('27231303435', accountAsociadoToAssert.CUIT__c);
		//System.assertEquals('GENERICO', accountAsociadoToAssert.Categoria_Nombre__c);
		//System.assertEquals('GEN', accountAsociadoToAssert.Categoria_codigo__c);
		//System.assertEquals('054', accountAsociadoToAssert.Clase_efector__c);
		//System.assertEquals('60667/18', accountAsociadoToAssert.Codigo_de_Afiliado__c);
		//System.assertEquals('60667', accountAsociadoToAssert.Codigo_de_Entidad__c);
		//System.assertEquals('MUTUAL ASOCIADOS COOPERATIVA OBRERA', accountAsociadoToAssert.Empresa_nombre__c);
		//System.assertEquals('REING 2 DA SEM AS200/204 VOLDIR CBU/TC PC 2017', accountAsociadoToAssert.Empresa_sucursal_nombre__c);
		//System.assertEquals('Activo', accountAsociadoToAssert.Estado__c);
		//System.assertEquals('Soltero', accountAsociadoToAssert.Estado_civil__c);
		//System.assertEquals('VANINA NATALIA', accountAsociadoToAssert.FirstName);
		//System.assertEquals('ARGENTINO', accountAsociadoToAssert.Gentilicio__c);
		//System.assertEquals('OGANDO', accountAsociadoToAssert.LastName);
		//System.assertEquals('AS200', accountAsociadoToAssert.Modelo_Plan_Codigo__c);
		//System.assertEquals('INTEGRAL AS200', accountAsociadoToAssert.Modelo_Plan_Nombre__c);
		//System.assertEquals('Femenino', accountAsociadoToAssert.Sexo__c);
		//System.assertEquals(null, accountAsociadoToAssert.Motivo_de_baja__c);
		//System.assertEquals('23130343', accountAsociadoToAssert.Numero_de_documento__c);
		//System.assertEquals('SPM', accountAsociadoToAssert.Obra_social_ant_nombre__c);
		//System.assertEquals('ACA SALUD', accountAsociadoToAssert.Obra_social_nombre__c);
		//System.assertEquals(null, accountAsociadoToAssert.Parentesco__c);
		//System.assertEquals('AS200', accountAsociadoToAssert.Plan_Codigo__c);
		//System.assertEquals('INTEGRAL AS200', accountAsociadoToAssert.Plan_Nombre__c);
		//System.assertEquals(false, accountAsociadoToAssert.Sujeto_facturacion__c);
		//System.assertEquals(null, accountAsociadoToAssert.Tipo_de_baja_nombre__c);
		//System.assertEquals('DNI', accountAsociadoToAssert.Tipo_de_documento__c);
		//System.assertEquals(null, accountAsociadoToAssert.Tipo_de_baja_codigo__c);
		//System.assertEquals(null, accountAsociadoToAssert.Titular_apellidos__c);
		//System.assertEquals(null, accountAsociadoToAssert.Titular_codigo__c);
		//System.assertEquals(null, accountAsociadoToAssert.Titular_nombres__c);
		//System.assertEquals('Titular', accountAsociadoToAssert.Type);
	//}

	//static XHttpCalloutMock getResponseFound;

	//static {
		//getResponseFound = new XHttpCalloutMock();
		//getResponseFound.buildResponse()
			//.withStatus('OK')
			//.withStatusCode(200)
			//.withBody(WSAuthTokenMock.getTokenSuccess())
			//.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		//getResponseFound.buildResponse()
			//.withStatus('OK')
			//.withStatusCode(200)
			//.withBody(WSAsociadoGetAsociadoMock.getFound())
			//.addForAddress(WSAsociadoGetAsociado.SERVICE_CONFIG.URL__c + '/v1/salud/consultar-afiliado/afi_id/131153');
	//}
}