force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Telefono__c</fullName>
    <label>Tipo de Teléfono</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Telefono</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Telefonos__c.field-meta.xml
<CustomField>
    <fullName>Telefonos__c</fullName>
    <label>Telefonos</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Telefono__c/Telefono__c.object-meta.xml
<CustomObject>
    <label>Telefono</label>
    <nameField>
        <displayFormat>TEL-{000000000}</displayFormat>
        <label>Nombre de Telefono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telefonos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Telefono__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Asociado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Telefonos</relationshipLabel>
    <relationshipName>Telefonos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Telefono__c/fields/TEL_ID__c.field-meta.xml
<CustomField>
    <fullName>TEL_ID__c</fullName>
    <externalId>true</externalId>
    <label>TEL ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Telefono__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Telefono__c/fields/Telefono_principal__c.field-meta.xml
<CustomField>
    <fullName>Telefono_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Al seleccionar teléfono principal, se impactará como teléfono principal del asociado en Salesforce y el mismo se podrá ver en la ficha del asociado.</inlineHelpText>
    <label>Telefono principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Telefono__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TEL</fullName>
            </value>
            <value>
                <fullName>CEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TelefonoProcessorTest.cls
@isTest 
private class TelefonoProcessorTest {

	static MasterConfigs__c config;
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundTwoPages;
	static XHttpCalloutMock getResponseFoundInitialDataLoad;
	static XHttpCalloutMock getResponseFoundTwoPagesInitialDataLoad;
	static Account asociado;

	static {
		String today = System.now().format('yyyy-MM-dd');

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos/' + today + '?pageSize=15&page=2');

		getResponseFoundTwoPages = new XHttpCalloutMock();
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndContinue())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos/' + today + '?pageSize=15&page=1');	
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos/' + today + '?pageSize=15&page=2');

		getResponseFoundInitialDataLoad = new XHttpCalloutMock();
		getResponseFoundInitialDataLoad.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundInitialDataLoad.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos-m/' + today + '?pageSize=15&page=2');

		getResponseFoundTwoPagesInitialDataLoad = new XHttpCalloutMock();
		getResponseFoundTwoPagesInitialDataLoad.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundTwoPagesInitialDataLoad.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndContinue())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos-m/' + today + '?pageSize=15&page=1');	
		getResponseFoundTwoPagesInitialDataLoad.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchTelefonoMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/telefonos-m/' + today + '?pageSize=15&page=2');


		asociado = Build.anAccountCuentapersonal().build();
		asociado.Afi_Id__c = '167755';
		insert asociado;
	}

	static {
		config = Build.aMasterConfigs().build();
		insert config;
	}

	@isTest static void externalsTelefonosCanBeProcessed_InitialDataLoad() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundInitialDataLoad);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new TelefonoProcessor(15, 2, 2, System.now(), true)));
		Test.stopTest();

		Telefono__c[] telefonos = [SELECT TEL_ID__c, Tipo__c, Telefono__c, Cuenta__c, Telefono_principal__c FROM Telefono__c];
		asociado = [SELECT Phone, Tipo_de_Telefono__c FROM Account WHERE Id = :asociado.Id];

		System.assertEquals('3411480105', asociado.Phone);
		System.assertEquals(1, telefonos.size());
		for(Telefono__c tel : telefonos) {
			if(tel.TEL_ID__c == '226244') {
				System.assertEquals('3411480105', tel.Telefono__c);
				System.assertEquals('TEL', tel.Tipo__c);
				System.assertEquals(asociado.Id, tel.Cuenta__c);
				System.assertEquals(true, tel.Telefono_principal__c);
			}
		}
	}

	@isTest static void aSecondBatchOfTelefonosCanBeCalled_InitialDataLoad() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundTwoPagesInitialDataLoad);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new TelefonoProcessor(15, System.now(), true)));
		Test.stopTest();

		Telefono__c[] telefonos = [SELECT TEL_ID__c, Tipo__c, Telefono__c, Telefono_principal__c, Cuenta__c FROM Telefono__c];
		asociado = [SELECT Phone, Tipo_de_Telefono__c FROM Account WHERE Id = :asociado.Id];

		System.assertEquals('3411480105', asociado.Phone);
		System.assertEquals(2, telefonos.size());
		for(Telefono__c tel : telefonos) {
			if(tel.TEL_ID__c == '226245') {
				System.assertEquals('3411480106', tel.Telefono__c);
				System.assertEquals('CEL', tel.Tipo__c);
				System.assertEquals(asociado.Id, tel.Cuenta__c);
				System.assertEquals(false, tel.Telefono_principal__c);
			}

		}
		
	}

	@isTest static void externalsTelefonosCanBeProcessed() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new TelefonoProcessor(15, 2, 2, System.now(), false)));
		Test.stopTest();

		Telefono__c[] telefonos = [SELECT TEL_ID__c, Tipo__c, Telefono__c, Cuenta__c, Telefono_principal__c FROM Telefono__c];
		asociado = [SELECT Phone, Tipo_de_Telefono__c FROM Account WHERE Id = :asociado.Id];

		System.assertEquals('3411480105', asociado.Phone);
		System.assertEquals(1, telefonos.size());
		for(Telefono__c tel : telefonos) {
			if(tel.TEL_ID__c == '226244') {
				System.assertEquals('3411480105', tel.Telefono__c);
				System.assertEquals('TEL', tel.Tipo__c);
				System.assertEquals(asociado.Id, tel.Cuenta__c);
				System.assertEquals(true, tel.Telefono_principal__c);
			}
		}
	}

	@isTest static void aSecondBatchOfTelefonosCanBeCalled() {		
		Test.setMock(HttpCalloutMock.class, getResponseFoundTwoPages);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new TelefonoProcessor(15, System.now())));
		Test.stopTest();

		Telefono__c[] telefonos = [SELECT TEL_ID__c, Tipo__c, Telefono__c, Telefono_principal__c, Cuenta__c FROM Telefono__c];
		asociado = [SELECT Phone, Tipo_de_Telefono__c FROM Account WHERE Id = :asociado.Id];

		System.assertEquals('3411480105', asociado.Phone);
		System.assertEquals(2, telefonos.size());
		for(Telefono__c tel : telefonos) {
			if(tel.TEL_ID__c == '226245') {
				System.assertEquals('3411480106', tel.Telefono__c);
				System.assertEquals('CEL', tel.Tipo__c);
				System.assertEquals(asociado.Id, tel.Cuenta__c);
				System.assertEquals(false, tel.Telefono_principal__c);
			}

		}
		
	}

	@isTest 
	static void atTheLastBatchTheLastUpdatedDateIsUpdated() {
		XHttpCalloutMock mock = new XHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Datetime now = System.now();

		Datetime yesterday = Datetime.now().addDays(-1);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new TelefonoProcessor(15, 2, 2, now, false)));
		Test.stopTest();

		System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Telefonos__c);
	}
}