force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Color_estado_de_cuenta__c.field-meta.xml
<CustomField>
    <fullName>Color_estado_de_cuenta__c</fullName>
    <label>Color estado de cuenta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EstadoDeCuentaBtnCtrl.cls
public class EstadoDeCuentaBtnCtrl {
    @AuraEnabled
	public static Response sendAccount(String afi){
        WSEstadoDeCuenta.Response resp = WSEstadoDeCuenta.getEstado(afi);
        
        Account acc = [
            SELECT Id, Afi_Id__C, Color_estado_de_cuenta__c
            FROM Account
            WHERE Afi_Id__C =: afi
        ];

        if(!resp.hasError){
            acc.Color_estado_de_cuenta__c = resp.result.data.estado_cuenta;
            update acc;
        }

        return new Response (resp.hasError, resp.message);
    }

    public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message) {
            this.hasError = hasError;
            this.message = message;
        }
	}
}