force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{0000}</displayFormat>
        <label>Nombre de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Localidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/Domicilio__c.object-meta.xml
<CustomObject>
    <label>Domicilio</label>
    <nameField>
        <displayFormat>DOM-{000000000}</displayFormat>
        <label>Nombre de Domicilio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Domicilios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Domicilio__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Asociado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Domicilios</relationshipLabel>
    <relationshipName>Domicilios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/DOM_ID__c.field-meta.xml
<CustomField>
    <fullName>DOM_ID__c</fullName>
    <externalId>true</externalId>
    <label>DOM ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/DPTO__c.field-meta.xml
<CustomField>
    <fullName>DPTO__c</fullName>
    <label>DPTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Domicilios</relationshipLabel>
    <relationshipName>Domicilios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Numero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Piso__c.field-meta.xml
<CustomField>
    <fullName>Piso__c</fullName>
    <label>Piso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Tipo_de_domicilio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_domicilio__c</fullName>
    <label>Tipo de domicilio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>PART</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>LEG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Domicilios__c.field-meta.xml
<CustomField>
    <fullName>Domicilios__c</fullName>
    <label>Domicilios</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DomicilioProcessor.cls
public class DomicilioProcessor implements IMasterBuilder {

	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForDomicilios;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public DomicilioProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public DomicilioProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForDomicilios) {
		this(pageSize, 1, 1, runTime, lastUpdateForDomicilios);
	}

	public DomicilioProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public DomicilioProcessor(
		Integer pageSize, 
		Integer currentPage, 
		Integer lastPage, 
		Datetime runTime, 
		Datetime lastUpdateForDomicilios 
	) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForDomicilios = lastUpdateForDomicilios;
	}

	public List<WSBatchDomicilioResp.Data> callWebService() {
		List<WSBatchDomicilioResp.Data> wsData = new List<WSBatchDomicilioResp.Data>();
		WSBatchDomicilio.Response result;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchDomicilio.getBatchDomicilio(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.resp.links.next != null;
			currentPage = result.resp.meta.current_page + 1;
			lastPage = result.resp.meta.last_page;
			wsData = result.resp.data;
		} else {
			this.errorWs = true;
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Domicilio__c> domiciliosToUpsert = new List<Domicilio__c>();
		List<String> externarlIds = new List<String>();

		for(Object resp : wsResponses) {
			WSBatchDomicilioResp.Data domicilioWS = (WSBatchDomicilioResp.Data) resp;

			Domicilio__c domicilio = new Domicilio__c();
			domicilio.DOM_ID__c = domicilioWS.domiafi_id;
			domicilio.Calle__c = domicilioWS.calle;
			domicilio.Numero__c = String.isNotBlank(domicilioWS.numero) ? Integer.valueOf(domicilioWS.numero) : null;
			domicilio.Piso__c = domicilioWS.piso;
			domicilio.DPTO__c = domicilioWS.dpto;
			domicilio.Tipo_de_domicilio__c = domicilioWS.td_codigo;

			if(String.isNotBlank(domicilioWS.afi_id)) {
				domicilio.Cuenta__r = new Account(Afi_Id__c = domicilioWS.afi_id);
			} 

			if(String.isNotBlank(domicilioWS.loc_id)) {
				domicilio.Localidad__r = new Localidad__c(Loc_Id__c = domicilioWS.loc_id);
			} 
			
			domiciliosToUpsert.add(domicilio);
			externarlIds.add(domicilioWS.domiafi_id);
		}

		Database.UpsertResult[] results = Database.upsert(
			domiciliosToUpsert, Domicilio__c.Fields.DOM_ID__c, false
		);
		System.debug('*****results ' + results); 

		Utils.insertBatchLogs(results, null, null, externarlIds, 'Domicilios');
	}

	public void updateDate() {

		if (!hasNext) {
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Domicilios__c = lastUpdateForDomicilios;
				upsert lastUpdate;
			}
			else {
				System.debug('<<** HUBO UN ERROR EN EL WS **>>');
			}
		} 
		else {
			DomicilioProcessor nextProcessor = new DomicilioProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}

}