force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Envio_de_recibo__c.field-meta.xml
<CustomField>
    <fullName>Envio_de_recibo__c</fullName>
    <label>Envío de recibo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Envio_de_recibo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <externalId>true</externalId>
    <label>Número de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_documento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Telefono__c</fullName>
    <label>Tipo de Teléfono</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Telefono</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
public class AccountTriggerHelper {

	
	@Future(callout=true)
	public static void updateFacturaElectronicaOnSS(Id[] accIds) {
		Account[] accs = [SELECT Id, Envio_de_recibo__c, Afi_Id__c FROM Account WHERE Id IN :accIds];
		String body;
		WSAsociadoFacturaElectronica.Response resp;

		for(Account anAcc : accs) {
			
			if(anAcc.Envio_de_recibo__c == 'Factura online') {
				body = '{ "adherido": "S" }';
				resp = WSAsociadoFacturaElectronica.updateFacturaElectronica(anAcc.Afi_Id__c, body);
			} else if (anAcc.Envio_de_recibo__c == 'Factura papel') {
				body = '{ "adherido": "N" }';
				resp = WSAsociadoFacturaElectronica.updateFacturaElectronica(anAcc.Afi_Id__c, body);
			}

			System.debug('****resp ' + resp);
		}
	}

	//Este metodo es para enviar flag de actualizacion al WS
	public static void updateAccountDetailsToWS(List<Account> accounts, Map<Id, Account> oldMap) {
		if(!System.isBatch()) {
			Set<String> asociadosToSend = new Set<String>();
			for(Account acc : accounts) {
				Account oldAcc = oldMap.get(acc.id);
				if((acc.Tipo_de_documento__c != oldAcc.Tipo_de_documento__c 
							|| acc.Numero_de_documento__c != oldAcc.Numero_de_documento__c
							|| acc.PersonEmail != oldAcc.PersonEmail 
							|| acc.Tipo_de_Telefono__c != oldAcc.Tipo_de_Telefono__c
							|| acc.Phone != oldAcc.Phone) 
						&& !String.isBlank(
								acc.Afi_Id__c
							)
				) {
					asociadosToSend.add(acc.Afi_Id__c);
				}
			}
			if(!asociadosToSend.isEmpty()) {
				WSDatosAfiliados.submitChanges(asociadosToSend);
			}
		}
	}

	

}