force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_log__c/Batch_log__c.object-meta.xml
<CustomObject>
    <description>Objeto donde se van a reflejar los errores de los batchs</description>
    <label>Batch log</label>
    <nameField>
        <label>Nombre de Batch log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_log__c/fields/Id_registro_error__c.field-meta.xml
<CustomField>
    <fullName>Id_registro_error__c</fullName>
    <externalId>true</externalId>
    <label>Id registro error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/Domicilio__c.object-meta.xml
<CustomObject>
    <label>Domicilio</label>
    <nameField>
        <displayFormat>DOM-{000000000}</displayFormat>
        <label>Nombre de Domicilio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Domicilios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Domicilio__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Asociado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Domicilios</relationshipLabel>
    <relationshipName>Domicilios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/DOM_ID__c.field-meta.xml
<CustomField>
    <fullName>DOM_ID__c</fullName>
    <externalId>true</externalId>
    <label>DOM ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/DPTO__c.field-meta.xml
<CustomField>
    <fullName>DPTO__c</fullName>
    <label>DPTO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Domicilios</relationshipLabel>
    <relationshipName>Domicilios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Numero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Piso__c.field-meta.xml
<CustomField>
    <fullName>Piso__c</fullName>
    <label>Piso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domicilio__c/fields/Tipo_de_domicilio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_domicilio__c</fullName>
    <label>Tipo de domicilio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>PART</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>LEG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Domicilios__c.field-meta.xml
<CustomField>
    <fullName>Domicilios__c</fullName>
    <label>Domicilios</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DomicilioProcessorTest.cls
@isTest 
private class DomicilioProcessorTest {

	static MasterConfigs__c config;
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundTwoPages;
	static Account asociado;
	static Account asociado2;
	static Localidad__c localidad;
	static Localidad__c localidad2;

	static {
		String today = System.now().format('yyyy-MM-dd');

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchDomicilioMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/domicilios/' + today + '?pageSize=15&page=2');

		getResponseFoundTwoPages = new XHttpCalloutMock();
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchDomicilioMock.getFoundAndContinue())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/domicilios/' + today + '?pageSize=15&page=1');	
		getResponseFoundTwoPages.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchDomicilioMock.getFoundAndStop())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/asociados/domicilios/' + today + '?pageSize=15&page=2');

		asociado = Build.anAccountCuentapersonal().build();
		asociado.Afi_Id__c = '131784';
		insert asociado;

		asociado2 = Build.anAccountCuentapersonal().build();
		asociado2.Afi_Id__c = '131811';
		insert asociado2;

		localidad = new Localidad__c();
		localidad.Loc_Id__c = '10055';
		insert localidad;

		localidad2 = new Localidad__c();
		localidad2.Loc_Id__c = '3032';
		insert localidad2;
		
		config = Build.aMasterConfigs().build();
		insert config;
	}

	@isTest static void externalsDomiciliosCanBeProcessed() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new DomicilioProcessor(15, 2, 2, System.now())));
		Test.stopTest();

		Domicilio__c[] domicilios = [
			SELECT DOM_ID__c, Calle__c, Numero__c, Piso__c, DPTO__c, Tipo_de_domicilio__c, Cuenta__c, Localidad__c
			FROM Domicilio__c
		];

		System.assertEquals(2, domicilios.size());
		for(Domicilio__c domicilio : domicilios) {
			if(domicilio.DOM_ID__c == '352276') {
				System.assertEquals('MIGUEL CANE', domicilio.Calle__c);
				System.assertEquals(406, domicilio.Numero__c);
				System.assertEquals('PB', domicilio.Piso__c);
				System.assertEquals('A', domicilio.DPTO__c);
				System.assertEquals('COM', domicilio.Tipo_de_domicilio__c);
				System.assertEquals(asociado.Id, domicilio.Cuenta__c);
				System.assertEquals(localidad.Id, domicilio.Localidad__c);
			}
		}
	}

	@isTest static void aSecondBatchOfDomiciliosCanBeCalled() {		
		Test.setMock(HttpCalloutMock.class, getResponseFoundTwoPages);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new DomicilioProcessor(15, System.now())));
		Test.stopTest();

		Domicilio__c[] domicilios = [
			SELECT DOM_ID__c, Calle__c, Numero__c, Piso__c, DPTO__c, Tipo_de_domicilio__c, Cuenta__c, Localidad__c
			FROM Domicilio__c
		];
		Batch_log__c[] logs = [SELECT Id_registro_error__c, Error__c FROM Batch_log__c];

		// 4 en el mock, pero 1 falla
		System.assertEquals(3, domicilios.size());
		for(Domicilio__c domicilio : domicilios) {
			if(domicilio.DOM_ID__c == '352276') {
				System.assertEquals('MIGUEL CANE', domicilio.Calle__c);
				System.assertEquals(406, domicilio.Numero__c);
				System.assertEquals('PB', domicilio.Piso__c);
				System.assertEquals('A', domicilio.DPTO__c);
				System.assertEquals('COM', domicilio.Tipo_de_domicilio__c);
				System.assertEquals(asociado.Id, domicilio.Cuenta__c);
				System.assertEquals(localidad.Id, domicilio.Localidad__c);
			}
		}
		// domicilio que falla
		System.assertEquals('72241', logs[0].Id_registro_error__c); 
		System.debug(logs[0].Error__c);
		
	}

	@isTest 
	static void atTheLastBatchTheLastUpdatedDateIsUpdated() {
		XHttpCalloutMock mock = new XHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Datetime now = System.now();

		Datetime yesterday = Datetime.now().addDays(-1);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new DomicilioProcessor(15, 2, 2, now)));
		Test.stopTest();

		System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Domicilios__c);
	}
}