force-app/main/default/objects/Account/fields/Afi_Id__c.field-meta.xml
<CustomField>
    <fullName>Afi_Id__c</fullName>
    <externalId>true</externalId>
    <label>Afi Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  PersonBirthdate  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(PersonBirthdate), 
				AND( 
					MONTH(TODAY()) == MONTH(PersonBirthdate), 
					DAY(TODAY()) &lt; DAY(PersonBirthdate) 
					) 
		), 
	1, 
	0 
	)

/*IF( NOT( ISBLANK(  PersonBirthdate  ) ) ,
  IF( DATE( 2000 , MONTH( PersonBirthdate ) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( PersonBirthdate ),
     YEAR (Today()) - YEAR ( PersonBirthdate ) -1 ),
  null)*/</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Organizador_lookup__c.field-meta.xml
<CustomField>
    <fullName>Organizador_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Localidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  Fecha_de_Nacimiento__c  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(Fecha_de_Nacimiento__c), 
				AND( 
					MONTH(TODAY()) == MONTH(Fecha_de_Nacimiento__c), 
					DAY(TODAY()) &lt; DAY(Fecha_de_Nacimiento__c) 
					) 
		), 
	1, 
	0 
	)</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organizador_lookup__c.field-meta.xml
<CustomField>
    <fullName>Organizador_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Individual_Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Individual_Corporativo</fullName>
    <active>true</active>
    <businessProcess>Individual Corporativo</businessProcess>
    <description>Tipo de registro exclusivo para detalle de Individual Corporativas</description>
    <label>Individual Corporativo</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Individuos.recordType-meta.xml
<RecordType>
    <fullName>Individuos</fullName>
    <active>true</active>
    <businessProcess>Venta Individual</businessProcess>
    <description>Tipo de registro para ventas individuales</description>
    <label>Individuos</label>
</RecordType>

force-app/main/default/classes/ReingresoBtnCtrl.cls
public class ReingresoBtnCtrl  {
	@AuraEnabled
	public static Response assingTo(String accId) {
	// LLamar al WS domicilios de asociado, obtener el codigo postal y con eso obtener el codigo de localidad de otro WS que 
	// aun no esta, al obtener la localidad, buscar el organizador asociado a ella(custom field) y
	// Al crear la oportunindad asignarle el organizador al OwnerId
		Account acc = [
			SELECT Estado__c, Fecha_vigencia__c, Edad__c, Afi_Id__c, Name, Empresa__c
			FROM Account
			WHERE Id =: accId
		];
		//User usuario = [SELECT Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
		String recordTypeIndividuos = XappiaHelper.getRecordType('Opportunity', 'Individuos').Id;
		//String recordTypeIndCorp = XappiaHelper.getRecordType('Opportunity', 'Individual_Corporativo').Id;
		//// llamar al WS para saber si tiene deuda o no -------------------
		////WSAsociadoGetCuentaCorrienteResp 
		//WSAsociadoGetCuentaCorriente.Response resp = WSAsociadoGetCuentaCorriente.getAsociadoCuentaCorriente(
			//acc.Afi_Id__c);
		//if(resp.hasError) {
			//return new Response(true, 'No se puede obtener la deuda del asociado', recordTypeIndividuos, null, null);
		//}
		//Boolean hasNotDeuda = resp.asociadoCuentaCorriente.data.cuenta_corriente.detallesAfi.size() == 0; 

		//WSAsociadoGetDomicilios.Response respDomicilio = WSAsociadoGetDomicilios.getAsociadoDomicilios(
			//acc.Afi_Id__c);
		//if(respDomicilio.hasError) {
			//return new Response(true, 'No se puede obtener el domicilio del asociado', recordTypeIndividuos, null, null);
		//}
		
		//List<Localidad__c> localidadesList = new List<Localidad__c>();
		
		//if(respDomicilio.asociadoDomicilios.data.size() >= 1) {
			//localidadesList = [
				//SELECT Id, Codigo_Postal__c, Organizador_lookup__c 
				//FROM Localidad__c 
				//WHERE Codigo_Postal__c =: respDomicilio.asociadoDomicilios.data[0].codigo_postal
			//];
		//}
		//String organizador = localidadesList.size() >= 1 ? localidadesList[0].Organizador_lookup__c : null;
		//----------------------------------------------------------------
		//Boolean salesProfile = usuario.Profile.Name == 'Agente de Ventas' || usuario.Profile.Name == 'Lider de Ventas';
		//Boolean assignToSales = salesProfile
				//|| (
						//acc.Estado__c == 'Dado de baja' 
						//&& (System.today().daysBetween(acc.Fecha_vigencia__c) <= -335) 
						//&& hasNotDeuda 
						//&& acc.Edad__c < 61
					//);

		//if(assignToSales) {
			//return new Response(false, 'Ventas', recordTypeIndividuos, organizador, acc.Name);
		//}
		
		String profileId = UserInfo.getProfileId();
    	Profile profile = [SELECT Id, Name FROM Profile WHERE Id =:profileId];

		return new Response(false, 'Servicio', recordTypeIndividuos, null, acc.Name,profile.Name);
		
		
	}

	 public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;
		@AuraEnabled public String recordTypeIndividuos;
		@AuraEnabled public String organizador;
		@AuraEnabled public String nombre;
        @AuraEnabled public String profile;

        public Response(Boolean hasError, String message, String recordTypeIndividuos, String organizador, String nombre,String profile) {
            this.hasError = hasError;
            this.message = message;
			this.recordTypeIndividuos = recordTypeIndividuos;
			this.organizador = organizador;
			this.nombre = nombre;
            this.profile = profile;
        }
    }
}