force-app/main/default/objects/Account/fields/Afiliados_sujetos_de_facturacion__c.field-meta.xml
<CustomField>
    <fullName>Afiliados_sujetos_de_facturacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Afiliados sujetos de facturación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Canjes__c.field-meta.xml
<CustomField>
    <fullName>Canjes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Canjes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_grupo_empresarial__c.field-meta.xml
<CustomField>
    <fullName>Codigo_grupo_empresarial__c</fullName>
    <label>Código grupo empresarial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Grupos__c.field-meta.xml
<CustomField>
    <fullName>Grupos__c</fullName>
    <label>Grupos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Identificacion_de_afiliados__c.field-meta.xml
<CustomField>
    <fullName>Identificacion_de_afiliados__c</fullName>
    <label>Identificación de afiliados</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interna</fullName>
            </value>
            <value>
                <fullName>Empresa</fullName>
            </value>
            <value>
                <fullName>Empleador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Importe_de_canje__c.field-meta.xml
<CustomField>
    <fullName>Importe_de_canje__c</fullName>
    <label>Importe de canje</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_alta_masiva_afiliado__c.field-meta.xml
<CustomField>
    <fullName>Motivo_alta_masiva_afiliado__c</fullName>
    <label>Motivo alta masiva afiliado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_baja_masiva_de_afiliado__c.field-meta.xml
<CustomField>
    <fullName>Motivo_baja_masiva_de_afiliado__c</fullName>
    <label>Motivo baja masiva de afiliado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_canje__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_canje__c</fullName>
    <label>Porcentaje de canje</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_Limite_de_edad__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_Limite_de_edad__c</fullName>
    <label>Porcentaje de Límite de edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sujeto_facturacion__c.field-meta.xml
<CustomField>
    <fullName>Sujeto_facturacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sujeto facturación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_baja__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_baja__c</fullName>
    <label>Tipo de baja</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Agrupacion__c/Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Agrupación</label>
    <nameField>
        <label>Nombre de Agrupación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agrupaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/Cuenta_Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Cuenta Agrupacion</label>
    <nameField>
        <displayFormat>AGRP-{00000}</displayFormat>
        <label>Nombre de Cuenta Agrupacion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuenta Agrupaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Agrupacion__c.field-meta.xml
<CustomField>
    <fullName>Agrupacion__c</fullName>
    <label>Agrupación</label>
    <referenceTo>Agrupacion__c</referenceTo>
    <relationshipLabel>Cuenta Agrupaciones</relationshipLabel>
    <relationshipName>Cuenta_Agrupaciones</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agrupaciones</relationshipLabel>
    <relationshipName>Cuenta_Agrupaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Empresas__c.field-meta.xml
<CustomField>
    <fullName>Empresas__c</fullName>
    <label>Empresas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountEmpresaProcessor.cls
public class AccountEmpresaProcessor implements IMasterBuilder {

	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForEmpresas;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public AccountEmpresaProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public AccountEmpresaProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForAsociado) {
		this(pageSize, 1, 1, runTime, lastUpdateForAsociado);
	}

	public AccountEmpresaProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public AccountEmpresaProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForEmpresas) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForEmpresas = lastUpdateForEmpresas;
	}

	public List<WSBatchEmpresaResp.Data> callWebService() {
		List<WSBatchEmpresaResp.Data> wsData = new List<WSBatchEmpresaResp.Data>();
		WSBatchEmpresa.Response result;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchEmpresa.getBatchEmpresa(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.empresa.links.next != null;
			currentPage = result.empresa.meta.current_page + 1;
			lastPage = result.empresa.meta.last_page;
			//wsData.addAll(result.empresa);
			wsData = result.empresa.data;
		} else {
			this.errorWs = true;
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {

		List<Account> accountList = new List<Account>();
		List<String> externarlIds = new List<String>();
		Set<Agrupacion__c> agrupacionSet = new Set<Agrupacion__c>();
		List<Cuenta_Agrupacion__c> cuentaAgrupacionList = new List<Cuenta_Agrupacion__c>();
		//Set<Account> agenciasSet = new Set<Account>();

		for(Object res : wsResponses) {
			WSBatchEmpresaResp.Data empresa = (WSBatchEmpresaResp.Data) res;

			Account acc = new Account();
			acc.RecordTypeId = XappiaHelper.getRecordType('Account', 'Empresa').Id;
			acc.Name = empresa.descripcion_empresa;
			acc.Codigo_de_empresa__c = empresa.codigo_empresa;
			acc.Canjes__c = empresa.canje == 'F' ? false : true;
			acc.Porcentaje_de_Limite_de_edad__c = empresa.porcentaje_limite_edad != null ? Decimal.valueOf(empresa.porcentaje_limite_edad) : null;
			acc.Porcentaje_de_canje__c = empresa.porcentaje_canje != null ? Decimal.valueOf(empresa.porcentaje_canje) : null;
			acc.Importe_de_canje__c = empresa.importe_canje != null ? Decimal.valueOf(empresa.importe_canje) : null;
			acc.Afiliados_sujetos_de_facturacion__c = empresa.afiliados_sujetos_facturacion == 'F' ? false : true;
			acc.Identificacion_de_afiliados__c = empresa.identificacion_afiliados;
			acc.Grupos__c = empresa.grupos != null ? Decimal.valueOf(empresa.grupos) : null;
			acc.Motivo_alta_masiva_afiliado__c = empresa.mot_sol_alta_masiva;
			acc.Sujeto_facturacion__c = empresa.es_sujeto_facturacion == 'F' ? false : true;
			acc.Estado__c = empresa.estado_empresa;
			acc.CUIT__c = empresa.cuit;
			acc.Codigo_grupo_empresarial__c= empresa.codigo_grupo_empresarial != null ? Decimal.valueOf(empresa.codigo_grupo_empresarial) : null ;
			acc.Observaciones__c = empresa.observaciones;
			acc.Tipo_de_baja__c = empresa.codigo_tipo_baja;
			acc.Motivo_baja_masiva_de_afiliado__c = empresa.mot_sol_baja_masiva;

			if(empresa.agencia != null) {
				//Account agencia = new Account(Name = empresa.agencia,
						//Codigo_de_delegacion__c = empresa.agencia.substringBefore('_'),
						//Type = 'Agencia');
				//agencia.RecordTypeId = XappiaHelper.getRecordType('Account', 'Delegacion').Id;
				acc.Delegacion__r = new Account(Codigo_de_delegacion__c = empresa.agencia.substringBefore('_'));
				//agenciasSet.add(agencia);
			}

			if(empresa.codigo_agrupacion != null && empresa.descripcion_agrupacion != null) {
				 agrupacionSet.add(new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion, Nombre__c = empresa.descripcion_agrupacion));
				 Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				 junction.Id_Externo__c = empresa.codigo_empresa + '-' + empresa.codigo_agrupacion;
				 junction.Cuenta__r = new Account(Codigo_de_empresa__c = empresa.codigo_empresa);
				 junction.Agrupacion__r = new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion);
				 cuentaAgrupacionList.add(junction);
			}
			if(empresa.codigo_agrupacion1 != null && empresa.descripcion_agrupacion1 != null) {
				 agrupacionSet.add(new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion1, Nombre__c = empresa.descripcion_agrupacion1));
				 Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				 junction.Id_Externo__c = empresa.codigo_empresa + '-' + empresa.codigo_agrupacion1;
				 junction.Cuenta__r = new Account(Codigo_de_empresa__c = empresa.codigo_empresa);
				 junction.Agrupacion__r = new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion1);
				 cuentaAgrupacionList.add(junction);
			}
			if(empresa.codigo_agrupacion2 != null && empresa.descripcion_agrupacion2 != null) {
				 agrupacionSet.add(new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion2, Nombre__c = empresa.descripcion_agrupacion2));
				 Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				 junction.Id_Externo__c = empresa.codigo_empresa + '-' + empresa.codigo_agrupacion2;
				 junction.Cuenta__r = new Account(Codigo_de_empresa__c = empresa.codigo_empresa);
				 junction.Agrupacion__r = new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion2);
				 cuentaAgrupacionList.add(junction);
			}
			if(empresa.codigo_agrupacion3 != null && empresa.descripcion_agrupacion3 != null) {
				 agrupacionSet.add(new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion3, Nombre__c = empresa.descripcion_agrupacion3));
				 Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				 junction.Id_Externo__c = empresa.codigo_empresa + '-' + empresa.codigo_agrupacion3;
				 junction.Cuenta__r = new Account(Codigo_de_empresa__c = empresa.codigo_empresa);
				 junction.Agrupacion__r = new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion3);
				 cuentaAgrupacionList.add(junction);
			}
			if(empresa.codigo_agrupacion4 != null && empresa.descripcion_agrupacion4 != null) {
				 agrupacionSet.add(new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion4, Nombre__c = empresa.descripcion_agrupacion4));
				 Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				 junction.Id_Externo__c = empresa.codigo_empresa + '-' + empresa.codigo_agrupacion4;
				 junction.Cuenta__r = new Account(Codigo_de_empresa__c = empresa.codigo_empresa);
				 junction.Agrupacion__r = new Agrupacion__c(Codigo__c = empresa.codigo_agrupacion4);
				 cuentaAgrupacionList.add(junction);
			}

			accountList.add(acc);
			externarlIds.add(empresa.codigo_empresa);
		}

		List<Agrupacion__c> agrupacionList = new List<Agrupacion__c>(agrupacionSet);

		Database.UpsertResult[] resultsAgrup = Database.upsert(
			agrupacionList, Agrupacion__c.Fields.Codigo__c, false
		);
		Database.UpsertResult[] results = Database.upsert(
			accountList, Account.Fields.Codigo_de_empresa__c,false
		);
		Database.UpsertResult[] resultsCtaAgrup = Database.upsert(
			cuentaAgrupacionList, Cuenta_Agrupacion__c.Fields.Id_Externo__c, false
		);
		System.debug('*****resultsAgrup ' + resultsAgrup); 
		System.debug('*****results ' + results); 
		System.debug('*****resultsCtaAgrup ' + resultsCtaAgrup); 
		
		//EmailUtils.sendErrorMail(resultsAgrup, null, null, null, 'Empresas(Agrupaciones)');
		//EmailUtils.sendErrorMail(results, null, null, externarlIds, 'Empresas');
		//EmailUtils.sendErrorMail(resultsCtaAgrup, null, null, null, 'Empresas(JunctionCtaAgrup)');

		Utils.insertBatchLogs(results, null, null, externarlIds, 'Empresas');
	}

	public void updateDate() {

		if (!hasNext) {
			SucursalesEmpresaProcessor nextProcessor = new SucursalesEmpresaProcessor(pageSize, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
			
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Empresas__c = lastUpdateForEmpresas;
				upsert lastUpdate;
			}

		} else {

			AccountEmpresaProcessor nextProcessor = new AccountEmpresaProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}
}