force-app/main/default/objects/Account/fields/Autonumerico__c.field-meta.xml
<CustomField>
    <fullName>Autonumerico__c</fullName>
    <displayFormat>A-{00000000}</displayFormat>
    <label>Autonumerico</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Localidad_Nombre__c</fullName>
    <formula>Localidad_new__r.Nombre_de_Localidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Localidad Nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Efector.recordType-meta.xml
<RecordType>
    <fullName>Efector</fullName>
    <active>true</active>
    <description>Efectores y Prestadores</description>
    <label>Efector</label>
</RecordType>

force-app/main/default/objects/Matricula__c/Matricula__c.object-meta.xml
<CustomObject>
    <label>Matrícula</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Nombre de Matrícula</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrículas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Matricula__c/fields/Efector__c.field-meta.xml
<CustomField>
    <fullName>Efector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Matrículas</relationshipLabel>
    <relationshipName>Matriculas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Matricula__c.field-meta.xml
<CustomField>
    <fullName>Matricula__c</fullName>
    <label>Matrícula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Provincia_codigo__c.field-meta.xml
<CustomField>
    <fullName>Provincia_codigo__c</fullName>
    <label>Provincia código</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provincia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Provincia_nombre__c.field-meta.xml
<CustomField>
    <fullName>Provincia_nombre__c</fullName>
    <description>Nombre de provincia usado solo para el componente EfectorSearch</description>
    <label>Provincia nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EfectorSearchController.cls
public class EfectorSearchController  {

	@AuraEnabled
	public static Response search(String matricula, String provincia, String localidad) {
		System.debug(matricula);
		System.debug(provincia);
		System.debug(localidad);
		//String query = 'SELECT Name FROM Account WHERE RecordType.DeveloperName = \'Efector\'';
		//List<Account> efectores = Database.query(query);
		//Medico[] medicos = new List<Medico>();
		String query = 'SELECT Id, Matricula__c, Efector__c, Provincia_codigo__c, Efector__r.Codigo_de_efector__c, ' +
							'Efector__r.Autonumerico__c, Efector__r.Name ' +
						'FROM Matricula__c ' +
						'WHERE Matricula__c LIKE \'%' + matricula + '%\' ' +
							'AND Efector__r.Localidad_Nombre__c LIKE \'%' + localidad + '%\'';
						//'%\' AND Provincia_codigo__c LIKE \'%' + provincia + 
		query += String.isNotEmpty(provincia) ? ' AND Provincia_codigo__c = \'' + provincia + '\'' : '';
		List<Matricula__c> matriculas = Database.query(query);

		for(Matricula__c mat : matriculas) {
			String provinciaNombre = XappiaHelper.getPicklistLabelAndValues('Matricula__c','Provincia_codigo__c')
										.get(mat.Provincia_codigo__c);
			
			mat.Provincia_nombre__c = provinciaNombre;			
			
		}

		//return new Response(false, efectores);
		return new Response(false, matriculas);
	}

	public class Response {
		@AuraEnabled public Boolean hasError;
		//@AuraEnabled public String[] efectores;
		@AuraEnabled public Matricula__c[] efectores;

		//public Response(Boolean hasError, String[] efectores) {
		public Response(Boolean hasError, Matricula__c[] efectores) {
            this.hasError = hasError;
            this.efectores = efectores;
        }
	}

	//public class Medico {
		//@AuraEnabled public String nombre;
		//@AuraEnabled public String matricula;
		//@AuraEnabled public String provincia;
		//@AuraEnabled public String autonumerico;

		//public Response(String nombre, String matricula, String provincia, String autonumerico) {
            //this.nombre = nombre;
            //this.matricula = matricula;
			//this.provincia = provincia;
			//this.autonumerico = autonumerico;
			//this.medicos = medicos;
        //}
	//}
}