force-app/main/default/objects/Account/fields/Categoria_codigo__c.field-meta.xml
<CustomField>
    <fullName>Categoria_codigo__c</fullName>
    <label>Categoría código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Clase_efector__c.field-meta.xml
<CustomField>
    <fullName>Clase_efector__c</fullName>
    <description>Clases en el RT Efector, texto que llega de la int</description>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Egresado__c.field-meta.xml
<CustomField>
    <fullName>Egresado__c</fullName>
    <label>Egresado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Es_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Es_Prestador__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>En caso de que sea prestador, la casilla estará activa. Deberá completar los campos correspondientes a la sección Prestador</inlineHelpText>
    <label>Es Prestador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Es_Profesional__c.field-meta.xml
<CustomField>
    <fullName>Es_Profesional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Profesional?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Casado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Soltero</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Concubinato</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Separado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Estado_Prestador__c</fullName>
    <label>Estado Prestador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Alta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Alta__c</fullName>
    <label>Fecha Alta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_alta_prestador__c.field-meta.xml
<CustomField>
    <fullName>Fecha_alta_prestador__c</fullName>
    <label>Fecha alta prestador</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_baja_prestador__c.field-meta.xml
<CustomField>
    <fullName>Fecha_baja_prestador__c</fullName>
    <label>Fecha baja prestador</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_nacimiento_efector__c.field-meta.xml
<CustomField>
    <fullName>Fecha_nacimiento_efector__c</fullName>
    <description>Fecha de nacimiento del Efector</description>
    <label>Fecha nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_Titulo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Titulo__c</fullName>
    <label>Fecha Título</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia_prestador__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia_prestador__c</fullName>
    <label>Fecha vigencia prestador</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Matricula_nacional__c.field-meta.xml
<CustomField>
    <fullName>Matricula_nacional__c</fullName>
    <label>Matrícula nacional</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Matricula_provincial2__c.field-meta.xml
<CustomField>
    <fullName>Matricula_provincial2__c</fullName>
    <label>Matrícula provincial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Matricula_provincial__c.field-meta.xml
<CustomField>
    <fullName>Matricula_provincial__c</fullName>
    <label>Matrícula provincial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_Baja_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Baja_Prestador__c</fullName>
    <label>Motivo Baja Prestador</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones_prestador__c.field-meta.xml
<CustomField>
    <fullName>Observaciones_prestador__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Efector.recordType-meta.xml
<RecordType>
    <fullName>Efector</fullName>
    <active>true</active>
    <description>Efectores y Prestadores</description>
    <label>Efector</label>
</RecordType>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Efectores__c.field-meta.xml
<CustomField>
    <fullName>Efectores__c</fullName>
    <label>Efectores</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountEfectorProcessor.cls
public class AccountEfectorProcessor implements IMasterBuilder {

	public Boolean hasNext = false;
	public String next;
	public String followUpEndpoint;
	public Datetime runTime;
	public Datetime lastUpdateForEfectores;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public List<String> efectoresCod;

	public AccountEfectorProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now(),new List<String>());
	}

	public AccountEfectorProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForAsociado) {
		this(pageSize, 1, 1, runTime, lastUpdateForAsociado,new List<String>());
	}

	public AccountEfectorProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime,List<String> efectores) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now(),efectores);
	}

	public AccountEfectorProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForEfectores, List<String> efectores) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForEfectores = lastUpdateForEfectores;
		this.efectoresCod = efectores;
	}

	public List<WSBatchEfectorResp.Data> callWebService() {
		List<WSBatchEfectorResp.Data> wsData = new List<WSBatchEfectorResp.Data>();
		WSBatchEfector.Response result;


		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchEfector.getBatchEfector(fecha, this.pageSize, this.currentPage);
		}

		System.debug(result);
		if(!result.hasError) {
			hasNext = result.efector.links.next != null;
			currentPage = result.efector.meta.current_page +1;
			lastPage = result.efector.meta.last_page;
		
			wsData = result.efector.data;
		} else {
			this.errorWs = true;
		}
		System.debug(wsData);
		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Account> accountList = new List<Account>();
		List<String> efectores = new List<String>();
		System.debug(wsResponses);
		for(Object res : wsResponses) {
			
			WSBatchEfectorResp.Data efector = (WSBatchEfectorResp.Data) res;
			//String matricula = efector.pcia_mat != null ? 'MP ' + efector.pcia_mat + ' ' + efector.matricula : 'MN ' + efector.matricula;
			System.debug('****efector ' + efector);
			
			Account acc = new Account();
			acc.RecordTypeId = XappiaHelper.getRecordType('Account', 'Efector').Id;
			acc.Name = efector.nombre;
			acc.Es_Profesional__c = efector.es_profesional == 'V' ? true : false;
			acc.Codigo_de_efector__c = efector.codigo;
			acc.Clase_efector__c = efector.clase;
			acc.Es_Prestador__c = efector.es_prestador == 'V' ? true : false;
			acc.Categoria_codigo__c = efector.categoria;
			acc.Egresado__c = efector.egresado;
			acc.Fecha_Titulo__c = efector.fecha_titulo != null ? Date.valueOf(efector.fecha_titulo) : null;
			acc.Estado_civil__c = efector.estado_civil;
			acc.Fecha_nacimiento_efector__c = efector.fecha_nacimiento != null ? Date.valueOf(efector.fecha_nacimiento) : null;
			acc.Observaciones__c = efector.observaciones;
			acc.Estado__c = efector.estado;
			acc.Fecha_vigencia__c = efector.fecha_vigencia != null ? Date.valueOf(efector.fecha_vigencia) : null;
			acc.CUIT__c = efector.cuit;
			acc.Observaciones_prestador__c = efector.obs_prestador;
			acc.Estado_Prestador__c = acc.Estado_Prestador__c;
			acc.Fecha_vigencia_prestador__c = efector.fecha_vigencia_prestador != null ? Date.valueOf(efector.fecha_vigencia_prestador) : null;
			acc.Fecha_Alta__c = efector.fecha_alta != null ? Date.valueOf(efector.fecha_alta) : null;
			acc.Fecha_baja_prestador__c = efector.fecha_baja != null ? Date.valueOf(efector.fecha_baja) : null;
			acc.Fecha_alta_prestador__c = efector.fecha_alta != null ? Date.valueOf(efector.fecha_alta) : null;
			acc.Motivo_Baja_Prestador__c = efector.motivo_baja;
			acc.Correo_electronico__c = Utils.isAValidEmail(efector.mail) ? efector.mail : null;

			
			if(efector.matricula_1 != null){
				System.debug('****name ' + efector.nombre );
				if(efector.matricula_1.startsWith('MP')){
					List<String> listPartes = efector.matricula_1.split(' ');
					acc.Matricula_provincial__c = listPartes[2] + ' ' + listPartes[0] + ' ' + listPartes[1];
				}else if(efector.matricula_1 != null){
					List<String> listPartes = efector.matricula_1.split(' ');
					acc.Matricula_nacional__c = listPartes[2] + ' ' + listPartes[0];
				}
			}

			if(efector.matricula_2 != null){
				if(efector.matricula_2.startsWith('MP') && acc.Matricula_provincial__c == null){
					List<String> listPartes = efector.matricula_2.split(' ');
					acc.Matricula_provincial__c = listPartes[2] + ' ' + listPartes[0] + ' ' + listPartes[1];
				}else if(acc.Matricula_provincial__c != null && acc.Matricula_provincial2__c == null && efector.matricula_2.startsWith('MP')){
					List<String> listPartes = efector.matricula_2.split(' ');
					acc.Matricula_provincial2__c = listPartes[2] + ' ' + listPartes[0] + ' ' + listPartes[1];
				}else if(efector.matricula_2.startsWith('MN')){
					List<String> listPartes = efector.matricula_2.split(' ');
					acc.Matricula_nacional__c = listPartes[2] + ' ' + listPartes[0];
				}
			}

			if(efector.matricula_3 != null){
				if(efector.matricula_3.startsWith('MN')){
					List<String> listPartes = efector.matricula_3.split(' ');
					acc.Matricula_nacional__c = listPartes[2] + ' ' + listPartes[0];
				}else{
					List<String> listPartes = efector.matricula_3.split(' ');
					acc.Matricula_provincial__c = listPartes[2] + ' ' + listPartes[0] + ' ' + listPartes[1];
				}
			}
			accountList.add(acc);
			efectores.add(acc.Codigo_de_efector__c);
		}

		efectoresCod.addAll(efectores);


		Database.UpsertResult[] results = Database.upsert(
				accountList, Account.Fields.Codigo_de_efector__c,false
		);
		System.debug('****resultsEfectores: ' + results);
		//EmailUtils.sendErrorMail(results,null,null, efectores, 'Efectores ' + (currentPage - 1) + ' pagina');

		Utils.insertBatchLogs(results,null,null, efectores, 'Efectores');
	}



	public void updateDate() {


		if (!hasNext) {

			ConsultoriosEfectorProcessor nextProcessor = new ConsultoriosEfectorProcessor(100, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
			
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Efectores__c = lastUpdateForEfectores;
				upsert lastUpdate;
			}

		} else {

			AccountEfectorProcessor nextProcessor = new AccountEfectorProcessor(pageSize, currentPage, lastPage, runTime,efectoresCod);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}


}