force-app/main/default/objects/Account/fields/Clase_obra_social__c.field-meta.xml
<CustomField>
    <fullName>Clase_obra_social__c</fullName>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_Agrupacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Agrupacion__c</fullName>
    <label>Código Agrupación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_obra_social__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_obra_social__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de obra social</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_financiero__c.field-meta.xml
<CustomField>
    <fullName>Codigo_financiero__c</fullName>
    <label>Código financiero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_RNOS__c.field-meta.xml
<CustomField>
    <fullName>Codigo_RNOS__c</fullName>
    <label>Código RNOS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/descripcion_agrupacion_os__c.field-meta.xml
<CustomField>
    <fullName>descripcion_agrupacion_os__c</fullName>
    <label>Descripción agrupación</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Descripcion_obra_social__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_obra_social__c</fullName>
    <label>Descripción</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_activacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_activacion__c</fullName>
    <label>Fecha de activación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Obra_social_nombre__c.field-meta.xml
<CustomField>
    <fullName>Obra_social_nombre__c</fullName>
    <label>Obra social nombre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Obra_social.recordType-meta.xml
<RecordType>
    <fullName>Obra_social</fullName>
    <active>true</active>
    <label>Obra social</label>
</RecordType>

force-app/main/default/objects/Agrupacion__c/Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Agrupación</label>
    <nameField>
        <label>Nombre de Agrupación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agrupaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/Cuenta_Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Cuenta Agrupacion</label>
    <nameField>
        <displayFormat>AGRP-{00000}</displayFormat>
        <label>Nombre de Cuenta Agrupacion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuenta Agrupaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Agrupacion__c.field-meta.xml
<CustomField>
    <fullName>Agrupacion__c</fullName>
    <label>Agrupación</label>
    <referenceTo>Agrupacion__c</referenceTo>
    <relationshipLabel>Cuenta Agrupaciones</relationshipLabel>
    <relationshipName>Cuenta_Agrupaciones</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agrupaciones</relationshipLabel>
    <relationshipName>Cuenta_Agrupaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Obras_Sociales__c.field-meta.xml
<CustomField>
    <fullName>Obras_Sociales__c</fullName>
    <label>Obras Sociales</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ObraSocialProcessor.cls
public class ObraSocialProcessor implements IMasterBuilder  {

	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForObraSocial;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;

	public ObraSocialProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public ObraSocialProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForObraSocial) {
		this(pageSize, 1, 1, runTime, lastUpdateForObraSocial);
	}

	public ObraSocialProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public ObraSocialProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForObraSocial) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForObraSocial = lastUpdateForObraSocial;
	}

	public List<WSBatchObraSocialResp.Data> callWebService() {
		List<WSBatchObraSocialResp.Data> wsData = new List<WSBatchObraSocialResp.Data>();
		WSBatchObraSocial.Response result;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchObraSocial.getBatchObrasSociales(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.obrasSociales.links.next != null;
			currentPage = result.obrasSociales.meta.current_page + 1;
			lastPage = result.obrasSociales.meta.last_page;
			wsData.addAll(result.obrasSociales.data);
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Account> obraSocialList = new List<Account>();
		List<String> externalIds = new List<String>();
        Set<Agrupacion__c> agrupacionSet = new Set<Agrupacion__c>();
		Set<Account> delegacionesSet = new Set<Account>();
		List<Cuenta_Agrupacion__c> cuentaAgrupacionList = new List<Cuenta_Agrupacion__c>();

		for(Object res : wsResponses) {
			WSBatchObraSocialResp.Data obraSocialResp = (WSBatchObraSocialResp.Data) res;
			Account obraSocial = new Account();
			obraSocial.RecordTypeId = XappiaHelper.getRecordType('Account', 'Obra_social').Id;

			obraSocial.Name = obraSocialResp.nombre;
			obraSocial.Codigo_de_obra_social__c = obraSocialResp.codigo;
			obraSocial.Descripcion_obra_social__c= obraSocialResp.descripcion ;
			obraSocial.CUIT__c = obraSocialResp.cuit ;
			obraSocial.Fecha_de_activacion__c = obraSocialResp.fecha_activacion != null ? Date.valueOf(obraSocialResp.fecha_activacion) : null;
			obraSocial.Estado__c = obraSocialResp.estado ;
			obraSocial.Codigo_Agrupacion__c = obraSocialResp.codigo_agrupacion ;
			obraSocial.Clase_obra_social__c = obraSocialResp.clase ;
			obraSocial.Obra_social_nombre__c = obraSocialResp.nombre ;
			obraSocial.Codigo_RNOS__c = obraSocialResp.codigo_rnos;
			obraSocial.Type = obraSocialResp.tipo ;
			obraSocial.Codigo_financiero__c = obraSocialResp.codigo_financiero ;
			obraSocial.Correo_electronico__c = Utils.isAValidEmail(obraSocialResp.email) ? obraSocialResp.email : null;
			obraSocial.descripcion_agrupacion_os__c = obraSocialResp.descripcion_agrupacion;
			
			obraSocialList.add(obraSocial);
			externalIds.add(obraSocialResp.codigo);

			if(obraSocialResp.codigo_agrupacion != null && obraSocialResp.descripcion_agrupacion != null) {
				Agrupacion__c agrupacion = new Agrupacion__c(Codigo__c = obraSocialResp.codigo_agrupacion, Nombre__c = obraSocialResp.descripcion_agrupacion);
				agrupacionSet.add(agrupacion);
				Cuenta_Agrupacion__c junction = new Cuenta_Agrupacion__c();
				junction.Id_Externo__c = obraSocialResp.codigo + '-' + obraSocialResp.codigo_agrupacion;
				junction.Cuenta__r = new Account(Codigo_de_obra_social__c = obraSocialResp.codigo);
				junction.Agrupacion__r = new Agrupacion__c(Codigo__c = obraSocialResp.codigo_agrupacion);
				cuentaAgrupacionList.add(junction);
			}
            
		}

		List<Account> delegacionList = new List<Account>(delegacionesSet);
		Database.UpsertResult[] delegacionRes = Database.upsert(
			delegacionList, Account.Fields.Codigo_de_delegacion__c,false
		);

		Database.UpsertResult[] results = Database.upsert(
			obraSocialList, Account.Fields.Codigo_de_obra_social__c, false
		);
		List<Agrupacion__c> agrupacionList = new List<Agrupacion__c>(agrupacionSet);
		Database.UpsertResult[] resultsAgrup = Database.upsert(
				agrupacionList, Agrupacion__c.Fields.Codigo__c, false
		);
		Database.UpsertResult[] resultsCtaAgrup = Database.upsert(
				cuentaAgrupacionList, Cuenta_Agrupacion__c.Fields.Id_Externo__c, false
		);
		System.debug(delegacionRes);
		System.debug(results);
		//EmailUtils.sendErrorMail(delegacionRes, null, null, null, 'OS(Delegaciones)');
		//EmailUtils.sendErrorMail(results, null, null, externalIds, 'Obras Sociales');
		//EmailUtils.sendErrorMail(resultsAgrup, null, null, null, 'OS(Agrupaciones)');
		//EmailUtils.sendErrorMail(resultsCtaAgrup, null, null, null, 'OS(JunctionCtaAgrup)');

		Utils.insertBatchLogs(results, null, null, externalIds, 'Obras Sociales');

	}

	public void updateDate() {

		if (!hasNext) {
			MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
			lastUpdate.Obras_Sociales__c = lastUpdateForObraSocial;
			upsert lastUpdate;
		} else {
			ObraSocialProcessor nextProcessor = new ObraSocialProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}
}