force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <defaultValue>&quot;Masculino&quot;</defaultValue>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Asociado__c.field-meta.xml
<CustomField>
    <fullName>Asociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asociado</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asignaciones de cláusulas temporarias</relationshipLabel>
    <relationshipName>Asignaciones_de_clausulas_temporarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_vigencia_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_vigencia_hasta__c</fullName>
    <label>Fecha de vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_FUM__c.field-meta.xml
<CustomField>
    <fullName>Fecha_FUM__c</fullName>
    <label>Fecha FUM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClausulaTempNotificationCtrlTest.cls
@isTest
public with sharing class ClausulaTempNotificationCtrlTest {
    @isTest
    private static void whenCheckIfHaveAnAttachmentAndFindIt_ShowAnAlertMessage() {
        Date today = Date.today();
        Date tomorrow = Date.today().addDays(1);
        Date yesterday = Date.Today().addDays(-1);

        Account acc = Build.anAccount().withLastName('AccountTest').build();
        acc.Codigo_de_Afiliado__c = '123';
        acc.Sexo__c = 'F';
        insert acc;

		Asignacion_de_clausula_temporaria__c clausula = new Asignacion_de_clausula_temporaria__c(
            Fecha_desde__c = today,
            Fecha_de_vigencia_hasta__c = yesterday,
            Asociado__c = acc.Id,
            Fecha_FUM__c = yesterday
        );
        insert clausula;

        ContentVersion contentVersion = new ContentVersion(
			Title = 'Test',
			PathOnClient = 'test.pdf',
			VersionData = Blob.valueOf('Test Content'),
			IsMajorVersion = true
		);
        insert contentVersion;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
		ContentDocumentLink cdl = New ContentDocumentLink();
		cdl.LinkedEntityId = clausula.Id;
		cdl.ContentDocumentId = documents[0].Id;
		cdl.shareType = 'V';
        insert cdl;
        
        Test.startTest();
        ClausulaTempNotificationCtrl.Response alertMsg = ClausulaTempNotificationCtrl.hasAttachmentsErrorMsg(clausula.Id);
        Test.stopTest();

        System.assertEquals('ok', alertMsg.message);
    }

    @isTest
    private static void whenCheckIfHaveAnAttachmentAndDontFindIt_ShowAnAlertMessage() {
        Date today = Date.today();
        Date tomorrow = Date.today().addDays(1);
        Date yesterday = Date.Today().addDays(-1);

        Account acc = Build.anAccount().withLastName('AccountTest').build();
        acc.Codigo_de_Afiliado__c = '123';
        acc.Sexo__c = 'F';
        insert acc;

		Asignacion_de_clausula_temporaria__c clausula = new Asignacion_de_clausula_temporaria__c(
            Fecha_desde__c = today,
            Fecha_de_vigencia_hasta__c = yesterday,
            Asociado__c = acc.Id,
            Fecha_FUM__c = yesterday
        );
        insert clausula;
        
        
        Test.startTest();
        ClausulaTempNotificationCtrl.Response alertMsg = ClausulaTempNotificationCtrl.hasAttachmentsErrorMsg(clausula.Id);
        Test.stopTest();

        System.assertEquals('Recuerde adjuntar el Certificado de Embarazo', alertMsg.message);
    }

}