force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ap_autorizada__c.field-meta.xml
<CustomField>
    <fullName>Ap_autorizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se utiliza para marcar con un trigger cuando todas las alertas de todas las prestaciones se resuelven o no tienen alertas</description>
    <label>Ap autorizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Cambio_Manual__c.field-meta.xml
<CustomField>
    <fullName>Cambio_Manual__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Cambio Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <formula>Codigo_Nomenclador__r.Prestacion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prestación</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORÍA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseAPRevertirOrdenCtrl.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class CaseAPRevertirOrdenCtrl  {
	static final String[] ADMIN_PROFILES = new List<String>{'System Administrator','Administrador del sistema', 'Administrador de Servicio'};
	public static Id emiId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_internacion').Id;
	@AuraEnabled
	public static BasicResponse revertirOrden(String caseId) {
		Case caso = [SELECT Status, Nivel_de_derivacion__c, OwnerId, Delegacion__r.Codigo_de_delegacion__c, Nro_AP__c,
						Orden_de_Compra__c, Orden_de_Compra__r.Estado_OC__c, Evento_medico__c,Evento_medico__r.RecordTypeId,
						(SELECT Id FROM Prestaciones__r)
					FROM Case
					WHERE Id = :caseId];
		User usuario = [SELECT CommunityNickname, Profile.Name, UserRole.DeveloperName, Codigo_delegacion__c
						FROM User
						WHERE Id =: UserInfo.getUserId()];
		BasicResponse validation = validatePermissions(usuario, caso);
		if(validation.message != 'ok') {
			return validation;
		}
		String body = JSON.serialize(new Map<String, Object> {'username' => usuario.CommunityNickname?.toUpperCase()});
		WSCaseAPRevertirOrden.Response resp = WSCaseAPRevertirOrden.revertirOrden(caso.Nro_AP__c, body);
		if (!resp.hasError) {
			caso.Cambio_Manual__c = false;
			caso.Status = resp.caseRes.data.ap.estado;
			caso.Nivel_de_derivacion__c = resp.caseRes.data.ap.nivel;
			caso.Ap_autorizada__c = false;
			caso.Caso_Rechazado__c = false;
			deleteOrdenAttached(caseId);
			if(caso.Evento_medico__c != null && caso.Evento_medico__r.RecordTypeId == emiId){
				deleteOrdenAttached(caso.Evento_medico__c);
			}
			revertirOrdenDeCompra(caso);
			Database.SaveResult resultCaso = Database.update(caso);
			Map<Id, Prestacion__c> prestaciones = new Map<Id, Prestacion__c>(caso.Prestaciones__r);
			for(Prestacion__c prest : prestaciones.values()){
				prest.Estado__c = 'C1-----G';
			}
			List<Database.SaveResult> resultPrestaciones = Database.update(prestaciones.values());
			List<Alerta__c> alertasToDelete = [SELECT Id FROM Alerta__c WHERE Prestacion__c IN :prestaciones.keySet()];
			if (!prestaciones.isEmpty() && !alertasToDelete.isEmpty()) {
				delete alertasToDelete;
			}
			return new BasicResponse(false, 'ok');
		}
		return new BasicResponse(true, resp.message);
	}
	private static BasicResponse validatePermissions(User usuario, Case caso) {
		String strObjPrefix = String.valueOf(caso.OwnerId).substring(0, 3);
        Boolean isUserInqueue = false;
		if(strObjPrefix == Group.sObjectType.getDescribe().getKeyPrefix()){
			Group cola = [SELECT Id FROM Group WHERE Type = 'Queue' AND Id = :caso.OwnerId];
			if(cola != null){
				List<GroupMember> gms = [SELECT Id,UserOrGroupId FROM GroupMember WHERE GroupId = :cola.Id];
				for(GroupMember gm : gms){
					if(gm.UserOrGroupId == UserInfo.getUserId()){
						isUserInqueue = true;
                        break;
					}
				}
            }
        }
		String nick =  usuario.CommunityNickname != null ? usuario.CommunityNickname.toUppercase() : null;
		Boolean admin = ADMIN_PROFILES.contains(usuario.Profile.Name);
		Boolean propietario = admin || (isUserInqueue ? isUserInqueue : caso.OwnerId == usuario.Id);
		if(caso.Status != 'CA-----E') {
			return new BasicResponse(false, System.Label.Alerta_NoAuth_EstadoOrdenDebeSerEmitida);
		}
		if(usuario.CommunityNickname == null) {
			return new BasicResponse(false, System.Label.Alerta_NoAuth_ApodoCMVacio);
		}
		List<GroupMember> grupo = new List<GroupMember>();
		if(caso.Nivel_de_derivacion__c == 'Nivel 1') {
			grupo = [SELECT Id FROM GroupMember WHERE Group.DeveloperName = 'Front' AND UserOrGroupId =: usuario.Id];
			if(grupo.isEmpty() && !admin) {return new BasicResponse(false, System.Label.Alerta_NoAuth_UsuarioNoFront);
			}
		}
		else if(caso.Nivel_de_derivacion__c == 'Nivel 2') {
			grupo = [SELECT Id FROM GroupMember WHERE Group.DeveloperName = 'Mesa_de_ayuda' AND UserOrGroupId =: usuario.Id];
			if(grupo.isEmpty() && !admin) {
				return new BasicResponse(false, System.Label.Alerta_NoAuth_UsuarioNoMesaAyuda);
			}
		}
		else if(caso.Nivel_de_derivacion__c == 'Nivel 3') {
			List<CaseTeamMember> equipo = [SELECT MemberId FROM CaseTeamMember WHERE ParentId =: caso.Id AND MemberId =: usuario.Id];
			if(equipo.isEmpty() && !admin) {
				return new BasicResponse(false, System.Label.Alerta_NoAuth_UsuarioNoEquipoCaso);
			}
		}
		else if(caso.Nivel_de_derivacion__c == null && !propietario) {
			return new BasicResponse(false, System.Label.Alerta_NoAuth_UsuarioNoPropietario);
		}
		return new BasicResponse(false, 'ok');
	}
	private static void deleteOrdenAttached(Id caseId) {
		Id[] contentDocumentIds = new List<Id>();
		Id[] contentDocumentIdsToDelete = new List<Id>();
		ContentDocumentLink[] links = [SELECT LinkedEntityId, ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title,
											ShareType, ContentDocument.FileType, ContentDocument.FileExtension
										FROM ContentDocumentLink
										WHERE LinkedEntityId =: caseId
											AND ContentDocument.Title LIKE 'Orden_%'
											AND ContentDocument.FileExtension = 'pdf'];

		for(ContentDocumentLink cdl : links) {
			contentDocumentIds.add(cdl.ContentDocumentId);
		}
		ContentVersion[] versions = [SELECT Id, PathOnClient, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentIds];
		for(ContentVersion version : versions) {
			if(!version.PathOnClient.startsWith('Orden_')) {
				contentDocumentIdsToDelete.add(version.ContentDocumentId);
			}
		}
		ContentDocument[] documentsToDelete = [SELECT Id FROM ContentDocument WHERE Id IN :contentDocumentIdsToDelete];
		Database.DeleteResult[] resultDocumentsToDelete = Database.delete(documentsToDelete);
	}
	private static void revertirOrdenDeCompra(Case caso) {
		if(String.isNotBlank(caso.Orden_de_Compra__c)) {
			Orden_de_Compra__c orden = caso.Orden_de_Compra__r;
			orden.Estado_OC__c = 'Generada';
			update orden;
		}
	}
	@AuraEnabled
	public static Boolean canRevertOrders() {
		Boolean isLider = Utils.isLeader();
		Boolean isEncargado = Utils.isEncargado();
		return isLider || isEncargado;
	}
}