force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Agrupacion__c/Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Agrupación</label>
    <nameField>
        <label>Nombre de Agrupación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agrupaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/Cuenta_Agrupacion__c.object-meta.xml
<CustomObject>
    <label>Cuenta Agrupacion</label>
    <nameField>
        <displayFormat>AGRP-{00000}</displayFormat>
        <label>Nombre de Cuenta Agrupacion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuenta Agrupaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuenta_Agrupacion__c/fields/Agrupacion__c.field-meta.xml
<CustomField>
    <fullName>Agrupacion__c</fullName>
    <label>Agrupación</label>
    <referenceTo>Agrupacion__c</referenceTo>
    <relationshipLabel>Cuenta Agrupaciones</relationshipLabel>
    <relationshipName>Cuenta_Agrupaciones</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Obras_Sociales__c.field-meta.xml
<CustomField>
    <fullName>Obras_Sociales__c</fullName>
    <label>Obras Sociales</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ObraSocialProcessorTest.cls
@isTest
public class ObraSocialProcessorTest  {

    static MasterConfigs__c config;
    static XHttpCalloutMock getResponseFound;
    static XHttpCalloutMock getErrorResponse;
    static XHttpCalloutMock getEmptyListResponse;
    static XHttpCalloutMock getResponseFoundSecondPageOnly;

    static {
        String today = System.now().format('yyyy-MM-dd').substringBefore(' ');

        getResponseFound = new XHttpCalloutMock();
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSBatchObraSocialMock.getFound())
                .addForAddress(WSBatchObraSocial.SERVICE_CONFIG.URL__c + '/v1/salud/batch/obras-sociales/' + today + '?pageSize=15&page=1');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSBatchObraSocialMock.getFoundSecondPage())
                .addForAddress(WSBatchObraSocial.SERVICE_CONFIG.URL__c + '/v1/salud/batch/obras-sociales/' + today + '?pageSize=15&page=2');

        getResponseFoundSecondPageOnly = new XHttpCalloutMock();
        getResponseFoundSecondPageOnly.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFoundSecondPageOnly.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSBatchObraSocialMock.getFoundSecondPage())
                .addForAddress(WSBatchObraSocial.SERVICE_CONFIG.URL__c + '/v1/salud/batch/obras-sociales/' + today + '?pageSize=15&page=2');
    }

    static {
        config = Build.aMasterConfigs().build();
        insert config;
    }

    @isTest static void externalsOSCanBeProcessed() {
        Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPageOnly);

        Test.startTest();
        Database.executeBatch(new MasterBatch(new ObraSocialProcessor(15, 2, 2, System.now())));
        Test.stopTest();

        //System.assertEquals(3, [SELECT Count() FROM Account]);
		// Sin delegaciones son 2, los 2 registros del mock
		System.assertEquals(2, [SELECT Count() FROM Account]);
    }

    @isTest static void aSecondBatchOfAccountsCanBeCalled() {
        Test.setMock(HttpCalloutMock.class, getResponseFound);

        Test.startTest();
        Database.executeBatch(new MasterBatch(new ObraSocialProcessor(15, System.now())));
        Test.stopTest();
		
		// Ya no se insertan las delegaciones
        //System.assertEquals(1, [SELECT Count() FROM Account WHERE Codigo_de_delegacion__c = '650098']);
        System.assertEquals(3, [SELECT Count() FROM Account]);
        System.assertEquals(2, [SELECT Count() FROM Agrupacion__c]);
        System.assertEquals(3, [SELECT Count() FROM Cuenta_Agrupacion__c]);
    }

    @isTest static void atTheLastBatchTheLastUpdatedDateIsUpdated() {
        Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPageOnly);

        Datetime now = System.now();

        Datetime yesterday = Datetime.now().addDays(-1);

        Test.startTest();
        Database.executeBatch(new MasterBatch(new ObraSocialProcessor(15, yesterday, now)));
        Test.stopTest();

        System.debug(MasterConfigs__c.getOrgDefaults().Obras_Sociales__c);

        System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Obras_Sociales__c);
    }

}