force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sucursal__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sucursales</relationshipLabel>
    <relationshipName>Sucursales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchIdExternoSucursalesTest.cls
@isTest 
private class BatchIdExternoSucursalesTest {
	
	@testSetup 
    static void setup() {
		
		Account empresa = Build.anAccountEmpresa().build();
		empresa.Codigo_de_empresa__c = '12345';
		insert empresa;

		Account empresa2 = Build.anAccountEmpresa().build();
		insert empresa2;

		List<Sucursal__c> sucursales = new List<Sucursal__c>();

		for (Integer i = 1; i < 9; i++) {
			Sucursal__c suc = new Sucursal__c();
			suc.Codigo__c = String.valueOf(i);
			suc.Empresa__c = empresa.Id;

			sucursales.add(suc);
		}
		Sucursal__c suc1 = new Sucursal__c();
		suc1.Empresa__c = empresa.Id;
		sucursales.add(suc1);

		Sucursal__c suc2 = new Sucursal__c();
		suc2.Empresa__c = empresa2.Id;
		suc2.Codigo__c = '10';
		sucursales.add(suc2);

		insert sucursales;

	}

	@isTest
	private static void testName() {

		Test.startTest();
		BatchIdExternoSucursales myBatchObject = new BatchIdExternoSucursales(); 
		Id batchId = Database.executeBatch(myBatchObject);
		Test.stopTest();
    
		List<Sucursal__c> sucursalesQuery = [
			SELECT Id, Id_externo__c, Codigo__c, Empresa__r.Codigo_de_empresa__c FROM Sucursal__c WHERE Id_externo__c != null
		];

		for(Sucursal__c suc : sucursalesQuery) {
			String idExterno = suc.Empresa__r.Codigo_de_empresa__c + '-' + suc.Codigo__c;
			System.debug(suc.Id_externo__c);

			System.assertEquals(idExterno, suc.Id_externo__c);
		}
		// 2 no se actualizan porque uno no tiene codigo la sucursal y el otro no tiene codigo la empresa
		System.assertEquals(2, [SELECT count() FROM Sucursal__c WHERE Id_externo__c = null]);
		
	}

}