force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Case/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <label>CUIL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cuit_empleador__c.field-meta.xml
<CustomField>
    <fullName>Cuit_empleador__c</fullName>
    <label>Cuit empleador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Razon_social__c.field-meta.xml
<CustomField>
    <fullName>Razon_social__c</fullName>
    <label>Razón social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integrante_caso__c/Integrante_caso__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integrante_caso__c/fields/Cuit_empleador__c.field-meta.xml
<CustomField>
    <fullName>Cuit_empleador__c</fullName>
    <label>Cuit empleador</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante_caso__c/fields/Razon_Social__c.field-meta.xml
<CustomField>
    <fullName>Razon_Social__c</fullName>
    <label>Razón Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/recordTypes/Integrante.recordType-meta.xml
<RecordType>
    <fullName>Integrante</fullName>
    <active>true</active>
    <label>Integrante</label>
</RecordType>

force-app/main/default/objects/Nota_de_Auditoria__c/recordTypes/Ventas.recordType-meta.xml
<RecordType>
    <fullName>Ventas</fullName>
    <active>true</active>
    <label>Ventas</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <label>CUIT (sin guiones)</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CrearNotaDeAuditoriaControllerTest.cls
@isTest 
private class CrearNotaDeAuditoriaControllerTest {

	@isTest
	private static void whenCallingFromCaseReturnCorrectRecordType() {
		Case aCase = new Case();
		aCase.RecordTypeId = XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id;
		insert aCase;

		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(aCase.Id);
		Test.stopTest();
		RecordType serviceRecordType = [
			SELECT Id, DeveloperName, SobjectType
			FROM RecordType
			WHERE SobjectType = 'Nota_de_Auditoria__c'
				AND DeveloperName = 'Service'
		];
		System.assertEquals(false, response.hasError);
		System.assertEquals(serviceRecordType.Id, ((Id)response.data));
	}

	@isTest
	private static void whenCallingFromEMReturnCorrectRecordType() {
		Evento_medico__c em = new Evento_medico__c();
		insert em;

		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(em.Id);
		Test.stopTest();
		RecordType serviceRecordType = [
			SELECT Id, DeveloperName, SobjectType
			FROM RecordType
			WHERE SobjectType = 'Nota_de_Auditoria__c'
				AND DeveloperName = 'Service'
		];
		System.assertEquals(false, response.hasError);
		System.assertEquals(serviceRecordType.Id, ((Id)response.data));
	}

	@isTest
	private static void whenCallingFromIntegranteReturnCorrectRecordType() {
		Integrante_caso__c integrante = Build.anIntegranteCaso().build();
		integrante.Razon_Social__c = 'Test';
		integrante.Cuit_empleador__c = '20414624416';
		insert integrante;

		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(integrante.Id);
		Test.stopTest();
		RecordType integranteRecordType = [
			SELECT Id, DeveloperName, SobjectType
			FROM RecordType
			WHERE SobjectType = 'Nota_de_Auditoria__c'
				AND DeveloperName = 'Integrante'
		];
		System.assertEquals(false, response.hasError);
		System.assertEquals(integranteRecordType.Id, ((Id)response.data));
	}

	@isTest
	private static void whenCallingFromOpportunityReturnCorrectRecordType() {
		Opportunity opp = Build.anOpportunityIndividuos().build();
		insert opp;

		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(opp.Id);
		Test.stopTest();
		RecordType VentasRecordType = [
			SELECT Id, DeveloperName, SobjectType
			FROM RecordType
			WHERE SobjectType = 'Nota_de_Auditoria__c'
				AND DeveloperName = 'Ventas'
		];
		System.assertEquals(false, response.hasError);
		System.assertEquals(VentasRecordType.Id, ((Id)response.data));
	}

	@isTest
	private static void ifObjectNameIsNullReturnError() {
		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(null);
		Test.stopTest();
		System.assertEquals(true, response.hasError);
		System.assertEquals(null, ((Id)response.data));
	}

	@isTest
	private static void ifCreateNewNotaFromCaseOfTypeAltaFamiliarShouldReturnTypeOfNotaToo (){
		Account delegacion = Build.anAccountDelegacion().withCodigoDeDelegacion('868663').build();
		insert delegacion;
		
        Account entidad = Build.anAccountEmpresa().build();
        entidad.CUIT__c = '30676863822';
        entidad.Codigo_de_empresa__c = '639506';
		insert entidad;
		
        Account cuenta = build.anAccount()
									.withAfiIddelTitular(182701)
									.withType('TIT')
                                    .withCodigodeAfiliado('70332/34')
                                    .withLastName('Testing182701')
                                    .build();
        cuenta.Estado__c = 'A';
		insert cuenta;
		
        Account obraSocial = Build.anAccountObrasocial().build();
		insert obraSocial;
		
        Date fechaNacimiento = Date.newInstance(1990, 05, 01);
		Date fechaVigencia = Date.newInstance(2020, 08, 01);
		
		Case casoSolicitudAltaFamiliar = Build.aCaseSolicituddealtafamiliar()
                                .withDerivaAportes(true)
                                .withAporte(5000)
								.withBebeSinDNI(true)
								.withInformacionCompleta(false)
								.withBebeNacidoEnElSistema(true)
								.withInformacionAlAsociado('info')
								.withEstadoDeSolicitud('TRANSFORMADA')
								.withNroDeSolicitudSS('868663')
                                .withCuit('20414624416')
                                .withCuitEmpleador('20434624726')
                                .withDiscapacidad(false)
                                .withDNI('41462441')
                                .withEstadoCivil('N')
                                .withFechaDeNacimiento(fechaNacimiento)
                                .withFechaDeVigencia(fechaVigencia)
                                .withFirstName('Santiago')
                                .withLastName('Test')
                                .withNacionalidad('Argentina')
                                .withSexo('Masculino')
                                .withTipodedocumento('DNI')
                                .withTipoDeParentesco('CO')
                                .withObraSocial2(obraSocial.Id)
                                .withEmpleador(entidad.Id)
                                .withCuil('20414624416')
                                .withAccountId(cuenta.Id)
                                .withDelegacionId(delegacion.Id)
                                .build();
		insert casoSolicitudAltaFamiliar;
		Tipo_nota_de_auditoria__c typeOfNota = new Tipo_nota_de_auditoria__c(Name= 'NOTA DDJJ - SOLICITUDES');
		insert typeOfNota;

		CrearNotaDeAuditoriaController.Response response;
		Test.startTest();
		response = CrearNotaDeAuditoriaController.getRecordTypeId(casoSolicitudAltaFamiliar.Id);
		Test.stopTest();
		System.assertEquals(false, response.hasError);
		System.assertEquals(typeOfNota.Id, ((Id) response.typeOfNota));

	}
}