force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/Nota_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Nota de Auditoria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Nota de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Auditorias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/APr_Id__c.field-meta.xml
<CustomField>
    <fullName>APr_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Evento_Medico_Id__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Nota__c.field-meta.xml
<CustomField>
    <fullName>Nota__c</fullName>
    <label>Nota</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_de_Auditoria__c/fields/Tipo_nota_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Tipo_nota_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo nota de Auditoria</label>
    <referenceTo>Tipo_nota_de_auditoria__c</referenceTo>
    <relationshipLabel>Notas de Auditorias</relationshipLabel>
    <relationshipName>Notas_de_Auditorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordenes de Compras</relationshipLabel>
    <relationshipName>Ordenes_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/Tipo_nota_de_auditoria__c.object-meta.xml
<CustomObject>
    <label>Tipo nota de Auditoria</label>
    <nameField>
        <label>Nombre de Tipo nota de auditoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos notas de Auditoria</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_nota_de_auditoria__c/fields/Codigo_tipoNA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_tipoNA__c</fullName>
    <externalId>true</externalId>
    <label>Codigo tipoNA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnvioDeNotaAUserCtrl.cls
public class EnvioDeNotaAUserCtrl  {
	@AuraEnabled
	public static Response envioNota(Id ap_id){
		List<String> emails = new List<String>();

		if(ap_id == null){
			return new Response(true,'Debe tener un Caso asociado.');
		}

		Case ap = [
			SELECT Id, CreatedById, Evento_Medico__c
			FROM Case 
			WHERE Id = :ap_id
		];

		User propietario = [
			SELECT Id, Email, Codigo_delegacion__c 
			FROM User 
			WHERE Id = :ap.CreatedById
		];

		if(!String.isBlank(propietario.Email)) {
			emails.add(propietario.Email); 
		 }

		List<Account> delegacion = [
			SELECT Id, Codigo_de_delegacion__c, Correo_electronico__c 
			FROM Account 
			WHERE Codigo_de_delegacion__c = :propietario.Codigo_delegacion__c
		];

		if(!delegacion.isEmpty()){
			if (!String.isBlank(delegacion.get(0).Correo_electronico__c)){
				emails.add(delegacion.get(0).Correo_electronico__c);
			}
		}
		System.debug('****ap.Id: ' + ap.Id);
		System.debug('****ap.Evento_Medico__c: ' + ap.Evento_Medico__c);
		List<Nota_de_Auditoria__c> notas = [
			SELECT Id, Nota__c 
			FROM Nota_de_Auditoria__c 
			WHERE Tipo_nota_de_Auditoria__r.Codigo_tipoNA__c = 'NOT_COB_PROT' 
				AND (
					APr_Id__c = :ap.Id
						OR Evento_Medico_Id__c =: ap.Evento_Medico__c
				)
		];

		if(notas.isEmpty()){
			return new Response(true,'Nota de auditoria COB_PROT inexistente');
		}

		Orden_de_Compra__c orden = [
			SELECT Id, Estado_OC__c
			FROM Orden_de_Compra__c
			WHERE Caso__c = :ap_id
		];		

		EmailUtils.MailResponse resp = EmailUtils.sendMailWithTemplate(emails,orden.Id,'Sol_de_preinscripcion');

		orden.Estado_OC__c = 'Diferencia Socio';
		update orden;

		return new Response(resp.hasError,resp.message);
	}

	public class Response{
		@AuraEnabled public String message;
		@AuraEnabled public Boolean hasError;

		public Response(Boolean err,String msg){
			this.message = msg;
			this.hasError = err;
		}
	}
}