force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de cuenta</description>
    <formula>TEXT(Account.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_hora_fin_ems__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_fin_ems__c</fullName>
    <label>Fecha y hora fin EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_Hora_inicio_EMS__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_inicio_EMS__c</fullName>
    <label>Fecha y Hora inicio EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Forma_de_egreso__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_egreso__c</fullName>
    <label>Forma de egreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTA_INTERN_DOM</fullName>
                <label>ALTA CONTINUA INTERNACION DOMICILIARIA</label>
            </value>
            <value>
                <fullName>ALTA_MEDICA</fullName>
                <label>ALTA MEDICA</label>
            </value>
            <value>
                <fullName>ALTA_VOL</fullName>
                <label>ALTA VOLUNTARIA</label>
            </value>
            <value>
                <fullName>COMPRA_EQUIPO</fullName>
                <label>COMPRA EQUIPO</label>
            </value>
            <value>
                <fullName>CIERRE</fullName>
                <label>DUPLICIDAD EVENTO/EVENTO VENCIDO</label>
            </value>
            <value>
                <fullName>EMBARAZO</fullName>
            </value>
            <value>
                <fullName>ALTA_FUERA_VIG</fullName>
                <label>EVENTO DE ALTA POR FUERA DE VIGENCIA</label>
            </value>
            <value>
                <fullName>FALLECIMIENTO</fullName>
                <label>FALLECIMIENTO DEL PACIENTE</label>
            </value>
            <value>
                <fullName>FUGA</fullName>
            </value>
            <value>
                <fullName>RECH</fullName>
                <label>RECHAZO</label>
            </value>
            <value>
                <fullName>BAJA</fullName>
                <label>SOCIO BAJA</label>
            </value>
            <value>
                <fullName>EDAD_LIMITE</fullName>
                <label>SUPERA EL LIMITE DE EDAD</label>
            </value>
            <value>
                <fullName>TRASLADO</fullName>
                <label>TRASLADO A CENTRO DE MAYOR COMPLEJIDAD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto costo</fullName>
            </value>
            <value>
                <fullName>Celiaco</fullName>
            </value>
            <value>
                <fullName>Clinico</fullName>
            </value>
            <value>
                <fullName>Covid</fullName>
            </value>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Discapacidad</fullName>
            </value>
            <value>
                <fullName>Esclero</fullName>
            </value>
            <value>
                <fullName>Fertilidad</fullName>
            </value>
            <value>
                <fullName>Hepatitis</fullName>
            </value>
            <value>
                <fullName>HIV</fullName>
            </value>
            <value>
                <fullName>Leches</fullName>
            </value>
            <value>
                <fullName>Oxigenoterapia</fullName>
            </value>
            <value>
                <fullName>Programa Cronicos</fullName>
            </value>
            <value>
                <fullName>Provision Anticonceptivos</fullName>
            </value>
            <value>
                <fullName>Provision Oncologicos</fullName>
            </value>
            <value>
                <fullName>Quirurgico</fullName>
            </value>
            <value>
                <fullName>Transplante</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Anticonceptivos</fullName>
                <isActive>false</isActive>
                <label>Anticonceptivos</label>
            </value>
            <value>
                <fullName>EMS Discapacidad</fullName>
                <isActive>false</isActive>
                <label>EMS Discapacidad</label>
            </value>
            <value>
                <fullName>EMS Fertilidad</fullName>
                <isActive>false</isActive>
                <label>EMS Fertilidad</label>
            </value>
            <value>
                <fullName>EMS Oxigenoterapia</fullName>
                <isActive>false</isActive>
                <label>EMS Oxigenoterapia</label>
            </value>
            <value>
                <fullName>EMS Trasplante</fullName>
                <isActive>false</isActive>
                <label>EMS Trasplante</label>
            </value>
            <value>
                <fullName>Internacion</fullName>
                <isActive>false</isActive>
                <label>Internacion</label>
            </value>
            <value>
                <fullName>Internacion Domiciliaria</fullName>
                <isActive>false</isActive>
                <label>Internacion Domiciliaria</label>
            </value>
            <value>
                <fullName>Provision de Oncologicos</fullName>
                <isActive>false</isActive>
                <label>Provision de Oncologicos</label>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion</label>
            </value>
            <value>
                <fullName>Trastornos Alimentarios</fullName>
                <isActive>false</isActive>
                <label>Trastornos Alimentarios</label>
            </value>
            <value>
                <fullName>Tratamiento Adicciones</fullName>
                <isActive>false</isActive>
                <label>Tratamiento Adicciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En auditoria</fullName>
                <label>En auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webservice_endpoint__mdt/Webservice_endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Endpoints para las APIs de SS</description>
    <label>Webservice endpoint</label>
    <pluralLabel>Webservice endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webservice_endpoint__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Webservice_endpoint__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventoMedicoTriggerTest.cls
@IsTest
private class EventoMedicoTriggerTest {
	private static Map<String, Webservice_endpoint__mdt> endpointsEventosMedicos = ConfigUtils.getEndpointsByTipo('eventos-medicos');
	private static final String SEGUIMIENTO_URL = endpointsEventosMedicos.get('seguimiento').Endpoint__c;
	private static final String UNIQUE_USER_NAME = 'standarduseremtriggertest' + DateTime.now().getTime() + '@testorg.com';
	private static final Id EMS_ID = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
	private static List<String> profilesNamesList = new List<String>{'Back Administrativo', 'Auditor Medico'};
	private static List<Profile> profileList = [SELECT Id, Name FROM Profile WHERE Name IN :profilesNamesList];
	private static XHttpCalloutMock getResponseFound = new XHttpCalloutMock();
	private static User medico = Build.anUser()
		.withUserName(UNIQUE_USER_NAME + 'Medico')
		.build();
	private static User usuarioBack = Build.anUser()
		.withUserName(UNIQUE_USER_NAME + 'Back')
		.build();
	static {
		List<User> usersToInsert = new List<User>();
		for (Profile profileToAssign : profileList) {
			switch on profileToAssign.Name {
				when 'Back Administrativo' {
					usuarioBack.ProfileId = profileToAssign.Id;
				} when 'Auditor Medico'{
					medico.ProfileId = profileToAssign.Id;
					usersToInsert.add(medico);
				}
			}
		}
		System.runAs(new User(Id = UserInfo.getUserId())) {
			insert usersToInsert;
		}
		TestUtils.setMockResponse(getResponseFound, SEGUIMIENTO_URL, WSEventoMedicoEnviarASSMock.getFound());
	}
	/**-----------------------------------------------------------------------------------------------------------------------
		Validación del caso y el RT asociados.
	------------------------------------------------------------------------------------------------------------------------*/
		@IsTest
		static void ifAnEventoMedicoIsAuthorizedItShouldNotAuthorizeTheRelatedCaseIfTheRecordTypeIsNotSeguimientoOrInternacion() {
			Evento_medico__c em = new Evento_medico__c();
			insert em;
			Case aCase = new Case(
				RecordTypeId = XappiaHelper.getRecordType('Case','Autorizacion_previa').Id,
				Evento_Medico__c = em.Id
			);
			insert aCase;
			Test.startTest();
			em.Estado__c = 'Autorizado';
			update em;
			Test.stopTest();
			Case updatedCase = [SELECT Id, Status FROM Case WHERE Id = :aCase.Id];
			System.assertEquals('CA-----G', updatedCase.Status , 'El estado debe ser CA-----G');
		}
	/**-----------------------------------------------------------------------------------------------------------------------
		Validación de Delegaciones
	------------------------------------------------------------------------------------------------------------------------*/
		@IsTest
		static void assignDelegacionFromUserTest() {
			Account delegacion = new Account();
			delegacion.RecordTypeId = XappiaHelper.getRecordType('Account', 'Delegacion').Id;
			delegacion.Name = 'Test';
			delegacion.Codigo_de_delegacion__c = '661089';
			insert  delegacion;
			usuarioBack.Codigo_delegacion__c = delegacion.Codigo_de_delegacion__c;
			insert usuarioBack;
			User usuario2 = Build.anUser()
				.withUserName(UNIQUE_USER_NAME + 'Back2')
				.withProfile(usuarioBack.ProfileId)
				.withCodigoDelegacion(delegacion.Codigo_de_delegacion__c)
				.build();
			insert usuario2;
			List<Evento_medico__c> ems = new List<Evento_medico__c> {
				new Evento_medico__c(OwnerId = usuarioBack.Id),
				new Evento_medico__c(OwnerId = usuario2.Id),
				new Evento_medico__c(OwnerId = usuario2.Id)
			};
			Test.startTest();
			insert ems;
			Test.stopTest();
			List<Evento_medico__c> emsToAssert = [SELECT Delegacion__r.Codigo_de_delegacion__c FROM Evento_medico__c WHERE Id =: ems];
			for(Evento_medico__c emToAssert : emsToAssert) {
				System.assertEquals('661089', emToAssert.Delegacion__r.Codigo_de_delegacion__c, 'El código de delegación debe ser 661089');
			}
		}
		@IsTest
		static void ifTheDelegacionDoesNotExistInUserDoNotGiveError() {
			usuarioBack.Codigo_delegacion__c = '123456';
			insert usuarioBack;
			Evento_medico__c em = new Evento_medico__c();
			System.runAs(usuarioBack) {
				Test.startTest();
				insert em;
				Test.stopTest();
			}
			Evento_medico__c emToAssert = [SELECT Delegacion__r.Codigo_de_delegacion__c FROM Evento_medico__c WHERE Id =: em.Id];
			System.assertEquals(null, emToAssert.Delegacion__r.Codigo_de_delegacion__c, 'No debe haber un código de delegación');
		}
		@IsTest
		static void ifTheDelegacionIsNullInUserDoNotGiveError() {
			insert usuarioBack;
			Evento_medico__c em = new Evento_medico__c();
			System.runAs(usuarioBack) {
				Test.startTest();
				insert em;
				Test.stopTest();
			}
			Evento_medico__c emToAssert = [SELECT Delegacion__r.Codigo_de_delegacion__c FROM Evento_medico__c WHERE Id =: em.Id];
			System.assertEquals(null, emToAssert.Delegacion__r.Codigo_de_delegacion__c,  'No debe haber un código de delegación');
		}
	/**-----------------------------------------------------------------------------------------------------------------------
		Validación de Forma de egreso
	------------------------------------------------------------------------------------------------------------------------*/
		@IsTest
		static void tryUpdateFormaDeEgresoWithFechaFinEMLessThanOrEqual_UpdateSuccess() {
			Boolean expectedExceptionThrown;
			Evento_medico__c em = new Evento_medico__c(
				Fecha_y_Hora_inicio_EMS__c = DateTime.now().addDays(-2),
				Fecha_y_hora_fin_ems__c = DateTime.now(),
				RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id
			);
			insert em;
			Case aCase = new Case(
				Evento_Medico__c = em.Id,
				Fecha__c = Date.today().addDays(-1)
			);
			insert aCase;
			Test.startTest();
				em.Forma_de_egreso__c = 'ALTA_MEDICA';
				update em;
			Test.stopTest();
			System.assertEquals('ALTA_MEDICA', em.Forma_de_egreso__c, 'La forma de egreso debe ser ALTA MEDICA');
		}
		@IsTest
		static void tryUpdateFormaDeEgresoWithFechaFinEMGreaterThanFechaDelCaso_UpdateSuccess() {
			Boolean expectedExceptionThrown;
			Evento_medico__c em = new Evento_medico__c(
				Fecha_y_Hora_inicio_EMS__c = DateTime.now().addDays(-2),
				Fecha_y_hora_fin_ems__c = DateTime.now(),
				RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id
			);
			insert em;
			Case aCase = new Case(
				Evento_Medico__c = em.Id,
				Fecha__c = Date.today().addDays(-1)
			);
			insert aCase;
			Test.startTest();
				em.Forma_de_egreso__c = 'ALTA_MEDICA';
				update em;
			Test.stopTest();
			System.assertEquals('ALTA_MEDICA', em.Forma_de_egreso__c, 'La forma de egreso debe ser ALTA MEDICA');
		}
		@IsTest
		static void tryUpdateFormaDeEgresoWithFechaFinEMLessThanFechaDelCaso_UpdateFail() {
			String error;
			Evento_medico__c em = new Evento_medico__c(
				Fecha_y_Hora_inicio_EMS__c = DateTime.now().addDays(-2),
				Fecha_y_hora_fin_ems__c = DateTime.now().addDays(-1),
				RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id
			);
			insert em;
			Case aCase = new Case(
				Evento_Medico__c = em.Id,
				Fecha__c = Date.today()
			);
			insert aCase;
			Test.startTest();
			try{
				em.Forma_de_egreso__c = 'ALTA_MEDICA';
				update em;
			}catch(Exception e){
				error = e.getMessage();
			}
			Test.stopTest();
			Evento_medico__c eventoToAssert = [SELECT Forma_de_egreso__c FROM Evento_medico__c WHERE Id = :em.Id];
			System.assertEquals(null, eventoToAssert.Forma_de_egreso__c, 'No debe haber una forma de egreso');
			System.assert(error.contains(System.Label.Alerta_Trigger_EM_FechaCierreMenorAFechaCaso), 'El mensaje no indica el error esperado');
		}
		@IsTest
		static void tryUpdateFormaDeEgresoWithFechaFinEMEqualFechaDelCaso_UpdateEM() {
			String error;
			Evento_medico__c em = new Evento_medico__c(
				Fecha_y_Hora_inicio_EMS__c = DateTime.now().addDays(-2),
				Fecha_y_hora_fin_ems__c = DateTime.now(),
				RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id
			);
			insert em;
			Case aCase = new Case(
				Evento_Medico__c = em.Id,
				Fecha__c = Date.today()
			);
			insert aCase;
			Test.startTest();
				em.Forma_de_egreso__c = 'ALTA_MEDICA';
				update em;
			Test.stopTest();
			Evento_medico__c eventoToAssert = [SELECT Forma_de_egreso__c FROM Evento_medico__c WHERE Id = :em.Id];
			System.assertEquals('ALTA_MEDICA', eventoToAssert.Forma_de_egreso__c, 'La forma de egreso debe ser ALTA MEDICA');
		}
		@IsTest
		static void whenFormaEgresoIsChanged_SendTheEMIToSS() {
			Evento_medico__c emi = new Evento_medico__c();
			emi.RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_internacion').Id;
			emi.Nro_de_Evento_Medico_SS__c = '275751';
			insert emi;
			Test.setMock(HttpCalloutMock.class, getResponseFound);
			Test.startTest();
			emi.Forma_de_egreso__c = 'ALTA_MEDICA';
			emi.Fecha_y_hora_fin_ems__c = System.now();
			update emi;
			Test.stopTest();
			System.assertNotEquals(0, getResponseFound.callsMade, 'No deben haberse hecho ninguna llamada');
		}
		@IsTest
		static void whenFormaEgresoIsChanged_SendTheEMSToSS() {
			Evento_medico__c ems = new Evento_medico__c();
			ems.RecordTypeId = EMS_ID;
			ems.Nro_de_Evento_Medico_SS__c = '275751';
			insert ems;
			Test.setMock(HttpCalloutMock.class, getResponseFound);
			Test.startTest();
			ems.Forma_de_egreso__c = 'ALTA_MEDICA';
			ems.Fecha_y_hora_fin_ems__c = System.now();
			update ems;
			Test.stopTest();
			System.assertNotEquals(0, getResponseFound.callsMade, 'No deben haberse hecho ninguna llamada');
		}
		@IsTest
		static void whenResultadoIsChanged_SendTheEMSToSS() {
			Evento_medico__c ems = new Evento_medico__c();
			ems.RecordTypeId = EMS_ID;
			ems.Nro_de_Evento_Medico_SS__c = '275751';
			ems.Tipo__c = 'COVID';
			insert ems;
			Test.setMock(HttpCalloutMock.class, getResponseFound);
			Test.startTest();
			ems.Resultado__c = 'Positivo';
			update ems;
			Test.stopTest();
			System.assertNotEquals(0, getResponseFound.callsMade, 'No deben haberse hecho ninguna llamada');
		}
		@IsTest
		static void whenFormaEgresoIsChangedAndTheEMhasSegmentosWithoutClose_ShowErrorMsg() {
			Evento_medico__c ems = new Evento_medico__c();
			ems.RecordTypeId = EMS_ID;
			ems.Nro_de_Evento_Medico_SS__c = '275751';
			ems.Tipo__c = 'COVID';
			insert ems;
			Segmentos__c seg = new Segmentos__c();
			seg.Evento_Medico__c = ems.Id;
			insert seg;
			Test.startTest();
			ems.Forma_de_egreso__c = 'ALTA_MEDICA';
			ems.Fecha_y_hora_fin_ems__c = System.now();
			Database.SaveResult res = Database.update(ems, false);
			Test.stopTest();
			System.assert(!res.isSuccess(), 'Debe haber un error');
			System.assertEquals(System.Label.Alerta_Trigger_EM_FaltanSegmentos, res.getErrors()[0].getMessage(), 'El mensaje no indica el error');
		}
		@IsTest
		static void tryUpdateFormaDeEgresoWithFechaFinEMLessThanFechaDelCaso_UsuarioIntegracion_UpdateSuccess () {
			Evento_medico__c em = new Evento_medico__c(
				Fecha_y_Hora_inicio_EMS__c = DateTime.now().addDays(-2),
				Fecha_y_hora_fin_ems__c = DateTime.now().addDays(-1),
				RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id
			);
			insert em;
			Case aCase = new Case(
				Evento_Medico__c = em.Id,
				Fecha__c = Date.today()
			);
			insert aCase;
			List<User> integracionSSUsers = [SELECT Id FROM User WHERE isActive = true AND UserName LIKE 'dev@acasalud%'];
			User integracionSSUser = integracionSSUsers.isEmpty() ? null : integracionSSUsers[0];
			Database.SaveResult result;
			XappiaHelper.isIntegracionSSUser = null;
			System.runAs(integracionSSUser){
				em.Forma_de_egreso__c = 'ALTA_MEDICA';
				result = Database.update(em, false);
			}
			Test.startTest();
			Test.stopTest();
			System.assert(result.isSuccess(), 'No debe haber ningún error');
			Evento_medico__c eventoToAssert = [SELECT Forma_de_egreso__c FROM Evento_medico__c WHERE Id = :em.Id];
			System.assertEquals('ALTA_MEDICA', em.Forma_de_egreso__c, 'La forma de egreso debe ser ALTA MEDICA');
		}
	/**-----------------------------------------------------------------------------------------------------------------------
		Validación de Permisos de auditores.
	------------------------------------------------------------------------------------------------------------------------*/
		@IsTest
		static void whenNoUserAdminWantsDeleteAnEMShowError() {
			Database.DeleteResult result;
			Evento_medico__c em = new Evento_Medico__c();
			em.RecordTypeId = EMS_ID;
			em.OwnerId = medico.Id;
			insert em;
			System.runAs(medico) {
				result = Database.delete(em, false);
			}
			System.assert(!result.isSuccess(), 'Debe haber un error');
			System.assertEquals(System.Label.Alerta_Trigger_EM_CantDeleteEM, result.getErrors()[0].getMessage(), 'El mensaje no indica el error');
		}
		@IsTest
		static void whenDiagnosticoIsChangedAndUserIsAuditorMedicoOrLider_SendTheEMIToSS() {
			System.runAs(medico) {
				Diagnostico__c diag1 = new Diagnostico__c();
				insert diag1;
				Diagnostico__c diag2 = new Diagnostico__c();
				insert diag2;
				Evento_medico__c emi = new Evento_medico__c();
				emi.RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_internacion').Id;
				emi.Nro_de_Evento_Medico_SS__c = '275751';
				emi.Diagnostico__c = diag1.id;
				insert emi;
				Test.setMock(HttpCalloutMock.class, getResponseFound);
				Test.startTest();
				emi.Diagnostico__c = diag2.id;
				update emi;
				Test.stopTest();
				System.assertEquals(diag2.id, emi.Diagnostico__c, 'Los Ids no coinciden');
				System.assertNotEquals(0, getResponseFound.callsMade, 'No deben haberse hecho ninguna llamada');
			}
		}
		@IsTest
		static void whenDiagnosticoIsChangedAndUserIsAuditorMedicoOrLider_SendTheEMSToSS() {
			System.runAs(medico) {
				Diagnostico__c diag1 = new Diagnostico__c();
				insert diag1;
				Diagnostico__c diag2 = new Diagnostico__c();
				insert diag2;
				Evento_medico__c ems = new Evento_medico__c();
				ems.RecordTypeId = EMS_ID;
				ems.Nro_de_Evento_Medico_SS__c = '275751';
				ems.Diagnostico__c = diag1.id;
				insert ems;
				Test.setMock(HttpCalloutMock.class, getResponseFound);
				Test.startTest();
				ems.Diagnostico__c = diag2.id;
				update ems;
				Test.stopTest();
				System.assertEquals(diag2.id, ems.Diagnostico__c, 'Los Ids no coinciden');
				System.assertNotEquals(0, getResponseFound.callsMade, 'No deben haberse hecho ninguna llamada');
			}
		}
}