force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/Consultorio__c.object-meta.xml
<CustomObject>
    <label>Consultorio</label>
    <nameField>
        <label>Nombre de Consultorio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultorio__c/fields/Secuencia__c.field-meta.xml
<CustomField>
    <fullName>Secuencia__c</fullName>
    <label>Secuencia</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico__c/fields/Codigo_del_Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_Diagnostico__c</fullName>
    <externalId>true</externalId>
    <label>Código del Diagnóstico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/AP_presupuesto__c.field-meta.xml
<CustomField>
    <fullName>AP_presupuesto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AP presupuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Asociado__c.field-meta.xml
<CustomField>
    <fullName>Asociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asociado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <filterItems>
            <field>Account.Codigo_de_Afiliado__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Asociado)</relationshipLabel>
    <relationshipName>Eventos_Medicos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <label>Código de Afiliado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Consultorio__c.field-meta.xml
<CustomField>
    <fullName>Consultorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultorio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Consultorio__c.Efector_Prestador__c</field>
            <operation>equals</operation>
            <valueField>$Source.Prestador__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Consultorio__c</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Efector_Solicitante__c.field-meta.xml
<CustomField>
    <fullName>Efector_Solicitante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector Solicitante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Efector Solicitante)</relationshipLabel>
    <relationshipName>Eventos_Medicos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_Hora_inicio_EMS__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_inicio_EMS__c</fullName>
    <label>Fecha y Hora inicio EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Importe_presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Importe_presupuesto__c</fullName>
    <label>Importe Presupuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Sin_complicaciones__c.field-meta.xml
<CustomField>
    <fullName>Sin_complicaciones__c</fullName>
    <label>Sin complicaciones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Sin complicaciones</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Con complicaciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto costo</fullName>
            </value>
            <value>
                <fullName>Celiaco</fullName>
            </value>
            <value>
                <fullName>Clinico</fullName>
            </value>
            <value>
                <fullName>Covid</fullName>
            </value>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Discapacidad</fullName>
            </value>
            <value>
                <fullName>Esclero</fullName>
            </value>
            <value>
                <fullName>Fertilidad</fullName>
            </value>
            <value>
                <fullName>Hepatitis</fullName>
            </value>
            <value>
                <fullName>HIV</fullName>
            </value>
            <value>
                <fullName>Leches</fullName>
            </value>
            <value>
                <fullName>Oxigenoterapia</fullName>
            </value>
            <value>
                <fullName>Programa Cronicos</fullName>
            </value>
            <value>
                <fullName>Provision Anticonceptivos</fullName>
            </value>
            <value>
                <fullName>Provision Oncologicos</fullName>
            </value>
            <value>
                <fullName>Quirurgico</fullName>
            </value>
            <value>
                <fullName>Transplante</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Anticonceptivos</fullName>
                <isActive>false</isActive>
                <label>Anticonceptivos</label>
            </value>
            <value>
                <fullName>EMS Discapacidad</fullName>
                <isActive>false</isActive>
                <label>EMS Discapacidad</label>
            </value>
            <value>
                <fullName>EMS Fertilidad</fullName>
                <isActive>false</isActive>
                <label>EMS Fertilidad</label>
            </value>
            <value>
                <fullName>EMS Oxigenoterapia</fullName>
                <isActive>false</isActive>
                <label>EMS Oxigenoterapia</label>
            </value>
            <value>
                <fullName>EMS Trasplante</fullName>
                <isActive>false</isActive>
                <label>EMS Trasplante</label>
            </value>
            <value>
                <fullName>Internacion</fullName>
                <isActive>false</isActive>
                <label>Internacion</label>
            </value>
            <value>
                <fullName>Internacion Domiciliaria</fullName>
                <isActive>false</isActive>
                <label>Internacion Domiciliaria</label>
            </value>
            <value>
                <fullName>Provision de Oncologicos</fullName>
                <isActive>false</isActive>
                <label>Provision de Oncologicos</label>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion</label>
            </value>
            <value>
                <fullName>Trastornos Alimentarios</fullName>
                <isActive>false</isActive>
                <label>Trastornos Alimentarios</label>
            </value>
            <value>
                <fullName>Tratamiento Adicciones</fullName>
                <isActive>false</isActive>
                <label>Tratamiento Adicciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/Nomenclador_de_Prestacion__c.object-meta.xml
<CustomObject>
    <label>Nomenclador de Prestación</label>
    <nameField>
        <label>Código Nomenclador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomenclador de Prestaciónes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>36000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>36000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventoMedicoEnviarASSParser.cls
/**-----------------------------------------------------------------------------------------------------------------------
@author			Jeferson Ruiz.
@description	Clase deserializadora para las solicitudes de llamados a SS para Eventos Médicos.
@date			06/12/2021
------------------------------------------------------------------------------------------------------------------------*/
@SuppressWarnings('PMD.ExcessiveParameterList')
public with sharing class EventoMedicoEnviarASSParser {
	public Evento_medico__c eventoMedico {get; set;}
	public String userNick {get; set;}
	private String rTSeguimientoID = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
	private String rTInternacionID = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_internacion').Id;
	public EventoMedicoEnviarASSParser(Evento_medico__c eventoMedico, String userNick) {
		this.eventoMedico = eventoMedico;
		this.userNick = userNick;
	}
	public class EventoMedicoASS {
		public String em_id {get; set;}
		public String codigo_afiliado {get; set;}
		public String agencia_codigo {get; set;}
		public String fecha_inicio {get; set;}
		public String codigo_lugar {get; set;}
		public Integer consultorio {get; set;}
		public String responsable {get; set;}
		public String solicitante {get; set;}
		public String tipo_em {get; set;}
		public String subtipo_em {get; set;}
		public String recupero {get; set;}
		public String anestesia {get; set;}
		public String codigo_diagnostico {get; set;}
		public Integer nivel_complicacion {get; set;}
		public String codigo_prestacion {get; set;}
		public String descripcion {get; set;}
		public String observaciones {get; set;}
		public String suspendido {get; set;}
		public String usuario {get; set;}
		public String numero_sf {get; set;}
		public String chk_material {get; set;}
		public String chk_presupuesto {get; set;}
		public String importe_presupuesto {get; set;}
		public String forma_egreso {get; set;}
		public String fecha_vto_certificado {get; set;}
		public String mail {get; set;}
		public String dom_entrega {get; set;}
		public String agen_entrega {get; set;}
		public String otro_entrega {get; set;}
		public String resul {get; set;}
		public String via_entrega {get; set;}
	}
	/**-----------------------------------------------------------------------------------------------------------------------
	@author			Jeferson Ruiz
	@company		Xappia
	@description	Método para entregar el body de la solicitud a la API para un evento médico.
	------------------------------------------------------------------------------------------------------------------------*/
	public String parseCargarEventoMedicoSS () {
		EventoMedicoASS solicitud = new EventoMedicoASS();
		try {
			Integer consultorio = this.eventoMedico.Consultorio__r.Secuencia__c != null ? Integer.valueOf(this.eventoMedico.Consultorio__r.Secuencia__c) : null;
			Integer complicaciones = this.eventoMedico.Sin_complicaciones__c != null ? Integer.valueOf(this.eventoMedico.Sin_complicaciones__c) : null;
			// Construcción de la solicitud
			solicitud.usuario = this.userNick;
			solicitud.numero_sf = this.eventoMedico.Id;
			solicitud.consultorio = consultorio;
			solicitud.nivel_complicacion = complicaciones;
			solicitud.em_id = this.eventoMedico.Nro_de_Evento_Medico_SS__c;
			solicitud.codigo_afiliado = this.eventoMedico.Asociado__r.Codigo_de_Afiliado__c;
			solicitud.fecha_inicio = this.eventoMedico.Fecha_y_Hora_inicio_EMS__c == null
										? null : this.eventoMedico.Fecha_y_Hora_inicio_EMS__c.format('dd/MM/yyyy');
			solicitud.tipo_em = this.eventoMedico.Tipo__c != null ? this.eventoMedico.Tipo__c.toUpperCase() : null;
			solicitud.codigo_diagnostico = this.eventoMedico.Diagnostico__r.Codigo_del_Diagnostico__c;
			solicitud.descripcion = this.eventoMedico.Descripcion__c;
			solicitud.observaciones = this.eventoMedico.Observaciones__c;
			solicitud.chk_presupuesto = this.eventoMedico.AP_presupuesto__c ? 'V' : 'F';
			solicitud.importe_presupuesto = this.eventoMedico.AP_presupuesto__c ? String.valueOf(this.eventoMedico.Importe_presupuesto__c) : '0';
			solicitud.agencia_codigo = this.eventoMedico.Delegacion__r.Codigo_de_delegacion__c;
			solicitud.solicitante = this.eventoMedico.Efector_Solicitante__r.Codigo_de_efector__c;
			solicitud.forma_egreso = this.eventoMedico.Forma_de_egreso__c;
			solicitud.codigo_lugar = this.eventoMedico.Prestador__r.Codigo_de_efector__c;
			if (this.eventoMedico.RecordTypeId == rTSeguimientoID) {
				solicitud.fecha_vto_certificado = this.eventoMedico.Fecha_de_Vencimiento_Certificado__c == null
				? null : this.eventoMedico.Fecha_de_Vencimiento_Certificado__c.format();
				solicitud.mail = this.eventoMedico.Mail__c;
				solicitud.dom_entrega = this.eventoMedico.Domicilio_Entrega__c;
				solicitud.agen_entrega = this.eventoMedico.Domicilio_Entrega__c == 'Agencia'
											? this.eventoMedico.Domicilio__c : null;
				solicitud.otro_entrega = this.eventoMedico.Domicilio_Entrega__c == 'Otros'
											? this.eventoMedico.Otro_domicilio__c : null;
				solicitud.via_entrega = this.eventoMedico.Via_Entrega__c;
				solicitud.resul = this.eventoMedico.Resultado__c;
			} else if (this.eventoMedico.RecordTypeId == rTInternacionID) {
				solicitud.responsable = this.eventoMedico.Responsable__r.Codigo_de_efector__c;
				solicitud.subtipo_em = this.eventoMedico.Subtipo__c != null ? this.eventoMedico.Subtipo__c.toUpperCase() : null;
				solicitud.recupero = this.eventoMedico.Recupero__c == 'V' ? 'V' : 'F';
				solicitud.anestesia = this.eventoMedico.Ap_Anestesia__c == 'V' ? 'S' : 'N';
				solicitud.codigo_prestacion = this.eventoMedico.Codigo_Nomenclador__r.Codigo__c;
				solicitud.suspendido = this.eventoMedico.Suspendido__c == 'Si' ? 'V' : 'F';
				solicitud.chk_material = this.eventoMedico.AP_material__c ? 'V' : 'F';
			}
		} catch (Exception err) {
			System.debug(err.getMessage());
		}
		return JSON.serialize(solicitud, true);
	}
}