force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_hora_fin_ems__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_fin_ems__c</fullName>
    <label>Fecha y hora fin EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Forma_de_egreso__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_egreso__c</fullName>
    <label>Forma de egreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTA_INTERN_DOM</fullName>
                <label>ALTA CONTINUA INTERNACION DOMICILIARIA</label>
            </value>
            <value>
                <fullName>ALTA_MEDICA</fullName>
                <label>ALTA MEDICA</label>
            </value>
            <value>
                <fullName>ALTA_VOL</fullName>
                <label>ALTA VOLUNTARIA</label>
            </value>
            <value>
                <fullName>COMPRA_EQUIPO</fullName>
                <label>COMPRA EQUIPO</label>
            </value>
            <value>
                <fullName>CIERRE</fullName>
                <label>DUPLICIDAD EVENTO/EVENTO VENCIDO</label>
            </value>
            <value>
                <fullName>EMBARAZO</fullName>
            </value>
            <value>
                <fullName>ALTA_FUERA_VIG</fullName>
                <label>EVENTO DE ALTA POR FUERA DE VIGENCIA</label>
            </value>
            <value>
                <fullName>FALLECIMIENTO</fullName>
                <label>FALLECIMIENTO DEL PACIENTE</label>
            </value>
            <value>
                <fullName>FUGA</fullName>
            </value>
            <value>
                <fullName>RECH</fullName>
                <label>RECHAZO</label>
            </value>
            <value>
                <fullName>BAJA</fullName>
                <label>SOCIO BAJA</label>
            </value>
            <value>
                <fullName>EDAD_LIMITE</fullName>
                <label>SUPERA EL LIMITE DE EDAD</label>
            </value>
            <value>
                <fullName>TRASLADO</fullName>
                <label>TRASLADO A CENTRO DE MAYOR COMPLEJIDAD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Efector_solicitante__c.field-meta.xml
<CustomField>
    <fullName>Efector_solicitante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector solicitante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En auditoria</fullName>
                <label>En auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_real__c</fullName>
    <label>Fecha Fin real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Inicio_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_real__c</fullName>
    <label>Fecha Inicio real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventoMedicoTriggerHelper.cls
public without sharing class EventoMedicoTriggerHelper {
	public static String rTSeguimientoID = XappiaHelper.getRecordType('Evento_Medico__c', 'Evento_medico_de_seguimiento').Id;
	public static String rtInternacionID = XappiaHelper.getRecordType('Evento_Medico__c', 'Evento_medico_de_internacion').Id;
	public static void validateFormaDeEgreso(Map<Id, Evento_medico__c> newMap, Map<Id, Evento_medico__c> oldMap) {
		List<Evento_medico__c> eventos = [SELECT Id, Fecha_y_hora_fin_ems__c, RecordTypeId, Forma_de_egreso__c,
											(SELECT Id, Fecha__c FROM Casos__r WHERE Status != 'CA-----N'),
											(SELECT Id, Estado__c FROM Segmentos__r WHERE Fecha_Inicio_real__c = null OR Fecha_Fin_real__c = null)
										FROM Evento_medico__c
										WHERE Id IN :newMap.keySet()];
        for (Evento_medico__c em : eventos) {
			Evento_medico__c oldEm = oldMap.get(em.Id);
            if(newMap.get(em.Id).Forma_de_egreso__c != oldEm.Forma_de_egreso__c) {
				if(newMap.get(em.Id).Forma_de_egreso__c != null && !em.Segmentos__r.isEmpty()) {
					newMap.get(em.Id).Forma_de_egreso__c.addError(System.Label.Alerta_Trigger_EM_FaltanSegmentos);
				}
				if (em.RecordTypeId == rTSeguimientoID) {
					for (Case caso : em.Casos__r) {
						if (em.Fecha_y_hora_fin_ems__c.date() < caso.Fecha__c) {
							newMap.get(em.Id).Forma_de_egreso__c.addError(System.Label.Alerta_Trigger_EM_FechaCierreMenorAFechaCaso);
						}
					}
				}
            }
        }
	}
	public static void assignDelegacionFromUser(Map<Id, List<Evento_medico__c>> userIdEMsMap) {
		List<Evento_medico__c> emToUpdateList = new List<Evento_medico__c>();
        Map<String, List<Evento_medico__c>> codDelegacionEMsMap = new Map<String, List<Evento_medico__c>>();
        for (User usuario : [SELECT Codigo_delegacion__c
							FROM User
							WHERE Id IN :userIdEMsMap.keySet()]) {
            if (usuario.Codigo_delegacion__c != null) {
                List<Evento_medico__c> emsFromUserMap = userIdEMsMap.get(usuario.Id);
                if (codDelegacionEMsMap.containsKey(usuario.Codigo_delegacion__c)) {
                    List<Evento_medico__c> emsFromDelegacionMap = codDelegacionEMsMap.get(usuario.Codigo_delegacion__c);
                    emsFromDelegacionMap.addAll(emsFromUserMap);
                    codDelegacionEMsMap.put(usuario.Codigo_delegacion__c, emsFromDelegacionMap);
                } else {
                    codDelegacionEMsMap.put(usuario.Codigo_delegacion__c, emsFromUserMap);
                }
            }
        }
        for(Account delegacion : [SELECT Id, Codigo_de_delegacion__c
									FROM Account
									WHERE Codigo_de_delegacion__c IN :codDelegacionEMsMap.keySet()]) {
            for (Evento_medico__c em : codDelegacionEMsMap.get(delegacion.Codigo_de_delegacion__c)) {
                em.Delegacion__c = delegacion.Id;
                emToUpdateList.add(em);
            }
        }
        if (!emToUpdateList.isEmpty()) {
			update emToUpdateList;
        }
    }
	@future(callout = true)
	public static void sendToSS(Id[] emIds) {
		Id rtSeguimiento = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
		Id rtInternacion = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_internacion').Id;
		Evento_medico__c[] eventos = EventoMedicoEnviarASSBtnCtrl.getEventosMedicos(emIds);
		User usuario = [SELECT CommunityNickname, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
		if(String.isNotBlank(usuario.CommunityNickname)) {
			String nick = usuario.CommunityNickname.toUpperCase();
			for(Evento_medico__c em : eventos) {
				EventoMedicoEnviarASSParser parser = new EventoMedicoEnviarASSParser(em, nick);
				String body = parser.parseCargarEventoMedicoSS();
				if (em.RecordTypeId == rTSeguimientoID) {
					WSEventoMedicoEnviarASSHelper.enviarEventoMedico(body, 'eventos-medicos', 'seguimiento');
				} else if (em.RecordTypeId == rTInternacionID) {
					WSEventoMedicoEnviarASSHelper.enviarEventoMedico(body, 'eventos-medicos', 'eventos-medicos');
				}
			}
		}
	}
	public static void validateDeletion(Map<Id, Evento_medico__c> oldMap) {
		User currentUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
		Boolean isAdmin = currentUser.Profile.Name == 'Administrador del sistema' || currentUser.Profile.Name == 'System Administrator';
		for (Evento_medico__c em : oldMap.values()) {
			if(!isAdmin) {
				em.addError(System.Label.Alerta_Trigger_EM_CantDeleteEM);
			}
		}
	}
}