force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <defaultValue>&quot;Masculino&quot;</defaultValue>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Asignaciones de cláusulas temporarias</relationshipLabel>
    <relationshipName>Asignaciones_de_clausulas_temporarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico__c/fields/Codigo_del_Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_Diagnostico__c</fullName>
    <externalId>true</externalId>
    <label>Código del Diagnóstico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Clausulas_Temporales__c.field-meta.xml
<CustomField>
    <fullName>Clausulas_Temporales__c</fullName>
    <label>Clausulas Temporales</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Monodroga__c/Monodroga__c.object-meta.xml
<CustomObject>
    <label>Monodroga</label>
    <nameField>
        <label>Nro. de Monodroga</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monodrogas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClausulasTempProcessorTest.cls
@isTest 
private class ClausulasTempProcessorTest {

	static MasterConfigs__c config;
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getErrorResponse; 
	static XHttpCalloutMock getEmptyListResponse;
	static XHttpCalloutMock getResponseFoundSecondPageOnly;
	static Account asociado;
	static Account asociado2;
	static Account asociado3;
	static Account asociado4;
	static Diagnostico__c diagnostico;

	static {
		asociado = Build.anAccountCuentapersonal().build();
		asociado.Sexo__c = 'F';
		asociado.Codigo_de_Afiliado__c = '51692/10';
		insert asociado;

		asociado2 = Build.anAccountCuentapersonal().build();
		asociado2.Sexo__c = 'F';
		asociado2.Codigo_de_Afiliado__c = '51773/14';
		insert asociado2;

		diagnostico = new Diagnostico__c();
		diagnostico.Codigo_del_Diagnostico__c = 'Z34';
		insert diagnostico;

		String today = System.now().addDays(-90).format('yyyy-MM-dd').substringBefore(' ');

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchClausulasTempMock.getFound())
			.addForAddress(WSBatchClausulasTemp.SERVICE_CONFIG.URL__c + '/v1/salud/batch/clausulas-temporarias/' + today + '?pageSize=15&page=1');	
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchClausulasTempMock.getFoundSecondPage())
			.addForAddress(WSBatchClausulasTemp.SERVICE_CONFIG.URL__c + '/v1/salud/batch/clausulas-temporarias/' + today + '?pageSize=15&page=2');

		getResponseFoundSecondPageOnly = new XHttpCalloutMock();
		getResponseFoundSecondPageOnly.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundSecondPageOnly.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchClausulasTempMock.getFoundSecondPage())
			.addForAddress(WSBatchClausulasTemp.SERVICE_CONFIG.URL__c + '/v1/salud/batch/clausulas-temporarias/' + today + '?pageSize=15&page=2');
		
		config = Build.aMasterConfigs().build();
		insert config;
	}

	@isTest static void externalsClausulasTempCanBeProcessed() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPageOnly);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new ClausulasTempProcessor(15, 2, 2, System.now())));
		Test.stopTest();
		
		System.assertEquals(2, [SELECT Count() FROM Asignacion_de_clausula_temporaria__c]);

	}

	@isTest static void aSecondBatchOfClausulasTempCanBeCalled() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);
        
		Test.startTest();
		Database.executeBatch(new MasterBatch(new ClausulasTempProcessor(15, System.now())));
		Test.stopTest();
		
		System.assertEquals(4, [SELECT Count() FROM Asignacion_de_clausula_temporaria__c]);
		//System.assertEquals(4, [SELECT Count() FROM Monodroga__c]);

	}

	@isTest static void atTheLastBatchTheLastUpdatedDateIsUpdated() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPageOnly);

		Datetime now = System.now();

		Datetime yesterday = Datetime.now().addDays(-1);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new ClausulasTempProcessor(15, 2, 2, now)));
		Test.stopTest();

		System.debug(MasterConfigs__c.getOrgDefaults().Clausulas_Temporales__c);

		System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Clausulas_Temporales__c);
	}
}