force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Asociado__c.field-meta.xml
<CustomField>
    <fullName>Asociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asociado</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asignaciones de cláusulas temporarias</relationshipLabel>
    <relationshipName>Asignaciones_de_clausulas_temporarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para determinar si el registro llega del batch</description>
    <label>Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/codigo_ACT_SS__c.field-meta.xml
<CustomField>
    <fullName>codigo_ACT_SS__c</fullName>
    <externalId>true</externalId>
    <label>codigo ACT SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Asignaciones de cláusulas temporarias</relationshipLabel>
    <relationshipName>Asignaciones_de_clausulas_temporarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_vigencia_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_vigencia_hasta__c</fullName>
    <label>Fecha de vigencia hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_FUM__c.field-meta.xml
<CustomField>
    <fullName>Fecha_FUM__c</fullName>
    <label>Fecha FUM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/FPP__c.field-meta.xml
<CustomField>
    <fullName>FPP__c</fullName>
    <label>FPP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMI_MADRE</fullName>
                <default>true</default>
                <label>PMI Madre</label>
            </value>
            <value>
                <fullName>PMI_HIJO</fullName>
                <label>PMI Hijo</label>
            </value>
            <value>
                <fullName>COB EMER</fullName>
            </value>
            <value>
                <fullName>COB ADIC IDM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico__c/fields/Codigo_del_Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_Diagnostico__c</fullName>
    <externalId>true</externalId>
    <label>Código del Diagnóstico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Clausulas_Temporales__c.field-meta.xml
<CustomField>
    <fullName>Clausulas_Temporales__c</fullName>
    <label>Clausulas Temporales</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ClausulasTempProcessor.cls
public class ClausulasTempProcessor implements IMasterBuilder  {
	
	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForACT;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public ClausulasTempProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public ClausulasTempProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForACT) {
		this(pageSize, 1, 1, runTime, lastUpdateForACT);
	}

	public ClausulasTempProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public ClausulasTempProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForACT) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForACT = lastUpdateForACT;
	}

	public List<WSBatchClausulasTempResp.Data> callWebService() {
		List<WSBatchClausulasTempResp.Data> wsData = new List<WSBatchClausulasTempResp.Data>();
		WSBatchClausulasTemp.Response resp;

		if (currentPage <= lastPage) {
			String fecha = runTime.addDays(-90).format('yyyy-MM-dd');
			resp = WSBatchClausulasTemp.getBatchClausulasTemp(fecha, this.pageSize, this.currentPage);
		}

		if(!resp.hasError) {
			hasNext = resp.result.links.next != null;
			currentPage = resp.result.meta.current_page + 1;
			lastPage = resp.result.meta.last_page;
			wsData.addAll(resp.result.data);
		} else {
			this.errorWs = true;
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Asignacion_de_clausula_temporaria__c> actList = new List<Asignacion_de_clausula_temporaria__c>();
		List<String> externalIds = new List<String>();

		for(Object resp : wsResponses) {
			WSBatchClausulasTempResp.Data actWs = (WSBatchClausulasTempResp.Data) resp;
			Asignacion_de_clausula_temporaria__c act = new Asignacion_de_clausula_temporaria__c();
            
			act.codigo_ACT_SS__c = actWs.acta_id;
			act.Batch__c = true;
			act.Tipo__c = actWs.tacta_codigo;
			act.Descripcion__c = actWs.observaciones;
			act.Fecha_desde__c = actWs.fecha_vigencia_desde != null ? Date.valueOf(actWs.fecha_vigencia_desde) : null;
			act.Fecha_de_vigencia_hasta__c = actWs.fecha_vigencia_hasta != null 
												? Date.valueOf(actWs.fecha_vigencia_hasta) : null;
			act.Fecha_FUM__c = actWs.fecha_fum != null ? Date.valueOf(actWs.fecha_fum) : null;
			act.FPP__c = actWs.fecha_pp != null ? Date.valueOf(actWs.fecha_pp) : null;
			
			if(String.isNotBlank(actWs.diag_codigo)) {
				act.Diagnostico__r = new Diagnostico__c(Codigo_del_Diagnostico__c = actWs.diag_codigo);
			}
			if(String.isNotBlank(actWs.codigo)) {
				act.Asociado__r = new Account(Codigo_de_Afiliado__c = actWs.codigo);
			}
				
			actList.add(act);
			externalIds.add(actWs.acta_id);
		}

		Database.UpsertResult[] results = Database.upsert(
			actList, Asignacion_de_clausula_temporaria__c.codigo_ACT_SS__c, false
		);
		System.debug('****results* ' + results);
		//EmailUtils.sendErrorMail(results, null, null, externalIds, 'Clausulas Temporarias ' + (currentPage - 1) + ' pagina');

		Utils.insertBatchLogs(results, null, null, externalIds, 'Clausulas Temporarias');

	}

	public void updateDate() {

		if (!hasNext) {
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Clausulas_Temporales__c = lastUpdateForACT;
				upsert lastUpdate;
			}
		} else {
			ClausulasTempProcessor nextProcessor = new ClausulasTempProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}
}