force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <defaultValue>&quot;Masculino&quot;</defaultValue>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/Asignacion_de_clausula_temporaria__c.object-meta.xml
<CustomObject>
    <label>Asignacion de clausula temporaria</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Asignacion de clausula tempora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asignaciones de clauslas temporarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Asociado__c.field-meta.xml
<CustomField>
    <fullName>Asociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asociado</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Cuenta personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asignaciones de cláusulas temporarias</relationshipLabel>
    <relationshipName>Asignaciones_de_clausulas_temporarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/codigo_ACT_SS__c.field-meta.xml
<CustomField>
    <fullName>codigo_ACT_SS__c</fullName>
    <externalId>true</externalId>
    <label>codigo ACT SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/Fecha_FUM__c.field-meta.xml
<CustomField>
    <fullName>Fecha_FUM__c</fullName>
    <label>Fecha FUM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asignacion_de_clausula_temporaria__c/fields/FPP__c.field-meta.xml
<CustomField>
    <fullName>FPP__c</fullName>
    <label>FPP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClausulaTempReintentoEnvioASSBatchTest.cls
@isTest
private class ClausulaTempReintentoEnvioASSBatchTest {
    static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseError;
	static Asignacion_de_clausula_temporaria__c clausula;

	static {
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSClausulaTempEnviarASSMock.getFound())
			.addForAddress(WSClausulaTempEnviarASS.SERVICE_CONFIG.URL__c + '/v1/salud/clausulas-temporarias/pmi');
		getResponseError = new XHttpCalloutMock();
		getResponseError.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseError.buildResponse()
			.withStatus('Error')
			.withStatusCode(422)
			.withBody(WSClausulaTempEnviarASSMock.getError())
			.addForAddress(WSClausulaTempEnviarASS.SERVICE_CONFIG.URL__c + '/v1/salud/clausulas-temporarias/pmi');


		
	}

	@TestSetup
	private static void setup(){
        Test.setMock(HttpCalloutMock.class, getResponseError);
        Date today = Date.today();
        Date tomorrow = Date.today().addDays(1);
        Date yesterday = Date.Today().addDays(-1);
		Date fpp = Date.Today().addDays(-2);
        Account acc = Build.anAccount().withLastName('AccountTest').build();
        acc.Codigo_de_Afiliado__c = '123';
        acc.Sexo__c = 'F';
		insert acc;
		
		clausula = new Asignacion_de_clausula_temporaria__c(
            Fecha_desde__c = today,
            Asociado__c = acc.Id,
			Fecha_FUM__c = yesterday,
			FPP__c = fpp
        );
	
		Test.startTest();
        insert clausula;
		Test.stopTest();
	}

	@isTest
	private static void whenAClausulaIsCreatedWithValidFields_ItShouldSendToSSAndFillTheCorrespondingFields() {
	
		clausula = [SELECT codigo_ACT_SS__c, Fecha_de_fallo__c, Fallo_en_SS__c FROM Asignacion_de_clausula_temporaria__c LIMIT 1];

		System.assertEquals(null, clausula.codigo_ACT_SS__c);
		System.assertNotEquals(null,clausula.Fecha_de_fallo__c);
		System.assertNotEquals(null,clausula.Fallo_en_SS__c);
		
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		
		Database.executeBatch(new ClausulaTempReintentoEnvioASSBatch());
		
		Test.stopTest();


		clausula = [SELECT codigo_ACT_SS__c, Fecha_de_fallo__c, Fallo_en_SS__c FROM Asignacion_de_clausula_temporaria__c WHERE Id = :clausula.Id];

		System.assertEquals('47518', clausula.codigo_ACT_SS__c);
		System.assertEquals(null,clausula.Fecha_de_fallo__c);
		System.assertEquals(null,clausula.Fallo_en_SS__c);

	}
}