force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ap_autorizada__c.field-meta.xml
<CustomField>
    <fullName>Ap_autorizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se utiliza para marcar con un trigger cuando todas las alertas de todas las prestaciones se resuelven o no tienen alertas</description>
    <label>Ap autorizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Celula__c.field-meta.xml
<CustomField>
    <fullName>Celula__c</fullName>
    <label>Célula</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celula 1</fullName>
                <label>Emi sin material</label>
            </value>
            <value>
                <fullName>Celula 2</fullName>
                <label>Trámites con material</label>
            </value>
            <value>
                <fullName>Celula 3</fullName>
                <label>Oxigenoterapia</label>
            </value>
            <value>
                <fullName>Celula 4</fullName>
                <label>Fertilidad</label>
            </value>
            <value>
                <fullName>Celula 5</fullName>
                <label>Célula 5</label>
            </value>
            <value>
                <fullName>Celula 6</fullName>
                <label>Programas</label>
            </value>
            <value>
                <fullName>Celula 7</fullName>
                <label>Medicación alto costo</label>
            </value>
            <value>
                <fullName>Celula 8</fullName>
                <label>Reintegros</label>
            </value>
            <value>
                <fullName>Celula 9</fullName>
                <label>Discapacidad</label>
            </value>
            <value>
                <fullName>Celula 10</fullName>
                <label>Célula 10</label>
            </value>
            <value>
                <fullName>Celula 11</fullName>
                <label>Falseamiento de DDJJ</label>
            </value>
            <value>
                <fullName>Celula 12</fullName>
                <label>IDOM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Cambio_Manual__c.field-meta.xml
<CustomField>
    <fullName>Cambio_Manual__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Cambio Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <formula>Codigo_Nomenclador__r.Prestacion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prestación</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORÍA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion_CA__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_CA__c</fullName>
    <externalId>true</externalId>
    <label>Prestacion CA</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseAutorizarAPRechazadaBtnCtrl.cls
public without Sharing class CaseAutorizarAPRechazadaBtnCtrl  {
	
	@AuraEnabled
	public static Response autorizarAPRechazada(String caseId) {
		List<Case> casos = [
			SELECT Status, Nivel_de_derivacion__c, OwnerId, Nro_AP__c, Delegacion__r.Codigo_de_delegacion__c,
				Caso_Rechazado__c, Celula__c,
					(SELECT Id, Prestacion_CA__c FROM Prestaciones__r)
			FROM Case 
			WHERE Id =: caseId
		];
		User usuario = [
			SELECT CommunityNickname, Profile.Name, UserRole.DeveloperName, Codigo_delegacion__c 
			FROM User 
			WHERE Id =: UserInfo.getUserId()
		];
		
		Response validation = validatePermissions(usuario, casos);
		if(validation.message != 'ok') {
			return validation;
		}

		String body = JSON.serialize(new Map<String, Object> {'usuario' => usuario.CommunityNickname.toUpperCase()});

		WSCaseAutorizarAPRechazada.Response resp = WSCaseAutorizarAPRechazada.autorizarApRechazada(casos[0].Nro_AP__c, body);
		
		if (!resp.hasError) {
			updateAPPrestsAndAlerts(resp.result.data.ap, casos[0]);
			return new Response(false, 'ok');
		}
		return new Response(true, resp.message);
		 
	}

	private static void updateAPPrestsAndAlerts(WSCaseAutorizarAPRechazadaResp.Ap apWS, Case caso) {
		List<Prestacion__c> prestacionesToUpdate = new List<Prestacion__c>();
		List<Alerta__c> alertasToUpsert = new List<Alerta__c>();
		
		caso.Cambio_Manual__c = false;
		//caso.Status = 'Autorizada';
		//caso.Ap_autorizada__c = true;
		caso.Caso_Rechazado__c = false;

		for(WSCaseAutorizarAPRechazadaResp.Prestaciones presWS: apWS.prestaciones) {
			for(Prestacion__c pres : caso.Prestaciones__r) {
				
				if(pres.Prestacion_CA__c == presWS.pca_id) {
					pres.Estado__c = presWS.estado_prestacion;

					prestacionesToUpdate.add(pres);

					for(WSCaseAutorizarAPRechazadaResp.Alertas alertWS : presWS.alertas) {
						Alerta__c alerta = new Alerta__c();
	//--------------------------------------------------------------------------------------
						alerta.Prestacion__c = pres.Id;
						//alerta.Evento_Medico__c = emFromSF.Id;
						alerta.idalerta__c = alertWs.aca_id;
						alerta.Control__c = alertWs.control;
						alerta.Funcion__c = alertWs.funcion;
						alerta.Texto_aclarativo__c = alertWs.texto_aclarativo;
						alerta.Nivel_de_auditoria__c = alertWs.nivel_auditoria != null
								? Integer.valueOf(alertWs.nivel_auditoria) : null;
						alerta.Fecha_de_generacion_de_Alerta__c = alertWs.fecha_generacion != null ?
								Date.valueOf(alertWs.fecha_generacion.substringBefore(' ')) :
								null;
						alerta.Lectura_de_alerta_auditor__c = alertWs.auditor_lee;
						alerta.Resolucion_de_alerta_auditor__c = alertWs.auditor_resuelve;
						alerta.Fecha_resolucion_de_Alerta__c = alertWs.fecha_resolucion != null
								? Date.valueOf(alertWs.fecha_resolucion) : null;
						//alerta.Fecha_resolucion_de_Alerta__c = alertWs.fecha_resolucion != null ?
								//Date.valueOf(alertWs.fecha_resolucion.substringBefore(' ')) :
								//null;
						alerta.Estado__c = alertWs.estado_alerta;
	//--------------------------------------------------------------------------------------
						alertasToUpsert.add(alerta);
					}
				}
			
			}
		}

		Database.SaveResult resultCaso = Database.update(caso);
		System.debug('****resultCaso: ' + resultCaso);
		List<Database.SaveResult> resultPrestaciones = Database.update(prestacionesToUpdate);
		System.debug('****resultPrestaciones: ' + resultPrestaciones);
		List<Database.UpsertResult> resultAlerts = Database.upsert(alertasToUpsert, Alerta__c.Fields.idalerta__c);
        System.debug('****resultAlerts ' + resultAlerts);
		
	}

	private static Response validatePermissions(User usuario, List<Case> casos) {
		//Boolean propietario = usuario.Profile.Name == 'Administrador del sistema' || caso.OwnerId == usuario.Id;
		Boolean liderMesa = usuario.Profile.Name == 'Administrador del sistema' 
							|| usuario.Profile.Name == 'Coordinador de Mesa de Ayuda';
		
		if(!casos[0].Caso_Rechazado__c) {
			return new Response(false, 'El caso debe estar rechazado');
		}

		//if( !Utils.perteneceALaDelegacionCorrecta(casos[0], usuario) ) {	
			//return new Response(false, 'El usuario puede modificar casos de su delegación solamente');
		//}
		if(casos[0].Nivel_de_derivacion__c == 'Nivel 1' || casos[0].Nivel_de_derivacion__c == null) {
			GroupMember[] members = [
				SELECT Id, UserOrGroupId, Group.DeveloperName 
				FROM GroupMember 
				WHERE Group.DeveloperName LIKE 'Celula%' AND UserOrGroupId = :usuario.Id
			];

			if(members.isEmpty() && !liderMesa) {
				return new Response(false, '- El usuario debe ser el líder de la célula');
			}
		} 
		else if(casos[0].Nivel_de_derivacion__c == 'Nivel 2') {
			if(!liderMesa) {
				return new Response(false, '- El usuario debe ser el líder de Mesa de Ayuda');
			}
		} 
		else if(casos[0].Nivel_de_derivacion__c == 'Nivel 3') {
			if(usuario.Profile.Name != 'Administrador del sistema') {
				if(String.isBlank(casos[0].Celula__c)) {
					return new Response(false, '- El campo célula debe estar completo');
				}
				else {
					String queueName = casos[0].Celula__c.replace(' ', '_');
					GroupMember[] members = [
						SELECT Id, UserOrGroupId, Group.DeveloperName 
						FROM GroupMember 
						WHERE Group.DeveloperName = :queueName AND UserOrGroupId = :usuario.Id
					];
		
					if(members.isEmpty()) {
						return new Response(false, '- El usuario debe ser el líder de la célula');
					}
				}
			}
		}

		return new Response(false, 'ok');
	}

	public class Response {
		@AuraEnabled public Boolean hasError;
		@AuraEnabled public String message;

		public Response(Boolean hasError, String message){
			this.hasError = hasError;
			this.message = message;
		}
	}

}