force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Empresas__c.field-meta.xml
<CustomField>
    <fullName>Empresas__c</fullName>
    <label>Empresas</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sucursal__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sucursales</relationshipLabel>
    <relationshipName>Sucursales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountEmpresaProcessorTest.cls
@isTest
public class AccountEmpresaProcessorTest  {

	static MasterConfigs__c config;
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundSecondPage;
	static XHttpCalloutMock getErrorResponse;
	static XHttpCalloutMock getEmptyListResponse;
	static Account agencia;

	static {
		String today = System.now().format('yyyy-MM-dd');

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEmpresaMock.getFound())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/empresas/' + today + '?pageSize=15&page=2');

		getResponseFoundSecondPage = new XHttpCalloutMock();
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEmpresaMock.getFoundAndContinue())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/empresas/' + today + '?pageSize=15&page=1');	
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEmpresaMock.getFound())
			.addForAddress(WSBatchEmpresa.SERVICE_CONFIG.URL__c + '/v1/salud/batch/empresas/' + today + '?pageSize=15&page=2');
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchSucursalMock.getFound())
			.addForAddress(WSBatchSucursal.SERVICE_CONFIG.URL__c + '/v1/salud/batch/sucursales-empresas/' + today + '?pageSize=15&page=1');	
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchSucursalMock.getFoundSecondPage())
			.addForAddress(WSBatchSucursal.SERVICE_CONFIG.URL__c + '/v1/salud/batch/sucursales-empresas/' + today + '?pageSize=15&page=2');

		agencia = Build.anAccountDelegacion().withCodigoDeDelegacion('650098').build();
		insert agencia;
	}

	static {
		config = Build.aMasterConfigs().build();
		insert config;
	}

	@isTest static void externalsAccountsCanBeProcessed() {
		XHttpCalloutMock mock = new XHttpCalloutMock();

		Test.setMock(HttpCalloutMock.class, getResponseFound);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEmpresaProcessor(15, 2, 2, System.now())));
		Test.stopTest();

		System.assertEquals(1, [SELECT Count() FROM Account WHERE RecordType.DeveloperName = 'Empresa']);
	}

	@isTest static void aSecondBatchOfAccountsCanBeCalled() {

		XHttpCalloutMock mock = new XHttpCalloutMock();
		
		Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPage);
		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEmpresaProcessor(15, System.now())));
		Test.stopTest();

		System.assertEquals(2, [SELECT Count() FROM Account WHERE RecordType.DeveloperName = 'Empresa']);
        System.assertEquals(2, [SELECT Count() FROM Sucursal__c WHERE Empresa__r.Codigo_de_empresa__c = '600001']);// + 1 manager
		//System.assertEquals(1, [SELECT Count() FROM Dependiente__c]);
	}

	@isTest static void atTheLastBatchTheLastUpdatedDateIsUpdated() {


		XHttpCalloutMock mock = new XHttpCalloutMock();

		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Datetime now = System.now();

		Datetime yesterday = Datetime.now().addDays(-1);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEmpresaProcessor(15, 2, 2, now)));
		Test.stopTest();

		System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Empresas__c);
	}

}