force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Es_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Es_Prestador__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>En caso de que sea prestador, la casilla estará activa. Deberá completar los campos correspondientes a la sección Prestador</inlineHelpText>
    <label>Es Prestador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Efector.recordType-meta.xml
<RecordType>
    <fullName>Efector</fullName>
    <active>true</active>
    <description>Efectores y Prestadores</description>
    <label>Efector</label>
</RecordType>

force-app/main/default/objects/Consultorio__c/Consultorio__c.object-meta.xml
<CustomObject>
    <label>Consultorio</label>
    <nameField>
        <label>Nombre de Consultorio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultorio__c/fields/Convenio__c.field-meta.xml
<CustomField>
    <fullName>Convenio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Convenio</label>
    <referenceTo>Convenio__c</referenceTo>
    <relationshipLabel>Consultorios</relationshipLabel>
    <relationshipName>Consultorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convenio__c/Convenio__c.object-meta.xml
<CustomObject>
    <label>Convenio</label>
    <nameField>
        <label>Nombre de Convenio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Convenios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Convenio__c/fields/Consultorio__c.field-meta.xml
<CustomField>
    <fullName>Consultorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultorio</label>
    <referenceTo>Consultorio__c</referenceTo>
    <relationshipLabel>Convenios</relationshipLabel>
    <relationshipName>Convenios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Efectores__c.field-meta.xml
<CustomField>
    <fullName>Efectores__c</fullName>
    <label>Efectores</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountEfectorProcessorTest.cls
@isTest
public class AccountEfectorProcessorTest  {

	static MasterConfigs__c config;
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundSecondPage;
	static XHttpCalloutMock getErrorResponse; 

	static {
		String today = System.now().format('yyyy-MM-dd');


		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEfectorMock.getFound())
			.addForAddress(WSBatchEfector.SERVICE_CONFIG.URL__c + '/v1/salud/batch/efectores/' + today + '?pageSize=15&page=1');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getFound2())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700050');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getFound())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700047');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700616');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700076');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700711');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSBatchConsultoriosMock.getFound())
				.addForAddress(WSBatchConsultorios.SERVICE_CONFIG.URL__c + '/v1/salud/batch/consultorios/' + today + '?pageSize=100&page=1');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSBatchConvenioMock.getFoundSecondPage())
				.addForAddress(WSBatchConvenio.SERVICE_CONFIG.URL__c + '/v1/salud/batch/convenios-prestadores/' + today + '?pageSize=100&page=1');

		getResponseFoundSecondPage = new XHttpCalloutMock();
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEfectorMock.getFoundAndContinue())
			.addForAddress(WSBatchEfector.SERVICE_CONFIG.URL__c + '/v1/salud/batch/efectores/' + today + '?pageSize=15&page=1');	
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchEfectorMock.getFound())
			.addForAddress(WSBatchEfector.SERVICE_CONFIG.URL__c + '/v1/salud/batch/efectores/' + today + '?pageSize=15&page=2');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700050');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getFound())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700047');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700711');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700076');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSEfectorConveniosMock.getEmpty())
				.addForAddress(WSEfectorConvenios.SERVICE_CONFIG.URL__c + '/v1/salud/efectores/convenios/700084');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSBatchConsultoriosMock.getFound())
				.addForAddress(WSBatchConsultorios.SERVICE_CONFIG.URL__c + '/v1/salud/batch/consultorios/' + today + '?pageSize=100&page=1');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSBatchConvenioMock.getFoundSecondPage())
				.addForAddress(WSBatchConvenio.SERVICE_CONFIG.URL__c + '/v1/salud/batch/convenios-prestadores/' + today + '?pageSize=100&page=2');
		getResponseFoundSecondPage.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSBatchConvenioMock.getFound())
				.addForAddress(WSBatchConvenio.SERVICE_CONFIG.URL__c + '/v1/salud/batch/convenios-prestadores/' + today + '?pageSize=100&page=1');

		Account acc = new Account(
				RecordTypeId = XappiaHelper.getRecordType('Account', 'Efector').Id,
				Codigo_de_efector__c = '700711',
				Name = 'Efector1',
				Es_Prestador__c = true
		);
		Account acc2 = new Account(
				RecordTypeId = XappiaHelper.getRecordType('Account', 'Efector').Id,
				Codigo_de_efector__c = '700047',
				Name = 'Efector1',
				Es_Prestador__c = true
		);
//		ContentVersion contVer = new ContentVersion();
//		contVer.PathOnClient = '/700047_M_20181001.pdf';
//		contVer.origin = 'H';
//		contVer.Title = '700047_M_20181001.pdf';
//		Blob pdfBody;
//		pdfBody = Blob.valueOf('Test data');
//		contVer.VersionData = pdfBody;
//		insert contVer;
		insert  acc;insert  acc2;
//		ContentVersion newCont = [
//				SELECT ContentDocumentId
//				FROM ContentVersion
//				WHERE Id = :contVer.Id
//		];
//		ContentDocumentLink contLink = new ContentDocumentLink();
//		contLink.ContentDocumentId = newCont.ContentDocumentId;
//		contLink.LinkedEntityId =acc2.Id;
//		contLink.ShareType = 'V';
//		insert contLink;

	}

	static {
		config = Build.aMasterConfigs().build();
		insert config;
	}

	@isTest static void externalsAccountsEfectorCanBeProcessed() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);


		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEfectorProcessor(15, 1, 1, System.now(),new List<String>())));

		Database.executeBatch(new MasterBatch(new AccountEfectorProcessor(15, 1, 1, System.now(),new List<String>())));
		Test.stopTest();

		System.assertEquals(5, [SELECT Count() FROM Account]);
		Id accountId = [SELECT Id FROM Account WHERE Codigo_de_efector__c = '700047'].Id;
		//System.assertEquals(4, [SELECT Count() FROM ContentVersion]);
		//System.assertEquals(4, [SELECT Count() FROM ContentDocumentLink WHERE LinkedEntityId = :accountId]);
		System.assertEquals(3, [SELECT Count() FROM Consultorio__c]);
		System.assertEquals(1, [SELECT Count() FROM Convenio__c]);

	}

	@isTest static void aSecondBatchOfAccountsCanBeCalled() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPage);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEfectorProcessor(15, System.now())));
		Test.stopTest();

		System.assertEquals(6, [SELECT Count() FROM Account]);
		Id accountId = [SELECT Id FROM Account WHERE Codigo_de_efector__c = '700047'].Id;
		System.assertEquals(2, [SELECT Count() FROM Convenio__c]);
		//System.assertEquals(4, [SELECT Count() FROM ContentVersion]);
		//System.assertEquals(4, [SELECT Count() FROM ContentDocumentLink WHERE LinkedEntityId = :accountId]);
		System.assertEquals(3, [SELECT Count() FROM Consultorio__c]);

	}

	@isTest static void atTheLastBatchTheLastUpdatedDateIsUpdated() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);

		Datetime now = System.now();

		Datetime yesterday = Datetime.now().addDays(-1);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new AccountEfectorProcessor(15, now)));
		Test.stopTest();

		System.assertEquals(now, MasterConfigs__c.getOrgDefaults().Efectores__c);
	}

}