force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>Rosario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos (Prestador)</relationshipLabel>
    <relationshipName>Casos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <label>Código de Afiliado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_Hora_inicio_EMS__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_inicio_EMS__c</fullName>
    <label>Fecha y Hora inicio EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Prestador)</relationshipLabel>
    <relationshipName>Eventos_Medicosp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Nombre_de_Localidad__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Localidad__c</fullName>
    <label>Nombre de Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordenes de Compras</relationshipLabel>
    <relationshipName>Ordenes_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdenDeCompraEnvioMailBtnCtrl.cls
public class OrdenDeCompraEnvioMailBtnCtrl  {
	
	@AuraEnabled
	public static Response sendAttachmentsToAllPrest(Id ocId){
		List<Cotizacion_Prestador__c> cotizaciones = [
			SELECT Id, Prestador__r.Correo_electronico__c, Prestador__r.Localidad_new__r.Nombre_de_Localidad__c
			FROM Cotizacion_Prestador__c
			WHERE  Orden_de_Compra__c = :ocId
		];

		User usuarioActual = [
			SELECT Id, Organizacion__c, Email
			FROM User
			WHERE Id = :UserInfo.getUserId()
		];

		Orden_de_Compra__c orden = [
			SELECT Id, Caso__c, Caso__r.Evento_Medico__c, Caso__r.ParentId, Estado_OC__c,Caso__r.Account.Codigo_de_Afiliado__c,
			Caso__r.Account.Name,Caso__r.Evento_Medico__r.Fecha_y_Hora_inicio_EMS__c,Caso__r.Fecha__c,Caso__r.Type
			FROM Orden_de_Compra__c
			WHERE Id = :ocId
		];

		if(cotizaciones.isEmpty()){
			return new Response(true, 'La orden de compra no tiene ninguna cotización');
		}

		orden.Estado_OC__c = 'Pedido Cotizacion';
		update orden;
		Id caseId = orden.Caso__r.ParentId != null ? orden.Caso__r.ParentId : orden.Caso__c;
		ContentDocumentLink[] linksCaso = [
			SELECT ContentDocumentId
			FROM ContentDocumentLink
			WHERE LinkedEntityId = :caseId
		];


		List<Id> docIdsCaso = new List<Id>();
		List<Id> docIdsEM = new List<Id>();

		for(ContentDocumentLink link : linksCaso){
			docIdsCaso.add(link.ContentDocumentId);
		}

		

		ContentVersion[] versionsCaso = [
			SELECT Id,VersionData, FileExtension
			FROM ContentVersion
			WHERE ContentDocumentId IN :docIdsCaso
			AND Title LIKE '%PRESCRI%'
		];
		ContentVersion[] versionsEM = new List<ContentVersion>();
		if(orden.Caso__r.Evento_Medico__c != null){
			ContentDocumentLink[] linksEM = [
				SELECT ContentDocumentId
				FROM ContentDocumentLink
				WHERE LinkedEntityId = :orden.Caso__r.Evento_Medico__c
			];
			for(ContentDocumentLink link : linksEM){
				docIdsEM.add(link.ContentDocumentId);
			}
			versionsEM = [
			SELECT Id,VersionData, FileExtension
			FROM ContentVersion
			WHERE ContentDocumentId IN :docIdsEM
			AND Title LIKE '%PRESCRI%'
		];
		}

		if(versionsCaso.isEmpty() && versionsEM.isEmpty()){
			return new Response(true, 'No se encontro ningun adjunto que contenga PRESCRI');
		}

		EmailUtils.MailResponse resp;
		List<String> errores = new List<String>();

		for(Cotizacion_Prestador__c cot : cotizaciones){
			
			String replyTo;
			String subject;
			String fecha;
			List<String> emailList = new List<String>();

			emailList.add(usuarioActual.Email);
			emailList.add(cot.Prestador__r.Correo_electronico__c);

			if(orden.Caso__r.Evento_Medico__c != null){
                System.debug('Entra al em ' + orden.Caso__r.Evento_Medico__r.Fecha_y_Hora_inicio_EMS__c);
				fecha = String.valueOf(orden.Caso__r.Evento_Medico__r.Fecha_y_Hora_inicio_EMS__c);
			}else{
				fecha = String.valueOf(orden.Caso__r.Fecha__c);
			}

			if(orden.Caso__r.Type == 'Prestacion'){
				replyTo = 'cotizaciones_interior@avalian.com';
				subject = 'Avalian - Cotizar - '+ orden.Caso__r.Account.Name +' - CX - '+ fecha + cot.Prestador__r.Localidad_new__r.Nombre_de_Localidad__c;
			}
			if(orden.Caso__r.Type == 'Medicamento'){
				replyTo = 'cotizaciones_medicamentos@avalian.com';
				subject = 'Avalian - Cotizar - '+ orden.Caso__r.Account.Name +' - ' + orden.Caso__r.Account.Codigo_de_Afiliado__c;
			}
			if(!versionsCaso.isEmpty()){
				resp = EmailUtils.sendMailWithAttachment(emailList,
				versionsCaso[0].VersionData,'Prescripcion.' + versionsCaso[0].FileExtension,cot.Id,'Solicitud_de_cotizacion',replyTo);
				if(resp.hasError){
					errores.add(resp.message);
				}
			}
			else{
				resp =EmailUtils.sendMailWithAttachment(emailList,
				versionsEM[0].VersionData,'Prescripcion.' + versionsEM[0].FileExtension,cot.Id,'Solicitud_de_cotizacion',replyTo);
			}
		}
		if(errores.size() == cotizaciones.size()){
			return new Response(true,'Falló el envio de mails.');
		}
		else if(errores.size() > 0 && errores.size() > cotizaciones.size()){
			return new Response(false,'Falló el envio de' + errores.size() + ' mails.');
		}
		else{
			return new Response(false, 'Se realizó el envío de mails');
		}
	}

	public class Response {
		@AuraEnabled public Boolean hasError;
		@AuraEnabled public String message;

		public Response(Boolean hasError, String message){
			this.hasError = hasError;
			this.message = message;
		}
	}  
}