force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Efector_Solicitante__c.field-meta.xml
<CustomField>
    <fullName>Efector_Solicitante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector Solicitante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Efector Solicitante)</relationshipLabel>
    <relationshipName>Eventos_Medicos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_hora_fin_ems__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_fin_ems__c</fullName>
    <label>Fecha y hora fin EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_Hora_inicio_EMS__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora_inicio_EMS__c</fullName>
    <label>Fecha y Hora inicio EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Datetime_Insert_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Datetime_Insert_Trigger__c</fullName>
    <label>Datetime Insert Trigger</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Datetime_Update_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Datetime_Update_Trigger__c</fullName>
    <label>Datetime Update Trigger</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Efector_solicitante__c.field-meta.xml
<CustomField>
    <fullName>Efector_solicitante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector solicitante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Error_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Error_en_SS__c</fullName>
    <label>Error en SS</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En auditoria</fullName>
                <label>En auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_real__c</fullName>
    <label>Fecha Fin real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_tentativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_tentativa__c</fullName>
    <label>Fecha Fin tentativa</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Inicio_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_real__c</fullName>
    <label>Fecha Inicio real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Inicio_tentativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_tentativa__c</fullName>
    <label>Fecha Inicio tentativa</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Numero_del_segmento__c.field-meta.xml
<CustomField>
    <fullName>Numero_del_segmento__c</fullName>
    <label>Número del segmento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Result_Insert_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Result_Insert_Trigger__c</fullName>
    <label>Result Insert Trigger</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Result_Update_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Result_Update_Trigger__c</fullName>
    <label>Result Update Trigger</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Segmento_actual__c.field-meta.xml
<CustomField>
    <fullName>Segmento_actual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Segmento actual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Semid__c.field-meta.xml
<CustomField>
    <fullName>Semid__c</fullName>
    <externalId>true</externalId>
    <label>Sem_id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Solicitante__c.field-meta.xml
<CustomField>
    <fullName>Solicitante__c</fullName>
    <label>Solicitante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SegmentoHelper.cls
public class SegmentoHelper {
	public static void checkSegmentoActualInTheLastSegmento(Map<Id, Segmentos__c[]> emIdsSegmentosMap) {
		List<Segmentos__c> segmentosList = new List<Segmentos__c>();
		for(Evento_medico__c em : [
			SELECT Id, Estado__c, (
				SELECT Segmento_actual__c, Numero_del_segmento__c
				FROM Segmentos__r
			)
			FROM Evento_medico__c
			WHERE Id IN :emIdsSegmentosMap.keySet()
		]) {
			Integer size = em.Segmentos__r.size();
			Integer i = 1;
			Segmentos__c[] segmentosFromMap = emIdsSegmentosMap.get(em.Id);
			// segmentos existentes
			for (Segmentos__c segmento : em.Segmentos__r) {
				if (segmento.Segmento_actual__c) {
					segmento.Segmento_actual__c = false;
					segmentosList.add(segmento);
				}
			}
			// segmentos nuevos
			for(Segmentos__c segFromMap : segmentosFromMap) {
				segFromMap.Numero_del_segmento__c = size + i;
				segFromMap.Segmento_actual__c = segmentosFromMap.size() == i ? true : false;
				i ++;
			}
			
		}
		if (!segmentosList.isEmpty()) {
			update segmentosList;
		}
	}

	public static void updatePreviousSegments(Map<Id,Decimal> emNroSegMap){
		List<Evento_medico__c> ems = [
			SELECT Estado__c, (
				SELECT Segmento_actual__c, Numero_del_segmento__c, Fecha_Fin_real__c, Error_en_SS__c
				FROM Segmentos__r
			) 
			FROM Evento_medico__c 
			WHERE Id IN :emNroSegMap.keySet()
		];

		List<Segmentos__c> segsToUpdate = new List<Segmentos__c>();
		for(Evento_medico__c em : ems){
//			if(em.Estado__c == 'Autorizado') {
				for (Segmentos__c seg : em.Segmentos__r) {
					if (seg.Numero_del_segmento__c == emNroSegMap.get(em.Id)) {
						seg.Segmento_actual__c = true;
						System.debug('****seg: ' + seg);
						if(String.isBlank(seg.Error_en_SS__c)) {
							em.Fecha_y_hora_fin_ems__c = seg.Fecha_Fin_real__c;
						}						
						segsToUpdate.add(seg);
					}
				}
//			}
		}
		System.debug('****segsToUpdate: ' + segsToUpdate);
		update segsToUpdate;
		update ems;
	}

	public static Boolean isChangedSomeFieldToSendToSS(Segmentos__c segmento, Segmentos__c oldSegmento) {
		return segmento.Estado__c != oldSegmento.Estado__c
				|| segmento.Numero_del_segmento__c != oldSegmento.Numero_del_segmento__c
				|| segmento.Evento_Medico__c != oldSegmento.Evento_Medico__c
				|| segmento.Fecha_Inicio_tentativa__c != oldSegmento.Fecha_Inicio_tentativa__c
				|| segmento.Fecha_Fin_tentativa__c != oldSegmento.Fecha_Fin_tentativa__c
				|| segmento.Fecha_Inicio_real__c != oldSegmento.Fecha_Inicio_real__c
				|| segmento.Fecha_Fin_real__c != oldSegmento.Fecha_Fin_real__c;
	}

	public static void avoidDeletionOfTheFirstSegmento(List<Segmentos__c> segmentosToDelete) {
		System.debug('****segmentosToDelete: ' + segmentosToDelete);
		List<Segmentos__c> segmentosCantDelete = new List<Segmentos__c>();
		for (Segmentos__c seg : segmentosToDelete) {
			if(seg.Numero_del_segmento__c == 1) {
				segmentosCantDelete.add(seg);
			}
		}
		System.debug('****segmentosCantDelete: ' + segmentosCantDelete);
		for(Segmentos__c seg : segmentosCantDelete) {
			seg.addError('No se puede eliminar el primer segmento del Evento Médico');
		}
	}

	//@future (callout=true)
	//public static void sendUpdatesToSS(List<String> idsList) {
		//String body;
		//List<Segmentos__c> segToUpdate = new List<Segmentos__c>();
		//List<Segmentos__c> segList = [
				//SELECT Semid__c, Fecha_Inicio_real__c, Fecha_Fin_real__c, Evento_Medico__r.Nro_de_Evento_Medico_SS__c,
						//Evento_Medico__r.Fecha_y_Hora_inicio_EMS__c
				//FROM Segmentos__c
				//WHERE Id IN :idsList
		//];
		//System.debug('****segList: ' + segList);
		//for(Segmentos__c seg : segList) {
			//body = SegmentoActualizarBtnCtrl.generateJSON(seg);
			//WSSegmentoActualizar.Response resp = WSSegmentoActualizar.actualizarSegmento(
					//seg.Evento_Medico__r.Nro_de_Evento_Medico_SS__c,
					//seg.Semid__c,
					//body
			//);

			//seg.Datetime_Update_Trigger__c = System.now();
			//if (!resp.hasError) {
				//for(WSSegmentoEliminarResp.Segmento wsSegmento : resp.result.data.em.segmento) {
					//if(wsSegmento.sem_id == seg.Semid__c) {
						//System.debug('sem_id del WS es == al de SF');
						//seg.Estado__c = wsSegmento.estado;
						//seg.Result_Update_Trigger__c = 'ok';
////						seg.Solicitante__c = wsSegmento.nom_solicitante;
////						seg.Fecha_Inicio_real__c = Datetime.parse(wsSegmento.fecha_real_desde.replace('-', '/'));
////						seg.Fecha_Fin_real__c = Datetime.parse(wsSegmento.fecha_real_hasta.replace('-', '/'));
					//}
				//}
			//} else {
				//seg.Result_Update_Trigger__c = resp.message;
			//}
			//segToUpdate.add(seg);
		//}
		//List<Database.SaveResult> results = Database.update(segToUpdate);
		//System.debug('****results: ' + results);
	//}

	//@future (callout=true)
	//public static void sendSegmentToSS(List<String> idsList) {
		//String body;
		//List<Segmentos__c> segsToUpdate = new List<Segmentos__c>();
		//List<Segmentos__c> segsList = [
				//SELECT Semid__c, Evento_Medico__r.Efector_Solicitante__r.Codigo_de_efector__c, Fecha_Inicio_tentativa__c,
						//Evento_Medico__r.Nro_de_Evento_Medico_SS__c, Fecha_Fin_tentativa__c
				//FROM Segmentos__c
				//WHERE Id IN :idsList
		//];
		//for(Segmentos__c seg : segsList) {
			//body = SegmentoAltaBtnCtrl.generateJSON(seg);
			//WSSegmentoAlta.Response resp = WSSegmentoAlta.crearSegmento(
					//seg.Evento_Medico__r.Nro_de_Evento_Medico_SS__c,
					//body
			//); 

			//seg.Datetime_Insert_Trigger__c = System.now();
			//System.debug(resp);
			//if (!resp.hasError) {
				//for(WSSegmentoEliminarResp.Segmento segWs : resp.result.data.em.segmento) {
					//String segId = seg.Id;
					//if(segId == segWs.aca_nro_sf) {
						//seg.Semid__c = segWs.sem_id;
						//seg.Fecha_Inicio_real__c = segWs.fecha_real_desde != null
								//? Datetime.parse(segWs.fecha_real_desde.replace('-', '/')) : null;
						//seg.Fecha_Fin_real__c = segWs.fecha_real_hasta != null
								//? Datetime.parse(segWs.fecha_real_hasta.replace('-', '/')) : null;
						//seg.Result_Insert_Trigger__c = 'ok';
					//}
				//}
			//} else {
				//seg.Result_Insert_Trigger__c = resp.message;
			//}
			//segsToUpdate.add(seg);
		//}
		//List<Database.SaveResult> results = Database.update(segsToUpdate);
		//System.debug('****results: ' + results);

	//}
}