force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Correo_gerencia_cooperativa__c.field-meta.xml
<CustomField>
    <fullName>Correo_gerencia_cooperativa__c</fullName>
    <label>Correo gerencia cooperativa</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion2__c.field-meta.xml
<CustomField>
    <fullName>Delegacion2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Filial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Filial</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Filiales</relationshipLabel>
    <relationshipName>Filiales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Descripcion_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_delegacion__c</fullName>
    <label>Descripción</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_activacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_activacion__c</fullName>
    <label>Fecha de activación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nivel_de_permiso__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_permiso__c</fullName>
    <label>Nivel de permiso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Nombre_delegacion__c</fullName>
    <label>Nombre delegación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Observaciones_delegacion__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>Rosario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Porcentaje_de_comision_dateras__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_comision_dateras__c</fullName>
    <label>Porcentaje de comisión dateras</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_comision_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_comision_de_venta__c</fullName>
    <label>Tipo de comisión de venta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_delegacion__c</fullName>
    <label>Tipo delegación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REAL</fullName>
            </value>
            <value>
                <fullName>VIRTUAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/MasterConfigs__c/MasterConfigs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MasterConfigs</label>
</CustomObject>

force-app/main/default/objects/MasterConfigs__c/fields/Delegaciones__c.field-meta.xml
<CustomField>
    <fullName>Delegaciones__c</fullName>
    <label>Delegaciones</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DelegacionProcessor.cls
public class DelegacionProcessor implements IMasterBuilder  {

	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForDelegacion;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public DelegacionProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public DelegacionProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForDelegacion) {
		this(pageSize, 1, 1, runTime, lastUpdateForDelegacion);
	}

	public DelegacionProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public DelegacionProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForDelegacion) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForDelegacion = lastUpdateForDelegacion;
	}

	public List<WSBatchDelegacionResp.Data> callWebService() {
		List<WSBatchDelegacionResp.Data> wsData = new List<WSBatchDelegacionResp.Data>();
		WSBatchDelegacion.Response result;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchDelegacion.getBatchDelegacion(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.delegacion.links.next != null;
			currentPage = result.delegacion.meta.current_page + 1;
			lastPage = result.delegacion.meta.last_page;
			wsData.addAll(result.delegacion.data);
		} else {
			this.errorWs = true;
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Account> delegacionesList = new List<Account>();
		List<String> externalIds = new List<String>();
		//Map<String, Account> filialesList = new Map<String, Account>();

		for(Object res : wsResponses) {
			WSBatchDelegacionResp.Data delegacionResp = (WSBatchDelegacionResp.Data) res;
			Account delegacion = new Account();
			delegacion.RecordTypeId = XappiaHelper.getRecordType('Account', 'Delegacion').Id;

			delegacion.Name = delegacionResp.nombre;
			delegacion.Nombre_delegacion__c = delegacionResp.nombre;
			delegacion.Codigo_de_delegacion__c = delegacionResp.codigo;
			delegacion.Fecha_de_activacion__c = delegacionResp.fecha_activacion != null 
				? Date.valueOf(delegacionResp.fecha_activacion) : null; 
			delegacion.Correo_electronico__c = Utils.isAValidEmail(delegacionResp.correo_electronico) 
												? delegacionResp.correo_electronico : null;
			delegacion.Porcentaje_de_comision_dateras__c = delegacionResp.pje_comis_dateras != null 
				? Decimal.valueOf(delegacionResp.pje_comis_dateras) : null;
			delegacion.Correo_gerencia_cooperativa__c = Utils.isAValidEmail(delegacionResp.correo_gerencia_coop) 
														? delegacionResp.correo_gerencia_coop : null;
			delegacion.Type = delegacionResp.tipo_delegacion;
			delegacion.Descripcion_delegacion__c = delegacionResp.descripcion;
			delegacion.Observaciones_delegacion__c = delegacionResp.observaciones;
			delegacion.Nivel_de_permiso__c = delegacionResp.nivel_permiso;
			delegacion.Organizacion__c = delegacionResp.organizacion == 'ROS' ? 'Rosario' 
				: delegacionResp.organizacion == 'BUE' ? 'Buenos Aires' 
				: null;
			delegacion.Estado__c = delegacionResp.estado;
			delegacion.Tipo_de_comision_de_venta__c = delegacionResp.tipo_comision_venta;
			delegacion.Delegacion2__r = delegacionResp.filial_depende != null 
				? new Account(Codigo_de_delegacion__c = delegacionResp.filial_depende) : null;
			delegacion.Tipo_delegacion__c = delegacionResp.tipo_real_virtual;

			delegacionesList.add(delegacion);
			externalIds.add(delegacionResp.codigo);
            
		}
		Database.UpsertResult[] results = Database.upsert(
			delegacionesList, Account.Fields.Codigo_de_delegacion__c, false
		);
		System.debug('****results* ' + results);

		//EmailUtils.sendErrorMail(results, null, null, externalIds, 'Delegaciones');

		Utils.insertBatchLogs(results, null, null, externalIds, 'Delegaciones');
	}

	public void updateDate() {

		if (!hasNext) {
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Delegaciones__c = lastUpdateForDelegacion;
				upsert lastUpdate;
			}
		} else {
			DelegacionProcessor nextProcessor = new DelegacionProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}
}