force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/Consultorio__c.object-meta.xml
<CustomObject>
    <label>Consultorio</label>
    <nameField>
        <label>Nombre de Consultorio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultorios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultorio__c/fields/Cod_Pami__c.field-meta.xml
<CustomField>
    <fullName>Cod_Pami__c</fullName>
    <label>Cod Pami</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Codigo_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_externo__c</fullName>
    <label>Código externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Cons__c.field-meta.xml
<CustomField>
    <fullName>Cons__c</fullName>
    <label>Cons</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Consultorio_Diabetes__c.field-meta.xml
<CustomField>
    <fullName>Consultorio_Diabetes__c</fullName>
    <label>Consultorio Diabetes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Cuit__c.field-meta.xml
<CustomField>
    <fullName>Cuit__c</fullName>
    <label>Cuit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Efector_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Efector_Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector/Prestador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consultorios</relationshipLabel>
    <relationshipName>Consultorios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Farmacia_Leches__c.field-meta.xml
<CustomField>
    <fullName>Farmacia_Leches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Farmacia Leches</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Fecha_desde_Usuario__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde_Usuario__c</fullName>
    <label>Fecha desde Usuario</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Fecha_hasta_Usuario__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hasta_Usuario__c</fullName>
    <label>Fecha hasta Usuario</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Fecha_vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_vigencia__c</fullName>
    <label>Fecha Vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Firma__c.field-meta.xml
<CustomField>
    <fullName>Firma__c</fullName>
    <label>Firma</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Horarios__c.field-meta.xml
<CustomField>
    <fullName>Horarios__c</fullName>
    <label>Horarios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Matri__c.field-meta.xml
<CustomField>
    <fullName>Matri__c</fullName>
    <label>Matri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Secuencia__c.field-meta.xml
<CustomField>
    <fullName>Secuencia__c</fullName>
    <label>Secuencia</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consultorio__c/fields/Tipo_Mat__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Mat__c</fullName>
    <label>Tipo Mat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsultoriosEfectorProcessor.cls
public class ConsultoriosEfectorProcessor implements IMasterBuilder{
    public Boolean hasNext = false;
    public String next;
    public String followUpEndpoint;
    public Datetime runTime;
    public Datetime lastUpdateForConsultorios;

    public Integer pageSize;
    public Integer currentPage;
    public Integer lastPage;


    public ConsultoriosEfectorProcessor(Integer pageSize, Datetime runTime) {
        this(pageSize, 1, 1, runTime, Datetime.now());
    }

    public ConsultoriosEfectorProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForAsociado) {
        this(pageSize, 1, 1, runTime, lastUpdateForAsociado);
    }

    public ConsultoriosEfectorProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
        this(pageSize, currentPage, lastPage, runTime, Datetime.now());
    }

    public ConsultoriosEfectorProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForEfectores) {
        this.pageSize = pageSize;
        this.currentPage = currentPage;
        this.lastPage = lastPage;
        this.runTime = runTime;
        this.lastUpdateForConsultorios = lastUpdateForEfectores;

    }

    public List<WSBatchConsultoriosResp.Data> callWebService() {
        List<WSBatchConsultoriosResp.Data> wsData = new List<WSBatchConsultoriosResp.Data>();
        WSBatchConsultorios.Response result;


        if (currentPage <= lastPage) {
            String fecha = runTime.format('yyyy-MM-dd');
            result = WSBatchConsultorios.getBatchConsultorios(fecha, this.pageSize, this.currentPage);
        }

        if(!result.hasError) {
            hasNext = result.consultorios.links.next != null;
            currentPage = result.consultorios.meta.current_page +1;
            lastPage = result.consultorios.meta.last_page;

            wsData = result.consultorios.data;
        }

        return wsData;
    }

    public void processResponse(List<Object> wsResponses) {
        List<Consultorio__c> consultorioList = new List<Consultorio__c>();
		List<String> ids = new List<String>();

        for(Object res : wsResponses) {
            WSBatchConsultoriosResp.Data consultorio = (WSBatchConsultoriosResp.Data) res;

            Consultorio__c con = new Consultorio__c();
            con.Efector_Prestador__r = new Account(Codigo_de_efector__c = consultorio.pres_efe_codigo);
            con.Secuencia__c = consultorio.secuencia != null ? Decimal.valueOf(consultorio.secuencia) : null;
            con.Name = consultorio.nombre;
            con.Username__c = consultorio.username;
            con.Id_Externo__c = consultorio.pres_efe_codigo + '-' + consultorio.secuencia;
            con.Principal__c = consultorio.principal == 'V' ? true : false;
            con.Fecha_vigencia__c = consultorio.fecha_vigencia != null ? Date.valueOf(consultorio.fecha_vigencia) : null;
            con.Estado__c = consultorio.estado;
            con.Descripcion__c = consultorio.descripcion;
            con.Consultorio_Diabetes__c = consultorio.consultorio_diabetes;
            con.Matri__c = consultorio.matri;
            con.Mail__c = Utils.isAValidEmail(consultorio.mail) ? consultorio.mail : null;
            con.Codigo_externo__c = consultorio.codigo_externo;
            con.Cod_Pami__c = consultorio.cod_pami;
            con.Fecha_desde_Usuario__c = consultorio.fecha_desde_usr != null ? Date.valueOf(consultorio.fecha_desde_usr) : null;
            con.Fecha_hasta_Usuario__c = consultorio.fecha_hasta_usr != null ? Date.valueOf(consultorio.fecha_hasta_usr) : null;
            con.Horarios__c = consultorio.horario;
            con.Farmacia_Leches__c = consultorio.farmacias_leches == 'V' ? true : false;
            con.Tipo_Mat__c = consultorio.tipo_matricula;
            con.Cuit__c = consultorio.cuit;
            con.Cons__c = consultorio.cons_cia;
            con.Firma__c = consultorio.firma;

            consultorioList.add(con);
			ids.add(con.Id_Externo__c);
        }

        Database.UpsertResult[] results = Database.upsert(
                consultorioList, Consultorio__c.Fields.Id_Externo__c,false
        );

        System.debug(results);
		//EmailUtils.sendErrorMail(results, null, null, ids, 'Consultorios');

		Utils.insertBatchLogs(results, null, null, ids, 'Consultorios');


    }



    public void updateDate() {


        if (!hasNext) {

            ConveniosEfectorProcessor convProcessor = new ConveniosEfectorProcessor(100,runTime);
            Database.executeBatch(new MasterBatch(convProcessor));

        } else {

            ConsultoriosEfectorProcessor nextProcessor = new ConsultoriosEfectorProcessor(pageSize, currentPage, lastPage, runTime);
            Database.executeBatch(new MasterBatch(nextProcessor));
        }
    }
}