force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Funcion__c.field-meta.xml
<CustomField>
    <fullName>Funcion__c</fullName>
    <label>Función</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion_de_reintegro__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_de_reintegro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación de reintegro</label>
    <referenceTo>Prestacion_de_reintegro__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <formula>Codigo_Nomenclador__r.Prestacion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prestación</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORÍA</label>
            </value>
            <value>
                <fullName>C1-----G</fullName>
                <label>GENERADO</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/Prestacion_de_reintegro__c.object-meta.xml
<CustomObject>
    <label>Prestación de reintegro</label>
    <nameField>
        <displayFormat>PREINT-{0000}</displayFormat>
        <label>Nombre de Prestacion de reintegro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones de reintegros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
            <value>
                <fullName>PREEX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion_de_reintegro__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C1-----G</fullName>
                <default>true</default>
                <label>GENERADA</label>
            </value>
            <value>
                <fullName>C1-----A</fullName>
                <label>EN AUDITORIA</label>
            </value>
            <value>
                <fullName>C1----AS</fullName>
                <label>AUTORIZADO POR EL SISTEMA</label>
            </value>
            <value>
                <fullName>C1EA-RAP</fullName>
                <label>RECHAZADO POR EL AUDITOR AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1---RSA</fullName>
                <label>RECHAZADO POR EL SISTEMA AL AFILIADO</label>
            </value>
            <value>
                <fullName>C1---RSP</fullName>
                <label>RECHAZADO POR EL SISTEMA AL PRESTADOR</label>
            </value>
            <value>
                <fullName>C1EA--AA</fullName>
                <label>AUTORIZADO POR EL AUDITOR</label>
            </value>
            <value>
                <fullName>C1EA-RAA</fullName>
                <label>RECHAZADO POR EL AUDITOR AL AFILIADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__mdt/Region__mdt.object-meta.xml
<CustomObject>
    <description>Contiene las delegaciones que pertenecen a cada Region</description>
    <label>Region</label>
    <pluralLabel>Regiones</pluralLabel>
</CustomObject>

force-app/main/default/objects/Region__mdt/fields/Delegaciones__c.field-meta.xml
<CustomField>
    <fullName>Delegaciones__c</fullName>
    <label>Delegaciones</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Utils.cls
public without sharing class Utils {
	public static String getTypeAndExtension(String extension) {
		switch on extension {
			when 'png' {
				return 'image/png';
			}
			when 'jpg' {
				return 'image/jpg';
			}
			when 'jpeg' {
				return 'image/jpeg';
			}
			when 'pdf' {
				return 'application/pdf';
			}
			when 'txt' {
				return 'text/plain';
			}
			when 'doc' {
				return 'application/msword';
			}
			when 'xml' {
				return 'application/xml';
			}
			when 'xls' {
				return 'application/vnd.ms-excel';
			}
			when 'csv' {
				return 'text/csv';
			}
			when 'gif' {
				return 'image/gif';
			}
			when 'webp' {
				return 'image/webp';
			}
			when 'docx' {
				return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
			}
			when 'xlsx' {
				return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
			}
			when 'pptx' {
				return 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
			}
			when 'zip' {
				return 'application/zip';
			}
		}
		return null;
	}
	public static String translateStateAPToReintegro(String estado) {
		switch on estado {
			when 'CA-----G' {
				return 'CR-----G';
			}
			when 'CA-----A' {
				return 'CR-----A';
			}
			when 'CA-----E' {
				return 'CR-----E';
			}
			when 'CA-----N' {
				return 'CR-----N';
			}
		}
		return null;
	}
	public static String translateStateReintegroToAP(String estado) {
		switch on estado {
			when 'CR-----G' {
				return 'CA-----G';
			}
			when 'CR-----A' {
				return 'CA-----A';
			}
			when 'CR-----E' {
				return 'CA-----E';
			}
			when 'CR-----N' {
				return 'CA-----N';
			}
		}
		return null;
	}
	public static String getEstadoCivilCodFromValue(String valor){
		switch on valor {
			when 'Casado' {
				return 'C';
			}
			when 'Concubinato' {
				return 'N';
			}
			when 'Divorciado' {
				return 'D';
			}
			when 'Separado' {
				return 'P';
			}
			when 'Soltero' {
				return 'S';
			}
			when 'Viudo' {
				return 'V';
			}
		}
		return null;
	}
	public static Boolean perteneceALaDelegacionCorrecta(Case caso, User usuario) {
		Boolean frontUser = usuario.Profile.Name == 'Front';
		List<Region__mdt> regiones = [SELECT Id, Delegaciones__c, DeveloperName FROM Region__mdt];
		List<String> delegacionesBsAsYPampeana = new List<String>();
		List<String> delegacionesAmba = new List<String>();
		List<String> delegacionesBsAsCentro = new List<String>();
		List<String> delegacionesBsAsNorte = new List<String>();
		List<String> delegacionesCordoba = new List<String>();
		List<String> delegacionesLitoral = new List<String>();
		List<String> delegacionesNEA = new List<String>();
		List<String> delegacionesNOA = new List<String>();
		List<String> delegacionesNucleo = new List<String>();
		List<String> delegacionesPatagoniaAnd = new List<String>();
		List<String> delegacionesPatagoniaAtl = new List<String>();
		for(Region__mdt region : regiones) {
			if(region.DeveloperName == 'Bs_As_y_So_Pampeana') {
				delegacionesBsAsYPampeana = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Amba') {
				delegacionesAmba = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Bs_As_Centro') {
				delegacionesBsAsCentro = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Bs_As_Norte') {
				delegacionesBsAsNorte = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Cordoba') {
				delegacionesCordoba = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Litoral') {
				delegacionesLitoral = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'NEA') {
				delegacionesNEA = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'NOA') {
				delegacionesNOA = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Nucleo') {
				delegacionesNucleo = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Patagonia_Andina') {
				delegacionesPatagoniaAnd = region.Delegaciones__c.split(';');
			}
			else if(region.DeveloperName == 'Patagonia_Atlantica') {
				delegacionesPatagoniaAtl = region.Delegaciones__c.split(';');
			}
		}
		if(frontUser) {
			if(caso.Delegacion__r.Codigo_de_delegacion__c != usuario.Codigo_delegacion__c) {
				if( usuario.UserRole.DeveloperName == null || !usuario.UserRole.DeveloperName.containsIgnoreCase('lider') ) {
					return false;
				}
				else if(usuario.UserRole.DeveloperName == 'Lider_Buenos_Aires_So_y_Pampeana') {
					if( !delegacionesBsAsYPampeana.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				else if(usuario.UserRole.DeveloperName == 'Lider_Amba') {
					if( !delegacionesAmba.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				else if(usuario.UserRole.DeveloperName == 'Lider_Buenos_Aires_Centro') {
					if( !delegacionesBsAsCentro.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				else if(usuario.UserRole.DeveloperName == 'Lider_Buenos_Aires_Norte') {
					if( !delegacionesBsAsNorte.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//Cordoba
				else if(usuario.UserRole.DeveloperName == 'Lider_Cordoba') {
					if( !delegacionesCordoba.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesLitoral
				else if(usuario.UserRole.DeveloperName == 'Lider_Litoral') {
					if( !delegacionesLitoral.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesNEA
				else if(usuario.UserRole.DeveloperName == 'Lider_NEA') {
					if( !delegacionesNEA.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesNOA
				else if(usuario.UserRole.DeveloperName == 'Lider_NOA') {
					if( !delegacionesNOA.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesNucleo
				else if(usuario.UserRole.DeveloperName == 'Lider_Nucleo') {
					if( !delegacionesNucleo.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesPatagoniaAnd
				else if(usuario.UserRole.DeveloperName == 'Lider_Patagonia_Andina') {
					if( !delegacionesPatagoniaAnd.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
				//delegacionesPatagoniaAtl
				else if(usuario.UserRole.DeveloperName == 'Lider_Patagonia_Atlantica') {
					if( !delegacionesPatagoniaAtl.contains(caso.Delegacion__r.Codigo_de_delegacion__c) ) {
						return false;
					}
				}
			}
		}
		return true;
	}
	public static Boolean autoasignarMedico(Id alertId) {
		Case parentCase = new Case();
		Alerta__c alert = [SELECT Estado__c, Prestacion__c, Evento_Medico__c, Funcion__c, Prestacion_de_reintegro__c
							FROM Alerta__c
							WHERE Id =: alertId];
		User usuario = [SELECT Id, Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
		Boolean isDoctor = usuario.Profile.Name == 'Auditor Medico' || usuario.Profile.Name == 'Coordinador de Mesa de Ayuda';
		if(alert.Funcion__c == 'AM' && isDoctor && (alert.Estado__c == 'C1-----A' || alert.Estado__c == 'C1-----G')) {
			if(String.isNotBlank(alert.Prestacion__c)) {
				Prestacion__c prest = [SELECT Id, Ap__c, Ap__r.Medico_asignado__c, Ap__r.Nivel_de_derivacion__c
										FROM Prestacion__c
										WHERE Id =: alert.Prestacion__c];
				String nivel = prest.Ap__r.Nivel_de_derivacion__c;
				if(String.isNotBlank(prest.Ap__c)
					&& String.isBlank(prest.Ap__r.Medico_asignado__c)
					&& (nivel == 'Nivel 2' || nivel == 'Nivel 3')) {
					parentCase = prest.Ap__r;
				}
			}
			else if(String.isNotBlank(alert.Prestacion_de_reintegro__c)) {
				Prestacion_de_reintegro__c pRein = [SELECT Id, Caso__c, Caso__r.Medico_asignado__c, Caso__r.Nivel_de_derivacion__c
													FROM Prestacion_de_reintegro__c
													WHERE Id =: alert.Prestacion_de_reintegro__c];
				String nivel = pRein.Caso__r.Nivel_de_derivacion__c;
				if(String.isNotBlank(pRein.Caso__c)
					&& String.isBlank(pRein.Caso__r.Medico_asignado__c)
					&& (nivel == 'Nivel 2' || nivel == 'Nivel 3')) {
					parentCase = pRein.Caso__r;
				}
			}
			if(String.isNotBlank(parentCase.Id)) {
				parentCase.Medico_asignado__c = usuario.Id;
				update parentCase;
				return true;
			}
		}
		return false;
	}
	public static void insertBatchLogs(List<Database.UpsertResult> upsertResults,
										List<Database.SaveResult> saveResults,
										List<Database.DeleteResult> deleteResults,
										List<String> ids,
										String nombre) {
        Batch_log__c[] logsToInsert = new List<Batch_log__c>();
		Integer index = 0;
		Boolean hasIds = ids != null && !ids.isEmpty();
		if(upsertResults != null) {
			for (Database.UpsertResult ur : upsertResults) {
				if (!ur.isSuccess()) {
					Batch_log__c[] logs = getBatchLogs(ur.getErrors(), ids, hasIds, index, nombre);
					logsToInsert.addAll(logs);
				}
				index++;
			}
		}
		if(saveResults != null){
			for (Database.SaveResult ur : saveResults) {
				if (!ur.isSuccess()) {
					Batch_log__c[] logs = getBatchLogs(ur.getErrors(), ids, hasIds, index, nombre);
					logsToInsert.addAll(logs);
				}
				index++;
			}
		}
		if(deleteResults != null){
			for (Database.DeleteResult ur : deleteResults) {
				if (!ur.isSuccess()) {
					Batch_log__c[] logs = getBatchLogs(ur.getErrors(), ids, hasIds, index, nombre);
					logsToInsert.addAll(logs);
				}
				index++;
			}
		}
        if(!logsToInsert.isEmpty()) {
            Database.SaveResult[] logResults = Database.insert(logsToInsert, false);
        }
    }
	private static Batch_log__c[] getBatchLogs(Database.Error[] errors,
												String[] ids,
												Boolean hasIds,
												Integer index,
												String nombre) {
		Batch_log__c[] logsToReturn = new List<Batch_log__c>();
		for(Database.Error err : errors) {
			Batch_log__c log = new Batch_log__c();
			log.Error__c = err.getStatusCode() + ', ' + err.getFields() + ', ' + err.getMessage();
			log.Name = nombre;
			log.Id_registro_error__c = hasIds ? ids[index] : null;
			logsToReturn.add(log);
		}
		return logsToReturn;
	}
	public static Boolean isAValidEmail(String mail) {
		String EMAIL_REGEX = '^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$';
		if(String.isBlank(mail) || mail.contains('@-') || mail.startsWith('.')) {
			return false;
		}
		else {
			return Pattern.matches(EMAIL_REGEX, mail);
		}
	}
	public static ResponseFailedUpserts getAccountsWithFailedUpsert(Database.UpsertResult[] results,
																	Account[] accounts,
																	String[] externalIds) {
		Account[] accountsWithFailedUpsert = new List<Account>();
		String[] externalIdsFromAccountsFailed = new List<String>();
		Integer index = 0;
		for(Database.UpsertResult ur : results) {
			if (!ur.isSuccess()) {
				accountsWithFailedUpsert.add(accounts[index]);
				externalIdsFromAccountsFailed.add(externalIds[index]);
			}
			index ++;
		}
		return new ResponseFailedUpserts(accountsWithFailedUpsert, externalIdsFromAccountsFailed);
	}
	public class ResponseFailedUpserts {
		public Account[] accounts;
		public String[] externalIds;
		public ResponseFailedUpserts(Account[] accounts, String[] externalIds){
			this.accounts = accounts;
			this.externalIds = externalIds;
		}
	}
	public static Boolean isLeader() {
		String[] ADMIN_PROFILES = new List<String> {'System Administrator',
													'Administrador del sistema',
													'Administrador de Servicio',
													'CDC'};
		String[] CellProfiles = new List<String> {'Back CT', 'Back Administrativo', 'Discapacidad Interdisciplinario'};
		String[] leaderProfiles = ADMIN_PROFILES.clone();
		leaderProfiles.add('Coordinador de Mesa de Ayuda');
		User usuario = [SELECT Id, Profile.Name, UserRole.DeveloperName FROM User WHERE Id =: UserInfo.getUserId()];
		GroupMember[] leaders = [SELECT Id, UserOrGroupId, Group.DeveloperName
								FROM GroupMember
								WHERE Group.DeveloperName LIKE 'Celula%' AND UserOrGroupId =: usuario.Id];
		Boolean hasLeaderProfile = leaderProfiles.contains(usuario.Profile.Name);
		Boolean hasLeaderRole = usuario.UserRole.DeveloperName?.toUpperCase().contains('LIDER') != null
								? usuario.UserRole.DeveloperName?.toUpperCase().contains('LIDER') : false;
		Boolean isLeaderOfCell = !leaders.isEmpty() && CellProfiles.contains(usuario.Profile.Name);
		return hasLeaderProfile || hasLeaderRole || isLeaderOfCell;
	}
	public static Boolean isEncargado () {
		User usuario = [SELECT Id, Profile.Name, UserRole.DeveloperName FROM User WHERE Id =: UserInfo.getUserId()];
		Boolean hasEncargadoRole = usuario.UserRole.DeveloperName?.toUpperCase().contains('ENCARGADO') != null
										? usuario.UserRole.DeveloperName?.toUpperCase().contains('ENCARGADO')
										: false;
		return hasEncargadoRole;
	}
	public static String getStringAlphanumericOnly(String text) {
		if (String.isBlank(text)) {
			return '';
		}
		String REGEX = '^[a-zA-Z0-9_ ]*$';
		String alphanumericString = '';
		Integer strLength = text.length();
		for (Integer i = 0; i < text.length(); i++) {
			String s = text.mid(i, 1);
			if (Pattern.matches(REGEX, s)) {
				alphanumericString += s;
			}
		}
		return alphanumericString.replaceAll('\\s{2}', ' ');
	}
}