force-app/main/default/objects/Account/fields/Codigo_de_delegacion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_delegacion__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código de delegación</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseAPAnularBtnCtrl.cls
public class CaseAPAnularBtnCtrl  {
	static final String[] ADMIN_PROFILES = new List<String> {'System Administrator',
															'Administrador del sistema',
															'Administrador de Servicio',
															'CDC'};
	@AuraEnabled
	public static Response ifStatusIsOrdenEmitidaAndRecordTypeIsSeguimientoCancelCase(String caseId) {
		List<Case> caso = [SELECT Status, RecordTypeId, Nivel_de_derivacion__c, Delegacion__r.Codigo_de_delegacion__c, Nro_AP__c
			FROM Case WHERE Id =: caseId];
		User usuario = [SELECT CommunityNickname, Profile.Name, UserRole.DeveloperName, Codigo_delegacion__c
			FROM User WHERE Id =: UserInfo.getUserId()];
		Response validation = validatePermissions(usuario, caso[0]);
		if(validation.message != 'ok') {
			return validation;
		}
		if(String.isNotBlank(caso[0].Nro_AP__c)) {
			String body = JSON.serialize(new Map<String, Object> {'username' => usuario.CommunityNickname.toUpperCase()});
			WSCaseAPAnular.Response resp = WSCaseAPAnular.anularCaso(caso[0].Nro_AP__c, body);
			if (!resp.hasError) {
				anularCaso(caso[0]);
				return new Response(false, 'ok');
			}
			return new Response(true, resp.message);
		}
		else {
			anularCaso(caso[0]);
			return new Response(false, 'ok');
		}
	}
	private static void anularCaso(Case caso) {
		caso.Cambio_Manual__c = false;
		caso.Status = 'CA-----N';
		Database.SaveResult result = Database.update(caso);
	}
	private static Response validatePermissions(User usuario, Case caso) {
		Boolean hasPermission = ADMIN_PROFILES.contains(usuario.Profile.Name);
		if(usuario.CommunityNickname == null) {
			return new Response(false, System.Label.Alerta_NoAuth_ApodoCMVacio);
		}
		List<GroupMember> grupo = new List<GroupMember>();
		if(caso.Nivel_de_derivacion__c == 'Nivel 1') {
			grupo = [SELECT Id FROM GroupMember WHERE Group.DeveloperName = 'Front' AND UserOrGroupId =: usuario.Id];
			if(grupo.isEmpty() && !hasPermission) {
				return new Response(false, System.Label.Alerta_NoAuth_UsuarioNoFront);
			}
		}
		else if(caso.Nivel_de_derivacion__c == 'Nivel 2') {
			grupo = [SELECT Id FROM GroupMember WHERE Group.DeveloperName = 'Mesa_de_ayuda' AND UserOrGroupId =: usuario.Id];
			if(grupo.isEmpty() && !hasPermission) {
				return new Response(false, System.Label.Alerta_NoAuth_UsuarioNoMesaAyuda);
			}
		}
		else if(caso.Nivel_de_derivacion__c == 'Nivel 3') {
			List<CaseTeamMember> equipo = [SELECT MemberId
											FROM CaseTeamMember
											WHERE ParentId =: caso.Id AND MemberId =: usuario.Id];
			if(equipo.isEmpty() && !hasPermission) {
				return new Response(false, System.Label.Alerta_NoAuth_UsuarioNoEquipoCaso);
			}
		}
		return new Response(false, 'ok');
	}
	@AuraEnabled
	public static Boolean canCancelAPs() {
		Boolean isLider = Utils.isLeader();
		Boolean isEncargado = Utils.isEncargado();
		return isLider || isEncargado;
	}
	public class Response {
		@AuraEnabled public Boolean hasError;
		@AuraEnabled public String message;
		public Response(Boolean hasError, String message){
			this.hasError = hasError;
			this.message = message;
		}
	}
}