force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_de_activacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_activacion__c</fullName>
    <label>Fecha de activación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sucursal__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sucursales</relationshipLabel>
    <relationshipName>Sucursales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Es_sujeto_de_facturacion__c.field-meta.xml
<CustomField>
    <fullName>Es_sujeto_de_facturacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es sujeto de facturacion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GENERADO</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <label>ACTIVO</label>
            </value>
            <value>
                <fullName>SUSPENDIDO</fullName>
            </value>
            <value>
                <fullName>B</fullName>
                <label>DADO DE BAJA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Fecha_de_Activacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Activacion__c</fullName>
    <label>Fecha de Activación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sucursal__c/fields/Referencia_externa__c.field-meta.xml
<CustomField>
    <fullName>Referencia_externa__c</fullName>
    <label>Referencia externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SucursalesEmpresaProcessor.cls
public class SucursalesEmpresaProcessor implements IMasterBuilder  {

	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForSucursal;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;

	public SucursalesEmpresaProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public SucursalesEmpresaProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForSucursal) {
		this(pageSize, 1, 1, runTime, lastUpdateForSucursal);
	}

	public SucursalesEmpresaProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public SucursalesEmpresaProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForSucursal) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForSucursal = lastUpdateForSucursal;
	}

	public List<WSBatchSucursalResp.Data> callWebService() {
		List<WSBatchSucursalResp.Data> wsData = new List<WSBatchSucursalResp.Data>();
		WSBatchSucursal.Response result;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			result = WSBatchSucursal.getBatchSucursal(fecha, this.pageSize, this.currentPage);
		}

		if(!result.hasError) {
			hasNext = result.sucursal.links.next != null;
			currentPage = result.sucursal.meta.current_page + 1;
			lastPage = result.sucursal.meta.last_page;
			wsData.addAll(result.sucursal.data);
		}

		return wsData;
	}
	
	public void processResponse(List<Object> wsResponses) {
		List<Sucursal__c> sucursalList = new List<Sucursal__c>();
		List<String> externalIds = new List<String>();

		for(Object res : wsResponses) {
			WSBatchSucursalResp.Data sucursalResp = (WSBatchSucursalResp.Data) res;
			Sucursal__c sucursal = new Sucursal__c();

			sucursal.Id_externo__c = sucursalResp.empl_empl_id + '-' + sucursalResp.codigo_suc;
			sucursal.Empresa__r = new Account(Codigo_de_empresa__c = sucursalResp.empl_empl_id); 
			sucursal.Name = sucursalResp.nombre;
			sucursal.Codigo__c = sucursalResp.codigo_suc;
			sucursal.Descripcion__c = sucursalResp.descripcion;
			sucursal.Fecha_de_Activacion__c = Date.valueOf(sucursalResp.fecha_activacion);
			sucursal.Estado__c = sucursalResp.estado_sucursal;
			sucursal.Mail__c = Utils.isAValidEmail(sucursalResp.email) ? sucursalResp.email : null;
			sucursal.Observaciones__c = sucursalResp.observaciones;
			sucursal.Es_sujeto_de_facturacion__c = sucursalResp.es_sujeto_facturacion != null 
				? sucursalResp.es_sujeto_facturacion == 'V' 
				? true : false 
				: null;
			sucursal.Referencia_externa__c = sucursalResp.referencia_externa;

			sucursalList.add(sucursal);
			externalIds.add(sucursal.Id_externo__c);
		}
		Database.UpsertResult[] results = Database.upsert(
			sucursalList, Sucursal__c.Fields.Id_externo__c, false
		);
		System.debug('****results* ' + results);
		//EmailUtils.sendErrorMail(results, null, null, externalIds, 'Sucursales');
		
		Utils.insertBatchLogs(results, null, null, externalIds, 'Sucursales');
	}

	public void updateDate() {

		if (hasNext) {	
			SucursalesEmpresaProcessor nextProcessor = new SucursalesEmpresaProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		} 
		
	}
}