force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Efector.recordType-meta.xml
<RecordType>
    <fullName>Efector</fullName>
    <active>true</active>
    <description>Efectores y Prestadores</description>
    <label>Efector</label>
</RecordType>

force-app/main/default/objects/Cobertura_Especial__c/Cobertura_Especial__c.object-meta.xml
<CustomObject>
    <label>Cobertura Especial</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Cobertura Especial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coberturas Especiales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cobertura_Especial__c/fields/Efector__c.field-meta.xml
<CustomField>
    <fullName>Efector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Profesional__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coberturas Especiales</relationshipLabel>
    <relationshipName>Coberturas_Especiales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Evento_Medico_de_Seguimiento__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico_de_Seguimiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico de Seguimiento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Evento_medico__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Evento médico de seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Coberturas Especiales</relationshipLabel>
    <relationshipName>Coberturas_Especiales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Fecha_desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_desde__c</fullName>
    <label>Fecha desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Fecha_hasta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_hasta__c</fullName>
    <label>Fecha hasta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Forma__c.field-meta.xml
<CustomField>
    <fullName>Forma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma</label>
    <referenceTo>Forma__c</referenceTo>
    <relationshipLabel>Coberturas Especiales</relationshipLabel>
    <relationshipName>Coberturas_Especiales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Incluye_Excluye__c.field-meta.xml
<CustomField>
    <fullName>Incluye_Excluye__c</fullName>
    <label>Incluye/ Excluye</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
                <label>Incluye</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Excluye</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Integracion__c.field-meta.xml
<CustomField>
    <fullName>Integracion__c</fullName>
    <label>Integración</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Verdadero</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Falso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Marca_Jueves__c.field-meta.xml
<CustomField>
    <fullName>Marca_Jueves__c</fullName>
    <label>Marca Jueves</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Verdadero</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Falso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Marca_Lunes__c.field-meta.xml
<CustomField>
    <fullName>Marca_Lunes__c</fullName>
    <label>Marca Lunes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Verdadero</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Falso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Marca_Martes__c.field-meta.xml
<CustomField>
    <fullName>Marca_Martes__c</fullName>
    <label>Marca Martes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Verdadero</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Falso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Marca_Miercoles__c.field-meta.xml
<CustomField>
    <fullName>Marca_Miercoles__c</fullName>
    <label>Marca Miércoles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V</fullName>
                <label>Verdadero</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Falso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Nomenclador_Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Nomenclador_Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nomenclador Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Coberturas Especiales (Nomenclador de Prestación)</relationshipLabel>
    <relationshipName>Coberturas_Especiales1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Potencia__c.field-meta.xml
<CustomField>
    <fullName>Potencia__c</fullName>
    <label>Potencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Tipo_de_Copago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Copago__c</fullName>
    <label>Tipo de Copago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <label>Importe Fijo</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>310</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cob. Plan</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Farm. Diab</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Porcentaje</label>
            </value>
            <value>
                <fullName>310</fullName>
                <isActive>false</isActive>
                <label>310</label>
            </value>
            <value>
                <fullName>Cob. Plan</fullName>
                <isActive>false</isActive>
                <label>Cob. Plan</label>
            </value>
            <value>
                <fullName>Farm. Diab</fullName>
                <isActive>false</isActive>
                <label>Farm. Diab</label>
            </value>
            <value>
                <fullName>Importe Fijo</fullName>
                <isActive>false</isActive>
                <label>Importe Fijo</label>
            </value>
            <value>
                <fullName>Porcentaje</fullName>
                <isActive>false</isActive>
                <label>Porcentaje</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Tope_Anual__c.field-meta.xml
<CustomField>
    <fullName>Tope_Anual__c</fullName>
    <label>Tope Anual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cobertura_Especial__c/fields/Tope_Mensual__c.field-meta.xml
<CustomField>
    <fullName>Tope_Mensual__c</fullName>
    <label>Tope Mensual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forma__c/Forma__c.object-meta.xml
<CustomObject>
    <label>Forma</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Nro. de Forma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forma__c/fields/Codigo_de_Forma__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Forma__c</fullName>
    <externalId>true</externalId>
    <label>Código de Forma</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grupo_de_Prestaciones__c/Grupo_de_Prestaciones__c.object-meta.xml
<CustomObject>
    <label>Grupo de Prestaciones</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Nro. de Grupo de Prestaciones</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupos de Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grupo_de_Prestaciones__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/Medicamento__c.object-meta.xml
<CustomObject>
    <label>Medicamento</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Medicamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medicamento__c/fields/Forma__c.field-meta.xml
<CustomField>
    <fullName>Forma__c</fullName>
    <label>Forma</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Potencia__c.field-meta.xml
<CustomField>
    <fullName>Potencia__c</fullName>
    <label>Potencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/Nomenclador_de_Prestacion__c.object-meta.xml
<CustomObject>
    <label>Nomenclador de Prestación</label>
    <nameField>
        <label>Código Nomenclador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nomenclador de Prestaciónes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nomenclador_de_Prestacion__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CoberturaEspecialTriggerHelper.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class CoberturaEspecialTriggerHelper {
	public static void reintentoEnvio(List<Cobertura_Especial__c> coberturas) {
		List<Cobertura_Especial__c> coberturasToUpdate = new List<Cobertura_Especial__c>();
		for(Cobertura_Especial__c cobertura : coberturas) {
			String apodo = cobertura.CreatedBy.CommunityNickname != null
							? cobertura.CreatedBy.CommunityNickname.toUpperCase() : null;
			coberturasToUpdate.add( resendToSS( cobertura.Id, apodo ) );
		}
		update coberturasToUpdate;
	}
	private static Cobertura_Especial__c resendToSS(Id coberturaId, String apodo) {
		List<Cobertura_Especial__c> coberturas = [SELECT Evento_Medico_de_Seguimiento__r.Nro_de_Evento_Medico_SS__c, Fecha_desde__c, Efector__r.Codigo_de_efector__c,
				Tipo_de_Copago__c, Incluye_Excluye__c, Prioridad__c, Valor__c, Tope_Mensual__c, Tope_Anual__c,
				Nomenclador_Prestacion__r.Codigo__c, Fecha_hasta__c, Forma__r.Codigo_de_Forma__c, Potencia__c, Integracion__c,
				Marca_Lunes__c, Marca_Martes__c, Marca_Miercoles__c, Marca_Jueves__c, Marca_Viernes__c, Marca_Sabado__c,
				Marca_Domingo__c, Dependencia__c, Id_externo__c, Prestador__r.Codigo_de_efector__c, Por_comprimido__c,
				Medicamento__r.Codigo_medicamento__c, Grupo_de_Prestaciones__r.Codigo__c, Monodroga__r.Codigo_de_monodroga__c,
				Consultorio__r.Secuencia__c, Accion_Grupo_Terapeutico__r.Codigo_Accion_Grupo_Terapeutico__c, Tipo__c,
				Tope_Semanal__c, Prescriptor__r.Codigo_de_efector__c, Diagnostico__r.Codigo_del_Diagnostico__c
			FROM Cobertura_Especial__c
			WHERE Id =: coberturaId];
		String body = generateJson(coberturas[0], apodo);
		WSCoberturaEspecialEnviar.Response resp = WSCoberturaEspecialEnviar.enviarCobertura(
			coberturas[0].Evento_Medico_de_Seguimiento__r.Nro_de_Evento_Medico_SS__c, body
		);
		if(!resp.hasError) {
			coberturas[0].Id_externo__c = resp.result.data.id_cobertura;
			coberturas[0].Error_en_SS__c = null;
			coberturas[0].Fecha_de_error_en_SS__c = null;
		}
		else {
			coberturas[0].Error_en_SS__c = '<p style="color: rgb(228, 10, 10);">' + resp.message + '</p>';
			coberturas[0].Fecha_de_error_en_SS__c = Datetime.now();
		}
		return coberturas[0];
	}
	public static String generateJson(Cobertura_Especial__c cobertura, String apodo) {
		String body;
		Map<String,Object> jsonMap = new Map<String, Object> {
			'dependencia' => cobertura.Dependencia__c,
			'marca_domingo' => cobertura.Marca_Domingo__c,
			'marca_sabado' => cobertura.Marca_Sabado__c,
			'marca_viernes' => cobertura.Marca_Viernes__c,
			'marca_jueves' => cobertura.Marca_Jueves__c,
			'marca_miercoles' => cobertura.Marca_Miercoles__c,
			'marca_martes' => cobertura.Marca_Martes__c,
			'marca_lunes' => cobertura.Marca_Lunes__c,
			'consultorio' => cobertura.Consultorio__r.Secuencia__c != null ? String.valueOf(cobertura.Consultorio__r.Secuencia__c) : null,
			'prestador' => cobertura.Prestador__r.Codigo_de_efector__c,
			'integracion' => cobertura.Integracion__c,
			'potencia' => cobertura.Potencia__c,
			'por_comprimido' => cobertura.Por_comprimido__c,
			'forma' => cobertura.Forma__r.Codigo_de_Forma__c,
			'fecha_fin_vigencia' => cobertura.Fecha_hasta__c != null ? String.valueOf(cobertura.Fecha_hasta__c) : null,
			'usuario' => apodo,
			'tope_anual' => cobertura.Tope_Anual__c,
			'tope_mensual' => cobertura.Tope_Mensual__c,
			'cant_semanal' => cobertura.Tope_Semanal__c != null ? String.valueOf(cobertura.Tope_Semanal__c) : null,
			'valor' => cobertura.Valor__c,
			'prioridad' => cobertura.Prioridad__c != null ? Integer.valueOf(cobertura.Prioridad__c) : null,
			'incluye_excluye' => cobertura.Incluye_Excluye__c,
			'tipo_copago' => cobertura.Tipo_de_Copago__c,
			'efector_codigo' => cobertura.Prescriptor__r.Codigo_de_efector__c,
			'efector' => cobertura.Efector__r.Codigo_de_efector__c,
			'diag_codigo' => cobertura.Diagnostico__r.Codigo_del_Diagnostico__c,
			'fecha_desde' => cobertura.Fecha_desde__c != null ? String.valueOf(cobertura.Fecha_desde__c) : null
		};
		if(String.isNotBlank(cobertura.Id_externo__c)) {
			jsonMap.put('id_cobertura', cobertura.Id_externo__c);
		}
		switch on cobertura.Tipo__c{
			when 'Nomenclador'{
				jsonMap.put('nom_prestacion', cobertura.Nomenclador_Prestacion__r.Codigo__c);
			}
			when 'Monodroga'{
				jsonMap.put('monodroga', cobertura.Monodroga__r.Codigo_de_monodroga__c);
			}
			when 'Grupo Prestaciones'{
				jsonMap.put('grupo_prestaciones', cobertura.Grupo_de_Prestaciones__r.Grupo__c);
			}
			when 'Medicamento'{
				jsonMap.put('codigo_medicamento', cobertura.Medicamento__r.Codigo_medicamento__c);
			}
			when 'Grupo Terapeutico'{
				jsonMap.put('grupo_terapeutico', cobertura.Accion_Grupo_Terapeutico__r.Codigo_Accion_Grupo_Terapeutico__c);
			}
		}
		body = JSON.serialize(jsonMap);
		return body;
	}
	public static Boolean isChangedSomeFieldToSendToSS(Cobertura_Especial__c cobertura, Cobertura_Especial__c oldCobertura) {
		return cobertura.Dependencia__c != oldCobertura.Dependencia__c
				|| cobertura.Marca_Domingo__c != oldCobertura.Marca_Domingo__c
				|| cobertura.Marca_Sabado__c != oldCobertura.Marca_Sabado__c
				|| cobertura.Marca_Viernes__c != oldCobertura.Marca_Viernes__c
				|| cobertura.Marca_Jueves__c != oldCobertura.Marca_Jueves__c
				|| cobertura.Marca_Miercoles__c != oldCobertura.Marca_Miercoles__c
				|| cobertura.Marca_Martes__c != oldCobertura.Marca_Martes__c
				|| cobertura.Marca_Lunes__c != oldCobertura.Marca_Lunes__c
				|| cobertura.Consultorio__c != oldCobertura.Consultorio__c
				|| cobertura.Prestador__c != oldCobertura.Prestador__c
				|| cobertura.Integracion__c != oldCobertura.Integracion__c
				|| cobertura.Potencia__c != oldCobertura.Potencia__c
				|| cobertura.Por_comprimido__c != oldCobertura.Por_comprimido__c
				|| cobertura.Forma__c != oldCobertura.Forma__c
				|| cobertura.Fecha_hasta__c != oldCobertura.Fecha_hasta__c
				|| cobertura.Tope_Anual__c != oldCobertura.Tope_Anual__c
				|| cobertura.Tope_Mensual__c != oldCobertura.Tope_Mensual__c
				|| cobertura.Tope_Semanal__c != oldCobertura.Tope_Semanal__c
				|| cobertura.Valor__c != oldCobertura.Valor__c
				|| cobertura.Prioridad__c != oldCobertura.Prioridad__c
				|| cobertura.Incluye_Excluye__c != oldCobertura.Incluye_Excluye__c
				|| cobertura.Tipo_de_Copago__c != oldCobertura.Tipo_de_Copago__c
				|| cobertura.Prescriptor__c != oldCobertura.Prescriptor__c
				|| cobertura.Efector__c != oldCobertura.Efector__c
				|| cobertura.Fecha_desde__c != oldCobertura.Fecha_desde__c
				|| cobertura.Medicamento__c != oldCobertura.Medicamento__c
				|| cobertura.Diagnostico__c != oldCobertura.Diagnostico__c;
	}
	public static void avoidDeletionOfSentCoberturas(List<Cobertura_Especial__c> coberturas) {
		List<Cobertura_Especial__c> coberturasInSS = new List<Cobertura_Especial__c>();
		for (Cobertura_Especial__c cobertura : coberturas) {
			if(String.isNotBlank(cobertura.Id_externo__c)) {
				coberturasInSS.add(cobertura);
			}
		}
		for (Cobertura_Especial__c cobertura : coberturasInSS) {
			cobertura.addError(System.Label.Error_NoPuedeEliminarCoberturaEnviadaSS);
		}
	}
}