force-app/main/default/objects/Account/fields/Codigo_de_empresa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_empresa__c</fullName>
    <externalId>true</externalId>
    <label>Código de empresa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empresas</relationshipLabel>
    <relationshipName>Empresas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sucursal</label>
    <referenceTo>Sucursal__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Sucursal__c/Sucursal__c.object-meta.xml
<CustomObject>
    <label>Sucursal</label>
    <nameField>
        <label>Nombre de Sucursal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sucursales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sucursal__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sucursales</relationshipLabel>
    <relationshipName>Sucursales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SucursalesEmpresaProcessorTest.cls
@isTest
public class SucursalesEmpresaProcessorTest  {
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseFoundSecondPage;
	static XHttpCalloutMock getErrorResponse; 
	static XHttpCalloutMock getEmptyListResponse;


	static {
		String today = System.now().format('yyyy-MM-dd');
		//List<Account> prestadorList = new List<Account>{
		Account empresa = new Account( 
			RecordTypeId = XappiaHelper.getRecordType('Account', 'Empresa').Id,
			Codigo_de_empresa__c = '600001',
			Name = 'Empresa'
		);

		insert empresa;

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchSucursalMock.getFoundSecondPage())
			.addForAddress(WSBatchSucursal.SERVICE_CONFIG.URL__c + '/v1/salud/batch/sucursales-empresas/' + today + '?pageSize=1&page=2');

		getResponseFoundSecondPage = new XHttpCalloutMock();
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchSucursalMock.getFound())
			.addForAddress(WSBatchSucursal.SERVICE_CONFIG.URL__c + '/v1/salud/batch/sucursales-empresas/' + today + '?pageSize=1&page=1');	
		getResponseFoundSecondPage.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSBatchSucursalMock.getFoundSecondPage())
			.addForAddress(WSBatchSucursal.SERVICE_CONFIG.URL__c + '/v1/salud/batch/sucursales-empresas/' + today + '?pageSize=1&page=2');	
	}

	@isTest static void externalsSucursalesCanBeProcessed() {
		Test.setMock(HttpCalloutMock.class, getResponseFound);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new SucursalesEmpresaProcessor(1, 2, 2, System.now())));
		Test.stopTest();

		System.assertEquals(1, [SELECT Count() FROM Sucursal__c WHERE Empresa__r.Codigo_de_empresa__c = '600001']);
	}

	@isTest static void aSecondBatchOfSucursalesCanBeCalled() {
		Test.setMock(HttpCalloutMock.class, getResponseFoundSecondPage);

		Test.startTest();
		Database.executeBatch(new MasterBatch(new SucursalesEmpresaProcessor(1, System.now())));
		Test.stopTest();

		System.assertEquals(2, [SELECT Count() FROM Sucursal__c WHERE Empresa__r.Codigo_de_empresa__c = '600001']);

	}

}