force-app/main/default/objects/Account/fields/Codigo_de_Afiliado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Afiliado__c</fullName>
    <externalId>true</externalId>
    <label>Código de Asociado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Color_scoring__c.field-meta.xml
<CustomField>
    <fullName>Color_scoring__c</fullName>
    <label>Color scoring</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Edad_maxima__c.field-meta.xml
<CustomField>
    <fullName>Edad_maxima__c</fullName>
    <description>campo de scoring</description>
    <label>Edad máxima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Indice_de_Rentabilidad__c.field-meta.xml
<CustomField>
    <fullName>Indice_de_Rentabilidad__c</fullName>
    <label>Indice de Rentabilidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tiene_evento_de_exclusion__c.field-meta.xml
<CustomField>
    <fullName>Tiene_evento_de_exclusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tiene evento de exclusión</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AsociadoScoreBtnCtrlTest.cls
@isTest
public class AsociadoScoreBtnCtrlTest {
    static XHttpCalloutMock getResponseFound;
    static XHttpCalloutMock getResponseError;

    static {
		WSCaseReintegroEnviarASSMock mock = new WSCaseReintegroEnviarASSMock();
		
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAsociadoScoreMock.getFound())
			.addForAddress(WSAsociadoScore.SERVICE_CONFIG.URL__c + '/v1/salud/score/202637-15');
        getResponseError = new XHttpCalloutMock();
        getResponseError.buildResponse()
            .withStatus('OK')
            .withStatusCode(200)
            .withBody(WSAuthTokenMock.getTokenSuccess())
            .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
            getResponseError.buildResponse()
			.withStatus('Not Found')
			.withStatusCode(404)
			.withBody(WSAsociadoScoreMock.getError())
            .addForAddress(WSAsociadoScore.SERVICE_CONFIG.URL__c + '/v1/salud/score/0');
    }

    @IsTest
    static void whenTheBtnIsClickedInTheView_consumeWSLoteEnviarMailAgenciasSucess() {
        Test.setMock(HttpCalloutMock.class, getResponseFound);
        Account acc = Build.anAccount().build();
        acc.Codigo_de_Afiliado__c = '202637/15';
		acc.Tiene_evento_de_exclusion__c = true;
        insert acc;

        Test.startTest();
        AsociadoScoreBtnCtrl.Response responseToAssert = AsociadoScoreBtnCtrl.sendAccount(acc.Codigo_de_Afiliado__c);
        Test.stopTest();

        Account accToAssert = [
            SELECT Indice_de_Rentabilidad__c, Color_scoring__c, Tiene_evento_de_exclusion__c, Edad_maxima__c
            FROM Account
            WHERE Id =: acc.Id
        ];

        System.assertEquals(false,responseToAssert.hasError);
        System.assertEquals(null,responseToAssert.message);
        System.assertEquals('-886034.17', accToAssert.Indice_de_Rentabilidad__c);
        System.assertEquals('ROJO', accToAssert.Color_scoring__c);
		System.assertEquals(44, accToAssert.Edad_maxima__c);
		System.assertEquals(false, accToAssert.Tiene_evento_de_exclusion__c);

    }

    @IsTest
    static void whenTheBtnIsClickedInTheView_consumeWSWithError() {
        Test.setMock(HttpCalloutMock.class, getResponseError);
        Account acc = Build.anAccount().build();
        acc.Codigo_de_Afiliado__c = '0';
        insert acc;

        Test.startTest();
        AsociadoScoreBtnCtrl.Response responseToAssert = AsociadoScoreBtnCtrl.sendAccount(acc.Codigo_de_Afiliado__c);
        Test.stopTest();

        System.assertEquals(true,responseToAssert.hasError);
        System.assertEquals('Código de Afiliado inválido.',responseToAssert.message);
    }
}