force-app/main/default/objects/Account/fields/Codigo_de_efector__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_efector__c</fullName>
    <externalId>true</externalId>
    <label>Código de efector</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Efector.recordType-meta.xml
<RecordType>
    <fullName>Efector</fullName>
    <active>true</active>
    <description>Efectores y Prestadores</description>
    <label>Efector</label>
</RecordType>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Nombre_de_Localidad__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Localidad__c</fullName>
    <label>Nombre de Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matricula__c/Matricula__c.object-meta.xml
<CustomObject>
    <label>Matrícula</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Nombre de Matrícula</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrículas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Matricula__c/fields/Efector__c.field-meta.xml
<CustomField>
    <fullName>Efector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Efector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Matrículas</relationshipLabel>
    <relationshipName>Matriculas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Matricula__c.field-meta.xml
<CustomField>
    <fullName>Matricula__c</fullName>
    <label>Matrícula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Provincia_codigo__c.field-meta.xml
<CustomField>
    <fullName>Provincia_codigo__c</fullName>
    <label>Provincia código</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provincia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matricula__c/fields/Tipo_de_Matricula__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Matricula__c</fullName>
    <label>Tipo de Matrícula</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <label>Provincial</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Nacional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EfectorSearchControllerTest.cls
@isTest 
private class EfectorSearchControllerTest {
	
	@testSetup 
	static void setup() {
        // Create common test accounts
		Localidad__c loc = new Localidad__c();
		loc.Loc_Id__c = '1234';
		loc.Nombre_de_Localidad__c = 'Test';
		insert loc;

        Account[] efectores = new List<Account>();
        for(Integer i = 0; i < 3; i++) {
			Account acc = Build.anAccountEfector().build();
			acc.Name = 'Efector Test' + i;
			acc.Codigo_de_efector__c = '12345' + i;
			acc.Localidad_new__c = loc.Id;

            efectores.add(acc);
        }
        insert efectores;

		Matricula__c[] matriculas = new List<Matricula__c>();
		for(Integer i = 0; i < 3; i++) {
			Matricula__c mat = new Matricula__c();
			mat.Matricula__c = '123' + i;
			mat.Tipo_de_Matricula__c = 'P';
			mat.Provincia_codigo__c = i == 0 ? 'C' : i == 1 ? 'B' : 'X';
			mat.Efector__c = efectores[i].Id;

            matriculas.add(mat);
        }
		insert matriculas;

    }

	@isTest
	private static void searchByMatricula() {
		EfectorSearchController.Response resp = EfectorSearchController.search('1230', '', '');
		EfectorSearchController.Response resp2 = EfectorSearchController.search('1232', '', '');

		System.assertEquals('Efector Test0', resp.efectores[0].Efector__r.Name);
		System.assertEquals('123450', resp.efectores[0].Efector__r.Codigo_de_efector__c);
		System.assertEquals('Efector Test2', resp2.efectores[0].Efector__r.Name);
		System.assertEquals('123452', resp2.efectores[0].Efector__r.Codigo_de_efector__c);
		
	}

	@isTest
	private static void searchByProvincia() {
		EfectorSearchController.Response resp = EfectorSearchController.search('', 'C', '');
		EfectorSearchController.Response resp2 = EfectorSearchController.search('', 'B', '');

		System.assertEquals('Efector Test0', resp.efectores[0].Efector__r.Name);
		System.assertEquals('123450', resp.efectores[0].Efector__r.Codigo_de_efector__c);
		System.assertEquals('Efector Test1', resp2.efectores[0].Efector__r.Name);
		System.assertEquals('123451', resp2.efectores[0].Efector__r.Codigo_de_efector__c);
	}

	@isTest
	private static void searchByLocalidad() {
		EfectorSearchController.Response resp = EfectorSearchController.search('', '', 'Test');
		
		System.assertEquals(3, resp.efectores.size());
	}
}