force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Es_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Es_Prestador__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>En caso de que sea prestador, la casilla estará activa. Deberá completar los campos correspondientes a la sección Prestador</inlineHelpText>
    <label>Es Prestador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resolucion Front</fullName>
            </value>
            <value>
                <fullName>Resolucion Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos (Prestador)</relationshipLabel>
    <relationshipName>Casos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de cuenta</description>
    <formula>TEXT(Account.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autorizacion_previa.recordType-meta.xml
<RecordType>
    <fullName>Autorizacion_previa</fullName>
    <active>true</active>
    <businessProcess>Autorizacion previa</businessProcess>
    <label>Autorización previa</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Seguimiento</fullName>
    <active>true</active>
    <businessProcess>Seguimiento</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <formula>Codigo_Nomenclador__r.Prestacion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prestación</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Prestador)</relationshipLabel>
    <relationshipName>Eventos_Medicosp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto costo</fullName>
            </value>
            <value>
                <fullName>Celiaco</fullName>
            </value>
            <value>
                <fullName>Clinico</fullName>
            </value>
            <value>
                <fullName>Covid</fullName>
            </value>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Discapacidad</fullName>
            </value>
            <value>
                <fullName>Esclero</fullName>
            </value>
            <value>
                <fullName>Fertilidad</fullName>
            </value>
            <value>
                <fullName>Hepatitis</fullName>
            </value>
            <value>
                <fullName>HIV</fullName>
            </value>
            <value>
                <fullName>Leches</fullName>
            </value>
            <value>
                <fullName>Oxigenoterapia</fullName>
            </value>
            <value>
                <fullName>Programa Cronicos</fullName>
            </value>
            <value>
                <fullName>Provision Anticonceptivos</fullName>
            </value>
            <value>
                <fullName>Provision Oncologicos</fullName>
            </value>
            <value>
                <fullName>Quirurgico</fullName>
            </value>
            <value>
                <fullName>Transplante</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Anticonceptivos</fullName>
                <isActive>false</isActive>
                <label>Anticonceptivos</label>
            </value>
            <value>
                <fullName>EMS Discapacidad</fullName>
                <isActive>false</isActive>
                <label>EMS Discapacidad</label>
            </value>
            <value>
                <fullName>EMS Fertilidad</fullName>
                <isActive>false</isActive>
                <label>EMS Fertilidad</label>
            </value>
            <value>
                <fullName>EMS Oxigenoterapia</fullName>
                <isActive>false</isActive>
                <label>EMS Oxigenoterapia</label>
            </value>
            <value>
                <fullName>EMS Trasplante</fullName>
                <isActive>false</isActive>
                <label>EMS Trasplante</label>
            </value>
            <value>
                <fullName>Internacion</fullName>
                <isActive>false</isActive>
                <label>Internacion</label>
            </value>
            <value>
                <fullName>Internacion Domiciliaria</fullName>
                <isActive>false</isActive>
                <label>Internacion Domiciliaria</label>
            </value>
            <value>
                <fullName>Provision de Oncologicos</fullName>
                <isActive>false</isActive>
                <label>Provision de Oncologicos</label>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion</label>
            </value>
            <value>
                <fullName>Trastornos Alimentarios</fullName>
                <isActive>false</isActive>
                <label>Trastornos Alimentarios</label>
            </value>
            <value>
                <fullName>Tratamiento Adicciones</fullName>
                <isActive>false</isActive>
                <label>Tratamiento Adicciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_seguimiento.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_seguimiento</fullName>
    <active>true</active>
    <label>Evento médico de seguimiento</label>
</RecordType>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>Nomenclador</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Medicamento</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Grupo de prestacion</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseEmitirOrdenBtnCtrlTest.cls
@isTest 
private class CaseEmitirOrdenBtnCtrlTest {

	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getErrorResponse;
	static User usuarioFront;
	static User usuarioMesa;
	static CaseTeamRole caseRole;
	//static Case caso;
	static Case casoSeguimiento;
	static Prestacion__c prestacion;
	static Prestacion__c prestacion2;
	static Alerta__c alerta1;
	static Alerta__c alerta2;
	static Alerta__c alerta3;

    static {
		System.runAs(new User(Id = UserInfo.getUserId())) {
			String uniqueUserName = 'standarduserAnularCase' + DateTime.now().getTime() + '@testorg.com';
			Profile pFront = [SELECT Id FROM Profile WHERE Name='Front'];
			UserRole role = [SELECT Id,Name FROM UserRole WHERE Name = 'Administrador'];
			usuarioFront = new User(Alias = 'standt', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='es',
					LocaleSidKey='es_AR', TimeZoneSidKey='America/Argentina/Buenos_Aires',
					UserName=uniqueUserName + 'Front', ProfileId = pFront.Id, UserRoleId = role.Id);
			insert usuarioFront;

			Profile pMesa = [SELECT Id FROM Profile WHERE Name='Mesa de ayuda'];
			usuarioMesa = new User(Alias = 'standt', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='es',
					LocaleSidKey='es_AR', TimeZoneSidKey='America/Argentina/Buenos_Aires',
					UserName=uniqueUserName + 'Mesa', ProfileId = pMesa.Id, UserRole = role);
			insert usuarioMesa;

			List<Group> groupFront = [SELECT Id, Name FROM Group WHERE DeveloperName = 'Front'];
			GroupMember groupMemberF = new GroupMember(groupId = groupFront[0].Id, UserOrGroupId = usuarioFront.Id);
			insert groupMemberF;

			List<Group> groupMesa = [SELECT Id, Name FROM Group WHERE DeveloperName = 'Mesa_de_ayuda'];
			GroupMember groupMemberM = new GroupMember(groupId = groupMesa[0].Id, UserOrGroupId = usuarioMesa.Id);
			insert groupMemberM;

			caseRole = new CaseTeamRole();
			caseRole.Name = 'Cel Test';
			caseRole.AccessLevel = 'Edit';

			insert caseRole;
		}

		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSAuthTokenMock.getTokenSuccess())
				.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSCaseAPEmitirOrdenMock.getFound())
				.addForAddress(WSCaseAPEmitirOrden.SERVICE_CONFIG.URL__c + '/v1/salud/autorizaciones/orden-ap/generar/12345678');
		getErrorResponse = new XHttpCalloutMock();
		getErrorResponse.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSAuthTokenMock.getTokenSuccess())
				.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getErrorResponse.buildResponse()
				.withStatus('La autorización solicitada es inválida.')
				.withStatusCode(404)
				.withBody(WSCasoEnviarASSMock.getError())
				.addForAddress(WSCaseAPEmitirOrden.SERVICE_CONFIG.URL__c + '/v1/salud/autorizaciones/orden-ap/generar/12345678');

		casoSeguimiento = new Case();
		casoSeguimiento.RecordTypeId = XappiaHelper.getRecordType('Case', 'Seguimiento').Id;
		casoSeguimiento.Nro_AP__c = '12345678';

	}

	@isTest
	private static void validCaseChangesStatusWhenCaseEmitirOrden() {
		Test.setMock(HttpCalloutMock.class,getResponseFound);
		Case caso = new Case();
		caso.Status = 'CA-----A	';
		caso.Nro_AP__c = '12345678';
		insert caso;

		Test.startTest();
		CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(caso.Nro_AP__c);
		Test.stopTest();

		Case caseToAssert = [SELECT Status FROM Case];
		System.assertEquals('CA-----E', caseToAssert.Status);
	}

//------------------------------------------------------------------------------------
	@isTest
	private static void validateUserWhenNoBelongsToFrontQueueAndCaseIsNivel1() {
		CaseEmitirOrdenBtnCtrl.Response resp;
		System.runAs(usuarioMesa) {
			Case newCaso = new Case();
			newCaso.Nro_AP__c = '12345678';
			newCaso.Status = 'CA-----A';
			newCaso.Nivel_de_derivacion__c = 'Nivel 1';
			insert newCaso;

			Test.startTest();
			resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(newCaso.Nro_AP__c);
			Test.stopTest();
		}

		System.assertEquals('- El usuario no pertenece a Front', resp.message);
	}

	@isTest
	private static void validateUserWhenNoBelongsToMesaQueueAndCaseIsNivel2() {
		CaseEmitirOrdenBtnCtrl.Response resp;
		System.runAs(usuarioFront) {
			Case newCaso = new Case();
			newCaso.Nro_AP__c = '12345678';
			newCaso.Status = 'CA-----A';
			newCaso.Nivel_de_derivacion__c = 'Nivel 2';
			insert newCaso;

			Test.startTest();
			resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(newCaso.Nro_AP__c);
			Test.stopTest();
		}

		System.assertEquals('- El usuario no pertenece a Mesa de Ayuda', resp.message);
	}

	@isTest
	private static void validateUserWhenNoBelongsToTeamCaseAndCaseIsNivel3() {
		CaseEmitirOrdenBtnCtrl.Response resp;
		System.runAs(usuarioMesa) {
			Case newCaso = new Case();
			newCaso.Nro_AP__c = '12345678';
			newCaso.Status = 'CA-----A';
			newCaso.Nivel_de_derivacion__c = 'Nivel 3';
			insert newCaso;

			Test.startTest();
			resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(newCaso.Nro_AP__c);
			Test.stopTest();
		}

		System.assertEquals('- El usuario no pertenece al equipo del caso', resp.message);
	}

	@isTest
	private static void whenAFrontUserBelongsToFrontQueue_revertirAP() {
		CaseEmitirOrdenBtnCtrl.Response resp;
		Case newCaso = new Case();

		System.runAs(usuarioFront) {
			newCaso.Nro_AP__c = '12345678';
			newCaso.Status = 'CA-----A';
			newCaso.Nivel_de_derivacion__c = 'Nivel 3';
			insert newCaso;

			System.runAs(new User(Id = UserInfo.getUserId())) {
				insert new CaseTeamMember(ParentId = newCaso.Id, MemberId = usuarioFront.Id, TeamRoleId = caseRole.Id);
			}

			Test.setMock(HttpCalloutMock.class,getResponseFound);
			Test.startTest();
			resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(newCaso.Nro_AP__c);
			Test.stopTest();
		}

		Case casoToAssert = [SELECT Status FROM Case WHERE Id =: newCaso.Id];

		System.assertEquals('ok', resp.message);
		System.assertEquals('CA-----E', casoToAssert.Status);
	}

	@IsTest
	private static void emitirOrdenWhenRTIsSeguimiento() {
		casoSeguimiento.Status = 'Autorizada';

		insert casoSeguimiento;

		Test.startTest();
		CaseEmitirOrdenBtnCtrl.Response resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(casoSeguimiento.Nro_AP__c);
		Test.stopTest();

		casoSeguimiento = [SELECT Status FROM Case WHERE Id =: casoSeguimiento.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('ok', resp.message);
		System.assertEquals('CA-----E', casoSeguimiento.Status);
	}

	@IsTest 
	private static void WhenRTIsSeguimientoAndStatusIsNotAutorizada_showValidationErrorMsg() {
		casoSeguimiento.Status = 'CA-----G';

		insert casoSeguimiento;

		Test.startTest();
		CaseEmitirOrdenBtnCtrl.Response resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(casoSeguimiento.Nro_AP__c);
		Test.stopTest();

		casoSeguimiento = [SELECT Status FROM Case WHERE Id =: casoSeguimiento.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('El estado debe estar autorizado para poder emitir la orden', resp.message);
		System.assertEquals('CA-----G', casoSeguimiento.Status);
	}

	@IsTest 
	private static void emitirOrdenAndSendEmailWhenTypeIsCOVID() {
		Account prestador = Build.anAccountEfector().build();
		prestador.Es_Prestador__c = true;
		prestador.Correo_electronico__c = 'test@test.com';
		insert prestador;

		Evento_medico__c emCovid = new Evento_medico__c();
		emCovid.RecordTypeId = XappiaHelper.getRecordType('Evento_medico__c', 'Evento_medico_de_seguimiento').Id;
		emCovid.Tipo__c = 'COVID';
		insert emCovid;

		Case aCase = new Case();
		aCase.RecordTypeId = XappiaHelper.getRecordType('Case', 'Autorizacion_previa').Id;
		aCase.Nro_AP__c = '12345678';
		aCase.Prestador__c = prestador.Id;
		aCase.Status = 'Autorizada';
		aCase.Evento_Medico__c = emCovid.Id;
		//aCase.Type= 'COVID';
		insert aCase;

		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		CaseEmitirOrdenBtnCtrl.Response resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(aCase.Nro_AP__c);
		Integer AfterInvocations = Limits.getEmailInvocations();
		Test.stopTest();

		aCase = [SELECT Status FROM Case WHERE Id =: aCase.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('ok', resp.message);
		System.assertEquals('CA-----E', aCase.Status);
		System.assertEquals(1, AfterInvocations);
	}

	//@isTest
	//private static void whenAFrontUserNotBelongsToDelegacion_showTheErrorMsg() {
		//Account delegacion = Build.anAccountDelegacion().withCodigoDeDelegacion('123456').build();
		//insert delegacion;
		
		//Case newCaso = new Case();
		//newCaso.Nro_AP__c = '1014009821';
		//newCaso.Status = 'CA-----A';
		//newCaso.Nivel_de_derivacion__c = 'Nivel 1';
		////newCaso.OwnerId = usuarioFront.Id;
		//insert newCaso;

		//newCaso.Delegacion__c = delegacion.Id;
		//update newCaso;

		//CaseEmitirOrdenBtnCtrl.Response resp;
		//System.runAs(usuarioFront) {	
			//Test.startTest();
			//resp = CaseEmitirOrdenBtnCtrl.changeStatusToOrdenEmitida(newCaso.Nro_AP__c);
			//Test.stopTest();
		//}

		//System.assertEquals('El usuario puede modificar casos de su delegación solamente', resp.message);

	//}
}