force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Es_Prestador__c.field-meta.xml
<CustomField>
    <fullName>Es_Prestador__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>En caso de que sea prestador, la casilla estará activa. Deberá completar los campos correspondientes a la sección Prestador</inlineHelpText>
    <label>Es Prestador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Evento_medico__c.Asociado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos (Prestador)</relationshipLabel>
    <relationshipName>Casos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/Cotizacion_Prestador__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Prestador</label>
    <nameField>
        <displayFormat>CPRES-{000000}</displayFormat>
        <label>Nombre de Cotizacion Prestador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Prestadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Mail_prestador__c.field-meta.xml
<CustomField>
    <fullName>Mail_prestador__c</fullName>
    <label>Mail prestador</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Orden_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Compra__c</fullName>
    <label>Orden de Compra</label>
    <referenceTo>Orden_de_Compra__c</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion_Prestador__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Efector</value>
        </filterItems>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cotizaciones Prestadores</relationshipLabel>
    <relationshipName>Cotizaciones_Prestadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Prestador__c.field-meta.xml
<CustomField>
    <fullName>Prestador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Es_Prestador__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Medicos (Prestador)</relationshipLabel>
    <relationshipName>Eventos_Medicosp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/Orden_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Orden de Compra</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Nombre de Orden de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orden_de_Compra__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordenes de Compras</relationshipLabel>
    <relationshipName>Ordenes_de_Compras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orden_de_Compra__c/fields/Estado_OC__c.field-meta.xml
<CustomField>
    <fullName>Estado_OC__c</fullName>
    <label>Estado OC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generada</fullName>
                <default>true</default>
                <label>Generada</label>
            </value>
            <value>
                <fullName>Pedido Cotizacion</fullName>
            </value>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>Diferencia Socio</fullName>
            </value>
            <value>
                <fullName>Desestimada</fullName>
            </value>
            <value>
                <fullName>Ctro Aut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdenDeCompraEnvioMailBtnCtrlTest.cls
@isTest 
private class OrdenDeCompraEnvioMailBtnCtrlTest {

	static Orden_de_Compra__c orden;
	static Cotizacion_Prestador__c cotPres;
	static Case caso;
	static Evento_medico__c em;

	static {
		em = new Evento_medico__c();
		insert em;

		caso = new Case();
		caso.Evento_Medico__c = em.Id;
		insert caso;

		orden = new Orden_de_Compra__c();
		orden.Caso__c = caso.Id;
		insert orden;

		Account acc = Build.anAccountEfector().build();
		acc.Correo_electronico__c = 'test@gmail.com';
		acc.Es_Prestador__c = true;
		insert acc;

		cotPres = new Cotizacion_Prestador__c();
		cotPres.Mail_prestador__c = 'test@gmail.com';
		cotPres.Orden_de_Compra__c = orden.Id;
		cotPres.Prestador__c = acc.Id;
		insert cotPres;
	} 


	@isTest
	private static void testSendEmailWithAttachment() {
		ContentVersion version = new ContentVersion();
        version.PathOnClient = '/' + 'PRESCRIP_TEST';
        version.origin = 'H';
        version.Title = 'PRESCRIP_TEST';
        Blob pdfBody;
		pdfBody = Blob.valueOf('Test File');
        version.VersionData = pdfBody;
		insert version;

		ContentVersion updatedContent = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :version.Id FOR UPDATE];

		ContentDocumentLink documentLink = new ContentDocumentLink();
        documentLink.ContentDocumentId = updatedContent.ContentDocumentId;
        documentLink.LinkedEntityId = caso.Id;
        documentLink.ShareType = 'V';

		insert documentLink;

		Test.startTest();
		OrdenDeCompraEnvioMailBtnCtrl.Response resp = OrdenDeCompraEnvioMailBtnCtrl.sendAttachmentsToAllPrest(orden.Id);
		Test.stopTest();

		Orden_de_Compra__c orden = [
			SELECT Id, Estado_OC__c
			FROM Orden_de_Compra__c
			WHERE Id = :orden.Id
		];

		System.assertEquals(false,resp.hasError);
		System.assertEquals('Se realizó el envío de mails',resp.message);
		System.assertEquals('Pedido Cotizacion', orden.Estado_OC__c);

	}

	

	@isTest
	private static void testSendEmailWithNoAttachment_ShouldReturnErrorMsg() {
		Test.startTest();
		OrdenDeCompraEnvioMailBtnCtrl.Response resp = OrdenDeCompraEnvioMailBtnCtrl.sendAttachmentsToAllPrest(orden.Id);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.assertEquals('No se encontro ningun adjunto que contenga PRESCRI',resp.message);

	}

		@isTest
	private static void testSendEmailWithNoAttachmentWithPRESCRIPPrefix_ShouldReturnErrorMsg() {

		ContentVersion version = new ContentVersion();
        version.PathOnClient = '/' + 'TEST';
        version.origin = 'H';
        version.Title = 'TEST';
        Blob pdfBody;
		pdfBody = Blob.valueOf('Test File');
        version.VersionData = pdfBody;
		insert version;

		ContentVersion updatedContent = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :version.Id FOR UPDATE];

		ContentDocumentLink documentLink = new ContentDocumentLink();
        documentLink.ContentDocumentId = updatedContent.ContentDocumentId;
        documentLink.LinkedEntityId = caso.Id;
        documentLink.ShareType = 'V';

		insert documentLink;

		Test.startTest();
		OrdenDeCompraEnvioMailBtnCtrl.Response resp = OrdenDeCompraEnvioMailBtnCtrl.sendAttachmentsToAllPrest(orden.Id);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.assertEquals('No se encontro ningun adjunto que contenga PRESCRI', resp.message);

	}


		@isTest
	private static void testSendEmailWithNoCotizacionAssociated_ShouldReturnErrorMsg() {

		Orden_de_Compra__c sOrden = new Orden_de_Compra__c();
		insert sOrden;

		Test.startTest();
		OrdenDeCompraEnvioMailBtnCtrl.Response resp = OrdenDeCompraEnvioMailBtnCtrl.sendAttachmentsToAllPrest(sOrden.Id);
		Test.stopTest();

		System.assertEquals(true, resp.hasError);
		System.assertEquals('La orden de compra no tiene ninguna cotización', resp.message);

	}
}