force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Telefono__c</fullName>
    <label>Tipo de Teléfono</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Telefono</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Empresa.recordType-meta.xml
<RecordType>
    <fullName>Empresa</fullName>
    <active>true</active>
    <label>Empresa</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Corporativo</fullName>
    <active>true</active>
    <businessProcess>Corporativo</businessProcess>
    <description>Tipo de registro exclusivo para ventas de tipo Corporativas</description>
    <label>Corporativo</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Es_corporativo__c.field-meta.xml
<CustomField>
    <fullName>Es_corporativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es corporativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Telefono__c</fullName>
    <label>Tipo de Teléfono</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Telefono</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Corporativo</fullName>
    <active>true</active>
    <businessProcess>Venta Corporativa</businessProcess>
    <description>Tipo de registro exclusivo para ventas corporativas</description>
    <label>Corporativo</label>
</RecordType>

force-app/main/default/objects/Telefono__c/Telefono__c.object-meta.xml
<CustomObject>
    <label>Telefono</label>
    <nameField>
        <displayFormat>TEL-{000000000}</displayFormat>
        <label>Nombre de Telefono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telefonos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Telefono__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ConvertLeadController.cls
public class ConvertLeadController  {

	@AuraEnabled
	public static Id convertLead(Id leadId,String newStatus){
		Lead theLead = [SELECT Id, Company, Conversion_manual__c,MobilePhone,Phone,Email, RecordType.Name ,Status FROM Lead WHERE Id = :leadId];
		theLead.Status = newStatus;
		if(theLead.Status == 'Contactado - Interesado'){
			theLead.Conversion_manual__c = true;
		}
		System.debug(theLead);
		Account corp;
		if(theLead.RecordType.Name == 'Corporativo'){
			theLead.Es_corporativo__c = true;
			corp = new Account(Name = theLead.Company);
			corp.RecordTypeId = XappiaHelper.getRecordType('Account','Empresa').Id;
			insert corp;
		}
		update theLead;
		if(theLead.Status == 'Contactado - Interesado'){
			LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];

			Database.LeadConvert lc = new Database.LeadConvert();
			lc.setLeadId(theLead.id);
			lc.setOwnerId(UserInfo.getUserId());
			lc.setConvertedStatus(convertStatus.MasterLabel);
			lc.setDoNotCreateOpportunity(false);
			if(theLead.RecordType.Name == 'Corporativo'){
				lc.setAccountId(corp.Id);
			}
			
			Database.LeadConvertResult res =  Database.convertLead(lc);
			System.debug(res);

			if(res.isSuccess()){
				List<Opportunity> oppCreated = [SELECT Id,Telefono__c FROM Opportunity WHERE Id = :res.getOpportunityId()];
				if(!oppCreated.isEmpty()){
					Opportunity opp = oppCreated.get(0);
					
					//if(String.isNotBlank(theLead.MobilePhone)) {
						opp.Telefono__c = String.isNotBlank(theLead.MobilePhone) ? theLead.MobilePhone : theLead.Phone;
						opp.Tipo_de_Telefono__c = String.isNotBlank(theLead.MobilePhone) ? 'CEL' : 'TEL';
					//}
					//else {
						//opp.Telefono__c = theLead.Phone;
						//opp.Tipo_de_Telefono__c = 'CEL';
					//}
					update opp;
				}
				if(theLead.RecordType.Name != 'Corporativo'){
					List<Account> accountCreated = [SELECT Id,Correo_electronico__c,Tipo_de_Telefono__c,Type FROM Account WHERE Id = :res.getAccountId()];
					if(!accountCreated.isEmpty()){
						Account accToUpdate = accountCreated.get(0);
						accToUpdate.Correo_electronico__c = theLead.Email;
						accToUpdate.Type = 'Titular';
						
						if(theLead.MobilePhone != null) {
							accToUpdate.Tipo_de_Telefono__c = 'CEL';
							accToUpdate.Phone = theLead.MobilePhone;
						}
						else{
							accToUpdate.Tipo_de_Telefono__c = 'TEL';
						}

						update accToUpdate;
					}
					return res.getAccountId();
				}
				return res.getContactId();
				
			}else{
				throw new LeadConvertionException();
			}

		}
		return null;
	}

	public class LeadConvertionException extends Exception{
	}

}