force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  PersonBirthdate  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(PersonBirthdate), 
				AND( 
					MONTH(TODAY()) == MONTH(PersonBirthdate), 
					DAY(TODAY()) &lt; DAY(PersonBirthdate) 
					) 
		), 
	1, 
	0 
	)

/*IF( NOT( ISBLANK(  PersonBirthdate  ) ) ,
  IF( DATE( 2000 , MONTH( PersonBirthdate ) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( PersonBirthdate ),
     YEAR (Today()) - YEAR ( PersonBirthdate ) -1 ),
  null)*/</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Casado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Soltero</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Concubinato</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Separado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_documento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{0000}</displayFormat>
        <label>Nombre de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion__c/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <label>Correo electrónico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <label>Edad</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Edad_conyuge__c.field-meta.xml
<CustomField>
    <fullName>Edad_conyuge__c</fullName>
    <label>Edad cónyuge</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Estado_Civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_Civil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Civil</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_entre_21_y_25_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_entre_21_y_25_aos__c</fullName>
    <label>Hijos entre 21 y 25 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_hasta_20_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_hasta_20_aos__c</fullName>
    <label>Hijos hasta 20 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Localidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Nombre_y_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_Apellido__c</fullName>
    <label>Nombre y Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Nro_Cotizacion_Corporativa__c.field-meta.xml
<CustomField>
    <fullName>Nro_Cotizacion_Corporativa__c</fullName>
    <externalId>true</externalId>
    <label>Nro. Cotización Corporativa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Nro_cotizacion_individual__c.field-meta.xml
<CustomField>
    <fullName>Nro_cotizacion_individual__c</fullName>
    <externalId>true</externalId>
    <label>Nro. Cotización Individual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Nro_de_Documento__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Documento__c</fullName>
    <label>Nro. de Documento</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad de cotización</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Pago_con_debito__c.field-meta.xml
<CustomField>
    <fullName>Pago_con_debito__c</fullName>
    <label>Pago con débito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Débito/CBU</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Tarjeta de Crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Plan_a_cotizar__c.field-meta.xml
<CustomField>
    <fullName>Plan_a_cotizar__c</fullName>
    <label>Plán a cotizar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AS100</fullName>
            </value>
            <value>
                <fullName>AS200</fullName>
            </value>
            <value>
                <fullName>AS204</fullName>
            </value>
            <value>
                <fullName>AS300</fullName>
            </value>
            <value>
                <fullName>AS400</fullName>
            </value>
            <value>
                <fullName>AS500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Precio_1er_hijo_menor_21_aos__c.field-meta.xml
<CustomField>
    <fullName>Precio_1er_hijo_menor_21_aos__c</fullName>
    <label>Precio 1er hijo menor 21 años</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Precio_Titular__c.field-meta.xml
<CustomField>
    <fullName>Precio_Titular__c</fullName>
    <label>Precio Titular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Telfono__c.field-meta.xml
<CustomField>
    <fullName>Telfono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_afiliado__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_afiliado__c</fullName>
    <label>Tipo de afiliado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Voluntario</fullName>
            </value>
            <value>
                <fullName>Relacion de Dependencia</fullName>
                <label>Relación de dependencia</label>
            </value>
            <value>
                <fullName>Monotributista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_contacto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_contacto__c</fullName>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Individuo</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Grupo familiar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Documento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Total_de_capitas_cotizadas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_capitas_cotizadas__c</fullName>
    <label>Total de cápitas cotizadas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  Fecha_de_Nacimiento__c  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(Fecha_de_Nacimiento__c), 
				AND( 
					MONTH(TODAY()) == MONTH(Fecha_de_Nacimiento__c), 
					DAY(TODAY()) &lt; DAY(Fecha_de_Nacimiento__c) 
					) 
		), 
	1, 
	0 
	)</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estado_Civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_Civil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Civil</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Piso__c.field-meta.xml
<CustomField>
    <fullName>Piso__c</fullName>
    <label>Piso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plan_Grupo_Corporativo__c.field-meta.xml
<CustomField>
    <fullName>Plan_Grupo_Corporativo__c</fullName>
    <label>Plan de Grupo Corporativo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS200</fullName>
            </value>
            <value>
                <fullName>AS204</fullName>
            </value>
            <value>
                <fullName>AS300</fullName>
            </value>
            <value>
                <fullName>AS400</fullName>
            </value>
            <value>
                <fullName>AS500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Documento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_mercado__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_mercado__c</fullName>
    <label>Tipo de mercado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Canal Corporativo</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>La segunda</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Gestión compartida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Corporativo.recordType-meta.xml
<RecordType>
    <fullName>Corporativo</fullName>
    <active>true</active>
    <businessProcess>Venta Corporativa</businessProcess>
    <description>Tipo de registro exclusivo para ventas corporativas</description>
    <label>Corporativo</label>
</RecordType>

force-app/main/default/classes/CotizadorBtnCtrlTest.cls
@isTest 
private class CotizadorBtnCtrlTest {
	static XHttpCalloutMock getResponseFoundInd;
	static XHttpCalloutMock getResponseFoundCorp;
	static XHttpCalloutMock getErrorInd;
	static XHttpCalloutMock getErrorCorp;
	static XHttpCalloutMock responseFound;

	static {
		getResponseFoundInd = new XHttpCalloutMock();
		getResponseFoundInd.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSAuthTokenMock.getTokenSuccess())
				.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundInd.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSCotizadorMock.getFound())
				.addForAddress(WSCotizador.SERVICE_CONFIG.URL__c + '/v1/cotizador/cotizaciones');

		getErrorInd = new XHttpCalloutMock();
		getErrorInd.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSAuthTokenMock.getTokenSuccess())
				.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getErrorInd.buildResponse()
				.withStatus('El campo tipo dni id es obligatorio.')
				.withStatusCode(422)
				.withBody(WSCotizadorMock.getError())
				.addForAddress(WSCotizador.SERVICE_CONFIG.URL__c + '/v1/cotizador/cotizaciones');

		getResponseFoundCorp = new XHttpCalloutMock();
		getResponseFoundCorp.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSAuthTokenMock.getTokenSuccess())
				.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFoundCorp.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSCotizadorMock.getFoundCorporativa())
				.addForAddress(WSCotizador.SERVICE_CONFIG.URL__c + '/v1/cotizador/corporativa/cotizaciones');
		getResponseFoundCorp.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSCotizadorCorporativaPDFMock.getFound())
				.addForAddress(WSCotizador.SERVICE_CONFIG.URL__c + '/v1/cotizador/corporativa/cotizaciones/print/310606');


		responseFound = new XHttpCalloutMock();
        responseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        responseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSCotizadorGetPDFMock.getResponseFound())
                .addForAddress(WSCotizador.SERVICE_CONFIG.URL__c + '/v1/cotizador/cotizaciones/print/731');

		
	}


	@isTest
	private static void testCotizacionCorp() {
		Test.setMock(HttpCalloutMock.class,getResponseFoundCorp);
		Opportunity op = new Opportunity(Calle__c='falsa',Name='Prueba test',CloseDate=Date.today(),
		StageName='Contactado',Numero__c=123,Piso__c='1',RecordTypeId = XappiaHelper.getRecordType('Opportunity','Corporativo').Id);
		op.Plan_Grupo_Corporativo__c = 'AS200';
		op.Tipo_de_mercado__c = '1';
		insert op;
		ContentVersion ver = new ContentVersion(VersionData=Blob.valueOf('test'),Title='Prueba',PathOnClient='/prueba');
		insert ver;
		ContentVersion updatedVer = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :ver.Id];
		Test.startTest();
		CotizadorBtnCtrl.Response cotResp = CotizadorBtnCtrl.sendToWSCotizadorCorp(op.Id,updatedVer.ContentDocumentId);
		Test.stopTest();
		System.debug(cotResp);

		System.assertEquals(false,cotResp.hasError);
		
		Cotizacion__c cot = [SELECT Id, Nro_Cotizacion_Corporativa__c FROM Cotizacion__c];
		System.assertEquals('310606', cot.Nro_Cotizacion_Corporativa__c);

		ContentDocumentLink[] cdls = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :cot.Id];
		System.assertEquals(2, cdls.size());
		Id[] cdIds = new List<Id>{cdls[0].ContentDocumentId, cdls[1].ContentDocumentId};

		ContentDocument[] cdXLSX = [SELECT Id, FileType FROM ContentDocument WHERE Id IN :cdIds AND FileExtension = 'xlsx'];
		ContentDocument[] cdPDF = [SELECT Id, FileType FROM ContentDocument WHERE Id IN :cdIds AND FileType = 'PDF'];
		System.assertEquals(1, cdXLSX.size());
		System.assertEquals(1, cdPDF.size());
	}


	@isTest
	private static void testCotizacionInd() {
		Localidad__c loc = Build.aLocalidad()
			.withLocId('123')
			.withNombreLocalidad('Ciudadela')
			.withCodigoPostal('1702')
			.withCodigoProvincia('B')
			.withOrganizador(UserInfo.getUserId())
			.build();
		insert loc;
		Test.setMock(HttpCalloutMock.class,getResponseFoundInd);
		Account ac = Build.anAccountCuentapersonal().build();
		insert ac;
		Opportunity op = new Opportunity(Calle__c='falsa',Name='Prueba test',CloseDate=Date.today(),
		StageName='Contactado',Numero__c=123,Piso__c='1');
		op.AccountId = ac.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Nombre_y_Apellido__c='Prueba test',Edad__c=20,
		Tipo_de_Documento__c='DNI',Nro_de_Documento__c=100000,Localidad__c='1349',Estado_Civil__c='C',
		Edad_conyuge__c=20,Telfono__c='161651',Tipo_de_afiliado__c='Voluntario',
		Tipo_de_contacto__c='2',Hijos_hasta_20_aos__c=0,Hijos_entre_21_y_25_aos__c=0,
		Correo_electronico__c='pepito@test.com',Pago_con_debito__c='1',
		Plan_a_cotizar__c='AS200');
		coti.Localidad_new__c = loc.Id;
		coti.Oportunidad__c = op.Id;
		insert coti;

		Test.startTest();
		CotizadorBtnCtrl.Response cotResp = CotizadorBtnCtrl.sendToWSCotizadorInd(coti.Id);
		Test.stopTest();

		System.assertEquals(false,cotResp.hasError);
		Cotizacion__c updatedCot = [
			SELECT Id,Total_de_capitas_cotizadas__c, Nro_cotizacion_individual__c,Precio_Titular__c,
			Precio_1er_hijo_menor_21_aos__c,Precio_Conyuge__c,Precio_hijo_entre_21_y_25_aos__c,Precio_total__c,
			Deduccion_de_aportes__c,Deduccin_de_aportes_Monotributo__c,Bonif_especial_6_meses__c,
			Dto_pago_con_tarjeta_de_credito__c,Diferencia_a_pagar__c,Precio_2do_hijo_menor_21_aos__c,Precio_3er_hijo_menor_21_aos__c 
			FROM Cotizacion__c 
			WHERE Id = :coti.Id
		];
		System.assertEquals('4',updatedCot.Total_de_capitas_cotizadas__c);
		System.assertEquals(null,updatedCot.Nro_cotizacion_individual__c);
		System.assertEquals('3192.95',updatedCot.Precio_Titular__c);
		System.assertEquals(null,updatedCot.Precio_1er_hijo_menor_21_aos__c);
		System.assertEquals('2313.67',updatedCot.Precio_Conyuge__c);
		System.assertEquals('2553.21',updatedCot.Precio_hijo_entre_21_y_25_aos__c);
		System.assertEquals('8059.84',updatedCot.Precio_total__c);
		System.assertEquals('32500',updatedCot.Deduccion_de_aportes__c);
		System.assertEquals(null,updatedCot.Deduccin_de_aportes_Monotributo__c);
		System.assertEquals('805.98',updatedCot.Bonif_especial_6_meses__c);
		System.assertEquals(null,updatedCot.Dto_pago_con_tarjeta_de_credito__c);
		System.assertEquals('2794.88',updatedCot.Diferencia_a_pagar__c);
		System.assertEquals(null,updatedCot.Precio_2do_hijo_menor_21_aos__c);
		System.assertEquals(null,updatedCot.Precio_3er_hijo_menor_21_aos__c);

	}

	@isTest
	private static void testCotizacionIndFails() {
		Test.setMock(HttpCalloutMock.class,getErrorInd);
		Account ac = Build.anAccountCuentapersonal().build();
		insert ac;
		Opportunity op = new Opportunity(Calle__c='falsa',Name='Prueba test',CloseDate=Date.today(),
		StageName='Contactado',Numero__c=123,Piso__c='1');
		op.AccountId = ac.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Nombre_y_Apellido__c='Prueba test',Edad__c=20,
		Tipo_de_Documento__c='DNI',Nro_de_Documento__c=0,Localidad__c='1349',Estado_Civil__c='C',
		Edad_conyuge__c=20,Telfono__c='161651',Tipo_de_afiliado__c='Voluntario',
		Tipo_de_contacto__c='2',Hijos_hasta_20_aos__c=0,Hijos_entre_21_y_25_aos__c=0,
		Correo_electronico__c='pepito@test.com',Pago_con_debito__c='1',
		Plan_a_cotizar__c='AS200');
		coti.Oportunidad__c = op.Id;
		insert coti;

		Test.startTest();
		CotizadorBtnCtrl.Response cotResp = CotizadorBtnCtrl.sendToWSCotizadorInd(coti.Id);
		Test.stopTest();

		System.assertEquals(true,cotResp.hasError);

	}

	@IsTest
	private static void getPdfFromCotizacion(){
		Test.setMock(HttpCalloutMock.class, responseFound);
		Localidad__c loc = Build.aLocalidad()
			.withLocId('123')
			.withNombreLocalidad('Ciudadela')
			.withCodigoPostal('1702')
			.withCodigoProvincia('B')
			.withOrganizador(UserInfo.getUserId())
			.build();
		insert loc;
		Account ac = Build.anAccountCuentapersonal().build();
		insert ac;
		Opportunity op = new Opportunity(Calle__c='falsa',Name='Prueba test',CloseDate=Date.today(),
		StageName='Contactado',Numero__c=123,Piso__c='1');
		op.AccountId = ac.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Nombre_y_Apellido__c='Prueba test',Edad__c=20,
		Tipo_de_Documento__c='DNI',Nro_de_Documento__c=100000,Localidad__c='1349',Estado_Civil__c='C',
		Edad_conyuge__c=20,Telfono__c='161651',Tipo_de_afiliado__c='Voluntario',
		Tipo_de_contacto__c='2',Hijos_hasta_20_aos__c=0,Hijos_entre_21_y_25_aos__c=0,
		Correo_electronico__c='pepito@test.com',Pago_con_debito__c='1',
		Plan_a_cotizar__c='AS200');
		coti.Localidad_new__c = loc.Id;
		coti.Oportunidad__c = op.Id;
		coti.Nro_cotizacion_individual__c = '731';
		insert coti;

		Test.startTest();
		CotizadorBtnCtrl.generatePDF(coti.Id);
		Test.stopTest();
		List<ContentVersion> versions = [
			SELECT Id
			FROM ContentVersion
		];
		System.assertEquals(1,versions.size());
	}
}