force-app/main/default/objects/Account/fields/Correo_electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_electronico__c</fullName>
    <description>Correo electronico custom, creado para todas las cuentas menos los asociados</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  PersonBirthdate  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(PersonBirthdate), 
				AND( 
					MONTH(TODAY()) == MONTH(PersonBirthdate), 
					DAY(TODAY()) &lt; DAY(PersonBirthdate) 
					) 
		), 
	1, 
	0 
	)

/*IF( NOT( ISBLANK(  PersonBirthdate  ) ) ,
  IF( DATE( 2000 , MONTH( PersonBirthdate ) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( PersonBirthdate ),
     YEAR (Today()) - YEAR ( PersonBirthdate ) -1 ),
  null)*/</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prefijo__c.field-meta.xml
<CustomField>
    <fullName>Prefijo__c</fullName>
    <label>Prefijo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <defaultValue>&quot;Masculino&quot;</defaultValue>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Femenino</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_documento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integrante__c/Integrante__c.object-meta.xml
<CustomObject>
    <label>Integrante</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Nro. de Integrante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Integrante__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Cobertura_anterior__c.field-meta.xml
<CustomField>
    <fullName>Cobertura_anterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cobertura anterior</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Obra social</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integrantes</relationshipLabel>
    <relationshipName>Integrantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/CUIT_Sin_guiones__c.field-meta.xml
<CustomField>
    <fullName>CUIT_Sin_guiones__c</fullName>
    <label>CUIT (Sin guiones)</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Discapacitado__c.field-meta.xml
<CustomField>
    <fullName>Discapacitado__c</fullName>
    <label>Discapacitado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR( Fecha_de_Nacimiento__c ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(Fecha_de_Nacimiento__c), 
				AND( 
					MONTH(TODAY()) == MONTH(Fecha_de_Nacimiento__c), 
					DAY(TODAY()) &lt; DAY(Fecha_de_Nacimiento__c) 
					) 
		), 
	1, 
	0 
	)</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Indicador_de_aporte__c.field-meta.xml
<CustomField>
    <fullName>Indicador_de_aporte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indicador de aporte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nacionalidad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Nro_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_documento__c</fullName>
    <label>Nro. de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Integrantes Nuevos</relationshipLabel>
    <relationshipName>Integrantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Prefijo__c.field-meta.xml
<CustomField>
    <fullName>Prefijo__c</fullName>
    <label>Prefijo</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Telfono__c.field-meta.xml
<CustomField>
    <fullName>Telfono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Integrante__c/fields/Tipo_de_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Documento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Prefijo__c.field-meta.xml
<CustomField>
    <fullName>Prefijo__c</fullName>
    <label>Prefijo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Correo_Electronico__c.field-meta.xml
<CustomField>
    <fullName>Correo_Electronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>YEAR(TODAY()) - YEAR(  Fecha_de_Nacimiento__c  ) - 
	IF(
		OR( 
			MONTH(TODAY()) &lt; MONTH(Fecha_de_Nacimiento__c), 
				AND( 
					MONTH(TODAY()) == MONTH(Fecha_de_Nacimiento__c), 
					DAY(TODAY()) &lt; DAY(Fecha_de_Nacimiento__c) 
					) 
		), 
	1, 
	0 
	)</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>054</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>410</fullName>
                <label>España</label>
            </value>
            <value>
                <fullName>039</fullName>
                <label>Italia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brasil</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <label>Cuba</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>SV</fullName>
                <label>El Salvador</label>
            </value>
            <value>
                <fullName>502</fullName>
                <label>Guatemala</label>
            </value>
            <value>
                <fullName>504</fullName>
                <label>Honduras</label>
            </value>
            <value>
                <fullName>MX</fullName>
                <label>Mexico</label>
            </value>
            <value>
                <fullName>NI</fullName>
                <label>Nicaragua</label>
            </value>
            <value>
                <fullName>PA</fullName>
                <label>Panama</label>
            </value>
            <value>
                <fullName>PY</fullName>
                <label>Paraguay</label>
            </value>
            <value>
                <fullName>PE</fullName>
                <label>Peru</label>
            </value>
            <value>
                <fullName>809</fullName>
                <label>República Dominicana</label>
            </value>
            <value>
                <fullName>UY</fullName>
                <label>Uruguay</label>
            </value>
            <value>
                <fullName>VE</fullName>
                <label>Venezuela</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segmento_del_Grupo_Familiar__c.field-meta.xml
<CustomField>
    <fullName>Segmento_del_Grupo_Familiar__c</fullName>
    <label>Segmento del Grupo Familiar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VOLDIR</fullName>
            </value>
            <value>
                <fullName>OBLDIR</fullName>
            </value>
            <value>
                <fullName>VOLEMP</fullName>
            </value>
            <value>
                <fullName>OBLEMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Documento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Telefono__c/Telefono__c.object-meta.xml
<CustomObject>
    <label>Telefono</label>
    <nameField>
        <displayFormat>TEL-{000000000}</displayFormat>
        <label>Nombre de Telefono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Telefonos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Telefono__c/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/IntegranteHelper.cls
global class IntegranteHelper  {
	public static void fillContactInformationFromOpp(Map<String, List<Integrante__c>> opportunityIdIntegrantesMap) {
		List<Integrante__c> integrantesToUpdate = new List<Integrante__c>();
		for (Opportunity opp : [
			SELECT Account.Phone, Account.Prefijo__c, Account.Correo_electronico__c, Codigo_Postal__c, Telefono__c, 
				Correo_Electronico__c, Localidad_new__r.Codigo_Postal__c, Localidad_new__r.Prefijo__c
			FROM Opportunity 
			WHERE Id IN :opportunityIdIntegrantesMap.keySet()]) 
			{
			for (Integrante__c integrante : opportunityIdIntegrantesMap.get(opp.Id)) {
				
				integrante.Telfono__c = integrante.Telfono__c != null ? integrante.Telfono__c : opp.Telefono__c;
				integrante.Prefijo__c = integrante.Prefijo__c != null ? integrante.Prefijo__c 
										: opp.Account.Prefijo__c != null ? Integer.valueOf(opp.Account.Prefijo__c) : 0;
				integrante.Correo_electronico__c = integrante.Correo_electronico__c != null 
													? integrante.Correo_electronico__c : opp.Correo_Electronico__c;
				integrante.Codigo_Postal__c = integrante.Codigo_Postal__c != null 
												? integrante.Codigo_Postal__c : opp.Localidad_new__r.Codigo_Postal__c;

				//integrante.Telfono__c = integrante.Telfono__c != null ? integrante.Telfono__c : opp.Account.Phone;
				//integrante.Prefijo__c = integrante.Prefijo__c != null ? integrante.Prefijo__c 
										//: opp.Account.Prefijo__c != null ? Integer.valueOf(opp.Account.Prefijo__c) : null;
				//integrante.Correo_electronico__c = integrante.Correo_electronico__c != null 
													//? integrante.Correo_electronico__c : opp.Account.Correo_electronico__c;
				//System.debug(integrante.Codigo_Postal__c);
				//integrante.Codigo_Postal__c = integrante.Codigo_Postal__c != null 
												//? integrante.Codigo_Postal__c : opp.Localidad_new__r.Codigo_Postal__c;
				//System.debug('CPHelper ' + opp.Localidad_new__r.Codigo_Postal__c);
				//System.debug(integrante.Codigo_Postal__c);
                //integrantesToUpdate.add(integrante);
			}				
		}
	}
    
    public static void validateFields(List<Integrante__c> integrantes,Map<Id,Opportunity> oppMap){
        for(Integrante__c integrante : integrantes){
        	Opportunity opp = oppMap.get(integrante.Oportunidad__c);
			Boolean obligatorio = opp.Segmento_del_Grupo_Familiar__c == 'OBLDIR'
									|| opp.Segmento_del_Grupo_Familiar__c == 'OBLEMP';

            if(integrante.Apellido__c == null){
                integrante.Apellido__c.addError('Campo Apellido obligatorio');
            }
            if(integrante.Nombre__c == null){
                integrante.Nombre__c.addError('Campo Nombre obligatorio');
            }
            if(integrante.Fecha_de_Nacimiento__c == null){
                integrante.Fecha_de_Nacimiento__c.addError('Campo Fecha de Nacimiento obligatorio');
            }        
            if(integrante.Nacionalidad__c == null){
                integrante.Nacionalidad__c.addError('Campo Nacionalidad obligatorio');
            }
            if(integrante.Discapacitado__c == null){
                integrante.Discapacitado__c.addError('Campo Discapacitado obligatorio');
            }
            if(integrante.Prefijo__c == null){
                integrante.Prefijo__c.addError('Campo Prefijo obligatorio');
            }
            if(integrante.Tipo_de_Documento__c == null){
                integrante.Tipo_de_Documento__c.addError('Campo Tipo de Documento obligatorio');
            }
            if(integrante.Nro_de_documento__c == null){
                integrante.Nro_de_documento__c.addError('Campo Documento obligatorio');
            }
            if(integrante.CUIT_Sin_guiones__c == null && obligatorio && integrante.Indicador_de_aporte__c){
                integrante.CUIT_Sin_guiones__c.addError('Campo CUIT obligatorio con segmento OBLDIR/OBLEMP');
            }
            if(integrante.Edad__c == null){
                integrante.Edad__c.addError('Campo Edad obligatorio');
            }
            if(integrante.Sexo__c == null){
                integrante.Sexo__c.addError('Campo Sexo obligatorio');
            }
			// No puede estar en null porque es tipo check
            //if(integrante.Indicador_de_aporte__c == null && obligatorio){
                //integrante.Indicador_de_aporte__c.addError('Campo obligatorio');
            //}
            if(integrante.Aportes__c == null && integrante.Indicador_de_aporte__c && obligatorio){
                integrante.Aportes__c.addError('Campo Aportes obligatorio');
            }
            if(integrante.Cobertura_anterior__c == null &&
               (opp.Segmento_del_Grupo_Familiar__c == 'VOLDIR' ||
               opp.Segmento_del_Grupo_Familiar__c == 'VOLEMP' ||
               opp.Segmento_del_Grupo_Familiar__c == 'DTCAP')){
                integrante.Cobertura_anterior__c.addError('Campo Cobertura Anterior obligatorio con segmento VOLDIR/VOLEMP/DTCAP');
            }
            if(integrante.Obra_social_actual__c == null &&
              (opp.Segmento_del_Grupo_Familiar__c == 'VOLDIR' ||
               opp.Segmento_del_Grupo_Familiar__c == 'VOLEMP')){
                   integrante.Obra_social_actual__c.addError('Campo Obra Social obligatorio con segmento VOLDIR/VOLEMP');
               }
            if(integrante.Estado_Civil__c == null){
                integrante.Estado_Civil__c.addError('Campo Estado Civil obligatorio');
            }
            if(integrante.Tipo_de_relacion_con_titular__c == null){
                integrante.Tipo_de_relacion_con_titular__c.addError('Campo Tipo de relacion con titular obligatorio');
            }
        }
        
    }

	public static void updateRelatedAccounts(Map<String,String> dniAsociados){
		List<Account> asociados = [
			SELECT Codigo_de_Afiliado__c, Numero_de_documento__c
			FROM Account
			WHERE Numero_de_documento__c IN :dniAsociados.keySet()
		];
		List<Account> accsToUpdate = new List<Account>();
		for(Account asociado : asociados){
			System.debug(asociado.Codigo_de_Afiliado__c);
			if(asociado.Codigo_de_Afiliado__c == null){
				asociado.Codigo_de_Afiliado__c = dniAsociados.get(asociado.Numero_de_documento__c);
				accsToUpdate.add(asociado);
			}
		}
		System.debug(accsToUpdate);
		update accsToUpdate;
	}
}