force-app/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delegaciones</relationshipLabel>
    <relationshipName>Delegaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Delegacion.recordType-meta.xml
<RecordType>
    <fullName>Delegacion</fullName>
    <active>true</active>
    <description>Filiales y agencias</description>
    <label>Delegación</label>
</RecordType>

force-app/main/default/objects/Alerta__c/Alerta__c.object-meta.xml
<CustomObject>
    <label>Alerta</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nro de Alerta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alerta__c/fields/idalerta__c.field-meta.xml
<CustomField>
    <fullName>idalerta__c</fullName>
    <externalId>true</externalId>
    <label>idalerta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alerta__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Prestacion__c</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Caso_Rechazado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Rechazado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cuando se rechazan todas las prestaciones te rechaza el caso</description>
    <label>Caso Rechazado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Celula__c.field-meta.xml
<CustomField>
    <fullName>Celula__c</fullName>
    <label>Célula</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Celula 1</fullName>
                <label>Emi sin material</label>
            </value>
            <value>
                <fullName>Celula 2</fullName>
                <label>Trámites con material</label>
            </value>
            <value>
                <fullName>Celula 3</fullName>
                <label>Oxigenoterapia</label>
            </value>
            <value>
                <fullName>Celula 4</fullName>
                <label>Fertilidad</label>
            </value>
            <value>
                <fullName>Celula 5</fullName>
                <label>Célula 5</label>
            </value>
            <value>
                <fullName>Celula 6</fullName>
                <label>Programas</label>
            </value>
            <value>
                <fullName>Celula 7</fullName>
                <label>Medicación alto costo</label>
            </value>
            <value>
                <fullName>Celula 8</fullName>
                <label>Reintegros</label>
            </value>
            <value>
                <fullName>Celula 9</fullName>
                <label>Discapacidad</label>
            </value>
            <value>
                <fullName>Celula 10</fullName>
                <label>Célula 10</label>
            </value>
            <value>
                <fullName>Celula 11</fullName>
                <label>Falseamiento de DDJJ</label>
            </value>
            <value>
                <fullName>Celula 12</fullName>
                <label>IDOM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delegación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Delegación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nivel_de_derivacion__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_derivacion__c</fullName>
    <label>Nivel de derivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nivel 1</fullName>
            </value>
            <value>
                <fullName>Nivel 2</fullName>
            </value>
            <value>
                <fullName>Nivel 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nro_AP__c.field-meta.xml
<CustomField>
    <fullName>Nro_AP__c</fullName>
    <externalId>true</externalId>
    <label>Nro AP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo tipo de búsqueda con el objeto nomenclador de prestación, se usa para el tipo de registro en el objeto caso de expedientes legales, en la sección &quot;detalles del caso&quot;</description>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/Prestacion__c.object-meta.xml
<CustomObject>
    <label>Prestación</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Número de Prestación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prestaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestacion__c/fields/Alerta__c.field-meta.xml
<CustomField>
    <fullName>Alerta__c</fullName>
    <label>Alerta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAM</fullName>
            </value>
            <value>
                <fullName>SAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Ap__c.field-meta.xml
<CustomField>
    <fullName>Ap__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ap</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion__c.field-meta.xml
<CustomField>
    <fullName>Prestacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prestación</label>
    <referenceTo>Nomenclador_de_Prestacion__c</referenceTo>
    <relationshipName>Prestaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestacion__c/fields/Prestacion_CA__c.field-meta.xml
<CustomField>
    <fullName>Prestacion_CA__c</fullName>
    <externalId>true</externalId>
    <label>Prestacion CA</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseAutorizarAPRechazadaBtnCtrlTest.cls
@isTest 
private class CaseAutorizarAPRechazadaBtnCtrlTest {
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getErrorResponse;
	static Case caso;
	static Prestacion__c prestacion;
	static Alerta__c alerta;
	static Alerta__c alerta2;
	static User usuario;

	static {
		String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
		Profile pFront = [SELECT Id FROM Profile WHERE Name='Front'];
		UserRole role = [SELECT Id,Name FROM UserRole WHERE Name = 'Administrador'];
		usuario = new User(Alias = 'standt', Email='standarduser@testorg.com',
				EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='es',
				LocaleSidKey='es_AR', TimeZoneSidKey='America/Argentina/Buenos_Aires',
				UserName=uniqueUserName + 'Front', ProfileId = pFront.Id, UserRoleId = role.Id);
		System.runAs( new User( Id = UserInfo.getUserId() ) ) {
			insert usuario;
		}

        getResponseFound = new XHttpCalloutMock();
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSCaseAutorizarAPRechazadaMock.getFound())
                .addForAddress(WSCaseAutorizarAPRechazada.SERVICE_CONFIG.URL__c + '/v1/salud/autorizaciones/rechazadas/1014011025');
		getResponseFound.buildResponse()
				.withStatus('OK')
				.withStatusCode(200)
				.withBody(WSCaseAPEmitirOrdenMock.getFound())
				.addForAddress(WSCaseAPEmitirOrden.SERVICE_CONFIG.URL__c + '/v1/salud/autorizaciones/orden-ap/generar/1014011025');

		getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('Error')
                .withStatusCode(400)
                .withBody(WSCaseAutorizarAPRechazadaMock.getError())
                .addForAddress(WSCaseAutorizarAPRechazada.SERVICE_CONFIG.URL__c + '/v1/salud/autorizaciones/rechazadas/1014011025');		
	
		caso = new Case();
		caso.Nro_AP__c = '1014011025';
		caso.Status = 'Rechazado';
		caso.Caso_Rechazado__c = true;
		insert caso;

		prestacion = new Prestacion__c();
		prestacion.Prestacion_CA__c = '74043569';
		prestacion.Ap__c = caso.Id;
		insert prestacion;

		alerta = new Alerta__c();
		alerta.idalerta__c = '16465741';
		alerta.Prestacion__c = prestacion.Id;
		insert alerta;

		alerta2 = new Alerta__c();
		alerta2.idalerta__c = '16465740';
		alerta2.Prestacion__c = prestacion.Id;
		insert alerta2;
    }

	@IsTest
    private static void whenClickTheButton_autorizarAPRechazada() {
        Test.setMock(HttpCalloutMock.class, getResponseFound);
        
        Test.startTest();
        CaseAutorizarAPRechazadaBtnCtrl.Response resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
        Test.stopTest();

		caso = [SELECT Status FROM Case WHERE Id =: caso.Id];
		prestacion = [SELECT Id, (SELECT Id FROM Alertas__r) FROM Prestacion__c WHERE Id =: prestacion.Id];

        System.assertEquals(false, resp.hasError);
		System.assertEquals('ok', resp.message);
		System.assertEquals('CA-----E', caso.Status);
		System.assertEquals(6, prestacion.Alertas__r.size());
    }

	@IsTest
    private static void whenClickTheButton_showErrorMsg() {
        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        
        Test.startTest();
        CaseAutorizarAPRechazadaBtnCtrl.Response resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
        Test.stopTest();

		caso = [SELECT Status FROM Case WHERE Id =: caso.Id];

        System.assertEquals(true, resp.hasError);
		System.assertEquals('La autorización solicitada es inválida.', resp.message);
		System.assertEquals('Rechazado', caso.Status);
    }

	@IsTest
    private static void whenAPIsNotRefused_showValidationError() {
        //Test.setMock(HttpCalloutMock.class, getErrorResponse);

		caso.Caso_Rechazado__c = false;
		update caso;

		Test.startTest();
        CaseAutorizarAPRechazadaBtnCtrl.Response resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
        Test.stopTest();

        System.assertEquals(false, resp.hasError);
		System.assertEquals('El caso debe estar rechazado', resp.message);
    }

	@IsTest
    private static void whenAPIsInNivel1AndUserNotIsLeader_showValidationError() {
		caso.OwnerId = usuario.Id;
		update caso;

		CaseAutorizarAPRechazadaBtnCtrl.Response resp;
		System.runAs(usuario) {
			Test.startTest();
			resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
			Test.stopTest();
		}

        System.assertEquals(false, resp.hasError);
		System.assertEquals('- El usuario debe ser el líder de la célula', resp.message);
    }

	@IsTest
    private static void whenAPIsInNivel2AndUserNotIsLeader_showValidationError() {
		caso.Nivel_de_derivacion__c = 'Nivel 2';
		update caso;

		CaseAutorizarAPRechazadaBtnCtrl.Response resp;
		System.runAs(usuario) {
			Test.startTest();
			resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
			Test.stopTest();
		}

        System.assertEquals(false, resp.hasError);
		System.assertEquals('- El usuario debe ser el líder de Mesa de Ayuda', resp.message);
    }

	@IsTest
    private static void whenAPIsInNivel3WithEmptyCelulaAndUserNotIsLeader_showValidationError() {
		caso.Nivel_de_derivacion__c = 'Nivel 3';
		update caso;

		CaseAutorizarAPRechazadaBtnCtrl.Response resp;
		System.runAs(usuario) {
			Test.startTest();
			resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
			Test.stopTest();
		}

        System.assertEquals(false, resp.hasError);
		System.assertEquals('- El campo célula debe estar completo', resp.message);
    }

	@IsTest
    private static void whenAPIsInNivel3Celula1AndUserNotIsLeader_showValidationError() {
		caso.Nivel_de_derivacion__c = 'Nivel 3';
		caso.Celula__c = 'Celula 1';
		update caso;

		CaseAutorizarAPRechazadaBtnCtrl.Response resp;
		System.runAs(usuario) {
			Test.startTest();
			resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(caso.Id);
			Test.stopTest();
		}

        System.assertEquals(false, resp.hasError);
		System.assertEquals('- El usuario debe ser el líder de la célula', resp.message);
    }

	// SE ELIMINO LA VALIDACION
	//@isTest
	//private static void whenAFrontUserNotBelongsToDelegacion_showTheErrorMsg() {
		//Account delegacion = Build.anAccountDelegacion().withCodigoDeDelegacion('123456').build();
		//insert delegacion;
		
		//Case newCaso = new Case();
		//newCaso.Nro_AP__c = '1014009821';
		//newCaso.Status = 'CA-----A';
		//newCaso.Nivel_de_derivacion__c = 'Nivel 1';
		//newCaso.Caso_Rechazado__c = true;
		////newCaso.OwnerId = usuarioFront.Id;
		//insert newCaso;

		//newCaso.Delegacion__c = delegacion.Id;
		//update newCaso;

		//CaseAutorizarAPRechazadaBtnCtrl.Response resp;
		//System.runAs(usuario) {	
			//Test.startTest();
			//resp = CaseAutorizarAPRechazadaBtnCtrl.autorizarAPRechazada(newCaso.Id);
			//Test.stopTest();
		//}

		//System.assertEquals('El usuario puede modificar casos de su delegación solamente', resp.message);

	//}

}