force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Activo</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Dado de baja</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Generado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspendido</label>
            </value>
            <value>
                <fullName>A (Activo)</fullName>
                <isActive>false</isActive>
                <label>A (Activo)</label>
            </value>
            <value>
                <fullName>B (Baja)</fullName>
                <isActive>false</isActive>
                <label>B (Baja)</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
                <isActive>false</isActive>
                <label>En proceso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <externalId>true</externalId>
    <label>Número de documento</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Nombre__c.field-meta.xml
<CustomField>
    <fullName>Plan_Nombre__c</fullName>
    <label>Plan Nombre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTEGRAL AS200</fullName>
            </value>
            <value>
                <fullName>INTEGRAL AS204</fullName>
            </value>
            <value>
                <fullName>PLAN 11 PMO</fullName>
            </value>
            <value>
                <fullName>PLAN 2</fullName>
            </value>
            <value>
                <fullName>PLAN 2D</fullName>
            </value>
            <value>
                <fullName>PLAN 3</fullName>
            </value>
            <value>
                <fullName>PLAN 50</fullName>
            </value>
            <value>
                <fullName>PLAN 9</fullName>
            </value>
            <value>
                <fullName>SELECTA AS400</fullName>
            </value>
            <value>
                <fullName>SELECTA AS500</fullName>
            </value>
            <value>
                <fullName>SUPERIOR AS300</fullName>
            </value>
            <value>
                <fullName>PLAN 4 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1 40</fullName>
            </value>
            <value>
                <fullName>PLAN ACTIVO 7 40</fullName>
            </value>
            <value>
                <fullName>PLAN 1</fullName>
            </value>
            <value>
                <fullName>PLAN 4</fullName>
            </value>
            <value>
                <fullName>PLAN 5</fullName>
            </value>
            <value>
                <fullName>PLAN 6</fullName>
            </value>
            <value>
                <fullName>PLAN 7</fullName>
            </value>
            <value>
                <fullName>PLAN 8</fullName>
            </value>
            <value>
                <fullName>PLAN 10/1</fullName>
            </value>
            <value>
                <fullName>PLAN 10/2</fullName>
            </value>
            <value>
                <fullName>PLAN 11</fullName>
            </value>
            <value>
                <fullName>PLAN 11/1</fullName>
            </value>
            <value>
                <fullName>PLAN 11/2</fullName>
            </value>
            <value>
                <fullName>PLAN 12</fullName>
            </value>
            <value>
                <fullName>PLAN 13</fullName>
            </value>
            <value>
                <fullName>PLAN 14</fullName>
            </value>
            <value>
                <fullName>PLAN 15/1</fullName>
            </value>
            <value>
                <fullName>PLAN 15/2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Consultas.recordType-meta.xml
<RecordType>
    <fullName>Consultas</fullName>
    <active>true</active>
    <businessProcess>Consultas</businessProcess>
    <label>Consultas</label>
</RecordType>

force-app/main/default/classes/CaseLibreDeudaBtnCtrlTest.cls
@isTest 
private class CaseLibreDeudaBtnCtrlTest {
	static Account cuenta;
	static Case caso;

	static{
		cuenta = Build.anAccountCuentapersonal().build();
		cuenta.Plan_Nombre__c = 'INTEGRAL AS200';
		cuenta.Numero_de_documento__c = '12345678';
		cuenta.Type = 'TIT';
		cuenta.Estado__c = 'B';
		insert cuenta;

		caso = new Case();
		caso.RecordTypeId = XappiaHelper.getRecordType('Case', 'Consultas').Id;
		caso.AccountId = cuenta.Id;
		insert caso;
	}

	@isTest
	private static void generatePdfCopago() {
		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id]; 

		System.assertEquals(false, resp.hasError);
		System.assertEquals('Se ha adjuntado el pdf correctamente.', resp.message);
		System.assertEquals(1, links.size());

	}

	@isTest
	private static void generatePdfSinCopago() {
		cuenta.Plan_Nombre__c = 'PLAN 1';
		update cuenta;

		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id]; 

		System.assertEquals(false, resp.hasError);
		System.assertEquals('Se ha adjuntado el pdf correctamente.', resp.message);
		System.assertEquals(1, links.size());
	}

	@isTest
	private static void ifCaseHaveNotAnAccountShowTheErrorMsg() {
		caso.AccountId = null;
		update caso;

		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id]; 

		System.assertEquals(true, resp.hasError);
		System.assertEquals('El caso debe tener una cuenta asociada.', resp.message);
		System.assertEquals(0, links.size());
	}

	@isTest
	private static void updateContentVersion() {
		ContentVersion cv = new ContentVersion();
		cv.Title = 'Libre_deuda_asociado';
		cv.VersionData = Blob.valueOf('Libre_deuda_asociado_Test');
		cv.PathOnClient = '/Libre_deuda_asociado';
		insert cv;

		cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];

		ContentDocumentLink link = new ContentDocumentLink();
		link.ContentDocumentId = cv.ContentDocumentId;
		link.LinkedEntityId = caso.Id;
		insert link;

		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id];
		ContentVersion[] versions = [SELECT Id FROM ContentVersion WHERE ContentDocumentId = :cv.ContentDocumentId];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('Se ha adjuntado el pdf correctamente.', resp.message);
		System.assertEquals(1, links.size());
		System.assertEquals(2, versions.size());
	}

	@isTest
	private static void whenAccountIsNotTitularShowTheErrorMsg() {
		cuenta.Type = 'FAM';
		update cuenta;

		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id]; 

		System.assertEquals(true, resp.hasError);
		System.assertEquals('La cuenta asociada al caso no pertenece a un titular.', resp.message);
		System.assertEquals(0, links.size());
	}

	@isTest
	private static void whenAccountIsNotDadoDeBajaShowTheErrorMsg() {
		cuenta.Estado__c = 'A';
		update cuenta;

		Test.startTest();
		CaseLibreDeudaBtnCtrl.Response resp = CaseLibreDeudaBtnCtrl.generatePdf(caso.Id);
		Test.stopTest();

		ContentDocumentLink[] links = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :caso.Id]; 

		System.assertEquals(true, resp.hasError);
		System.assertEquals('La cuenta asociada al caso no está dada de baja.', resp.message);
		System.assertEquals(0, links.size());
	}
	
}