force-app/main/default/objects/Account/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
                <label>Casado</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Soltero</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Concubinato</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divorciado</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Viudo</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Separado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_log__c/Batch_log__c.object-meta.xml
<CustomObject>
    <description>Objeto donde se van a reflejar los errores de los batchs</description>
    <label>Batch log</label>
    <nameField>
        <label>Nombre de Batch log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_log__c/fields/Id_registro_error__c.field-meta.xml
<CustomField>
    <fullName>Id_registro_error__c</fullName>
    <externalId>true</externalId>
    <label>Id registro error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{0000}</displayFormat>
        <label>Nombre de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion__c/fields/Cotizacion_de_prueba__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_de_prueba__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cotización de prueba</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Estado_Civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_Civil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Civil</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad de cotización</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Canal_de_contacto_Asesor_con_cliente__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_contacto_Asesor_con_cliente__c</fullName>
    <label>Canal de contacto (Asesor con cliente)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telefono</fullName>
            </value>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Presencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cotizacion_elegida__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_elegida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Individual elegida</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cotizacion__c.Oportunidad__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Cotizacion__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cotización Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estado_Civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_Civil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Civil</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_CBU_para_cobro_de_cuota__c.field-meta.xml
<CustomField>
    <fullName>Nro_CBU_para_cobro_de_cuota__c</fullName>
    <label>Nro. CBU para cobro de cuota</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segmento_del_Grupo_Familiar__c.field-meta.xml
<CustomField>
    <fullName>Segmento_del_Grupo_Familiar__c</fullName>
    <label>Segmento del Grupo Familiar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VOLDIR</fullName>
            </value>
            <value>
                <fullName>OBLDIR</fullName>
            </value>
            <value>
                <fullName>VOLEMP</fullName>
            </value>
            <value>
                <fullName>OBLEMP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CotizadorEliminarRegistrosBatchTest.cls
@IsTest
private class CotizadorEliminarRegistrosBatchTest {
    static testMethod void itShouldDeletesAllCotizacionRecordsIf7DaysHavePassedAndTheFlagCotizacionPruebaHasValueTrue() {
        Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity opp = new Opportunity(Name = 'asd',Nro_CBU_para_cobro_de_cuota__c='123456789',
			StageName='Contactado',CloseDate=System.today(), AccountId = acc.Id);
        insert opp;
        Cotizacion__c cot = new Cotizacion__c(Cotizacion_de_prueba__c = true,Oportunidad__c = opp.Id);
        insert cot;
        Datetime sevenDaysBefore = Datetime.now().addDays(-8);
        Test.setCreatedDate(cot.Id, sevenDaysBefore);
        Test.startTest();
        CotizadorEliminarRegistrosBatch batch = new CotizadorEliminarRegistrosBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(0,[SELECT COUNT() FROM Cotizacion__c]);

    }

    static testMethod void itShouldNotDeleteAllCotizacionRecordsIfLessThan7DaysHavePassedAndTheFlagCotizacionPruebaHasValueTrue() {
        Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity opp = new Opportunity(Name = 'asd',Nro_CBU_para_cobro_de_cuota__c='123456789',
			StageName='Contactado',CloseDate=System.today(), AccountId = acc.Id);
        insert opp;
        Cotizacion__c cot = new Cotizacion__c(Cotizacion_de_prueba__c = true,Oportunidad__c = opp.Id);
        insert cot;
        Datetime sevenDaysBefore = Datetime.now().addDays(-2);
        Test.setCreatedDate(cot.Id, sevenDaysBefore);
        Test.startTest();
        CotizadorEliminarRegistrosBatch batch = new CotizadorEliminarRegistrosBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(1,[SELECT COUNT() FROM Cotizacion__c]);

    }

    static testMethod void itShouldNotDeleteAllCotizacionRecordsIf7DaysHavePassedAndTheFlagCotizacionPruebaHasValueFalse() {
        Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity opp = new Opportunity(Name = 'asd',Nro_CBU_para_cobro_de_cuota__c='123456789',
			StageName='Contactado',CloseDate=System.today(), AccountId = acc.Id);
        insert opp;
        Cotizacion__c cot = new Cotizacion__c(Cotizacion_de_prueba__c = false,Oportunidad__c = opp.Id);
        insert cot;
        Datetime sevenDaysBefore = Datetime.now().addDays(-8);
        Test.setCreatedDate(cot.Id, sevenDaysBefore);
        Test.startTest();
        CotizadorEliminarRegistrosBatch batch = new CotizadorEliminarRegistrosBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assertEquals(1,[SELECT COUNT() FROM Cotizacion__c]);

    }

	static testMethod void checkTheBatchLogsObjects() {
        Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		
		Opportunity opp = new Opportunity(Name = 'asd',Nro_CBU_para_cobro_de_cuota__c='123456789',
			StageName='Contactado',CloseDate=System.today(), AccountId = acc.Id);
        insert opp;
        
		Cotizacion__c cot = new Cotizacion__c(Cotizacion_de_prueba__c = true,Oportunidad__c = opp.Id);
        insert cot;

		opp.Cotizacion_elegida__c = cot.Id;
		opp.StageName='Cotizado';
		update opp;

		opp.Segmento_del_Grupo_Familiar__c = 'VOLDIR';
		opp.Canal_de_contacto_Asesor_con_cliente__c = 'Telefono';
		opp.Estado_Civil__c = 'S';
		opp.StageName='En Negociación';
		update opp;
        
		Datetime sevenDaysBefore = Datetime.now().addDays(-8);
        Test.setCreatedDate(cot.Id, sevenDaysBefore);
        Test.startTest();
        CotizadorEliminarRegistrosBatch batch = new CotizadorEliminarRegistrosBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        //System.assertEquals(0,[SELECT COUNT() FROM Cotizacion__c]);

		Batch_log__c[] logs = [SELECT Id, Error__c, Id_registro_error__c FROM Batch_log__c];

		System.debug(logs);
		System.assertNotEquals(null, logs[0].Error__c);
		System.assertEquals(cot.Id, logs[0].Id_registro_error__c);

    }
}