force-app/main/default/objects/Account/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{0000}</displayFormat>
        <label>Nombre de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion__c/fields/Aporta_por_hijos__c.field-meta.xml
<CustomField>
    <fullName>Aporta_por_hijos__c</fullName>
    <label>Aporta por hijos</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/CP__c.field-meta.xml
<CustomField>
    <fullName>CP__c</fullName>
    <label>CP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Diferencia_a_pagar__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_a_pagar__c</fullName>
    <label>Diferencia a pagar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Edad_conyuge__c.field-meta.xml
<CustomField>
    <fullName>Edad_conyuge__c</fullName>
    <label>Edad cónyuge</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Grupo_de_potencialidad__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_potencialidad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Grupo de potencialidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_entre_21_y_25_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_entre_21_y_25_aos__c</fullName>
    <label>Hijos entre 21 y 25 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_hasta_20_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_hasta_20_aos__c</fullName>
    <label>Hijos hasta 20 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Localidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/LocId__c.field-meta.xml
<CustomField>
    <fullName>LocId__c</fullName>
    <label>LocId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Monotributista_conyuge__c.field-meta.xml
<CustomField>
    <fullName>Monotributista_conyuge__c</fullName>
    <label>Monotributista cónyuge</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad de cotización</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Sueldo_bruto__c.field-meta.xml
<CustomField>
    <fullName>Sueldo_bruto__c</fullName>
    <label>Sueldo bruto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_afiliado__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_afiliado__c</fullName>
    <label>Tipo de afiliado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Voluntario</fullName>
            </value>
            <value>
                <fullName>Relacion de Dependencia</fullName>
                <label>Relación de dependencia</label>
            </value>
            <value>
                <fullName>Monotributista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_contacto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_contacto__c</fullName>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Individuo</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Grupo familiar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/recordTypes/Cotizacion_Individual.recordType-meta.xml
<RecordType>
    <fullName>Cotizacion_Individual</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones de ventas individuales</description>
    <label>Cotización Individual</label>
</RecordType>

force-app/main/default/objects/Localidad__c/Localidad__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <displayFormat>Loc-{0000}</displayFormat>
        <label>Nro. Localidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Localidad__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localidad__c/fields/Loc_Id__c.field-meta.xml
<CustomField>
    <fullName>Loc_Id__c</fullName>
    <externalId>true</externalId>
    <label>Loc Id</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <label>Código Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cotizacion_elegida__c.field-meta.xml
<CustomField>
    <fullName>Cotizacion_elegida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotización Individual elegida</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cotizacion__c.Oportunidad__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Cotizacion__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cotización Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cotizacion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <label>Localidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Localidad_new__c.field-meta.xml
<CustomField>
    <fullName>Localidad_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Localidad__c</referenceTo>
    <relationshipLabel>Localidad</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CotizacionTriggerTest.cls
@IsTest
private class CotizacionTriggerTest  {

	@IsTest
	private static void copyLocIdWhenANewCotizacionIsCreated(){
		Localidad__c loc = new Localidad__c(Loc_Id__c='123',Codigo_Postal__c ='123ABC');
		insert loc;
		Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity op = Build.anOpportunityIndividuos().build();
		op.AccountId = acc.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(CP__c='123ABC',Oportunidad__c = op.Id,Localidad_new__c = loc.Id);
		Test.startTest();
		insert coti;
		Test.stopTest();
		Cotizacion__c updatedCot = [SELECT LocId__c FROM Cotizacion__c WHERE Id = :coti.Id];
		System.assertEquals(loc.Loc_Id__c,updatedCot.LocId__c);
	}

		@IsTest
	private static void copyLocIdWhenACotizacionIsUpdated(){
		Localidad__c loc = new Localidad__c(Loc_Id__c='123',Codigo_Postal__c ='123ABC');
		insert loc;
		Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity op = Build.anOpportunityIndividuos().build();
		op.AccountId = acc.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Oportunidad__c = op.Id,Localidad_new__c = loc.Id);
		insert coti;
		coti.CP__c = '123ABC';
		Test.startTest();
		update coti;
		Test.stopTest();
		Cotizacion__c updatedCot = [SELECT LocId__c FROM Cotizacion__c WHERE Id = :coti.Id];
		System.assertEquals(loc.Loc_Id__c,updatedCot.LocId__c);
	}

	@isTest
	private static void copyDiferenciaAPagarToOpportunityAmountWhenUpdated(){
		Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity op = Build.anOpportunityIndividuos().build();
		op.AccountId = acc.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Oportunidad__c = op.Id);
		coti.RecordTypeId = XappiaHelper.getRecordType('Cotizacion__c','Cotizacion_Individual').Id;
		insert coti;

		op.Cotizacion_elegida__c = coti.Id;
		update op;

		coti.Diferencia_a_pagar__c = '1919';

		Test.startTest();
		update coti;
		Test.stopTest();

		List<Opportunity> oppToAssert = [SELECT Id, Amount FROM Opportunity WHERE Id =: op.Id];

		System.assertEquals(1919, oppToAssert[0].Amount);
	}

	@isTest
	private static void copyDiferenciaAPagarToOpportunityAmountWhenUpdatedWithNullValue(){
		Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity op = Build.anOpportunityIndividuos().build();
		op.AccountId = acc.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Oportunidad__c = op.Id);
		coti.RecordTypeId = XappiaHelper.getRecordType('Cotizacion__c','Cotizacion_Individual').Id;
		insert coti;

		coti.Diferencia_a_pagar__c = null;

		Test.startTest();
		update coti;
		Test.stopTest();

		List<Opportunity> oppToAssert = [SELECT Id, Amount FROM Opportunity WHERE Id =: op.Id];

		System.assertEquals(null, oppToAssert[0].Amount);
	}

	@isTest
	private static void validationTest(){
		Account acc = Build.anAccountCuentapersonal().build();
		insert acc;
		Opportunity op = Build.anOpportunityIndividuos().build();
		op.AccountId = acc.Id;
		insert op;
		Cotizacion__c coti = new Cotizacion__c(Oportunidad__c = op.Id);
		coti.RecordTypeId = XappiaHelper.getRecordType('Cotizacion__c','Cotizacion_Individual').Id;
		coti.Tipo_de_afiliado__c = 'Relacion de dependencia';
		coti.Tipo_de_contacto__c = '1';
		coti.Sueldo_bruto__c = 50000;
		coti.Monotributista_conyuge__c = 'Si';
		coti.Grupo_de_potencialidad__c = true;
		coti.Aporta_por_hijos__c = 'Si';
		coti.Hijos_entre_21_y_25_aos__c = 24;
		coti.Hijos_hasta_20_aos__c = 1;
		coti.Edad_conyuge__c = 120;

		Cotizacion__c coti2 = new Cotizacion__c(Oportunidad__c = op.Id);
		coti2.RecordTypeId = XappiaHelper.getRecordType('Cotizacion__c','Cotizacion_Individual').Id;
		coti2.Tipo_de_afiliado__c = 'Voluntario';
		coti2.Tipo_de_contacto__c = '1';
		coti2.Sueldo_bruto__c = 50000;
		coti2.Monotributista_conyuge__c = 'Si';
		coti2.Grupo_de_potencialidad__c = true;
		coti2.Aporta_por_hijos__c = 'Si';
		coti2.Hijos_entre_21_y_25_aos__c = 24;
		coti2.Hijos_hasta_20_aos__c = 1;
		coti2.Edad_conyuge__c = 120;

		Cotizacion__c coti3 = new Cotizacion__c(Oportunidad__c = op.Id);
		coti3.RecordTypeId = XappiaHelper.getRecordType('Cotizacion__c','Cotizacion_Individual').Id;
		coti3.Tipo_de_afiliado__c = 'Monotributista';
		coti3.Tipo_de_contacto__c = '1';
		coti3.Sueldo_bruto__c = 50000;
		coti3.Monotributista_conyuge__c = 'Si';
		coti3.Grupo_de_potencialidad__c = true;
		coti3.Aporta_por_hijos__c = 'Si';
		coti3.Hijos_entre_21_y_25_aos__c = 24;
		coti3.Hijos_hasta_20_aos__c = 1;
		coti3.Edad_conyuge__c = 120;

		Test.startTest();
		Database.SaveResult res = Database.insert(coti,false);
		Database.SaveResult res2 = Database.insert(coti2,false);
		Database.SaveResult res3 = Database.insert(coti3,false);
		Test.stopTest();

		System.assertEquals(false, res.isSuccess());
		System.assertEquals(false, res2.isSuccess());
		System.assertEquals(false, res3.isSuccess());
	}

}