force-app/main/default/objects/Cotizacion__c/Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Cotización</label>
    <nameField>
        <displayFormat>COT-{0000}</displayFormat>
        <label>Nombre de Cotización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cotizacion__c/fields/Aporta_por_hijos__c.field-meta.xml
<CustomField>
    <fullName>Aporta_por_hijos__c</fullName>
    <label>Aporta por hijos</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Edad_conyuge__c.field-meta.xml
<CustomField>
    <fullName>Edad_conyuge__c</fullName>
    <label>Edad cónyuge</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Grupo_de_potencialidad__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_potencialidad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Grupo de potencialidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_entre_21_y_25_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_entre_21_y_25_aos__c</fullName>
    <label>Hijos entre 21 y 25 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Hijos_hasta_20_aos__c.field-meta.xml
<CustomField>
    <fullName>Hijos_hasta_20_aos__c</fullName>
    <label>Hijos hasta 20 años</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Monotributista_conyuge__c.field-meta.xml
<CustomField>
    <fullName>Monotributista_conyuge__c</fullName>
    <label>Monotributista cónyuge</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Sueldo_bruto__c.field-meta.xml
<CustomField>
    <fullName>Sueldo_bruto__c</fullName>
    <label>Sueldo bruto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_afiliado__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_afiliado__c</fullName>
    <label>Tipo de afiliado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Voluntario</fullName>
            </value>
            <value>
                <fullName>Relacion de Dependencia</fullName>
                <label>Relación de dependencia</label>
            </value>
            <value>
                <fullName>Monotributista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cotizacion__c/fields/Tipo_de_contacto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_contacto__c</fullName>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Individuo</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Grupo familiar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CotizacionTriggerHelper.cls
public class CotizacionTriggerHelper {

    public static void validateCotizacion(Cotizacion__c cot){
        if(cot.Tipo_de_afiliado__c == 'Relacion de dependencia'){
            if(cot.Sueldo_bruto__c == null || cot.Sueldo_bruto__c == 0){
                cot.Sueldo_bruto__c.addError('Campo Sueldo requerido cuando Tipo de afiliado es Relacion de dependencia');
            }
        }
        if(cot.Tipo_de_afiliado__c == 'Voluntario'){
            if(cot.Sueldo_bruto__c != null){
                cot.Sueldo_bruto__c.addError('Campo Sueldo no debe estar completo si tipo de afiliado es Voluntario');
            }
            if(cot.Monotributista_conyuge__c != null){
                cot.Monotributista_conyuge__c.addError('Campo Monotributista conyuge no debe estar completo si tipo de afiliado es Voluntario');
            }
            if(cot.Grupo_de_potencialidad__c != false){
                cot.Grupo_de_potencialidad__c.addError('Campo Potencialidad no debe estar completo si tipo de afiliado es Voluntario');
            }
        }
        if(cot.Tipo_de_afiliado__c == 'Voluntario' && cot.Tipo_de_contacto__c == '1'){


                if(cot.Aporta_por_hijos__c != null){
                    cot.Aporta_por_hijos__c.addError('Campo Aporta por hijos no debe estar completo si tipo de afiliado es Voluntario y Tipo de contacto Individuo');
                }
                if(cot.Hijos_entre_21_y_25_aos__c != null){
                    cot.Hijos_entre_21_y_25_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Voluntario y Tipo de contacto Individuo');
                }
                if(cot.Hijos_hasta_20_aos__c != null){
                    cot.Hijos_hasta_20_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Voluntario y Tipo de contacto Individuo');
                }
                if(cot.Edad_conyuge__c != null){
                    cot.Edad_conyuge__c.addError('Campo Edad conyuge no debe estar completo si tipo de afiliado es Voluntario y Tipo de contacto Individuo');
                }
            }
        if(cot.Tipo_de_afiliado__c == 'Relacion de dependencia' && cot.Tipo_de_contacto__c == '1'){
            	if(cot.Monotributista_conyuge__c != null){
                    cot.Monotributista_conyuge__c.addError('Campo Monotributista conyuge no debe estar completo si tipo de afiliado es Relacion de dependencia y Tipo de contacto Individuo');
                }
                if(cot.Aporta_por_hijos__c != null){
                    cot.Aporta_por_hijos__c.addError('Campo Aporta por hijos no debe estar completo si tipo de afiliado es Relacion de dependencia y Tipo de contacto Individuo');
                }
                if(cot.Hijos_entre_21_y_25_aos__c != null){
                    cot.Hijos_entre_21_y_25_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Relacion de dependencia y Tipo de contacto Individuo');
                }
                if(cot.Hijos_hasta_20_aos__c != null){
                    cot.Hijos_hasta_20_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Relacion de dependencia y Tipo de contacto Individuo');
                }
                if(cot.Edad_conyuge__c != null){
                    cot.Edad_conyuge__c.addError('Campo Edad conyuge no debe estar completo si tipo de afiliado es Relacion de dependencia y Tipo de contacto Individuo');
                }
        }
        if(cot.Tipo_de_afiliado__c == 'Monotributista'){
            if(cot.Sueldo_bruto__c != null){
                cot.Sueldo_bruto__c.addError('Campo Sueldo no debe estar completo si tipo de afiliado es Monotributista');
            }
            if(cot.Grupo_de_potencialidad__c != false){
                cot.Grupo_de_potencialidad__c.addError('Campo Potencialidad no debe estar completo si tipo de afiliado es Monotributista');
            }
        }
        if(cot.Tipo_de_afiliado__c == 'Monotributista' && cot.Tipo_de_contacto__c == '1'){
            	if(cot.Monotributista_conyuge__c != null){
                    cot.Monotributista_conyuge__c.addError('Campo Monotributista conyuge no debe estar completo si tipo de afiliado es Monotributista y Tipo de contacto Individuo');
                }
                if(cot.Aporta_por_hijos__c != null){
                    cot.Aporta_por_hijos__c.addError('Campo Aporta por hijos no debe estar completo si tipo de afiliado es Monotributista y Tipo de contacto Individuo');
                }
                if(cot.Hijos_entre_21_y_25_aos__c != null ){
                    cot.Hijos_entre_21_y_25_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Monotributista y Tipo de contacto Individuo');
                }
                if(cot.Hijos_hasta_20_aos__c != null){
                    cot.Hijos_hasta_20_aos__c.addError('Campo Cantidad de hijos no debe estar completo si tipo de afiliado es Monotributista y Tipo de contacto Individuo');
                }
                if(cot.Edad_conyuge__c != null){
                    cot.Edad_conyuge__c.addError('Campo Edad conyuge no debe estar completo si tipo de afiliado es Monotributista y Tipo de contacto Individuo');
                }

                
        }



    }
}