force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteReabrirCtrlTest.cls
@IsTest
public class LoteReabrirCtrlTest  {
	

	static XHttpCalloutMock getResponseSuccess;
	static XHttpCalloutMock getResponseError;
	static Lote__c lote;

	static {
		getResponseSuccess = new XHttpCalloutMock();
		getResponseSuccess.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseSuccess.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSLoteReabrirMock.getFound())
			.addForAddress(WSLoteReabrir.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes/5397');
		
		getResponseError = new XHttpCalloutMock();
		getResponseError.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseError.buildResponse()
			.withStatus('No se pudo reabrir el lote.')
			.withStatusCode(400)
			.withBody(WSLoteReabrirMock.getError())
			.addForAddress(WSLoteReabrir.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes/5397');
		
	}

	@TestSetup
	private static void setup(){
		Test.startTest();
		lote = new Lote__c(Id_lote_SS__c='5397',Estado__c = 'A');
		insert lote;
		Test.stopTest();
	}

	@IsTest
	private static void shouldReopenTheLote(){
		lote = [SELECT Id,Estado__c, Id_lote_SS__c FROM Lote__c LIMIT 1];

		lote.Estado__c = 'C';
		update lote;

		Test.setMock(HttpCalloutMock.class,getResponseSuccess);
		Test.startTest();
		LoteReabrirCtrl.Response resp = LoteReabrirCtrl.reopenLote(lote.Id_lote_SS__c);
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];

		System.assertEquals(false, resp.hasError);
		System.assertEquals('Se reabrió el lote con éxito.', resp.message);
		System.assertEquals('A', lote.Estado__c);
	}

	@IsTest
	private static void shouldNotReopenTheLoteWhenItsStateIsNotClosed(){
		lote = [SELECT Id,Estado__c, Id_lote_SS__c FROM Lote__c LIMIT 1];

		lote.Estado__c = 'O';
		update lote;

		Test.setMock(HttpCalloutMock.class,getResponseSuccess);
		Test.startTest();
		LoteReabrirCtrl.Response resp = LoteReabrirCtrl.reopenLote(lote.Id_lote_SS__c);
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];

		System.assertEquals(true, resp.hasError);
		System.assertEquals('El lote debe estar cerrado para poder reabrirlo', resp.message);
		System.assertEquals('O', lote.Estado__c);
	}


	@IsTest
	private static void shouldNotReopenTheLoteWhenItHasNoExternalID(){
		lote = [SELECT Id,Estado__c, Id_lote_SS__c FROM Lote__c LIMIT 1];
		lote.Id_lote_SS__c = null;
		lote.Estado__c = 'C';
		update lote;

		Test.setMock(HttpCalloutMock.class,getResponseSuccess);
		Test.startTest();
		LoteReabrirCtrl.Response resp = LoteReabrirCtrl.reopenLote(lote.Id_lote_SS__c);
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];

		System.assertEquals(true, resp.hasError);
		System.assertEquals('El lote no existe en SS', resp.message);
		System.assertEquals('C', lote.Estado__c);
	}

	@IsTest
	private static void shouldNotReopenTheLoteWhenTheWSFails(){
		lote = [SELECT Id,Estado__c, Id_lote_SS__c FROM Lote__c LIMIT 1];

		lote.Estado__c = 'C';
		update lote;

		Test.setMock(HttpCalloutMock.class,getResponseError);
		Test.startTest();
		LoteReabrirCtrl.Response resp = LoteReabrirCtrl.reopenLote(lote.Id_lote_SS__c);
		Test.stopTest();

		lote = [SELECT Estado__c FROM Lote__c WHERE Id = :lote.Id];

		System.assertEquals(true, resp.hasError);
		System.assertEquals('ERROR AL ABRIR LOTE. ERR Reabriendo el lote:. no esta en estado CERRADO', resp.message);
		System.assertEquals('C', lote.Estado__c);
	}

}