force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Este campo se utiliza en regla de validación para bloquear registro para bloquear registro y podes codificarlo desde el boton &quot;Reabrir orden&quot;</description>
    <label>Bloqueo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteReabrirCtrl.cls
public class LoteReabrirCtrl  {
	@AuraEnabled
    public static Response reopenLote(String id_lote) {

		if(String.isBlank(id_lote)){
			return new Response(true, 'El lote no existe en SS');
		}

		Lote__c lote = [SELECT Id, Estado__c FROM Lote__c WHERE Id_lote_SS__c = :id_lote];

		if(lote.Estado__c != 'C'){
			return new Response(true, 'El lote debe estar cerrado para poder reabrirlo');
		}

		User usuario = [SELECT Id,CommunityNickname FROM User WHERE Id = :UserInfo.getUserId()];
		String apodo = usuario.CommunityNickname != null ? usuario.CommunityNickname.toUpperCase() : null;

		String body = '{"accion":"REABRIR","usuario":"'+ apodo +'"}';
        System.debug(body);
		WSLoteReabrir.Response wsResponse =  WSLoteReabrir.reabrirLote(id_lote,body);

        if(!wsResponse.hasError){
			lote.Estado__c = 'A';
			lote.Bloqueo__c = false;
			update lote;
            return new Response(false,
                    'Se reabrió el lote con éxito.');
        }
		return new Response(true,
                    wsResponse.message);
        
    }

    public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;

        public Response(Boolean hasError, String message){
            this.hasError = hasError;
            this.message = message;
        }
    }
}