force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Emision__c.field-meta.xml
<CustomField>
    <fullName>Emision__c</fullName>
    <label>Emisión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>Diaria</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Semanal</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteReintentoEnvioASSBatchTest.cls
@isTest 
private class LoteReintentoEnvioASSBatchTest {
	
	static XHttpCalloutMock getResponseFound;
	static XHttpCalloutMock getResponseError;
	static Lote__c lote;

	static {
		getResponseFound = new XHttpCalloutMock();
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseFound.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSLoteEnviarASSMock.getFound())
			.addForAddress(WSLoteEnviarASS.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes');
		getResponseError = new XHttpCalloutMock();
		getResponseError.buildResponse()
			.withStatus('OK')
			.withStatusCode(200)
			.withBody(WSAuthTokenMock.getTokenSuccess())
			.addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
		getResponseError.buildResponse()
			.withStatus('Error')
			.withStatusCode(422)
			.withBody(WSLoteEnviarASSMock.getError())
			.addForAddress(WSLoteEnviarASS.SERVICE_CONFIG.URL__c + '/v1/salud/reintegros/lotes');


		
	}

	@TestSetup
	private static void setup(){
		Test.setMock(HttpCalloutMock.class, getResponseError);
		Test.startTest();
		lote = new Lote__c(Fecha__c = Date.today(),Emision__c='S',Observaciones__c='Sin obs');
		insert lote;
		Test.stopTest();
	}

	@isTest
	private static void whenALoteIsCreatedWithInValidFields_ItShouldReSendToSSAndFillTheCorrespondingFields() {
	
		lote = [SELECT Id_lote_SS__c, Estado__c, Fecha_de_fallo__c, Fallo_en_SS__c FROM Lote__c LIMIT 1];

		System.assertEquals(null, lote.Id_lote_SS__c);
		System.assertEquals('A', lote.Estado__c);
		System.assertNotEquals(null,lote.Fecha_de_fallo__c);
		System.assertNotEquals(null,lote.Fallo_en_SS__c);
		
		Test.setMock(HttpCalloutMock.class, getResponseFound);
		Test.startTest();
		
		Database.executeBatch(new LoteReintentoEnvioASSBatch());
		
		Test.stopTest();


		lote = [SELECT Id_lote_SS__c, Estado__c, Fecha_de_fallo__c, Fallo_en_SS__c FROM Lote__c WHERE Id = :lote.Id];

		System.assertEquals('5400', lote.Id_lote_SS__c);
		System.assertEquals('A', lote.Estado__c);
		System.assertEquals(null,lote.Fecha_de_fallo__c);
		System.assertEquals(null,lote.Fallo_en_SS__c);

	}
}