force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LoteReintentoEnvioASSBatch.cls
global class LoteReintentoEnvioASSBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Fallo_en_SS__c, Fecha_de_fallo__c, CreatedBy.CommunityNickname,CreatedById FROM Lote__c ' + 
            'WHERE Fallo_en_SS__c != null'
        );
    }
    global void execute(Database.BatchableContext bc, List<Lote__c> records){
        LoteTriggerHelper.reintentoEnvio(records);
    }    
    global void finish(Database.BatchableContext bc){
    }    
}