force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LotePasajeAIFCtrl.cls
public class LotePasajeAIFCtrl  {

	@AuraEnabled
    public static Response changeToIF(String id_lote) {
		User usuario = [SELECT CommunityNickname FROM User WHERE Id = :UserInfo.getUserId()];
		String apodo = usuario.CommunityNickname != null ? usuario.CommunityNickname.toUpperCase() : null;
		Lote__c lote = [SELECT Id, Estado__c FROM Lote__c WHERE Id_lote_SS__c = :id_lote];
        WSLotePasajeAIF.Response wsResponse =  WSLotePasajeAIF.pasajeIF(id_lote,'{"usuario":"'+ apodo +'"}');

        if(!wsResponse.hasError){
			PageReference page = new PageReference(wsResponse.lote.data.lote.link_if);
			ContentVersion ver = new ContentVersion();
			try{
				ver.VersionData = page.getContentAsPDF();
			}
			catch(VisualforceException e){
				if(Test.isRunningTest()){
					ver.VersionData = Blob.valueOf('test blob');
				}
				System.debug(e.getMessage());
			}

			ver.Title = 'OrdenesDeReintegro' + wsResponse.lote.data.lote.lr_id;
			ver.PathOnClient = '/OrdenesDeReintegro' + wsResponse.lote.data.lote.lr_id + '.pdf';
			insert ver;
			ver = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = : ver.Id];
			ContentDocumentLink link = new ContentDocumentLink();
			link.ContentDocumentId = ver.ContentDocumentId;
			link.LinkedEntityId = lote.Id;
			link.ShareType = 'V';
			insert link;
			lote.Estado__c = wsResponse.lote.data.lote.estado;
			update lote;
            return new Response(false,
                    wsResponse.lote.message,
                    wsResponse.lote);
        }
        else{
            return new Response(true,
                    wsResponse.message,
                    null);
        }
    }

    public class Response {
        @AuraEnabled public Boolean hasError;
        @AuraEnabled public String message;
        @AuraEnabled public WSLotePasajeAIFResp lote;

        public Response(Boolean hasError, String message, WSLotePasajeAIFResp lote){
            this.hasError = hasError;
            this.message = message;
            this.lote = lote;
        }
    }
}