force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Emision__c.field-meta.xml
<CustomField>
    <fullName>Emision__c</fullName>
    <label>Emisión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>Diaria</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Semanal</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteTriggerHelper.cls
public class LoteTriggerHelper {

	public static void reintentoEnvio(List<Lote__c> lotes) {
		List<Lote__c> lotesToUpdate = new List<Lote__c>();

		for(Lote__c lote : lotes){
			lotesToUpdate.add(resendToSS(lote.Id,lote.CreatedBy.CommunityNickname.toUpperCase()));
		}
		update lotesToUpdate;
	}

	private static Lote__c resendToSS(Id loteId, String username){
		Lote__c lote = [
			SELECT Id, Observaciones__c, Emision__c, Fecha__c
			FROM Lote__c
			WHERE Id = :loteId
		];
		String body = JSON.serialize(new Map<String,Object>{
			'usuario' => username,
			'observaciones' => lote.Observaciones__c,
			'emision' => lote.Emision__c,
			'fecha' => lote.Fecha__c != null ? String.valueOf(lote.Fecha__c) : null
		});
		System.debug('body to sendLote:  ' + body);
		WSLoteEnviarASS.Response resp = WSLoteEnviarASS.sendLoteToSS(body);

		if(!resp.hasError){
			lote.Id_lote_SS__c = resp.lote.data.lote_id != null ? String.valueOf(resp.lote.data.lote_id) : null;
			lote.Estado__c = resp.lote.data.estado;
			lote.Fallo_en_SS__c = null;
			lote.Fecha_de_fallo__c = null; 
		}
		else{
			lote.Fallo_en_SS__c = resp.message;
			lote.Fecha_de_fallo__c = Datetime.now(); 
		}
		System.debug(lote);
		return lote;

	}
}