force-app/main/default/objects/Lote__c/Lote__c.object-meta.xml
<CustomObject>
    <label>Lote</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Nombre de Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote__c/fields/Bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Este campo se utiliza en regla de validación para bloquear registro para bloquear registro y podes codificarlo desde el boton &quot;Reabrir orden&quot;</description>
    <label>Bloqueo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Emision__c.field-meta.xml
<CustomField>
    <fullName>Emision__c</fullName>
    <label>Emisión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>Diaria</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Semanal</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mensual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Cerrado</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Contabilizado</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Finalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fallo_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Fallo_en_SS__c</fullName>
    <label>Fallo en SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Fecha_de_fallo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_fallo__c</fullName>
    <label>Fecha de fallo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Id_lote_SS__c.field-meta.xml
<CustomField>
    <fullName>Id_lote_SS__c</fullName>
    <externalId>true</externalId>
    <label>Id lote SS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lote__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lote__c/recordTypes/Lote.recordType-meta.xml
<RecordType>
    <fullName>Lote</fullName>
    <active>true</active>
    <label>Lote</label>
</RecordType>

force-app/main/default/classes/LoteQueueable.cls
public class LoteQueueable  implements Queueable, Database.AllowsCallouts{
	public List<Lote__c> lotes;

	public LoteQueueable(List<Lote__c> loteList){
		lotes = loteList;
	}

	public void execute(QueueableContext context) {
		User usuario = [SELECT Alias, CommunityNickname, Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];
		String apodo = usuario.CommunityNickname.toUpperCase();
		if(!lotes.isEmpty()){
			Lote__c loteOriginal = lotes.remove(0);
			Lote__c lote = loteOriginal.clone(true,true,false,false);
			String body = JSON.serialize(new Map<String,Object>{
			'usuario' => apodo,
			'observaciones' => lote.Observaciones__c,
			'emision' => lote.Emision__c,
			'fecha' => lote.Fecha__c != null ? String.valueOf(lote.Fecha__c) : null
			});
			System.debug('body to sendLote:  ' + body);
			WSLoteEnviarASS.Response resp = WSLoteEnviarASS.sendLoteToSS(body);

			if(!resp.hasError){
				lote.Id_lote_SS__c = resp.lote.data.lote_id != null ? String.valueOf(resp.lote.data.lote_id) : null;
				lote.Estado__c = resp.lote.data.estado;
				lote.Fallo_en_SS__c = null;
				lote.Fecha_de_fallo__c = null; 
			}
			else{
				lote.Fallo_en_SS__c = resp.message;
				lote.Fecha_de_fallo__c = Datetime.now(); 
			}
			System.debug(lote);
			lote.Bloqueo__c = false;
			update lote;
			if(!lotes.isEmpty()){
				System.enqueueJob(new LoteQueueable(lotes));
			}
		}
	}
}