force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En Auditoria</fullName>
                <label>En Auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Suspendido</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Fecha_y_hora_fin_ems__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_fin_ems__c</fullName>
    <label>Fecha y hora fin EM</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>En auditoria</fullName>
                <label>En auditoría</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_real__c</fullName>
    <label>Fecha Fin real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Numero_del_segmento__c.field-meta.xml
<CustomField>
    <fullName>Numero_del_segmento__c</fullName>
    <label>Número del segmento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Segmento_actual__c.field-meta.xml
<CustomField>
    <fullName>Segmento_actual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Segmento actual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Semid__c.field-meta.xml
<CustomField>
    <fullName>Semid__c</fullName>
    <externalId>true</externalId>
    <label>Sem_id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SegmentoEliminarBtnCtrlTest.cls
@IsTest
private class SegmentoEliminarBtnCtrlTest {
    static XHttpCalloutMock getResponseFound;
    static XHttpCalloutMock getErrorResponse;

    static {
        getResponseFound = new XHttpCalloutMock();
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSSegmentoEliminarMock.getFound())
                .addForAddress(WSSegmentoEliminar.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/275822/segmentos/305716');
        getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('La autorización solicitada es inválida.')
                .withStatusCode(404)
                .withBody(WSSegmentoEliminarMock.getError())
                .addForAddress(WSSegmentoEliminar.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/275822/segmentos/305716');

    }

    @IsTest
    private static void deleteValidSegment() {
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '275822');
		em.RecordTypeId = XappiaHelper.getRecordType('Evento_Medico__c', 'Evento_medico_de_internacion').Id;
        em.Estado__c = 'Autorizado';

        insert em;

        Datetime actual = System.now();
        Segmentos__c seg1 = new Segmentos__c(Semid__c = '123',Evento_Medico__c = em.Id,Fecha_Fin_real__c = actual,Numero_del_segmento__c=1);
        insert seg1;

        Segmentos__c seg2 = new Segmentos__c(Semid__c = '305716',Evento_Medico__c = em.Id,Numero_del_segmento__c=2);
        insert seg2;

        Test.setMock(HttpCalloutMock.class, getResponseFound);
        Test.startTest();
        SegmentoEliminarBtnCtrl.Response resp = SegmentoEliminarBtnCtrl.deleteSegmento('305716');
        Test.stopTest();

        System.assertEquals(false,resp.hasError);
        System.assertEquals('Segmento eliminado exitosamente',resp.message);
        System.assertEquals(actual,[SELECT Fecha_y_hora_fin_ems__c FROM Evento_medico__c].Fecha_y_hora_fin_ems__c);
        System.assertEquals(true, [SELECT Segmento_actual__c FROM Segmentos__c WHERE Id = :seg1.Id].Segmento_actual__c);


    }

    @IsTest
    private static void deleteInvalidSegment() {
        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '275822');
        insert em;

        Segmentos__c seg = new Segmentos__c(Semid__c = '305716',Evento_Medico__c = em.Id);
        insert seg;

        Test.startTest();
        SegmentoEliminarBtnCtrl.Response resp = SegmentoEliminarBtnCtrl.deleteSegmento('305716');
        Test.stopTest();

        System.assertEquals(true, resp.hasError);
        System.assertEquals('El segmento solicitado es inválido.', resp.message);
    }

    @IsTest
    private static void showErrorMsgWhenTheExternalIdIsNull() {
//        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '275822');
        insert em;

        Segmentos__c seg = new Segmentos__c(Semid__c = null, Evento_Medico__c = em.Id);
        insert seg;

        Test.startTest();
        SegmentoEliminarBtnCtrl.Response resp = SegmentoEliminarBtnCtrl.deleteSegmento(seg.Semid__c);
        Test.stopTest();

        System.assertEquals(true, resp.hasError);
        System.assertEquals('El id externo está vacío', resp.message);
    }
}