force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/recordTypes/Evento_medico_de_internacion.recordType-meta.xml
<RecordType>
    <fullName>Evento_medico_de_internacion</fullName>
    <active>true</active>
    <label>Evento médico de internación</label>
</RecordType>

force-app/main/default/objects/Segmentos__c/Segmentos__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Nombre del Segmento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Segmentos__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_real__c</fullName>
    <label>Fecha Fin real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Fin_tentativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin_tentativa__c</fullName>
    <label>Fecha Fin tentativa</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Inicio_real__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_real__c</fullName>
    <label>Fecha Inicio real</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segmentos__c/fields/Fecha_Inicio_tentativa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_tentativa__c</fullName>
    <label>Fecha Inicio tentativa</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SegmentoAltaBtnCtrlTest.cls
@IsTest
private class SegmentoAltaBtnCtrlTest {
    static XHttpCalloutMock getResponseFound;
    static XHttpCalloutMock getErrorResponse;

    static {
//        getResponseFound = new XHttpCalloutMock();
//        getResponseFound.buildResponse()
//                .withStatus('OK')
//                .withStatusCode(200)
//                .withBody(WSAuthTokenMock.getTokenSuccess())
//                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
//        getResponseFound.buildResponse()
//                .withStatus('OK')
//                .withStatusCode(200)
//                .withBody(WSSegmentoAltaMock.getFound())
//                .addForAddress(WSSegmentoAlta.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/275822/segmentos');

        getErrorResponse = new XHttpCalloutMock();
        getErrorResponse.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getErrorResponse.buildResponse()
                .withStatus('exception')
                .withStatusCode(404)
                .withBody(WSSegmentoAltaMock.getError())
                .addForAddress(WSSegmentoAlta.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/275822/segmentos');

    }

    @IsTest
    private static void createSegmentTest() {
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '275822');
		em.RecordTypeId = XappiaHelper.getRecordType('Evento_Medico__c', 'Evento_medico_de_internacion').Id; 
        insert em;

        Datetime actual = System.now();
        Datetime masCincoDias = actual.addDays(5);
        Segmentos__c seg1 = new Segmentos__c(
                Evento_Medico__c = em.Id,
                Fecha_Inicio_tentativa__c = actual,
                Fecha_Fin_tentativa__c = masCincoDias
        );
        insert seg1;

        WSSegmentoAltaMock mock = new WSSegmentoAltaMock();
        String body = mock.getFound(seg1.Id);
        getResponseFound = new XHttpCalloutMock();
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(WSAuthTokenMock.getTokenSuccess())
                .addForAddress(WSAuthToken.SERVICE_CONFIG.URL__c + '/oauth/token');
        getResponseFound.buildResponse()
                .withStatus('OK')
                .withStatusCode(200)
                .withBody(body)
                .addForAddress(WSSegmentoAlta.SERVICE_CONFIG.URL__c + '/v1/salud/eventos-medicos/275822/segmentos');
        Test.setMock(HttpCalloutMock.class, getResponseFound);
        Test.startTest();
        BasicResponse resp = SegmentoAltaBtnCtrl.createSegmento(seg1.Id);
        Test.stopTest();

        System.assertEquals(false,resp.hasError);
        System.assertEquals('Segmento creado exitosamente', resp.message);
        Segmentos__c segToAssert = [SELECT Fecha_Inicio_real__c, Fecha_Fin_real__c FROM Segmentos__c WHERE Id =: seg1.Id];
        Datetime inicio = Datetime.newInstance(2020, 2, 3, 0, 0, 0);
        Datetime fin = Datetime.newInstance(2020, 2, 4, 0, 0, 0);
        System.assertEquals(inicio, segToAssert.Fecha_Inicio_real__c);
        System.assertEquals(fin, segToAssert.Fecha_Fin_real__c);

    }

    @IsTest
    private static void createSegmentErrorTest() {
        Test.setMock(HttpCalloutMock.class, getErrorResponse);
        Evento_medico__c em = new Evento_medico__c(Nro_de_Evento_Medico_SS__c = '275822');
        insert em;

        Segmentos__c seg = new Segmentos__c(Evento_Medico__c = em.Id);
        insert seg;

        Test.startTest();
        BasicResponse resp = SegmentoAltaBtnCtrl.createSegmento(seg.Id);
        Test.stopTest();

        System.assertEquals(true, resp.hasError);
		System.assertEquals('The given data was invalid.', resp.message);
        //System.assertEquals('efector es inválido.\n', resp.message);
    }
}