force-app/main/default/objects/SS_Segmento_Response__e/SS_Segmento_Response__e.object-meta.xml
<CustomObject>
    <description>Evento que se dispara una vez se ha enviado a SS el segmento y obtenido una respuesta.</description>
    <label>SS Segmento Response</label>
    <pluralLabel>SS Segmento Responses</pluralLabel>
</CustomObject>

force-app/main/default/objects/SS_Segmento_Response__e/fields/error__c.field-meta.xml
<CustomField>
    <fullName>error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si ocurre un error en SS al enviar el Segmento, marcar como true</description>
    <label>error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Segmento_Response__e/fields/Id_Segmento__c.field-meta.xml
<CustomField>
    <fullName>Id_Segmento__c</fullName>
    <description>Id Salesforce del segmento</description>
    <label>Id Segmento</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Segmento_Response__e/fields/Response_Error__c.field-meta.xml
<CustomField>
    <fullName>Response_Error__c</fullName>
    <description>Mensaje de error de SS al enviar un segmento fallido.</description>
    <label>Response Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice_endpoint__mdt/Webservice_endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Endpoints para las APIs de SS</description>
    <label>Webservice endpoint</label>
    <pluralLabel>Webservice endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webservice_endpoint__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Webservice_endpoint_setting__mdt/Webservice_endpoint_setting__mdt.object-meta.xml
<CustomObject>
    <description>Metadata store endpoint and credentials</description>
    <label>Webservice endpoint setting</label>
    <pluralLabel>Webservice endpoint setting</pluralLabel>
</CustomObject>

force-app/main/default/classes/WSSegmentoEnviarASSHelper.cls
/**-----------------------------------------------------------------------------------------------------------------------
@author			Jeferson Ruiz.
@description	Clase para realizar el envío a SS de la información de los segmentos en SF.
@date			21/12/2021
------------------------------------------------------------------------------------------------------------------------*/
@SuppressWarnings('PMD.ExcessiveParameterList')
public with sharing class WSSegmentoEnviarASSHelper {
	@TestVisible
	public static final Webservice_endpoint_setting__mdt SERVICE_CONFIG = ConfigUtils.getWebServiceConfig('SALUDSOFT.TEST');
	public static Map<String,Webservice_endpoint__mdt> ENDPOINTS;
	private static String segmentoId;
	public static Response enviarASS (String body,
										String serviceType,
										String service,
										String eventoMedicoID) {
		return enviarASS(body, serviceType, service, eventoMedicoID, null);
	}
	public static Response enviarASS (String body,
										String serviceType,
										String service,
										String eventoMedicoID,
										String segmentoId) {
		segmentoId = segmentoId;
		System.debug('BODY SOLICITUD: ');System.debug(body);
		ENDPOINTS = ConfigUtils.getEndpointsByTipo(serviceType);
		String url = SERVICE_CONFIG.URL__c + ENDPOINTS.get(service).Endpoint__c + '/' + eventoMedicoID + '/segmentos';
		if (!String.isBlank(segmentoId)) url += '/' + segmentoId;
		System.debug(url);
		RestWS ws = new RestWS(url, 'POST', null, body);
		ws.request.setHeader('Accept','application/json"');
		ws.request.setHeader('Content-Type', 'application/json');
		WSAuthToken.Response tokenResp = WSAuthToken.setAuthHeader(ws);
		Response res = (Response) ws.invoke(new Response());
		WSAuthToken.manageTokenResponse(tokenResp);
		return res;
	}
	public class Response extends WSResult {
		public WSSSGenericResponse result;
		public override void processResponse(HttpResponse response) {
			System.debug('BODY Respuesta: ');System.debug(response.getBody());
			result = WSSSGenericResponse.parse(response.getBody());
		}
		public override void processError(HttpResponse response) {
			System.debug('BODY Respuesta: ');System.debug(response.getBody());
			result = WSSSGenericResponse.parse(response.getBody());
			this.message = result.processMessage();
			SS_Segmento_Response__e errorEvent =  new SS_Segmento_Response__e(
				error__c = true,
				Response_Error__c = this.message,
				Id_Segmento__c = segmentoId
			);
			List<Database.SaveResult> results = EventBus.publish(new List<SS_Segmento_Response__e>{errorEvent});
		}
	}
}