force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico__c/fields/Codigo_del_Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_Diagnostico__c</fullName>
    <externalId>true</externalId>
    <label>Código del Diagnóstico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/Diagnostico_del_Evento__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico del Evento</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Nombre de Diagnóstico del Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnósticos del Evento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Diagnósticos del Evento</relationshipLabel>
    <relationshipName>Diagn_sticos_del_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFINITIVO</fullName>
            </value>
            <value>
                <fullName>PRESUNTIVO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiagnosticoDelEventoTriggerHelper.cls
public class DiagnosticoDelEventoTriggerHelper {
    public static String generateJson(Diagnostico_del_Evento__c diagnostico, String apodo) {
		String body;

		Map<String,Object> jsonMap = new Map<String, Object> {
			'usuario' => apodo,
            'fecha' => diagnostico.Fecha__c != null ? diagnostico.Fecha__c.format() : '',
            'diagnostico' => diagnostico.Diagnostico__r.Codigo_del_Diagnostico__c,
            'tipo_diagnostico' => diagnostico.Tipo__c
		};
		body = JSON.serialize(jsonMap);

		return body;
	}
}