force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico__c/fields/Codigo_del_Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_Diagnostico__c</fullName>
    <externalId>true</externalId>
    <label>Código del Diagnóstico</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/Diagnostico_del_Evento__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico del Evento</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Nombre de Diagnóstico del Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnósticos del Evento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Diagnósticos del Evento</relationshipLabel>
    <relationshipName>Diagn_sticos_del_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Error_en_SS__c.field-meta.xml
<CustomField>
    <fullName>Error_en_SS__c</fullName>
    <label>Error en SS</label>
    <length>66666</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Evento_Medico__c.field-meta.xml
<CustomField>
    <fullName>Evento_Medico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Médico</label>
    <referenceTo>Evento_medico__c</referenceTo>
    <relationshipLabel>Diagnósticos del Evento</relationshipLabel>
    <relationshipName>Diagn_sticos_del_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostico_del_Evento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEFINITIVO</fullName>
            </value>
            <value>
                <fullName>PRESUNTIVO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto costo</fullName>
            </value>
            <value>
                <fullName>Celiaco</fullName>
            </value>
            <value>
                <fullName>Clinico</fullName>
            </value>
            <value>
                <fullName>Covid</fullName>
            </value>
            <value>
                <fullName>Diabetes</fullName>
            </value>
            <value>
                <fullName>Discapacidad</fullName>
            </value>
            <value>
                <fullName>Esclero</fullName>
            </value>
            <value>
                <fullName>Fertilidad</fullName>
            </value>
            <value>
                <fullName>Hepatitis</fullName>
            </value>
            <value>
                <fullName>HIV</fullName>
            </value>
            <value>
                <fullName>Leches</fullName>
            </value>
            <value>
                <fullName>Oxigenoterapia</fullName>
            </value>
            <value>
                <fullName>Programa Cronicos</fullName>
            </value>
            <value>
                <fullName>Provision Anticonceptivos</fullName>
            </value>
            <value>
                <fullName>Provision Oncologicos</fullName>
            </value>
            <value>
                <fullName>Quirurgico</fullName>
            </value>
            <value>
                <fullName>Transplante</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Anticonceptivos</fullName>
                <isActive>false</isActive>
                <label>Anticonceptivos</label>
            </value>
            <value>
                <fullName>EMS Discapacidad</fullName>
                <isActive>false</isActive>
                <label>EMS Discapacidad</label>
            </value>
            <value>
                <fullName>EMS Fertilidad</fullName>
                <isActive>false</isActive>
                <label>EMS Fertilidad</label>
            </value>
            <value>
                <fullName>EMS Oxigenoterapia</fullName>
                <isActive>false</isActive>
                <label>EMS Oxigenoterapia</label>
            </value>
            <value>
                <fullName>EMS Trasplante</fullName>
                <isActive>false</isActive>
                <label>EMS Trasplante</label>
            </value>
            <value>
                <fullName>Internacion</fullName>
                <isActive>false</isActive>
                <label>Internacion</label>
            </value>
            <value>
                <fullName>Internacion Domiciliaria</fullName>
                <isActive>false</isActive>
                <label>Internacion Domiciliaria</label>
            </value>
            <value>
                <fullName>Provision de Oncologicos</fullName>
                <isActive>false</isActive>
                <label>Provision de Oncologicos</label>
            </value>
            <value>
                <fullName>Rehabilitacion</fullName>
                <isActive>false</isActive>
                <label>Rehabilitacion</label>
            </value>
            <value>
                <fullName>Trastornos Alimentarios</fullName>
                <isActive>false</isActive>
                <label>Trastornos Alimentarios</label>
            </value>
            <value>
                <fullName>Tratamiento Adicciones</fullName>
                <isActive>false</isActive>
                <label>Tratamiento Adicciones</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiagnosticoDelEventoQueueable.cls
public class DiagnosticoDelEventoQueueable implements Queueable, Database.AllowsCallouts {
	List<Diagnostico_del_Evento__c> diagnosticos;

	public DiagnosticoDelEventoQueueable(List<Diagnostico_del_Evento__c> diagnosticosList) {
		diagnosticos = diagnosticosList;
	}

	public void execute(QueueableContext context) {
		User usuario = [
            SELECT Alias, CommunityNickname, Profile.Name 
            FROM User 
            WHERE Id =: UserInfo.getUserId()
        ];
		String apodo = usuario.CommunityNickname != null ? usuario.CommunityNickname.toUpperCase() : null;

		if(!diagnosticos.isEmpty()) {
			Diagnostico_del_Evento__c diagnosticoOriginal = diagnosticos.remove(0);
			Diagnostico_del_Evento__c diagnostico = [
				SELECT Id, Fecha__c, Diagnostico__r.Codigo_del_Diagnostico__c, Tipo__c,
					Evento_Medico__r.Nro_de_Evento_Medico_SS__c, Error_en_SS__c
				FROM Diagnostico_del_Evento__c 
				WHERE Id =: diagnosticoOriginal.Id
					AND Evento_Medico__r.Nro_de_Evento_Medico_SS__c != null
			];

			String body = DiagnosticoDelEventoTriggerHelper.generateJson(diagnostico, apodo);

			WSDiagnosticoDelEventoEnviar.Response resp = WSDiagnosticoDelEventoEnviar.enviarDiagnostico(
				diagnostico.Evento_Medico__r.Nro_de_Evento_Medico_SS__c, body
			);

			System.debug('****resp: ' + resp);
			
			if(!resp.hasError) {
				diagnostico.Error_en_SS__c = null;
			}
			else {
				diagnostico.Error_en_SS__c = '<p style="color: rgb(228, 10, 10);">' + resp.message + '</p>';
			}

			Database.SaveResult resultDiagnostico = Database.update(diagnostico);
			System.debug('****resultDiagnostico: ' + resultDiagnostico);

			if(!diagnosticos.isEmpty()){
				System.enqueueJob(new DiagnosticoDelEventoQueueable(diagnosticos));
			}
		}
	}
}