force-app/main/default/objects/Diagnostico__c/Diagnostico__c.object-meta.xml
<CustomObject>
    <label>Diagnóstico</label>
    <nameField>
        <label>Nombre del Diagnóstico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnósticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/Evento_medico__c.object-meta.xml
<CustomObject>
    <label>Evento Médico</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Nombre de Evento medico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos Medicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_medico__c/fields/Diagnostico__c.field-meta.xml
<CustomField>
    <fullName>Diagnostico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Diagnóstico</label>
    <referenceTo>Diagnostico__c</referenceTo>
    <relationshipLabel>Eventos Medicos</relationshipLabel>
    <relationshipName>Eventos_Medicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Forma_de_egreso__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_egreso__c</fullName>
    <label>Forma de egreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTA_INTERN_DOM</fullName>
                <label>ALTA CONTINUA INTERNACION DOMICILIARIA</label>
            </value>
            <value>
                <fullName>ALTA_MEDICA</fullName>
                <label>ALTA MEDICA</label>
            </value>
            <value>
                <fullName>ALTA_VOL</fullName>
                <label>ALTA VOLUNTARIA</label>
            </value>
            <value>
                <fullName>COMPRA_EQUIPO</fullName>
                <label>COMPRA EQUIPO</label>
            </value>
            <value>
                <fullName>CIERRE</fullName>
                <label>DUPLICIDAD EVENTO/EVENTO VENCIDO</label>
            </value>
            <value>
                <fullName>EMBARAZO</fullName>
            </value>
            <value>
                <fullName>ALTA_FUERA_VIG</fullName>
                <label>EVENTO DE ALTA POR FUERA DE VIGENCIA</label>
            </value>
            <value>
                <fullName>FALLECIMIENTO</fullName>
                <label>FALLECIMIENTO DEL PACIENTE</label>
            </value>
            <value>
                <fullName>FUGA</fullName>
            </value>
            <value>
                <fullName>RECH</fullName>
                <label>RECHAZO</label>
            </value>
            <value>
                <fullName>BAJA</fullName>
                <label>SOCIO BAJA</label>
            </value>
            <value>
                <fullName>EDAD_LIMITE</fullName>
                <label>SUPERA EL LIMITE DE EDAD</label>
            </value>
            <value>
                <fullName>TRASLADO</fullName>
                <label>TRASLADO A CENTRO DE MAYOR COMPLEJIDAD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Nro_de_Evento_Medico_SS__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Evento_Medico_SS__c</fullName>
    <externalId>true</externalId>
    <label>Nro. de Evento Médico SS</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desestimado</fullName>
            </value>
            <value>
                <fullName>En Estudio</fullName>
            </value>
            <value>
                <fullName>Negativo</fullName>
            </value>
            <value>
                <fullName>Positivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_medico__c/fields/Suspendido__c.field-meta.xml
<CustomField>
    <fullName>Suspendido__c</fullName>
    <label>Suspendido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventoMedicoTriggerHandler.cls
public with sharing class EventoMedicoTriggerHandler extends TriggerHandler {
	List<Evento_medico__c> lNew = (List<Evento_medico__c>) Trigger.new;
	List<Evento_medico__c> lOld = (List<Evento_medico__c>) Trigger.old;
	Map<Id,Evento_medico__c> mNew = (Map<Id,Evento_medico__c>) Trigger.newMap;
	Map<Id,Evento_medico__c> mOld = (Map<Id,Evento_medico__c>) Trigger.oldMap;
	public override void beforeInsert(){
		// Nothing
	}
	public override void beforeUpdate(){
		EventoMedicoTriggerHelper.validateFormaDeEgreso(mNew, mOld);
	}
	public override void beforeDelete(){
		EventoMedicoTriggerHelper.validateDeletion(mOld);
	}
	public override void afterInsert(){
		Map<Id, List<Evento_medico__c>> userIdEMsMap = new Map<Id, List<Evento_medico__c>>();
		for (Evento_medico__c em : lNew) {
			if (userIdEMsMap.containsKey(em.OwnerId)) {
				List<Evento_medico__c> casesFromMap = userIdEMsMap.get(em.OwnerId);
				casesFromMap.add(new Evento_medico__c(Id = em.Id));
				userIdEMsMap.put(em.OwnerId, casesFromMap);
			} else {
				userIdEMsMap.put(em.OwnerId, new List<Evento_medico__c>{new Evento_medico__c(Id = em.Id)});
			}
		}
		if (!userIdEMsMap.isEmpty()) {
			EventoMedicoTriggerHelper.assignDelegacionFromUser(userIdEMsMap);
		}
	}
	public override void afterUpdate(){
		Id[] emsToSendToSS = new List<Id>();
		for(Evento_medico__c em : lNew) {
			Evento_medico__c oldEm = mOld.get(em.Id);
			if(String.isNotBlank(em.Nro_de_Evento_Medico_SS__c)
				&& (em.Forma_de_egreso__c != oldEm.Forma_de_egreso__c
					|| em.Resultado__c != oldEm.Resultado__c
					|| em.Diagnostico__c != oldEm.Diagnostico__c
					|| em.Suspendido__c != oldEM.Suspendido__c)) {
				emsToSendToSS.add(em.Id);
			}
		}
		if(!emsToSendToSS.isEmpty()) {
			EventoMedicoTriggerHelper.sendToSS(emsToSendToSS);
		}
	}
	public override void afterDelete(){
		//Nothing
	}
	public override void afterUndelete(){
		//Nothing
	}
}