force-app/main/default/objects/SS_Response_Event__e/fields/error__c.field-meta.xml
<CustomField>
    <fullName>error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si ocurre un error en SS al enviar el registro, marcar como true</description>
    <label>error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SS_Response_Event__e/fields/Id_Registro__c.field-meta.xml
<CustomField>
    <fullName>Id_Registro__c</fullName>
    <description>Id Salesforce del registro enviado a SS</description>
    <label>Id Registro</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SS_Response_Event__e/fields/Response_Error__c.field-meta.xml
<CustomField>
    <fullName>Response_Error__c</fullName>
    <description>Mensaje de error de SS al enviar un registro fallido.</description>
    <label>Response Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSResponseEventTriggerHandler.cls
/**-----------------------------------------------------------------------------------------------------------------------
@author			Jeferson Ruiz.
@description	Clase auxiliar para manejar el trigger de eventos SS_Response_Event__e
@date			07/06/2022
------------------------------------------------------------------------------------------------------------------------*/
public without sharing class SSResponseEventTriggerHandler {
    public void handleFiredEvent (SS_Response_Event__e event) {
		System.debug('Event error: ' + event.error__c);
		System.debug('Event message: ' + event.Response_Error__c);
		System.debug('Event Registro Id: ' + event.Id_Registro__c);
	}
}