force-app/main/default/objects/Medicamento__c/Medicamento__c.object-meta.xml
<CustomObject>
    <label>Medicamento</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Medicamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medicamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medicamento__c/fields/Accion_Terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Accion_Terapeutica__c</fullName>
    <label>Acción Terapéutica</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_de_Barras__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Barras__c</fullName>
    <label>Código de Barras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_Externo1__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo1__c</fullName>
    <label>Código Externo1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_Externo2__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo2__c</fullName>
    <label>Código Externo2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_Externo3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo3__c</fullName>
    <label>Codigo Externo3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Laboratorio__c</fullName>
    <label>Codigo Laboratorio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Codigo_medicamento__c.field-meta.xml
<CustomField>
    <fullName>Codigo_medicamento__c</fullName>
    <externalId>true</externalId>
    <label>Código Medicamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Accion_Terapeutica__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Accion_Terapeutica__c</fullName>
    <label>Descripcion Accion Terapeutica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Forma__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Forma__c</fullName>
    <label>Descripción Forma</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Laboratorio__c</fullName>
    <label>Descripcion Laboratorio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Monodroga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Monodroga__c</fullName>
    <label>Descripcion Monodroga</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Tamao__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Tamao__c</fullName>
    <label>Descripción Tamaño</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Unidad__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Unidad__c</fullName>
    <label>Descripción Unidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Descripcion_Via__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Via__c</fullName>
    <label>Descripción Vía</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Edad_Maxima__c.field-meta.xml
<CustomField>
    <fullName>Edad_Maxima__c</fullName>
    <label>Edad Máxima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Edad_Minima__c.field-meta.xml
<CustomField>
    <fullName>Edad_Minima__c</fullName>
    <label>Edad Mínima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Estado_Informado__c.field-meta.xml
<CustomField>
    <fullName>Estado_Informado__c</fullName>
    <label>Estado Informado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Estado_Presentacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Presentacion__c</fullName>
    <label>Estado Presentación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Estado_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Vigencia__c</fullName>
    <label>Estado Vigencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Estupefaciente__c.field-meta.xml
<CustomField>
    <fullName>Estupefaciente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estupefaciente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Excluye_Vademecum__c.field-meta.xml
<CustomField>
    <fullName>Excluye_Vademecum__c</fullName>
    <label>Excluye Vademecum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Fecha_Activacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Activacion__c</fullName>
    <label>Fecha Activación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Fecha_Baja__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Baja__c</fullName>
    <label>Fecha Baja</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Fecha_Estado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Estado__c</fullName>
    <label>Fecha Estado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Forma__c.field-meta.xml
<CustomField>
    <fullName>Forma__c</fullName>
    <label>Forma</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Grupo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Grupo_Terapeutico__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Terapeutico__c</fullName>
    <label>Grupo Terapeutico</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Maxima_Unidades__c.field-meta.xml
<CustomField>
    <fullName>Maxima_Unidades__c</fullName>
    <label>Máxima Unidades</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Medicamento_Bonificado__c.field-meta.xml
<CustomField>
    <fullName>Medicamento_Bonificado__c</fullName>
    <label>Medicamento Bonificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Monodroga__c.field-meta.xml
<CustomField>
    <fullName>Monodroga__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monodroga</label>
    <referenceTo>Monodroga__c</referenceTo>
    <relationshipLabel>Medicamentos</relationshipLabel>
    <relationshipName>Medicamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Nacional__c.field-meta.xml
<CustomField>
    <fullName>Nacional__c</fullName>
    <label>Nacional</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Nombre_de_Grupo__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Grupo__c</fullName>
    <label>Nombre de Grupo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Nombre_de_Presentacion__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Presentacion__c</fullName>
    <label>Nombre de Presentación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Nombre_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Producto__c</fullName>
    <label>Nombre de Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/PMI_Hijo__c.field-meta.xml
<CustomField>
    <fullName>PMI_Hijo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PMI Hijo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/PMI_Madre__c.field-meta.xml
<CustomField>
    <fullName>PMI_Madre__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PMI Madre</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Potencia__c.field-meta.xml
<CustomField>
    <fullName>Potencia__c</fullName>
    <label>Potencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Precio_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Precio_Referencia__c</fullName>
    <label>Precio Referencia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Psicofarmaco__c.field-meta.xml
<CustomField>
    <fullName>Psicofarmaco__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Psicofármaco</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Referencia2__c.field-meta.xml
<CustomField>
    <fullName>Referencia2__c</fullName>
    <label>Referencia 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Referencia3__c.field-meta.xml
<CustomField>
    <fullName>Referencia3__c</fullName>
    <label>Referencia 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Res_310__c.field-meta.xml
<CustomField>
    <fullName>Res_310__c</fullName>
    <label>Res 310</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Sexo_Permitido__c.field-meta.xml
<CustomField>
    <fullName>Sexo_Permitido__c</fullName>
    <label>Sexo Permitido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Tamanio__c.field-meta.xml
<CustomField>
    <fullName>Tamanio__c</fullName>
    <label>Tamaño</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Tipo_de_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cobertura__c</fullName>
    <label>Tipo de Cobertura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Tipo_Unidad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Unidad__c</fullName>
    <label>Tipo Unidades</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Troquel__c.field-meta.xml
<CustomField>
    <fullName>Troquel__c</fullName>
    <label>Troquel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/UDivisin__c.field-meta.xml
<CustomField>
    <fullName>UDivisin__c</fullName>
    <label>U/División</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/UnidDivisibles__c.field-meta.xml
<CustomField>
    <fullName>UnidDivisibles__c</fullName>
    <label>Unid/Divisibles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medicamento__c/fields/Venta_Libre__c.field-meta.xml
<CustomField>
    <fullName>Venta_Libre__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Venta Libre</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monodroga__c/Monodroga__c.object-meta.xml
<CustomObject>
    <label>Monodroga</label>
    <nameField>
        <label>Nro. de Monodroga</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monodrogas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monodroga__c/fields/Descripcion_monodroga__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_monodroga__c</fullName>
    <label>Descripción monodroga</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MedicamentosProcessor.cls
public class MedicamentosProcessor implements IMasterBuilder  {
	
	public Boolean hasNext = false;
	public Datetime runTime;
	public Datetime lastUpdateForMedicamento;
	public Integer pageSize;
	public Integer currentPage;
	public Integer lastPage;
	public Boolean errorWs = false;

	public MedicamentosProcessor(Integer pageSize, Datetime runTime) {
		this(pageSize, 1, 1, runTime, Datetime.now());
	}

	public MedicamentosProcessor(Integer pageSize, Datetime runTime, Datetime lastUpdateForMedicamento) {
		this(pageSize, 1, 1, runTime, lastUpdateForMedicamento);
	}

	public MedicamentosProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime) {
		this(pageSize, currentPage, lastPage, runTime, Datetime.now());
	}

	public MedicamentosProcessor(Integer pageSize, Integer currentPage, Integer lastPage, Datetime runTime, Datetime lastUpdateForMedicamento) {
		this.pageSize = pageSize;
		this.currentPage = currentPage;
		this.lastPage = lastPage;
		this.runTime = runTime;
		this.lastUpdateForMedicamento = lastUpdateForMedicamento;
	}

	public List<WSBatchMedicamentosResp.Data> callWebService() {
		List<WSBatchMedicamentosResp.Data> wsData = new List<WSBatchMedicamentosResp.Data>();
		WSBatchMedicamentos.Response resp;

		if (currentPage <= lastPage) {
			String fecha = runTime.format('yyyy-MM-dd');
			resp = WSBatchMedicamentos.getBatchMedicamentos(fecha, this.pageSize, this.currentPage);
		}

		if(!resp.hasError) {
			hasNext = resp.result.links.next != null;
			currentPage = resp.result.meta.current_page + 1;
			lastPage = resp.result.meta.last_page;
			wsData.addAll(resp.result.data);
		} else {
			this.errorWs = true;
		}

		return wsData;
	}

	public void processResponse(List<Object> wsResponses) {
		List<Medicamento__c> medicamentos = new List<Medicamento__c>();
		Set<Monodroga__c> setMonodrogas = new Set<Monodroga__c>();
		List<String> externalIds = new List<String>();

		for(Object resp : wsResponses) {
			WSBatchMedicamentosResp.Data medicamentoWS = (WSBatchMedicamentosResp.Data) resp;
			Medicamento__c medicamento = new Medicamento__c();
            
			
			medicamento.Codigo_medicamento__c = medicamentoWS.codigo;
			medicamento.Accion_Terapeutica__c = medicamentoWS.accion_terapeutica != null 
													? Integer.valueOf(medicamentoWS.accion_terapeutica) : null;
			medicamento.Nombre_de_Producto__c = medicamentoWS.nombre_producto;
            medicamento.Nombre_de_Presentacion__c = medicamentoWS.nombre_presentacion;
			medicamento.Grupo__c = medicamentoWS.grupo;
			medicamento.Nombre_de_Grupo__c = medicamentoWS.nombre_grupo; 
			medicamento.Troquel__c = medicamentoWS.troquel;
			medicamento.Codigo_de_Barras__c = medicamentoWS.codigo_barras;
			medicamento.Codigo_Externo1__c = medicamentoWS.codigo_externo_1;
			medicamento.Codigo_Externo2__c = medicamentoWS.codigo_externo_2;
			medicamento.Codigo_Externo3__c = medicamentoWS.codigo_externo_3;
			medicamento.Codigo_Laboratorio__c = medicamentoWS.medlab_codigo;
			medicamento.Descripcion__c = medicamentoWS.descripcion;
			medicamento.Descripcion_Laboratorio__c = medicamentoWS.nombre_lab;
			medicamento.Tipo_Unidad__c = medicamentoWS.nombre_tipouni;
			medicamento.Descripcion_Via__c = medicamentoWS.descrip_via;
			medicamento.Edad_Maxima__c = medicamentoWS.edad_maxima != null 
											? Integer.valueOf(medicamentoWS.edad_maxima) : null;
			medicamento.Edad_Minima__c = medicamentoWS.edad_minima != null
											? Integer.valueOf(medicamentoWS.edad_minima) : null;
			medicamento.Estado_Informado__c = medicamentoWS.estado_informado;
			medicamento.Estado_Presentacion__c = medicamentoWS.estado_presentacion;
			medicamento.Estado_Vigencia__c = medicamentoWS.estado_vigencia;
			medicamento.Excluye_Vademecum__c = medicamentoWS.excluye_vademecum;
			medicamento.Fecha_Activacion__c = medicamentoWS.fecha_activacion != null ? Date.valueOf(medicamento.Fecha_Activacion__c) : null;
			medicamento.Fecha_Baja__c = medicamentoWS.fecha_baja != null ? Date.valueOf(medicamento.Fecha_Baja__c) : null;
			medicamento.Fecha_Estado__c = medicamentoWS.fecha_estado != null ? Date.valueOf(medicamento.Fecha_Estado__c) : null;
			medicamento.Descripcion_Forma__c = medicamentoWS.nombre_forma;
			medicamento.Forma__c = medicamentoWS.forma != null ? Integer.valueOf(medicamentoWS.forma) : null;
			medicamento.Grupo_Terapeutico__c = medicamentoWS.grupo_terapeutico;
			medicamento.Maxima_Unidades__c = medicamentoWS.max_unidades;
			medicamento.Medicamento_Bonificado__c = medicamentoWS.med_bonificado;
			medicamento.Nacional__c = medicamentoWS.nacional;
			medicamento.Tipo_Unidad__c = medicamentoWS.tipo_uni;
			medicamento.Observaciones__c = medicamentoWS.observaciones;
			medicamento.PMI_Hijo__c = medicamentoWS.pmi_hijo == 'V';
			medicamento.PMI_Madre__c = medicamentoWS.pmi_madre == 'V';
			medicamento.Potencia__c = medicamentoWS.potencia;
			medicamento.Precio_Referencia__c = medicamentoWS.precio_referencia != null 
												? Decimal.valueOf(medicamentoWS.precio_referencia) : null;
			medicamento.Psicofarmaco__c = medicamentoWS.psicofarmaco == 'V';
			medicamento.Referencia2__c = medicamentoWS.referencia_externa_2;
			medicamento.Referencia3__c = medicamentoWS.referencia_externa_3;
			medicamento.Res_310__c = medicamentoWS.resol_310;
			medicamento.Sexo_Permitido__c = medicamentoWS.sexo_permitido;
			medicamento.UnidDivisibles__c = medicamentoWS.unidades_divisibles;
			medicamento.Unidad__c = medicamentoWS.unidad;
			medicamento.Venta_Libre__c = medicamentoWS.venta_libre == 'V';
			medicamento.Estupefaciente__c = medicamentoWS.estupefaciente == 'V';
			medicamento.Tipo_de_Cobertura__c = medicamentoWS.tipo_cober;
			medicamento.Descripcion_Accion_Terapeutica__c = medicamentoWS.medat_nombre;
			medicamento.Tamanio__c = medicamentoWS.tamano != null ? Integer.valueOf(medicamentoWS.tamano) : null;
			medicamento.Descripcion_Tamao__c = medicamentoWS.nombre_tam;
			medicamento.Descripcion_Unidad__c = medicamentoWS.nombre_unidad;
			medicamento.Descripcion_Monodroga__c = medicamentoWS.nombre_monodroga;
			medicamento.UDivisin__c = medicamentoWS.unidades_division; 

			if(medicamentoWS.monodroga != null) {
				medicamento.Monodroga__r = new Monodroga__c(Codigo_de_monodroga__c = medicamentoWS.monodroga);
				Monodroga__c monodroga = new Monodroga__c(Codigo_de_monodroga__c = medicamentoWS.monodroga);
				monodroga.Name = medicamentoWS.nombre_monodroga;

				setMonodrogas.add(monodroga);
			}

			
			medicamentos.add(medicamento);
			externalIds.add(medicamentoWS.codigo);
            
            
		}
		List<Monodroga__c> monodrogas = new List<Monodroga__c>(setMonodrogas);
		Database.UpsertResult[] resultsMonodrogas = Database.upsert(
			monodrogas, Monodroga__c.Fields.Codigo_de_monodroga__c, false
		);
		System.debug('****resultsMonodrogas: ' + resultsMonodrogas);
		Database.UpsertResult[] results = Database.upsert(
			medicamentos, Medicamento__c.Codigo_medicamento__c, false
		);
		System.debug('****results* ' + results);
		//EmailUtils.sendErrorMail(results, null, null, externalIds, 'Medicamentos ' + (currentPage - 1) + ' pagina');

		Utils.insertBatchLogs(results, null, null, externalIds, 'Medicamentos');

	}

	public void updateDate() {

		if (!hasNext) {
			if(!errorWs) {
				MasterConfigs__c lastUpdate = MasterConfigs__c.getOrgDefaults();
				lastUpdate.Medicamentos__c = lastUpdateForMedicamento;
				upsert lastUpdate;
			}
		} else {
			MedicamentosProcessor nextProcessor = new MedicamentosProcessor(pageSize, currentPage, lastPage, runTime);
			Database.executeBatch(new MasterBatch(nextProcessor));
		}
	}

	//private Date parseFecha(String fechaStr) {
		//List<String> fechaList = fechaStr.split('-');
		//return date.newInstance(
				//integer.valueOf(fechaList[0]),
				//integer.valueOf(fechaList[1]),
				//integer.valueOf(fechaList[2]));
	//}
}