force-app/main/default/objects/Grupo_de_tipos_de_registro__mdt/Grupo_de_tipos_de_registro__mdt.object-meta.xml
<CustomObject>
    <label>Grupo de tipos de registro</label>
    <pluralLabel>Grupos de tipos de registro</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tipo_de_registro_por_grupo__mdt/Tipo_de_registro_por_grupo__mdt.object-meta.xml
<CustomObject>
    <description>Utilizado para reemplazar comportamiento estándar de selección de tipo de registro</description>
    <label>Tipo de registro por grupo</label>
    <pluralLabel>Tipos de registro por grupos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tipo_de_registro_por_grupo__mdt/fields/Grupo__c.field-meta.xml
<CustomField>
    <fullName>Grupo__c</fullName>
    <label>Grupo</label>
    <referenceTo>Grupo_de_tipos_de_registro__mdt</referenceTo>
    <relationshipLabel>Tipos de registro</relationshipLabel>
    <relationshipName>Tipos_de_registro</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Tipo_de_registro_por_grupo__mdt/fields/Id_de_tipo_de_registro__c.field-meta.xml
<CustomField>
    <fullName>Id_de_tipo_de_registro__c</fullName>
    <label>Id de tipo de registro</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelectCaseTypeController.cls
public with sharing class SelectCaseTypeController {
	@AuraEnabled
	public static List<GroupOfTypes> getRecordTypesByGroup(){
		Map<Id, RecordType> typesById = new Map<Id, RecordType>();
		for (Schema.RecordTypeInfo typeInfo : case.SObjectType.getDescribe().getRecordTypeInfos()) {
			RecordType temp = new RecordType(
				Id = typeInfo.getRecordTypeId(),
				Name = typeInfo.getName()
			);
			typesById.put(temp.Id, temp);
		}
		
		List<GroupOfTypes> result = new List<GroupOfTypes>();
		GroupOfTypes currentGroup;
		for (Tipo_de_registro_por_grupo__mdt typeForGroup : [
			SELECT Grupo__r.MasterLabel, Id_de_tipo_de_registro__c
			FROM Tipo_de_registro_por_grupo__mdt
			WHERE Id_de_tipo_de_registro__c IN :typesById.keySet()
			ORDER BY Grupo__c ASC
		]) {
			if(currentGroup == null || currentGroup.name != typeForGroup.Grupo__r.MasterLabel) {
				currentGroup = new GroupOfTypes(typeForGroup.Grupo__r.MasterLabel);
				result.add(currentGroup);
			}
			currentGroup.types.add(typesById.get(typeForGroup.Id_de_tipo_de_registro__c));
		}
		
		return result;
	}
	
	
	public class GroupOfTypes {
		@AuraEnabled
		public String name;
		@AuraEnabled
		public List<RecordType> types;
		
		public GroupOfTypes(String name) {
			this.name = name;
			types = new List<RecordType>();
		}
	}
}